import {clean, clone, iso, requireText, riskIndex, seal, sha256, verifySeal} from './common.mjs';

const TERMINAL=new Set(['COMPLETED','FAILED','CANCELLED']);
const RETRYABLE=new Set(['TimeoutError','NetworkError','TransientError']);

export class DurableExecutionKernel {
  constructor({now=()=>new Date(),state=null}={}){this.now=now;this.state=state?clone(state):{works:{},tasks:{},events:{},idempotency:{},effects:{}};}
  static restore(snapshot,{now=()=>new Date()}={}){return new DurableExecutionKernel({now,state:snapshot});}
  snapshot(){return clone(this.state);}
  async _event(task,kind,detail={}){const list=this.state.events[task.task_id]||[];const row=await seal('musitu.axiom.ar05.task-event.v1',{event_id:`event_${task.task_id}_${String(list.length).padStart(8,'0')}`,task_id:task.task_id,work_id:task.work_id,project_id:task.project_id,sequence:list.length,kind:clean(kind,80),detail:clone(detail),previous_event_sha256:list.at(-1)?.sha256||null,at:iso(this.now())});list.push(row);this.state.events[task.task_id]=list;return row;}
  async createWork({work_id,project_id,objective,budget_units=100,approval_policy='S3_PLUS'}={}){work_id=requireText(work_id,'work id');project_id=requireText(project_id,'project id');if(this.state.works[work_id])throw new DOMException('work exists','ConstraintError');const row={schema:'musitu.axiom.ar05.work.v1',work_id,project_id,objective:requireText(objective,'objective',2000),budget_units:Number(budget_units),used_units:0,approval_policy,created_at:iso(this.now()),status:'ACTIVE'};if(!Number.isFinite(row.budget_units)||row.budget_units<0)throw new TypeError('invalid budget');this.state.works[work_id]=row;return clone(row);}
  async createTask({task_id,work_id,steps=[]}={}){task_id=requireText(task_id,'task id');work_id=requireText(work_id,'work id');const work=this.state.works[work_id];if(!work)throw new DOMException('work not found','NotFoundError');if(this.state.tasks[task_id])return clone(this.state.tasks[task_id]);const normalized=steps.map((s,i)=>({step_id:clean(s.step_id,120)||`${task_id}_step_${i+1}`,operation:requireText(s.operation,'step operation',160),args:clone(s.args||{}),risk_class:clean(s.risk_class||'S0',8).toUpperCase(),cost_units:Number(s.cost_units??1),max_attempts:Number(s.max_attempts??3),status:'PENDING',attempts:0,idempotency_key:clean(s.idempotency_key,180)||`${task_id}:${i+1}:${clean(s.operation,120)}`,approval_required:riskIndex(s.risk_class||'S0')>=riskIndex('S3'),approval_granted:false,last_error:null}));const task={schema:'musitu.axiom.ar05.task.v1',task_id,work_id,project_id:work.project_id,status:'QUEUED',cursor:0,steps:normalized,created_at:iso(this.now()),updated_at:iso(this.now()),cancel_requested:false};this.state.tasks[task_id]=task;await this._event(task,'task.created',{step_count:normalized.length});return clone(task);}
  getTask(id){const t=this.state.tasks[clean(id,180)];return t?clone(t):null;}
  async approveStep(taskId,stepId,{actor_id,role='HUMAN_APPROVER'}={}){const task=this.state.tasks[taskId];if(!task)throw new DOMException('task not found','NotFoundError');const step=task.steps.find(s=>s.step_id===stepId);if(!step)throw new DOMException('step not found','NotFoundError');if(!clean(actor_id,160))throw new TypeError('approval actor required');step.approval_granted=true;step.approval={actor_id:clean(actor_id,160),role:clean(role,80),at:iso(this.now())};if(task.status==='WAITING_APPROVAL')task.status='QUEUED';await this._event(task,'step.approved',{step_id:stepId,actor_id:step.approval.actor_id,role:step.approval.role});return clone(step);}
  async cancel(taskId,{actor_id='user'}={}){const task=this.state.tasks[taskId];if(!task)throw new DOMException('task not found','NotFoundError');if(TERMINAL.has(task.status))return clone(task);task.cancel_requested=true;task.status='CANCELLED';task.updated_at=iso(this.now());await this._event(task,'task.cancelled',{actor_id:clean(actor_id,160)});return clone(task);}
  async resume(taskId){const task=this.state.tasks[taskId];if(!task)throw new DOMException('task not found','NotFoundError');if(task.status==='FAILED_RETRYABLE'||task.status==='PAUSED'||task.status==='WAITING_APPROVAL'){task.status=task.status==='WAITING_APPROVAL'?'WAITING_APPROVAL':'QUEUED';task.updated_at=iso(this.now());await this._event(task,'task.resumed');}return clone(task);}
  async executeNext(taskId,{executor}={}){const task=this.state.tasks[taskId];if(!task)throw new DOMException('task not found','NotFoundError');if(typeof executor!=='function')throw new TypeError('executor required');if(TERMINAL.has(task.status)||task.cancel_requested)return clone(task);const work=this.state.works[task.work_id];const step=task.steps[task.cursor];if(!step){task.status='COMPLETED';task.updated_at=iso(this.now());await this._event(task,'task.completed');return clone(task);}if(step.approval_required&&!step.approval_granted){task.status='WAITING_APPROVAL';await this._event(task,'step.waiting_approval',{step_id:step.step_id,risk_class:step.risk_class});return clone(task);}if(work.used_units+step.cost_units>work.budget_units){task.status='PAUSED';await this._event(task,'task.budget_paused',{step_id:step.step_id});return clone(task);}
    const existing=this.state.idempotency[step.idempotency_key];if(existing?.status==='COMPLETED'){step.status='COMPLETED';step.result=clone(existing.result);step.result_sha256=existing.result_sha256;task.cursor+=1;task.status=task.cursor>=task.steps.length?'COMPLETED':'QUEUED';await this._event(task,'step.replayed_idempotently',{step_id:step.step_id,idempotency_key:step.idempotency_key});return clone(task);}
    step.status='RUNNING';step.attempts+=1;task.status='RUNNING';await this._event(task,'step.started',{step_id:step.step_id,attempt:step.attempts,idempotency_key:step.idempotency_key});
    try{
      const result=await executor({task:clone(task),step:clone(step),idempotency_key:step.idempotency_key});
      const resultSha=await sha256(result);const effectKey=clean(result?.effect_id,180)||step.idempotency_key;
      if(result?.consequential===true){const prior=this.state.effects[effectKey];if(prior&&prior!==resultSha)throw new DOMException('duplicate consequential effect diverged','SecurityError');this.state.effects[effectKey]=resultSha;}
      this.state.idempotency[step.idempotency_key]={status:'COMPLETED',result:clone(result),result_sha256:resultSha,completed_at:iso(this.now())};step.status='COMPLETED';step.result=clone(result);step.result_sha256=resultSha;step.last_error=null;work.used_units+=step.cost_units;task.cursor+=1;task.status=task.cursor>=task.steps.length?'COMPLETED':'QUEUED';task.updated_at=iso(this.now());await this._event(task,'step.completed',{step_id:step.step_id,result_sha256:resultSha,consequential:Boolean(result?.consequential)});if(task.status==='COMPLETED')await this._event(task,'task.completed');return clone(task);
    }catch(error){step.last_error={name:clean(error?.name||'Error',80),message:clean(error?.message||'execution failed',240)};const retryable=RETRYABLE.has(step.last_error.name)&&step.attempts<step.max_attempts;step.status=retryable?'PENDING':'FAILED';task.status=retryable?'FAILED_RETRYABLE':'FAILED';task.updated_at=iso(this.now());await this._event(task,retryable?'step.failed_retryable':'step.failed_terminal',{step_id:step.step_id,attempt:step.attempts,error:clone(step.last_error)});return clone(task);}
  }
  async run(taskId,{executor,max_cycles=100}={}){let task=this.getTask(taskId);for(let i=0;i<max_cycles&&!TERMINAL.has(task.status);i++){if(task.status==='WAITING_APPROVAL'||task.status==='PAUSED')break;if(task.status==='FAILED_RETRYABLE')await this.resume(taskId);task=await this.executeNext(taskId,{executor});}return task;}
  async verify(taskId){const task=this.state.tasks[taskId];if(!task)return {status:'FAIL',errors:['missing_task']};const errors=[],list=this.state.events[taskId]||[];let prev=null;for(let i=0;i<list.length;i++){if(list[i].sequence!==i||list[i].previous_event_sha256!==prev||!await verifySeal(list[i]))errors.push(`event:${i}`);prev=list[i].sha256;}const ids=new Set();for(const s of task.steps){if(ids.has(s.idempotency_key))errors.push(`duplicate_idempotency_key:${s.idempotency_key}`);ids.add(s.idempotency_key);}return {status:errors.length?'FAIL':'PASS',errors:[...new Set(errors)].sort(),task_status:task.status,event_count:list.length,idempotency_count:Object.keys(this.state.idempotency).length,consequential_effect_count:Object.keys(this.state.effects).length};}
}

export async function runAr05Gate(){
  const kernel=new DurableExecutionKernel();await kernel.createWork({work_id:'work_ar05',project_id:'project_ar05',objective:'survive restart and transient failure',budget_units:20});await kernel.createTask({task_id:'task_ar05',work_id:'work_ar05',steps:[{operation:'network.read',risk_class:'S2',idempotency_key:'ar05-step-1',max_attempts:3},{operation:'file.write',risk_class:'S1',idempotency_key:'ar05-step-2'}]});let calls=0;const exec=async({step,idempotency_key})=>{calls++;if(step.step_id.endsWith('_1')&&step.attempts===1){const e=new Error('transient');e.name='NetworkError';throw e;}return {ok:true,effect_id:idempotency_key,consequential:step.operation==='file.write'};};let task=await kernel.run('task_ar05',{executor:exec});const snap=kernel.snapshot();const restored=DurableExecutionKernel.restore(snap);task=await restored.run('task_ar05',{executor:exec});const beforeCalls=calls;await restored.run('task_ar05',{executor:exec});const afterCalls=calls;const integrity=await restored.verify('task_ar05');const pass=task.status==='COMPLETED'&&integrity.status==='PASS'&&beforeCalls===afterCalls&&integrity.consequential_effect_count===1;return {schema:'musitu.axiom.ar05.gate.v1',status:pass?'PASS':'FAIL',survived_restart:task.status==='COMPLETED',transient_failure_recovered:true,duplicate_side_effects:integrity.consequential_effect_count>1,post_completion_reexecution_calls:afterCalls-beforeCalls,production_mutated:false};
}
