import {clean, clone, deepFreeze, iso, requireText, sha256, validCommit, validSha} from './common.mjs';

export const AR11_STAGES=Object.freeze(['ISOLATED_STAGING','INTERNAL_SHADOW_TRAFFIC','INDEPENDENT_VERIFICATION','CANARY_COHORT','ROLLBACK_REHEARSAL','HUMAN_PRODUCTION_APPROVAL','GRADUAL_PRODUCTION_CUTOVER','MONITORING_HOLD','CANDIDATE_RESTORATION_TEST','CONTINUOUS_REGRESSION']);

export async function createRolloutPlan({candidate_commit,artifact_sha256,rollback_origin_commit,rollback_origin_evidence_sha256,created_at='2026-09-18T00:00:00.000Z'}={}){
  if(!validCommit(candidate_commit)||!validCommit(rollback_origin_commit))throw new TypeError('exact candidate and rollback commits required');if(!validSha(artifact_sha256)||!validSha(rollback_origin_evidence_sha256))throw new TypeError('artifact and rollback evidence sha256 required');const body={schema:'musitu.axiom.ar11.rollout-plan.v1',candidate_commit,artifact_sha256,rollback_origin_commit,rollback_origin_evidence_sha256,stage_order:[...AR11_STAGES],completed_stages:[],stage_receipts:[],status:'READY_FOR_ISOLATED_STAGING',current_production_retained:true,production_mutated:false,production_authority:false,superiority:'NOT_CERTIFIED',created_at:iso(created_at)};return deepFreeze({...body,plan_sha256:await sha256(body)});
}

export async function sealRolloutReceipt(body){const row={schema:'musitu.axiom.ar11.stage-receipt.v1',...clone(body)};return deepFreeze({...row,receipt_sha256:await sha256(row)});}

async function verifyPlan(plan){if(!plan||!validSha(plan.plan_sha256))return false;const body=Object.fromEntries(Object.entries(plan).filter(([k])=>k!=='plan_sha256'));return await sha256(body)===plan.plan_sha256&&JSON.stringify(plan.stage_order)===JSON.stringify(AR11_STAGES);}
async function verifyReceipt(receipt){if(!receipt||!validSha(receipt.receipt_sha256))return false;const body=Object.fromEntries(Object.entries(receipt).filter(([k])=>k!=='receipt_sha256'));return await sha256(body)===receipt.receipt_sha256;}

export async function advanceRollout(plan,receipt,{productionApproval=null}={}){
  if(!await verifyPlan(plan))throw new DOMException('rollout plan integrity failure','SecurityError');if(!await verifyReceipt(receipt))throw new DOMException('stage receipt integrity failure','SecurityError');const expected=AR11_STAGES[plan.completed_stages.length];if(!expected)throw new DOMException('rollout already terminal','InvalidStateError');if(receipt.stage!==expected||receipt.status!=='PASS'||receipt.candidate_commit!==plan.candidate_commit||receipt.artifact_sha256!==plan.artifact_sha256)throw new DOMException('stage receipt mismatch','SecurityError');if(!clean(receipt.actor_identity,160)||!clean(receipt.verifier_identity,160)||receipt.actor_identity===receipt.verifier_identity)throw new DOMException('distinct actor and verifier required','SecurityError');if(!validSha(receipt.evidence_sha256))throw new TypeError('stage evidence sha256 required');
  if(expected==='ROLLBACK_REHEARSAL'){if(receipt.rollback_succeeded!==true||receipt.rollback_origin_commit!==plan.rollback_origin_commit)throw new DOMException('rollback rehearsal proof required','SecurityError');}
  if(expected==='HUMAN_PRODUCTION_APPROVAL'){
    if(!productionApproval||productionApproval.authority_class!=='S4'||productionApproval.decision!=='APPROVED'||productionApproval.release_approver!==receipt.actor_identity||productionApproval.independent_verifier!==receipt.verifier_identity||productionApproval.release_approver===productionApproval.independent_verifier)throw new DOMException('exact distinct S4 production approval not bound','NotAllowedError');
  }
  if(['GRADUAL_PRODUCTION_CUTOVER','MONITORING_HOLD','CANDIDATE_RESTORATION_TEST','CONTINUOUS_REGRESSION'].includes(expected)&&!plan.completed_stages.includes('HUMAN_PRODUCTION_APPROVAL'))throw new DOMException('production approval prerequisite missing','NotAllowedError');
  if(expected==='MONITORING_HOLD'&&!(Number(receipt.clean_samples)>=3&&receipt.all_required_checks_passed===true))throw new DOMException('monitoring hold evidence incomplete','SecurityError');
  if(expected==='CANDIDATE_RESTORATION_TEST'&&receipt.candidate_restored!==true)throw new DOMException('candidate restoration proof required','SecurityError');
  const next=clone(plan);next.completed_stages.push(expected);next.stage_receipts.push(receipt.receipt_sha256);next.status=`${expected}_PASS`;if(expected==='HUMAN_PRODUCTION_APPROVAL')next.production_authority=true;if(expected==='GRADUAL_PRODUCTION_CUTOVER'){next.production_mutated=true;next.current_production_retained=false;}if(expected==='CONTINUOUS_REGRESSION')next.status='GOVERNED_RELEASE_COMPLETE';delete next.plan_sha256;return deepFreeze({...next,plan_sha256:await sha256(next)});
}

export async function runAr11CandidateGate(){
  const plan=await createRolloutPlan({candidate_commit:'a'.repeat(40),artifact_sha256:'b'.repeat(64),rollback_origin_commit:'c'.repeat(40),rollback_origin_evidence_sha256:'d'.repeat(64)});let p=plan;for(const stage of AR11_STAGES.slice(0,5)){const receipt=await sealRolloutReceipt({stage,status:'PASS',candidate_commit:p.candidate_commit,artifact_sha256:p.artifact_sha256,actor_identity:`actor-${stage}`,verifier_identity:`verifier-${stage}`,evidence_sha256:'e'.repeat(64),rollback_succeeded:stage==='ROLLBACK_REHEARSAL'?true:undefined,rollback_origin_commit:stage==='ROLLBACK_REHEARSAL'?p.rollback_origin_commit:undefined});p=await advanceRollout(p,receipt);}let approvalBlocked=false;const approvalReceipt=await sealRolloutReceipt({stage:'HUMAN_PRODUCTION_APPROVAL',status:'PASS',candidate_commit:p.candidate_commit,artifact_sha256:p.artifact_sha256,actor_identity:'release-human',verifier_identity:'independent-human',evidence_sha256:'f'.repeat(64)});try{await advanceRollout(p,approvalReceipt);}catch(e){approvalBlocked=e?.name==='NotAllowedError';}
  const pass=p.completed_stages.at(-1)==='ROLLBACK_REHEARSAL'&&approvalBlocked&&p.production_mutated===false&&p.current_production_retained===true;return {schema:'musitu.axiom.ar11.candidate-gate.v1',status:pass?'CANDIDATE_PASS_STOPPED_AT_S4_APPROVAL_BOUNDARY':'FAIL',completed_stages:[...p.completed_stages],human_production_approval_bound:false,production_cutover_executed:false,current_production_retained:p.current_production_retained,rollback_rehearsal_proven:p.completed_stages.includes('ROLLBACK_REHEARSAL'),phase_gate_earned:false,blocker:'EXACT_LIVE_S4_HUMAN_PRODUCTION_APPROVAL_AND_EXTERNAL_STAGING_CANARY_EVIDENCE_REQUIRED',superiority:'NOT_CERTIFIED',production_mutated:false};
}
