const KIT_BASE='https://payments.mftintelligence.com/chemistry/rescue';
const kitEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function kitShell({title,source,event,lead,body}){
  const link=`${KIT_BASE}?src=${source}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${kitEsc(title)} · MUSITU Chemistry Rescue 2026</title><meta name="description" content="${kitEsc(lead)}"><link rel="stylesheet" href="/chemistry/assets/storefront.css?v=3"><link rel="stylesheet" href="/chemistry/assets/rescue-print.css?v=1" media="print"><script src="/chemistry/assets/web-vitals-6.0.1.iife.js" defer></script><script src="/chemistry/assets/field-experience.js?v=1" defer></script></head><body><a class="skip-link" href="#main">Skip to main content</a><header class="site-header"><div class="wrap"><nav class="nav" aria-label="Primary"><a class="brand" href="/chemistry/">MUSITU<span>EDUCATION NEXUS</span></a><div class="nav-links"><a href="/chemistry/rescue">Chemistry Rescue</a><a href="/chemistry/support">Support</a></div></nav></div></header><main id="main" tabindex="-1" class="page-shell"><div class="wrap"><span class="eyebrow">MUSITU Chemistry Rescue 2026</span><h1>${kitEsc(title)}</h1><p class="intro">${kitEsc(lead)}</p>${body}<section class="panel"><h2>Free Rescue link</h2><p><strong>${kitEsc(link)}</strong></p><p><a class="button" data-field-event="${kitEsc(event)}" data-field-detail="${kitEsc(source)}" href="/chemistry/rescue?src=${kitEsc(source)}">Open and share the Free Rescue check</a></p><p class="muted">MUSITU Chemistry Rescue 2026 is a MUSITU Education Nexus campaign. It does not claim official ZIMSEC affiliation or endorsement.</p></section></div></main><footer class="site-footer"><div class="wrap">MUSITU Chemistry Mastery · Free Rescue access can be shared without purchasing Premium.<div class="footer-links"><a href="/chemistry/privacy">Privacy</a><a href="/chemistry/terms">Terms</a><a href="/chemistry/support">Support</a></div></div></footer><!-- @media print rules are served from the same-origin rescue-print stylesheet --></body></html>`;
}

export function renderTeacherKit(){
  return kitShell({title:'Teacher Rescue Kit',source:'wa_teacher',event:'teacher_kit',lead:'Give your A-Level Chemistry class the free MUSITU Rescue check.',body:`<section class="panel"><h2>How to use this with a class</h2><ol class="steps"><li>Share the Free Rescue link in your genuine class or revision group.</li><li>Ask learners to start with the free MUSITU Chemistry experience and identify what needs attention.</li><li>Use the results learners choose to discuss to guide revision priorities; do not require private diagnostic disclosure.</li></ol><p><strong>No purchase is required for a teacher to share the free Rescue campaign.</strong></p></section><section class="panel"><h2>WhatsApp group message</h2><p>“A-Level Chemistry students: use the free MUSITU Chemistry Rescue check to start identifying what you need to work on before exams. Free to start; no card required.”</p></section>`});
}

export function renderSchoolKit(){
  return kitShell({title:'School Rescue Pack',source:'school',event:'school_kit',lead:'Run a free A-Level Chemistry Rescue drive for your learners, then optionally upgrade interested learners through the existing School plan.',body:`<section class="panel"><h2>Suggested school rollout</h2><ol class="steps"><li>Give A-Level Chemistry learners the Free Rescue link.</li><li>Invite Chemistry teachers to use the campaign during revision planning.</li><li>Review genuine learner and teacher interest before any purchasing decision.</li><li>If useful, the existing school plan can provide paid learner access; the free campaign remains available without purchase.</li></ol></section><section class="panel"><h2>For heads of science and revision coordinators</h2><p>MUSITU is designed to complement teaching and revision. Schools should evaluate it on demonstrated learner usefulness, not marketing promises.</p></section>`});
}

export function renderAmbassadorKit(){
  return kitShell({title:'Rescue Ambassador Kit',source:'ambassador',event:'ambassador_kit',lead:'Help real A-Level Chemistry students discover the free MUSITU Rescue check through genuine peer networks.',body:`<section class="panel"><h2>Ambassador rules</h2><ul class="checklist"><li><strong>Do not spam</strong> groups, strangers or scraped contacts.</li><li>Do not create fabricated accounts, fake referrals or self-referral farms.</li><li>Do not publish fake results, guaranteed-pass claims or outcomes you did not personally experience.</li><li>Do not claim to represent ZIMSEC, a school or a teacher without authorization.</li><li>Share only where the Free Rescue check is genuinely relevant.</li></ul></section><section class="panel"><h2>What good ambassadors do</h2><p>Explain the problem MUSITU solves, show the free entry experience accurately, and invite classmates to decide for themselves.</p></section>`});
}

export const RESCUE_PRINT_CSS=`@media print{.site-header,.site-footer,.button,.skip-link{display:none!important}body{background:#fff!important;color:#000!important}.page-shell,.wrap,.panel{max-width:none!important;margin:0!important;box-shadow:none!important}.panel{break-inside:avoid;border:1px solid #999!important}}`;
