import {PRODUCT,RELEASE} from './content.mjs';
import {normalizeGrowthSource} from './rescue-growth.mjs';

const CANONICAL='https://payments.mftintelligence.com/chemistry/rescue';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function rescueShell(body){
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MUSITU Chemistry Rescue 2026</title><meta name="description" content="Find the A-Level Chemistry areas you need to work on before exams and start free with MUSITU Chemistry Mastery."><link rel="stylesheet" href="/chemistry/assets/storefront.css?v=3"><script src="/chemistry/assets/storefront.js?v=3" defer></script><script src="/chemistry/assets/web-vitals-6.0.1.iife.js" defer></script><script src="/chemistry/assets/field-experience.js?v=1" defer></script></head><body><a class="skip-link" href="#main">Skip to main content</a><header class="site-header"><div class="wrap"><nav class="nav" aria-label="Primary"><a class="brand" href="/chemistry/">MUSITU<span>EDUCATION NEXUS</span></a><div class="nav-links"><a href="/chemistry/rescue">Chemistry Rescue</a><a href="/chemistry/plans">Plans</a><a href="/chemistry/verify">Verify release</a><a href="/chemistry/support">Support</a></div></nav></div></header>${body}<div id="storefront-live" class="live-region" aria-live="polite" aria-atomic="true"></div><footer class="site-footer"><div class="wrap"><strong>${esc(PRODUCT.name)}</strong> · ${esc(PRODUCT.family)}<br><span>Free access is available without payment. Premium is issued only after verified settlement.</span><div class="footer-links"><a href="/chemistry/privacy">Privacy</a><a href="/chemistry/terms">Terms</a><a href="/chemistry/support">Support</a><a href="/chemistry/releases">Release notes</a><a href="/chemistry/experience">Experience evidence</a><a href="/chemistry/security.txt">Security</a></div></div></footer></body></html>`;
}

export function renderRescue({source='direct'}={}){
  const src=normalizeGrowthSource(source);
  const peerUrl=`${CANONICAL}?src=wa_student`;
  const shareText=`I just checked my A-Level Chemistry readiness with MUSITU. It helps me find what I need to fix before exams. Try the free MUSITU Chemistry Rescue check: ${peerUrl}`;
  const wa=`https://wa.me/?text=${encodeURIComponent(shareText)}`;
  const body=`<main id="main" tabindex="-1" data-rescue-source="${esc(src)}"><section class="hero"><div class="wrap"><span class="eyebrow">Zimbabwe · A-Level Chemistry · 2026 exam rescue</span><h1>MUSITU Chemistry Rescue 2026</h1><p class="lead"><strong>How ready are you for A-Level Chemistry? Find out free.</strong></p><p>Stop revising blindly. Start with MUSITU Chemistry Mastery, identify the areas that need work, then focus your revision where it can help most.</p><div class="cta-row"><a class="button" data-field-event="rescue_start" data-field-detail="${esc(src)}" href="/chemistry/download/${esc(RELEASE.apk)}">Start Free Rescue Check</a><a class="button secondary" data-field-event="rescue_share" data-field-detail="${esc(src)}" href="${esc(wa)}" rel="noopener noreferrer">Share with a classmate</a></div><p class="microcopy">Free to start · No card required · Android · Premium remains optional until you want the full mastery system.</p></div></section><section class="section"><div class="wrap"><h2>Find the gaps. Fix the gaps. Train under pressure.</h2><div class="journey-grid"><article><span>1</span><h3>Find</h3><p>Use the free entry experience to begin identifying where your Chemistry revision needs attention.</p></article><article><span>2</span><h3>Fix</h3><p>Work through structured Chemistry learning and targeted revision instead of treating every topic as equally weak.</p></article><article><span>3</span><h3>Prove</h3><p>Use timed practice to expose what still breaks under exam pressure.</p></article></div></div></section><section class="section"><div class="wrap"><div class="panel"><h2>Already know you want the complete system?</h2><p>Premium unlocks the full mastery experience. Prices remain server-authoritative and paid access is issued only after verified settlement.</p><a class="button secondary" data-field-event="premium_intent" data-field-detail="${esc(src)}" href="/chemistry/plans">See Premium access</a></div></div></section><section class="section"><div class="wrap"><h2>Help another Chemistry student before exams</h2><p class="intro">If MUSITU helps you identify what to work on, send the free Rescue check to one classmate. The shared message contains no private learning result.</p><a class="button" data-field-event="rescue_share" data-field-detail="${esc(src)}" href="${esc(wa)}" rel="noopener noreferrer">Share Rescue on WhatsApp</a></div></section></main>`;
  return rescueShell(body);
}

export const RESCUE_CANONICAL_URL=CANONICAL;
