#!/usr/bin/env python3
import json, pathlib, re, sys
HERE=pathlib.Path(__file__).resolve().parent
P=HERE/'ANDROID_SIDECAR_MIGRATION.json'
A=HERE/'ANDROID_SIDECAR_SOURCE_ARTIFACT.json'
S=HERE/'ANDROID_SIDECAR_PRIVATE_RELEASE_SIGNING.json'
j=json.loads(P.read_text())
a=json.loads(A.read_text())
s=json.loads(S.read_text())
checks=[]
def c(name, ok, detail=''): checks.append((name,bool(ok),detail))
def sha(v): return bool(re.fullmatch(r'[0-9a-f]{64}',str(v or '')))
def fid(v): return bool(re.fullmatch(r'file_[0-9a-f]+',str(v or '')))
c('schema',j.get('schema')=='musitu.chemistry.android_sidecar_migration.v1')
c('artifact_schema',a.get('schema')=='musitu.chemistry.android_sidecar.source_artifact.v1')
c('signing_schema',s.get('schema')=='musitu.chemistry.android_sidecar.private_release_signing.v1')
c('strategy',j.get('strategy')=='SIDE_BY_SIDE_MIGRATION')
c('legacy_package',j.get('legacy_application_id')=='com.mft.chemistry')
c('sidecar_package',j.get('sidecar_application_id')=='com.musitu.chemistry')
c('activity_preserved',j.get('preserved_native_activity')=='com.mft.chemistry.MainActivity')
for k in ['legacy_repaired_apk_sha256','legacy_repaired_certificate_sha256','baseline_frontier_unsigned_sha256','sidecar_unsigned_sha256','sidecar_v2_test_apk_sha256','sidecar_v2_test_certificate_sha256','sidecar_v2_test_content_digest_sha256']:
    c('sha256:'+k,sha(j.get(k)))
c('repair_key_not_recovered',j.get('repair_private_key_recovered') is False)
v=j.get('v2_test_signature',{})
c('v2_test_only',v.get('verified_locally') is True and v.get('production_authority') is False and v.get('private_test_key_persisted') is False)
c('v2_algorithm',v.get('algorithm_id')=='0x0103' and v.get('block_id')=='0x7109871a')
ver=j.get('verification',{})
c('red_observed',ver.get('tdd_red_observed') is True)
c('focused_40',ver.get('focused_sidecar_contract')=='40/40 PASS')
c('unsigned_14',ver.get('independent_unsigned_sidecar')=='14/14 PASS')
c('signed_14',ver.get('independent_v2_test_signed_sidecar')=='14/14 PASS')
c('deterministic',ver.get('deterministic_unsigned_rebuild') is True)
c('double_transform_fail_closed',ver.get('double_transform_fail_closed') is True)
c('v2_verified',ver.get('v2_signature_and_content_digest')=='PASS')
c('production_payload_preserved',ver.get('private_release_signed_payload_preservation')=='PASS')
c('production_v123',ver.get('private_release_v1_v2_v3')=='PASS')
m=j.get('migration_contract',{})
c('learner_schema_v2',m.get('learner_export_schema_version')==2 and m.get('learner_progress_export_import_compatible') is True)
c('commerce_separate',m.get('commercial_state_copied_between_installations') is False)
c('new_device_id',m.get('new_installation_device_id_expected') is True)
c('premium_reissue',m.get('premium_restore_or_reissue_required_for_new_device_id') is True)
b=j.get('manifest_change_boundary',{})
c('manifest_only',b.get('android_manifest_only') is True and b.get('dex_payload_changed') is False and b.get('resources_arsc_changed') is False and b.get('web_learning_assets_changed') is False)
c('debuggable_false',b.get('debuggable') is False)
pub=j.get('publication',{})
c('publication_false',pub.get('authorized') is False and pub.get('production_deployed') is False and pub.get('production_download_replaced') is False and pub.get('customer_exposed') is False)
ps=j.get('production_signing',{})
c('production_signing_recovered',ps.get('authority_recovered') is True)
c('production_cert_exact',ps.get('certificate_sha256')=='d4455ac3ec74a6d7cd7993ca640f554a83bba95dfd01ef508f7637b6bc72c0d8')
c('production_cert_lineage',ps.get('certificate_matches_rc2_rc3') is True)
c('production_signing_pointer',ps.get('private_release_signing_pointer')=='ANDROID_SIDECAR_PRIVATE_RELEASE_SIGNING.json')
c('production_signed_sha',sha(ps.get('signed_apk_sha256')) and ps.get('signed_apk_sha256')=='4ba442122d9c86a0c3cef660334fe337c6ea9ae6fe853c964b5e94961245babd')
c('production_v123_flags',ps.get('v1_verified') is True and ps.get('v2_verified') is True and ps.get('v3_verified') is True)
c('production_payload_equal',ps.get('non_signature_payload_equal') is True and ps.get('stored_alignment_failures')==0)
c('production_secret_boundary',ps.get('private_key_committed') is False and ps.get('private_key_embedded') is False)
gates=j.get('open_gates',[])
c('signing_gate_closed','durable production Android signing authority for com.musitu.chemistry' not in gates)
c('physical_gate_open','physical Android side-by-side install/relaunch/touch/offline/export/import smoke' in gates)
c('premium_gate_open','physical Premium transfer/restore validation on new Device ID' in gates)
c('publication_gate_open','explicit publication authorization' in gates)
c('source_artifact_hash',sha(a.get('artifact_sha256')) and int(a.get('artifact_bytes',0))>0 and int(a.get('artifact_file_count',0))==25)
c('artifact_unsigned_matches',a.get('unsigned_apk',{}).get('sha256')==j.get('sidecar_unsigned_sha256'))
c('artifact_v2_matches',a.get('v2_test_apk',{}).get('sha256')==j.get('sidecar_v2_test_apk_sha256'))
c('artifact_v2_cert_matches',a.get('v2_test_apk',{}).get('certificate_sha256')==j.get('sidecar_v2_test_certificate_sha256'))
c('artifact_library_id',fid(a.get('library_file_id')))
for section in ['unsigned_apk','v2_test_apk']:
    c('artifact_'+section+'_library_id',fid(a.get(section,{}).get('library_file_id')))
c('artifact_no_secrets',a.get('contains_private_keys') is False and a.get('contains_keystores') is False and a.get('contains_payment_secrets') is False and a.get('contains_licence_signing_private_key') is False)
c('artifact_no_authority',a.get('production_signing_authority') is False and a.get('publication_authority') is False and a.get('v2_test_apk',{}).get('production_authority') is False)
c('signing_app_id',s.get('application_id')==j.get('sidecar_application_id'))
c('signing_unsigned_matches',s.get('unsigned_apk_sha256')==j.get('sidecar_unsigned_sha256'))
sr=s.get('private_release_signed_apk',{})
c('signing_signed_sha_matches',sr.get('sha256')==ps.get('signed_apk_sha256') and sha(sr.get('sha256')) and int(sr.get('bytes',0))==5892286)
c('signing_signed_library_id',fid(sr.get('library_file_id')))
c('signing_cert_matches',s.get('certificate_sha256')==ps.get('certificate_sha256') and s.get('certificate_matches_rc2_rc3') is True)
c('signing_authority_recovered',s.get('private_signing_authority_recovered') is True)
c('signing_v123',s.get('v1_verified') is True and s.get('v2_verified') is True and s.get('v3_verified') is True)
c('signing_payload_alignment',s.get('non_signature_payload_equal') is True and s.get('stored_alignment_failures')==0)
c('signing_evidence_hash_id',sha(s.get('signing_evidence',{}).get('sha256')) and fid(s.get('signing_evidence',{}).get('library_file_id')))
c('v3_evidence_hash_id',sha(s.get('v3_verification',{}).get('sha256')) and fid(s.get('v3_verification',{}).get('library_file_id')))
c('signing_no_secrets',s.get('contains_private_key') is False and s.get('contains_keystore') is False and s.get('contains_password') is False)
c('signing_not_physical',s.get('physical_android_certified') is False)
c('signing_not_published',s.get('publication_authorized') is False and s.get('production_download_replaced') is False)
for bad in ['private_test_signing','sidecar-test-key.pem','.jks','.keystore','BEGIN PRIVATE KEY','MUSITU_ANDROID_SIGNING_KEY_PASSWORD']:
    c('no_private_key_reference:'+bad, all(bad not in x.read_text() for x in [P,A,S]))
failed=[x for x in checks if not x[1]]
for name,ok,detail in checks: print(('PASS' if ok else 'FAIL'),name,detail)
print(f'ANDROID_SIDECAR_RELEASE_CONTROL_CHECKS={len(checks)} PASS={len(checks)-len(failed)} FAIL={len(failed)}')
if failed: sys.exit(1)
print('MUSITU_CHEMISTRY_ANDROID_SIDECAR_RELEASE_CONTROL_PASS')
