const ISSUER_DEFAULT="https://auth.mftintelligence.com";
const RESOURCE_DEFAULT="https://mcp.mftintelligence.com";
const SCOPES=new Set(["axiom.execute","billing.read","billing.write","openid","email"]);
const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","pragma":"no-cache","x-content-type-options":"nosniff"};
function j(status,body,extra={}){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...extra}})}
function html(status,body,extra={}){return new Response(body,{status,headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","pragma":"no-cache","x-content-type-options":"nosniff","content-security-policy":"default-src 'none'; style-src 'unsafe-inline'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'","referrer-policy":"no-referrer",...extra}})}
function cfg(env){return{db:env.AXIOM_DB,issuer:env.OAUTH_ISSUER||ISSUER_DEFAULT,resource:env.MCP_RESOURCE||RESOURCE_DEFAULT}}
function iso(d=new Date()){return d.toISOString()}
function plus(seconds){return new Date(Date.now()+seconds*1000).toISOString()}
function b64url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function random(prefix,bytes=32){const a=new Uint8Array(bytes);crypto.getRandomValues(a);return prefix+b64url(a)}
async function sha256(s){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function pkce(v){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return b64url(new Uint8Array(d))}
function scopes(raw){const xs=String(raw||"").split(/\s+/).filter(Boolean);if(!xs.length)xs.push("axiom.execute");if(xs.some(x=>!SCOPES.has(x)))return null;return [...new Set(xs)].join(" ")}
function allowedRedirect(s){try{const u=new URL(s);if(u.protocol!=="https:")return false;if(u.hostname!=="chatgpt.com")return false;return u.pathname.startsWith("/connector/oauth/")||u.pathname==="/connector_platform_oauth_redirect"}catch{return false}}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function cookie(req,name){const raw=req.headers.get("cookie")||"";for(const part of raw.split(";")){const i=part.indexOf("=");if(i>0&&part.slice(0,i).trim()===name)return decodeURIComponent(part.slice(i+1).trim())}return""}
async function one(db,sql,args=[]){return await db.prepare(sql).bind(...args).first()}
async function run(db,sql,args=[]){return await db.prepare(sql).bind(...args).run()}
function errorPage(message){return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>MUSITU Axiom</title><style>body{font-family:system-ui;margin:0;background:#f6f7f8;color:#111}.c{max-width:560px;margin:8vh auto;background:white;border:1px solid #ddd;border-radius:16px;padding:28px}h1{margin-top:0}.e{padding:12px;border-radius:10px;background:#fff2f2;border:1px solid #e5bcbc}</style></head><body><main class="c"><h1>MUSITU Axiom</h1><div class="e">${esc(message)}</div><p>Return to ChatGPT and start the connection again.</p></main></body></html>`}
function consentPage(flow,scopeText){return`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connect MUSITU Axiom</title><style>body{font-family:system-ui;margin:0;background:#f6f7f8;color:#111}.c{max-width:580px;margin:7vh auto;background:#fff;border:1px solid #ddd;border-radius:18px;padding:30px}label{display:block;font-weight:650;margin:18px 0 7px}input{box-sizing:border-box;width:100%;padding:13px;border:1px solid #aaa;border-radius:10px;font:inherit}button{margin-top:20px;width:100%;padding:13px;border:0;border-radius:10px;background:#111;color:#fff;font:inherit;font-weight:700}.s{background:#f4f5f6;border-radius:10px;padding:12px;line-height:1.6}.m{color:#555;font-size:.92rem}</style></head><body><main class="c"><h1>Connect MUSITU Axiom</h1><p>Authorize ChatGPT to use your existing MUSITU Axiom account.</p><div class="s"><strong>Requested access</strong><br>${esc(scopeText.split(" ").join(" · "))}</div><form method="post" action="/oauth/authorize"><input type="hidden" name="flow_id" value="${esc(flow.id)}"><label for="key">MUSITU Axiom account key</label><input id="key" name="musitu_account_key" type="password" autocomplete="off" required><p class="m">Your account key is sent only to MUSITU over HTTPS for this authorization and is never returned to ChatGPT or stored in the authorization flow.</p><button type="submit">Authorize ChatGPT</button></form><p class="m">You can revoke the resulting OAuth session without changing your original MUSITU account key.</p></main></body></html>`}
async function discovery(c){return j(200,{issuer:c.issuer,authorization_endpoint:c.issuer+"/oauth/authorize",token_endpoint:c.issuer+"/oauth/token",registration_endpoint:c.issuer+"/oauth/register",revocation_endpoint:c.issuer+"/oauth/revoke",userinfo_endpoint:c.issuer+"/oauth/userinfo",response_types_supported:["code"],grant_types_supported:["authorization_code","refresh_token"],token_endpoint_auth_methods_supported:["none"],code_challenge_methods_supported:["S256"],scopes_supported:[...SCOPES],client_id_metadata_document_supported:false})}
async function register(req,c){let x;try{x=await req.json()}catch{return j(400,{error:"invalid_client_metadata"})}const uris=Array.isArray(x.redirect_uris)?x.redirect_uris:[];if(!uris.length||uris.length>8||uris.some(u=>!allowedRedirect(u)))return j(400,{error:"invalid_redirect_uri"});const cid=random("musitu_dcr_",24);const now=iso();await run(c.db,"INSERT INTO oauth_clients(client_id,redirect_uris_json,client_name,created_at) VALUES(?1,?2,?3,?4)",[cid,JSON.stringify([...new Set(uris)]),String(x.client_name||"ChatGPT").slice(0,160),now]);return j(201,{client_id:cid,client_id_issued_at:Math.floor(Date.now()/1000),redirect_uris:[...new Set(uris)],client_name:String(x.client_name||"ChatGPT").slice(0,160),token_endpoint_auth_method:"none",grant_types:["authorization_code","refresh_token"],response_types:["code"]})}
async function authorizeGet(req,c){const u=new URL(req.url),q=u.searchParams;if(q.get("response_type")!=="code")return html(400,errorPage("Unsupported OAuth response type."));const cid=q.get("client_id")||"",redirect=q.get("redirect_uri")||"",resource=q.get("resource")||"",challenge=q.get("code_challenge")||"",method=q.get("code_challenge_method")||"",scope=scopes(q.get("scope"));if(resource!==c.resource||method!=="S256"||challenge.length<40||!scope)return html(400,errorPage("Invalid OAuth authorization request."));const cl=await one(c.db,"SELECT redirect_uris_json FROM oauth_clients WHERE client_id=?1",[cid]);if(!cl)return html(400,errorPage("Unknown OAuth client."));let allowed=[];try{allowed=JSON.parse(cl.redirect_uris_json||"[]")}catch{}if(!allowed.includes(redirect))return html(400,errorPage("Redirect URI is not registered."));const id=random("flow_",24),csrf=random("csrf_",24),nh=await sha256(csrf),now=iso(),exp=plus(600);await run(c.db,"INSERT INTO oauth_authorization_flows(id,client_id,redirect_uri,state,resource,scope,code_challenge,nonce_hash,created_at,expires_at,used_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,NULL)",[id,cid,redirect,q.get("state")||"",resource,scope,challenge,nh,now,exp]);return html(200,consentPage({id},scope),{"set-cookie":`musitu_oauth_flow=${encodeURIComponent(csrf)}; Path=/oauth/authorize; Max-Age=600; HttpOnly; Secure; SameSite=Lax`})}
async function authorizePost(req,c){const f=await req.formData(),id=String(f.get("flow_id")||""),accountKey=String(f.get("musitu_account_key")||""),csrf=cookie(req,"musitu_oauth_flow");if(!id||!accountKey||!csrf)return html(400,errorPage("Authorization session is incomplete."));const flow=await one(c.db,"SELECT * FROM oauth_authorization_flows WHERE id=?1",[id]);if(!flow||flow.used_at||flow.expires_at<=iso()||flow.nonce_hash!==await sha256(csrf))return html(400,errorPage("Authorization session expired or invalid."));const kh=await sha256(accountKey);const user=await one(c.db,"SELECT k.id AS source_key_id,k.customer_id,c.email,c.plan FROM api_keys k JOIN customers c ON c.id=k.customer_id WHERE k.key_hash=?1 AND k.status='active' AND c.status='active' AND (k.expires_at IS NULL OR k.expires_at>?2) LIMIT 1",[kh,iso()]);if(!user)return html(401,errorPage("MUSITU account authentication failed."));const rawCode=random("musitu_oauth_code_",32),ch=await sha256(rawCode),now=iso();await c.db.batch([c.db.prepare("INSERT INTO oauth_authorization_codes(code_hash,client_id,customer_id,redirect_uri,resource,scope,code_challenge,created_at,expires_at,used_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,NULL)").bind(ch,flow.client_id,user.customer_id,flow.redirect_uri,flow.resource,flow.scope,flow.code_challenge,now,plus(300)),c.db.prepare("UPDATE oauth_authorization_flows SET used_at=?2 WHERE id=?1 AND used_at IS NULL").bind(id,now)]);const r=new URL(flow.redirect_uri);r.searchParams.set("code",rawCode);if(flow.state)r.searchParams.set("state",flow.state);return new Response(null,{status:302,headers:{location:r.toString(),"cache-control":"no-store","set-cookie":"musitu_oauth_flow=; Path=/oauth/authorize; Max-Age=0; HttpOnly; Secure; SameSite=Lax"}})}
async function mint(c,row,clientId,scopeText){const access=random("musitu_oauth_at_",36),refresh=random("musitu_oauth_rt_",40),accessHash=await sha256(access),refreshHash=await sha256(refresh),keyId="oauth_access_"+crypto.randomUUID().replaceAll("-",""),now=iso(),aexp=plus(3600),rexp=plus(2592000),prefix=access.slice(0,16);await c.db.batch([c.db.prepare("INSERT INTO api_keys(id,customer_id,key_hash,key_prefix,label,status,created_at,last_used_at,expires_at,revoked_at) VALUES(?1,?2,?3,?4,'chatgpt-oauth-access','active',?5,NULL,?6,NULL)").bind(keyId,row.customer_id,accessHash,prefix,now,aexp),c.db.prepare("INSERT INTO oauth_access_tokens(token_hash,api_key_id,client_id,customer_id,issuer,resource,scope,created_at,expires_at,revoked_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?9,NULL)").bind(accessHash,keyId,clientId,row.customer_id,c.issuer,c.resource,scopeText,now,aexp),c.db.prepare("INSERT INTO oauth_refresh_tokens(token_hash,api_key_id,client_id,customer_id,resource,scope,created_at,expires_at,revoked_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,NULL)").bind(refreshHash,keyId,clientId,row.customer_id,c.resource,scopeText,now,rexp)]);return{access_token:access,token_type:"Bearer",expires_in:3600,refresh_token:refresh,scope:scopeText,resource:c.resource}}
async function token(req,c){const f=await req.formData(),grant=String(f.get("grant_type")||""),cid=String(f.get("client_id")||""),resource=String(f.get("resource")||"");if(resource!==c.resource)return j(400,{error:"invalid_target"});const client=await one(c.db,"SELECT client_id FROM oauth_clients WHERE client_id=?1",[cid]);if(!client)return j(401,{error:"invalid_client"});if(grant==="authorization_code"){const code=String(f.get("code")||""),verifier=String(f.get("code_verifier")||""),redirect=String(f.get("redirect_uri")||"");if(!code||verifier.length<43)return j(400,{error:"invalid_grant"});const ch=await sha256(code),row=await one(c.db,"SELECT * FROM oauth_authorization_codes WHERE code_hash=?1",[ch]);if(!row||row.used_at||row.expires_at<=iso()||row.client_id!==cid||row.redirect_uri!==redirect||row.resource!==resource||await pkce(verifier)!==row.code_challenge)return j(400,{error:"invalid_grant"});const used=await run(c.db,"UPDATE oauth_authorization_codes SET used_at=?2 WHERE code_hash=?1 AND used_at IS NULL AND expires_at>?2",[ch,iso()]);if(Number(used.meta?.changes||0)!==1)return j(400,{error:"invalid_grant"});return j(200,await mint(c,row,cid,row.scope))}
if(grant==="refresh_token"){const rt=String(f.get("refresh_token")||"");if(!rt)return j(400,{error:"invalid_grant"});const rh=await sha256(rt),row=await one(c.db,"SELECT * FROM oauth_refresh_tokens WHERE token_hash=?1",[rh]);if(!row||row.revoked_at||row.expires_at<=iso()||row.client_id!==cid||row.resource!==resource)return j(400,{error:"invalid_grant"});const now=iso(),used=await run(c.db,"UPDATE oauth_refresh_tokens SET revoked_at=?2 WHERE token_hash=?1 AND revoked_at IS NULL",[rh,now]);if(Number(used.meta?.changes||0)!==1)return j(400,{error:"invalid_grant"});await c.db.batch([c.db.prepare("UPDATE oauth_access_tokens SET revoked_at=?2 WHERE api_key_id=?1 AND revoked_at IS NULL").bind(row.api_key_id,now),c.db.prepare("UPDATE api_keys SET status='revoked',revoked_at=?2 WHERE id=?1 AND status='active'").bind(row.api_key_id,now)]);return j(200,await mint(c,row,cid,row.scope))}return j(400,{error:"unsupported_grant_type"})}
function bearer(req){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")&&a.length>12?a.slice(7):""}
function scopeSet(raw){return new Set(String(raw||"").split(/\s+/).filter(Boolean))}
async function userinfo(req,c){const tok=bearer(req);if(!tok)return j(401,{error:"invalid_token"},{"www-authenticate":'Bearer error="invalid_token"'});const h=await sha256(tok),now=iso();const row=await one(c.db,"SELECT a.customer_id,a.issuer,a.resource,a.scope,a.expires_at,a.revoked_at,k.status AS key_status,k.expires_at AS key_expires,k.revoked_at AS key_revoked,cu.email,i.email_verified_at FROM oauth_access_tokens a JOIN api_keys k ON k.id=a.api_key_id JOIN customers cu ON cu.id=a.customer_id LEFT JOIN oauth_identity_claims i ON i.customer_id=a.customer_id WHERE a.token_hash=?1 LIMIT 1",[h]);if(!row||row.revoked_at||row.key_revoked||row.key_status!=="active"||row.expires_at<=now||(row.key_expires&&row.key_expires<=now)||row.issuer!==c.issuer||row.resource!==c.resource)return j(401,{error:"invalid_token"},{"www-authenticate":'Bearer error="invalid_token"'});const ss=scopeSet(row.scope);if(!ss.has("openid")||!ss.has("email"))return j(403,{error:"insufficient_scope"},{"www-authenticate":'Bearer error="insufficient_scope", scope="openid email"'});const sub=await sha256(c.issuer+"\n"+row.customer_id),mail=String(row.email||"");return j(200,{sub,email:mail,email_verified:Boolean(mail&&row.email_verified_at)})}
async function revoke(req,c){const f=await req.formData(),tok=String(f.get("token")||"");if(!tok)return j(200,{});const h=await sha256(tok),now=iso();const a=await one(c.db,"SELECT api_key_id FROM oauth_access_tokens WHERE token_hash=?1",[h]);if(a)await c.db.batch([c.db.prepare("UPDATE oauth_access_tokens SET revoked_at=?2 WHERE token_hash=?1 AND revoked_at IS NULL").bind(h,now),c.db.prepare("UPDATE api_keys SET status='revoked',revoked_at=?2 WHERE id=?1 AND status='active'").bind(a.api_key_id,now),c.db.prepare("UPDATE oauth_refresh_tokens SET revoked_at=?2 WHERE api_key_id=?1 AND revoked_at IS NULL").bind(a.api_key_id,now)]);const r=await one(c.db,"SELECT api_key_id FROM oauth_refresh_tokens WHERE token_hash=?1",[h]);if(r)await c.db.batch([c.db.prepare("UPDATE oauth_refresh_tokens SET revoked_at=?2 WHERE token_hash=?1 AND revoked_at IS NULL").bind(h,now),c.db.prepare("UPDATE oauth_access_tokens SET revoked_at=?2 WHERE api_key_id=?1 AND revoked_at IS NULL").bind(r.api_key_id,now),c.db.prepare("UPDATE api_keys SET status='revoked',revoked_at=?2 WHERE id=?1 AND status='active'").bind(r.api_key_id,now)]);return j(200,{})}
export default{async fetch(req,env){const c=cfg(env),u=new URL(req.url);if(!c.db)return j(503,{error:"database_unavailable"});if(u.pathname==="/.well-known/oauth-authorization-server"&&req.method==="GET")return discovery(c);if(u.pathname==="/oauth/register"&&req.method==="POST")return register(req,c);if(u.pathname==="/oauth/authorize"&&req.method==="GET")return authorizeGet(req,c);if(u.pathname==="/oauth/authorize"&&req.method==="POST")return authorizePost(req,c);if(u.pathname==="/oauth/token"&&req.method==="POST")return token(req,c);if(u.pathname==="/oauth/userinfo"&&(req.method==="GET"||req.method==="POST"))return userinfo(req,c);if(u.pathname==="/oauth/revoke"&&req.method==="POST")return revoke(req,c);if(u.pathname==="/health"&&req.method==="GET"){const x=await one(c.db,"SELECT count(*) AS n FROM oauth_clients");return j(200,{ok:true,service:"MUSITU Axiom OAuth 2.1",issuer:c.issuer,resource:c.resource,dcr:true,pkce_s256:true,userinfo:true,identity_scopes:["openid","email"],public_client_token_auth:"none",registered_clients:Number(x?.n||0)})}return j(404,{error:"not_found"})}};
