const VERSION="1.0.1";
const MODERN_PROTOCOL="2026-07-28";
const SERVER_INFO_KEY="io.modelcontextprotocol/serverInfo";
const PROTOCOL_META_KEY="io.modelcontextprotocol/protocolVersion";
const SERVER_INSTRUCTIONS="Private isolated MUSITU Axiom Operator Reviewer. Production/public submission authority is false.";
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
function out(status,body,extra={}){return new Response(JSON.stringify(body),{status,headers:{...H,...extra}})}
function serverMeta(){return{[SERVER_INFO_KEY]:{name:"musitu-axiom-operator-reviewer",version:VERSION}}}
function isModern(req,m){return m?.method==="server/discover"||req.headers.get("mcp-protocol-version")===MODERN_PROTOCOL||m?.params?._meta?.[PROTOCOL_META_KEY]===MODERN_PROTOCOL}
function discover(id){return out(200,{jsonrpc:"2.0",id,result:{resultType:"complete",supportedVersions:[MODERN_PROTOCOL],capabilities:{tools:{listChanged:false}},instructions:SERVER_INSTRUCTIONS,ttlMs:60000,cacheScope:"public",_meta:serverMeta()}})}
async function modernizeResponse(r,modern,cacheable=false){if(!modern)return r;const text=await r.text();let o;try{o=JSON.parse(text||"{}")}catch{return new Response(text,{status:r.status,headers:r.headers})}if(o?.result&&typeof o.result==="object"&&!Array.isArray(o.result)){const meta=o.result._meta&&typeof o.result._meta==="object"?o.result._meta:{};o.result.resultType=o.result.resultType||"complete";if(cacheable){o.result.ttlMs=Number.isInteger(o.result.ttlMs)?o.result.ttlMs:60000;o.result.cacheScope=o.result.cacheScope||"public"}o.result._meta={...meta,...serverMeta()}}return new Response(JSON.stringify(o),{status:r.status,headers:r.headers})}
function cfg(env){return{db:env.AXIOM_DB,issuer:env.AUTH_ISSUER||"",resource:env.MCP_PUBLIC_BASE||"",modal:env.MODAL_OPERATOR_URL||"",key:env.MODAL_PROXY_KEY||"",secret:env.MODAL_PROXY_SECRET||""}}
async function sha(s){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function bearer(req){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")&&a.length>12?a.slice(7):""}
function challenge(c){return `Bearer resource_metadata="${c.resource}/.well-known/oauth-protected-resource", scope="axiom.operator.execute", error="insufficient_scope", error_description="Connect the isolated MUSITU Axiom Operator Reviewer"`}
async function validate(req,c){const token=bearer(req);if(!token)return{ok:false,reason:"missing_token"};const th=await sha(token),now=new Date().toISOString();const row=await c.db.prepare("SELECT a.customer_id,a.issuer,a.resource,a.scope,a.expires_at,a.revoked_at,k.status AS key_status,k.expires_at AS key_expires,k.revoked_at AS key_revoked FROM oprev_oauth_access_tokens a JOIN oprev_api_keys k ON k.id=a.api_key_id WHERE a.token_hash=?1 LIMIT 1").bind(th).first();if(!row)return{ok:false,reason:"unknown_token"};if(row.revoked_at||row.key_revoked||row.key_status!=="active")return{ok:false,reason:"revoked_token"};if(row.expires_at<=now||(row.key_expires&&row.key_expires<=now))return{ok:false,reason:"expired_token"};if(row.issuer!==c.issuer||row.resource!==c.resource)return{ok:false,reason:"issuer_or_audience_mismatch"};const ss=new Set(String(row.scope||"").split(/\s+/).filter(Boolean));if(!ss.has("axiom.operator.execute"))return{ok:false,reason:"insufficient_scope"};return{ok:true,customer_id:row.customer_id}}
function modalHeaders(c,extra={}){return{"authorization":"Bearer "+c.key+"."+c.secret,...extra}}
async function modal(c,body){const extra={"content-type":"application/json","accept":"application/json","mcp-protocol-version":"2026-07-28","mcp-method":String(body?.method||"")};if(body?.method==="tools/call")extra["mcp-name"]=String(body?.params?.name||"");const r=await fetch(c.modal.replace(/\/$/,"")+"/mcp",{method:"POST",headers:modalHeaders(c,extra),body:JSON.stringify(body)});const text=await r.text();let obj={};try{obj=JSON.parse(text||"{}")}catch{return{status:502,obj:{jsonrpc:"2.0",id:body?.id??null,error:{code:-32603,message:"Operator runtime returned invalid JSON"}}}}return{status:r.status,obj}}
async function toolsList(c,id){const x=await modal(c,{jsonrpc:"2.0",id,method:"tools/list",params:{_meta:{"io.modelcontextprotocol/protocolVersion":"2026-07-28"}}});if(x.status!==200)return out(200,{jsonrpc:"2.0",id,error:{code:-32603,message:"Operator registry unavailable"}});const tools=x.obj?.result?.tools||[];return out(200,{jsonrpc:"2.0",id,result:{tools}})}
async function toolCall(req,c,m,id){const v=await validate(req,c);if(!v.ok)return out(200,{jsonrpc:"2.0",id,result:{content:[{type:"text",text:"Connect the isolated MUSITU Axiom Operator Reviewer to use this capability."}],structuredContent:{authenticated:false,required_scope:"axiom.operator.execute"},_meta:{"mcp/www_authenticate":[challenge(c)]},isError:true}});const x=await modal(c,m);return out(200,x.obj)}
async function health(c){let db=false,modalOk=false;try{await c.db.prepare("SELECT 1 FROM oprev_oauth_access_tokens LIMIT 1").first();db=true}catch{};try{const r=await fetch(c.modal.replace(/\/$/,"")+"/health",{headers:modalHeaders(c)});modalOk=r.status===200}catch{}return{ok:db&&modalOk,service:"MUSITU Axiom Operator Reviewer Gate",server_version:VERSION,oauth_enforced:true,auth_issuer:c.issuer,resource:c.resource,oauth_db_ready:db,operator_runtime_ready:modalOk,production_authority:false,public_submission_mutation_authority:false}}
export default{async fetch(req,env){const c=cfg(env),u=new URL(req.url);if(!c.db||!c.issuer||!c.resource||!c.modal||!c.key||!c.secret)return out(503,{error:"operator_reviewer_gate_not_configured"});if(u.pathname==="/health"&&req.method==="GET"){const h=await health(c);return out(h.ok?200:503,h)}if(u.pathname==="/.well-known/oauth-protected-resource"&&req.method==="GET")return out(200,{resource:c.resource,authorization_servers:[c.issuer],scopes_supported:["axiom.operator.execute"],resource_documentation:c.resource+"/docs"});if(u.pathname==="/docs"&&req.method==="GET")return out(200,{service:"MUSITU Axiom Operator Reviewer",private_reviewer:true,scope:"axiom.operator.execute",production_authority:false});if(u.pathname!=="/mcp")return out(404,{error:"not_found"});if(req.method!=="POST")return out(405,{error:"method_not_allowed"},{allow:"POST"});let m;try{m=await req.json()}catch{return out(200,{jsonrpc:"2.0",id:null,error:{code:-32700,message:"Parse error"}})}const id=m?.id??null,modern=isModern(req,m);if(m?.method==="server/discover")return discover(id);if(m?.method==="initialize")return out(200,{jsonrpc:"2.0",id,result:{protocolVersion:m?.params?.protocolVersion||MODERN_PROTOCOL,capabilities:{tools:{listChanged:false}},serverInfo:{name:"musitu-axiom-operator-reviewer",version:VERSION},instructions:SERVER_INSTRUCTIONS}});if(m?.method==="tools/list")return modernizeResponse(await toolsList(c,id),modern,true);if(m?.method==="tools/call")return modernizeResponse(await toolCall(req,c,m,id),modern,false);return out(200,{jsonrpc:"2.0",id,error:{code:-32601,message:"Method not found"}})}};