import {normalizeContextEdge,normalizeContextNode,sha256} from './deep_context_security.js';
import {buildSystemGraph,retrieveContext,verifySystemGraph} from './system_graph.js';
const DB='musitu-axiom-deep-context-v1',VERSION=1,WRITERS=new Set(['owner','editor']);
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const clone=value=>structuredClone(value),clean=(value,limit=180)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,limit);
function nodeInput(row){return {projectId:row.project_id,nodeId:row.node_id,domain:row.domain,title:row.title,sourceType:row.source_type,sourceId:row.source_id,sourceUri:row.source_uri,trust:row.trust,content:row.content,metadata:row.metadata,asOf:row.as_of,retrievedAt:row.retrieved_at};}
function edgeInput(row){return {projectId:row.project_id,edgeId:row.edge_id,fromId:row.from_id,toId:row.to_id,relation:row.relation,provenanceSource:row.provenance_source};}
export class DeepContextStore{
  constructor(db,{projects}){this.db=db;this.projects=projects;this.serial=Promise.resolve();}
  static async open({projects}={}){if(!projects?.getProject||!projects?.graph)throw new TypeError('earned ProjectStore required');const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('nodes')){const store=db.createObjectStore('nodes',{keyPath:'node_id'});store.createIndex('project_id','project_id',{unique:false});}if(!db.objectStoreNames.contains('edges')){const store=db.createObjectStore('edges',{keyPath:'edge_id'});store.createIndex('project_id','project_id',{unique:false});}if(!db.objectStoreNames.contains('events')){const store=db.createObjectStore('events',{keyPath:'event_id'});store.createIndex('project_id','project_id',{unique:false});}};return new DeepContextStore(await req(request),{projects});}
  close(){this.db.close();}
  _queue(task){const next=this.serial.then(task,task);this.serial=next.catch(()=>{});return next;}
  async _all(store,projectId){const tx=this.db.transaction(store,'readonly'),rows=await req(tx.objectStore(store).index('project_id').getAll(projectId));await done(tx);return rows.map(clone);}
  async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
  async _add(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).add(clone(row));await done(tx);return clone(row);}
  async _project(projectId,actorId,{write=false}={}){projectId=clean(projectId);actorId=clean(actorId);const project=await this.projects.getProject(projectId);if(!project)throw new DOMException('project not found','NotFoundError');const role=project.permissions?.find(row=>row.principal_id===actorId)?.role;if(!role||write&&!WRITERS.has(role))throw new DOMException('project context permission denied','NotAllowedError');return project;}
  async _event(projectId,actorId,kind,payload={}){const history=(await this._all('events',projectId)).sort((a,b)=>a.sequence-b.sequence),body={schema:'musitu.axiom.deep-context-event.browser.v1',event_id:`deep-context-event:${projectId}:${history.length}`,project_id:projectId,sequence:history.length,kind:clean(kind,80),actor_id:clean(actorId),payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:history.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};await this._add('events',row);return row;}
  async ingest(raw,actorId='local-user'){return this._queue(async()=>{const row=await normalizeContextNode(raw);await this._project(row.project_id,actorId,{write:true});const existing=await this._get('nodes',row.node_id);if(existing){if(existing.node_sha256===row.node_sha256)return existing;throw new DOMException('context node identity already exists with different content; use a new versioned id','ConstraintError');}await this._add('nodes',row);await this._event(row.project_id,actorId,'context.node.indexed',{node_id:row.node_id,node_sha256:row.node_sha256,domain:row.domain,authority_effect:row.authority_effect});return row;});}
  async link(raw,actorId='local-user'){return this._queue(async()=>{const row=await normalizeContextEdge(raw);await this._project(row.project_id,actorId,{write:true});const [from,to]=await Promise.all([this._get('nodes',row.from_id),this._get('nodes',row.to_id)]);if(!from||!to||from.project_id!==row.project_id||to.project_id!==row.project_id||from.node_id===to.node_id)throw new DOMException('context edge endpoints must be distinct in-project indexed nodes','SecurityError');const existing=await this._get('edges',row.edge_id);if(existing){if(existing.edge_sha256===row.edge_sha256)return existing;throw new DOMException('context edge identity already exists with different content; use a new versioned id','ConstraintError');}await this._add('edges',row);await this._event(row.project_id,actorId,'context.edge.indexed',{edge_id:row.edge_id,edge_sha256:row.edge_sha256,relation:row.relation,authority_effect:row.authority_effect});return row;});}
  async ingestProjection({projectId,records=[],edges=[]}={},actorId='local-user'){await this._project(projectId,actorId,{write:true});for(const row of records)await this.ingest(row,actorId);for(const row of edges)await this.link(row,actorId);return {nodes:(await this._all('nodes',projectId)).length,edges:(await this._all('edges',projectId)).length};}
  async eventIntegrity(projectId,actorId='local-user'){await this._project(projectId,actorId);const events=(await this._all('events',projectId)).sort((a,b)=>a.sequence-b.sequence),errors=[];let previous=null;for(let i=0;i<events.length;i++){const row=events[i],body=Object.fromEntries(Object.entries(row).filter(([key])=>key!=='event_sha256'));if(row.sequence!==i||row.previous_event_sha256!==previous||await sha256(body)!==row.event_sha256)errors.push(`event_chain:${i}`);previous=row.event_sha256;}const result={schema:'musitu.axiom.deep-context-event-integrity.browser.v1',project_id:projectId,status:errors.length?'FAIL':'PASS',event_count:events.length,event_chain_tip_sha256:previous,errors:[...new Set(errors)].sort()};result.integrity_sha256=await sha256(result);return result;}
  async snapshot(projectId,actorId='local-user',authorityEnvelope={}){await this._project(projectId,actorId);const [nodes,edges,eventIntegrity]=await Promise.all([this._all('nodes',projectId),this._all('edges',projectId),this.eventIntegrity(projectId,actorId)]);if(eventIntegrity.status!=='PASS')throw new DOMException('deep context event chain integrity failed','SecurityError');const graph=await buildSystemGraph({projectId,nodes:nodes.map(nodeInput),edges:edges.map(edgeInput),authorityEnvelope});return {...graph,event_integrity:eventIntegrity};}
  async verify(projectId,actorId='local-user',authorityEnvelope={}){try{const graph=await this.snapshot(projectId,actorId,authorityEnvelope),graphIntegrity=await verifySystemGraph(graph);return {schema:'musitu.axiom.deep-context-store-integrity.browser.v1',project_id:projectId,status:graphIntegrity.status==='PASS'&&graph.event_integrity.status==='PASS'?'PASS':'FAIL',graph_integrity:graphIntegrity,event_integrity:graph.event_integrity};}catch(error){return {schema:'musitu.axiom.deep-context-store-integrity.browser.v1',project_id:projectId,status:'FAIL',graph_integrity:{status:'FAIL',errors:[clean(error?.message||'context verification failed',240)]},event_integrity:{status:'FAIL',errors:['snapshot_unavailable']}};}}
  async search(projectId,query,{actorId='local-user',authorityEnvelope={},domains,limit=12}={}){const graph=await this.snapshot(projectId,actorId,authorityEnvelope);return retrieveContext(graph,query,{domains,limit});}
}
