import {ProjectStore} from '../projects.js';
import {ResearchClaimStore} from '../research_claims.js';
import {ObservabilityStore} from '../observability.js';
import {CONTEXT_DOMAINS,sha256} from './deep_context_security.js';
import {composeEarnedContext} from './deep_context_adapters.js';
import {DeepContextStore} from './deep_context_store.js';
const $=(selector,root=document)=>root.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])),clean=(value,limit=1000)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,limit),route=()=>((location.hash.match(/^#\/([^/?#]+)/)||[])[1]||'home'),activeProjectId=()=>{try{return localStorage.getItem('axiom.vnext.active-project')||''}catch{return ''}};
const AUTHORITY_ENVELOPE=Object.freeze({schema:'musitu.axiom.fa10-context-guard.browser.v1',actor_id:'local-user',authority_source:'GOVERNED_RUNTIME_NOT_RETRIEVED_CONTENT',risk_class:'S1',execution_mode:'CONTEXT_READ_INDEX_ONLY_NO_ACTION',network_policy:'NO_NEW_EXTERNAL_NETWORK_AUTHORITY',credential_policy:'NO_PLAINTEXT_SECRETS',approval_policy:'EXISTING_GOVERNED_POLICIES_UNCHANGED',production_authority:false});
let projects=null,research=null,observability=null,context=null,opening=null,scheduled=false;
async function open(){if(context)return context;if(opening)return opening;opening=(async()=>{projects=await ProjectStore.open();research=await ResearchClaimStore.open();observability=await ObservabilityStore.open();context=await DeepContextStore.open({projects});return context;})();try{return await opening}finally{opening=null}}
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;void render();});}
async function earnedProjection(projectId){const projectGraph=await projects.graph(projectId);let researchSnapshot=null;try{researchSnapshot=await research.snapshot(projectId);}catch{}const runs=(await observability.listRuns()).filter(row=>row.project_id===projectId).slice(0,40),replays=[];for(const run of runs)try{replays.push(await observability.replay(run.run_id));}catch{}return composeEarnedContext({projectGraph,researchSnapshot,observabilityReplays:replays});}
function coverageHtml(coverage={}){return CONTEXT_DOMAINS.map(domain=>`<div class="metric"><strong>${Number(coverage[domain]||0)}</strong><span>${esc(domain)}</span></div>`).join('');}
function resultHtml(result){return result.results.length?result.results.map(row=>`<article class="list-row"><span><strong>${esc(row.title)}</strong><small>${esc(row.domain)} · ${esc(row.trust)} · score ${row.score}${row.injection_flags.length?` · flags ${esc(row.injection_flags.join(', '))}`:''}</small></span><span class="badge ok">Data only</span></article>`).join(''):'<div class="card"><p>No matching verified local context.</p></div>';}
async function render(){if(route()!=='developer')return;const root=$('#workspace-root');if(!root||$('#vnext-deep-context',root))return;const projectId=activeProjectId();if(!projectId)return;try{await open();const integrity=await context.verify(projectId,'local-user',AUTHORITY_ENVELOPE),graph=integrity.status==='PASS'?await context.snapshot(projectId,'local-user',AUTHORITY_ENVELOPE):null,section=document.createElement('section');section.id='vnext-deep-context';section.className='section';section.setAttribute('aria-labelledby','vnext-deep-context-title');section.innerHTML=`<div class="card"><div class="card-top"><div><small class="eyebrow">FA-10 · Deep Context & System Graph</small><h2 id="vnext-deep-context-title">Deep Context</h2><p>Code, runtime, data, infrastructure, traces, requirements and evidence are indexed as provenance-bound data. Retrieved instructions never become authority.</p></div><span class="badge ${integrity.status==='PASS'?'ok':'warn'}">${esc(integrity.status)}</span></div><p class="muted">Local index only · no external fetch · authority envelope unchanged by context.</p><p><button id="vnext-context-sync" class="button primary" type="button">Sync earned local context</button></p></div><div class="metric-grid">${coverageHtml(graph?.domain_coverage)}</div><section class="section"><div class="card-grid"><form id="vnext-context-search" class="card"><small class="eyebrow">Local retrieval</small><h3>Search verified context</h3><label>Query<input id="vnext-context-query" maxlength="500" placeholder="dependency, trace, requirement…"></label><button class="button secondary" type="submit">Retrieve references</button></form><form id="vnext-context-add" class="card"><small class="eyebrow">Inert record</small><h3>Add project context</h3><label>Domain<select id="vnext-context-domain">${CONTEXT_DOMAINS.map(domain=>`<option>${esc(domain)}</option>`).join('')}</select></label><label>Title<input id="vnext-context-title" maxlength="240" required></label><label>Content<textarea id="vnext-context-content" maxlength="8000" rows="3" required></textarea></label><button class="button secondary" type="submit">Index as data only</button></form></div></section><section class="section"><div id="vnext-context-results" class="list" role="status" aria-live="polite"></div></section>`;root.append(section);bind(section,projectId);}catch(reason){const section=document.createElement('section');section.id='vnext-deep-context';section.className='section';section.innerHTML=`<div class="card"><h2>Deep Context unavailable</h2><p>${esc(clean(reason?.message||'Unable to open local context graph',240))}</p></div>`;root.append(section);}}
function bind(section,projectId){const status=$('#vnext-context-results',section);$('#vnext-context-sync',section)?.addEventListener('click',()=>void(async()=>{try{const projection=await earnedProjection(projectId);await context.ingestProjection(projection,'local-user');status.innerHTML='<div class="card"><strong>Earned local context synchronized.</strong><p>No retrieved content was granted authority.</p></div>';section.remove();schedule();}catch(reason){status.innerHTML=`<div class="card"><strong>Sync blocked</strong><p>${esc(clean(reason?.message,240))}</p></div>`;}})());$('#vnext-context-search',section)?.addEventListener('submit',event=>void(async()=>{event.preventDefault();try{const result=await context.search(projectId,$('#vnext-context-query',section).value,{actorId:'local-user',authorityEnvelope:AUTHORITY_ENVELOPE,limit:20});status.innerHTML=resultHtml(result);}catch(reason){status.innerHTML=`<div class="card"><strong>Retrieval blocked</strong><p>${esc(clean(reason?.message,240))}</p></div>`;}})());$('#vnext-context-add',section)?.addEventListener('submit',event=>void(async()=>{event.preventDefault();try{const content=$('#vnext-context-content',section).value,domain=$('#vnext-context-domain',section).value,title=$('#vnext-context-title',section).value,digest=await sha256({domain,title,content,at:new Date().toISOString()});await context.ingest({projectId,nodeId:`ctx:user:${digest.slice(0,24)}`,domain,title,sourceType:'user-context',sourceId:`user:${digest.slice(0,24)}`,trust:'USER_PROVIDED',content,metadata:{authority_source:'NONE_USER_CONTEXT_DATA_ONLY'},retrievedAt:new Date().toISOString()},'local-user');status.innerHTML='<div class="card"><strong>Context indexed as inert project data.</strong></div>';section.remove();schedule();}catch(reason){status.innerHTML=`<div class="card"><strong>Indexing blocked</strong><p>${esc(clean(reason?.message,240))}</p></div>`;}})());}
window.addEventListener('hashchange',schedule);const observer=new MutationObserver(()=>{if(route()==='developer'&&!$('#vnext-deep-context'))schedule();});observer.observe($('#workspace-root')||document.body,{childList:true});schedule();window.AxiomDeepContext=Object.freeze({refresh:schedule,retrieval_mode:'BROWSER_LOCAL_INDEX_ONLY_NO_EXTERNAL_FETCH',instruction_authority:'NONE_RETRIEVED_DATA_ONLY',authority_effect:'NONE'});
