export const CONTEXT_DOMAINS=Object.freeze(['code','runtime','data','infra','trace','requirement','evidence']);
export const CONTEXT_TRUST=Object.freeze(['FIRST_PARTY_EARNED_STORE','FIRST_PARTY_STATIC_DESCRIPTOR','USER_PROVIDED','RETRIEVED_UNTRUSTED','DERIVED_INDEX']);
export const CONTEXT_RELATIONS=Object.freeze(['depends-on','references','derived-from','observed-in','verified-by','implements','deployed-as']);
export const INSTRUCTION_AUTHORITY='NONE_RETRIEVED_DATA_ONLY';
export const AUTHORITY_EFFECT='NONE';
export const RETRIEVAL_MODE='BROWSER_LOCAL_INDEX_ONLY_NO_EXTERNAL_FETCH';
export const NETWORK_POLICY='NO_NEW_EXTERNAL_NETWORK_AUTHORITY';
const SECRET_RX=/(?:api[_ -]?key|access[_ -]?token|refresh[_ -]?token|password|private[_ -]?key|authorization)\s*[:=]|\b(?:sk|ghp|github_pat)_[A-Za-z0-9_-]{12,}|\bbearer\s+[A-Za-z0-9._~-]{12,}/i;
const AUTHORITY_KEY_RX=/(?:^|_)(?:authority|authoriz(?:e|ed|ation)|permissions?|scopes?|roles?|autonomy|risk(?:_class)?|approvals?|network|egress|secrets?|credentials?|tokens?|execution|production|deploy(?:ment)?|qualification|certif(?:y|ied|ication)|claim_authorization|polic(?:y|ies)|system_prompt|developer_message)(?:$|_)/i;
export const clean=(value,limit=1000)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,limit);
export const canonical=value=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`:JSON.stringify(value);
export async function sha256(value){const bytes=new TextEncoder().encode(canonical(value)),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}
export function rejectSecretLike(value,label='context'){if(SECRET_RX.test(typeof value==='string'?value:canonical(value)))throw new DOMException(`${label} contains forbidden plaintext secret-like material`,'SecurityError');}
function exact(value,allowed,label){const out=clean(value,80).toLowerCase();if(!allowed.includes(out))throw new TypeError(`${label} is invalid`);return out;}
function safeId(value,label){const out=clean(value,180);if(!out)throw new TypeError(`${label} required`);return out;}
function timestamp(value,label,{nullable=false}={}){if((value==null||value==='')&&nullable)return null;const out=clean(value,96),time=Date.parse(out);if(!out||Number.isNaN(time)||!/(?:Z|[+-]\d\d:\d\d)$/.test(out))throw new TypeError(`${label} requires timezone-aware ISO timestamp`);return new Date(time).toISOString();}
function cloneData(value){if(value==null)return {};if(typeof value!=='object'||Array.isArray(value))throw new TypeError('metadata must be an object');return structuredClone(value);}
export function injectionFlags(value){const text=(typeof value==='string'?value:canonical(value)).normalize('NFKC').replace(/[\u200b\u200c\u200d\u2060\ufeff]/g,' ').toLowerCase(),flags=[];if(/ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|rules?|polic)/.test(text))flags.push('ignore-prior');if(/(reveal|print|send|leak|dump|show).{0,96}(secret|token|credential|api[_ -]?key|password)/s.test(text))flags.push('credential-request');if(/(bypass|disable|override|ignore|evade).{0,96}(policy|safety|authorization|approval|guardrail|permission)/s.test(text))flags.push('policy-bypass');if(/(grant|give|assume|elevate).{0,72}(admin|root|owner|permission|authority|scope)/s.test(text))flags.push('authority-escalation-request');if(/(system|developer)\s+(message|instruction|prompt)/.test(text))flags.push('authority-impersonation');return [...new Set(flags)].sort();}
export function authorityLikePaths(value,prefix=''){const found=[];const walk=(node,path)=>{if(!node||typeof node!=='object')return;if(Array.isArray(node)){node.forEach((entry,index)=>walk(entry,`${path}[${index}]`));return;}for(const [key,entry] of Object.entries(node)){const next=path?`${path}.${key}`:key;if(AUTHORITY_KEY_RX.test(key))found.push(next);walk(entry,next);}};walk(value,prefix);return [...new Set(found)].sort();}
export function contextNodeBody(raw={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('context record required');const project_id=safeId(raw.projectId??raw.project_id,'project id'),node_id=safeId(raw.nodeId??raw.node_id,'node id'),domain=exact(raw.domain,CONTEXT_DOMAINS,'context domain'),trust=String(raw.trust??'RETRIEVED_UNTRUSTED').toUpperCase();if(!CONTEXT_TRUST.includes(trust))throw new TypeError('context trust is invalid');const title=clean(raw.title,240);if(!title)throw new TypeError('context title required');const source_type=clean(raw.sourceType??raw.source_type,80);const source_id=safeId(raw.sourceId??raw.source_id,'source id');const source_uri=clean(raw.sourceUri??raw.source_uri,1000)||null;const content=structuredClone(raw.content??'');const metadata=cloneData(raw.metadata);rejectSecretLike({content,metadata},'context record');const flags=injectionFlags({content,metadata}),authority_paths=authorityLikePaths({content,metadata});return {schema:'musitu.axiom.deep-context-node.browser.v1',project_id,node_id,domain,title,source_type,source_id,source_uri,trust,content,metadata,as_of:timestamp(raw.asOf??raw.as_of,'as_of',{nullable:true}),retrieved_at:timestamp(raw.retrievedAt??raw.retrieved_at,'retrieved_at',{nullable:true}),instruction_authority:INSTRUCTION_AUTHORITY,authority_effect:AUTHORITY_EFFECT,injection_flags:flags,authority_like_paths:authority_paths};}
export async function normalizeContextNode(raw){const body=contextNodeBody(raw);return {...body,content_sha256:await sha256(body.content),node_sha256:await sha256(body)};}
export function contextEdgeBody(raw={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('context edge required');const relation=clean(raw.relation,80);if(!CONTEXT_RELATIONS.includes(relation))throw new DOMException('context relation is not allow-listed and cannot represent authority delegation','SecurityError');return {schema:'musitu.axiom.deep-context-edge.browser.v1',project_id:safeId(raw.projectId??raw.project_id,'project id'),edge_id:safeId(raw.edgeId??raw.edge_id,'edge id'),from_id:safeId(raw.fromId??raw.from_id,'from id'),to_id:safeId(raw.toId??raw.to_id,'to id'),relation,provenance_source:safeId(raw.provenanceSource??raw.provenance_source,'provenance source'),authority_effect:AUTHORITY_EFFECT};}
export async function normalizeContextEdge(raw){const body=contextEdgeBody(raw);return {...body,edge_sha256:await sha256(body)};}
export async function authoritySnapshot(raw={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('governing authority envelope required');rejectSecretLike(raw,'authority envelope');const envelope=structuredClone(raw),authority_sha256=await sha256(envelope);return {envelope,authority_sha256};}
