import {BREADTH_SURFACES,ECC_MODE,MATRIX_ROWS,SYSTEM_GRAPH_LAYERS,clean,normalizeRowEvidence,requireBreadth,routeModel,sha256,validateDeploymentHistory} from './engineering_command_center_security.js';
const hasDigest=value=>/^[0-9a-f]{64}$/.test(String(value||'').toLowerCase());
const all=(obj,keys)=>keys.every(key=>obj?.[key]===true);
async function row(projectId,rowId,state,evidenceRefs=[],externalQualification=null,claimBoundary='IMPLEMENTATION_SCOPE_ONLY_NO_PRODUCTION_OR_SUPERIORITY_CLAIM'){return normalizeRowEvidence({row_id:rowId,project_id:projectId,state,evidence_refs:evidenceRefs,external_qualification:externalQualification,claim_boundary:claimBoundary,updated_at:new Date().toISOString()},{projectId});}
export async function deriveEngineeringMatrix(snapshot={}){
  const projectId=clean(snapshot.project_id,180);if(!projectId)throw new TypeError('project id required');const rows=[];
  const w=snapshot.workspace||{},workspaceReady=w.mode==='GOVERNED_ENGINEERING_WORKSPACE'&&all(w.capabilities,['file_tree','editor','diff','diagnostics','search','tests','preview']);
  rows.push(await row(projectId,'IDE',workspaceReady&&w.windsurf_class_claim_authorized===true?'IMPLEMENTED_VERIFIED':workspaceReady?'PARTIAL':'NOT_PROVEN',['engineering-workspace']));
  const fleet=snapshot.agent_fleet||{},fleetLocal=fleet.mission_control_integrity==='PASS'&&fleet.separate_workload_identities===true&&fleet.least_privilege===true&&fleet.budgets_enforced===true&&fleet.kill_controls===true&&fleet.independent_verifier===true;
  const fleetCloud=fleet.cloud_qualification&&hasDigest(fleet.cloud_execution_receipt_sha256);rows.push(await row(projectId,'agent_fleet',fleetLocal&&fleetCloud?'IMPLEMENTED_VERIFIED':fleetLocal?'IMPLEMENTED_BLOCKED_EXTERNAL':'NOT_PROVEN',['mission-control','workload-identities'],fleetCloud?fleet.cloud_qualification:null));
  const s=snapshot.engineering_space||{};rows.push(await row(projectId,'spaces',s.project_graph_integrity==='PASS'&&s.full_project_graph===true&&s.sessions===true&&s.files===true&&s.context===true?'IMPLEMENTED_VERIFIED':'NOT_PROVEN',['project-graph','engineering-space']));
  const c=snapshot.deep_context||{},domains=['code','runtime','data','infra','trace','requirement','evidence'];rows.push(await row(projectId,'context',c.status==='PASS'&&c.authority_unchanged===true&&domains.every(x=>(c.domains||[]).includes(x))?'IMPLEMENTED_VERIFIED':'NOT_PROVEN',['deep-context']));
  const g=snapshot.system_graph||{};rows.push(await row(projectId,'maps',g.status==='PASS'&&g.authority_effect==='NONE'&&g.authority_unchanged===true&&SYSTEM_GRAPH_LAYERS.every(x=>(g.layers||[]).includes(x))?'IMPLEMENTED_VERIFIED':'PARTIAL',['system-graph']));
  const e=snapshot.execution||{},risk=['S0','S1','S2','S3','S4','S5'];rows.push(await row(projectId,'terminal',e.integrity==='PASS'&&e.independent_gateway===true&&e.network_default_deny===true&&e.host_shell_enabled===false&&e.plaintext_secrets===false&&risk.every(x=>(e.risk_classes||[]).includes(x))?'IMPLEMENTED_VERIFIED':'NOT_PROVEN',['fa11-s0-s5-gateway']));
  const cps=snapshot.checkpoints||[],latest=cps.at(-1),checkpointReady=Boolean(latest)&&['git_tree','environment','plan','acceptance','tests','security','artifacts','evidence'].every(key=>latest?.components?.[key]?.state==='PRESENT');rows.push(await row(projectId,'checkpoints',checkpointReady?'IMPLEMENTED_VERIFIED':'PARTIAL',['engineering-checkpoint']));
  const p=snapshot.product_reality||{};rows.push(await row(projectId,'preview',p.integration===true&&p.contract==='NO_FAKE_VISUAL_COMPLETION'&&p.fake_visual_completion_allowed===false?'IMPLEMENTED_VERIFIED':'NOT_PROVEN',['fa12-product-reality']));
  const h=snapshot.cloud_handoff||{},handoffExternal=h.external_qualification&&hasDigest(h.external_execution_receipt_sha256)&&h.status==='VERIFIED';rows.push(await row(projectId,'cloud_handoff',handoffExternal?'IMPLEMENTED_VERIFIED':h.governed_package===true?'IMPLEMENTED_BLOCKED_EXTERNAL':'NOT_PROVEN',['cloud-handoff-contract'],handoffExternal?h.external_qualification:null));
  const m=snapshot.model_routing||{};rows.push(await row(projectId,'models',m.multi_model===true&&m.qualification_aware===true&&m.cost_aware===true&&m.privacy_aware===true&&m.unqualified_execution_allowed===false?'IMPLEMENTED_VERIFIED':'PARTIAL',['qualification-router']));
  const d=snapshot.deployment||{},history=validateDeploymentHistory(d.history),deploymentExternal=d.external_qualification&&history.production_reached&&history.highest_stage==='ROLLBACK'&&hasDigest(d.release_receipt_sha256);rows.push(await row(projectId,'deployment',deploymentExternal?'IMPLEMENTED_VERIFIED':d.control_plane_only===true&&history.status==='PASS'?'IMPLEMENTED_BLOCKED_EXTERNAL':'PARTIAL',['deployment-control-plane'],deploymentExternal?d.external_qualification:null));
  const ent=snapshot.enterprise||{},enterpriseExternal=ent.external_qualification&&ent.sso_status==='VERIFIED';rows.push(await row(projectId,'enterprise',enterpriseExternal?'IMPLEMENTED_VERIFIED':ent.policy_graph===true&&ent.rbac_model===true?'IMPLEMENTED_BLOCKED_EXTERNAL':'PARTIAL',['enterprise-policy-graph'],enterpriseExternal?ent.external_qualification:null));
  const sec=snapshot.security||{},securityExternal=sec.external_qualification&&sec.red_team_status==='VERIFIED';rows.push(await row(projectId,'security',securityExternal?'IMPLEMENTED_VERIFIED':sec.independent_security_authority===true&&sec.builder_self_certifies===false&&sec.independent_verifier===true?'IMPLEMENTED_BLOCKED_EXTERNAL':'NOT_PROVEN',['independent-security-gate'],securityExternal?sec.external_qualification:null));
  const breadth=requireBreadth(snapshot.breadth?.routes||[]);rows.push(await row(projectId,'breadth',breadth.status==='PASS'&&snapshot.breadth?.home_outcome_first===true&&snapshot.breadth?.engineering_redefines_product!==true?'IMPLEMENTED_VERIFIED':'PARTIAL',['axiom-breadth-registry']));
  return rows;
}
export async function makeEngineeringSnapshot(input={}){
  const project_id=clean(input.project_id,180);if(!project_id)throw new TypeError('project id required');const body={schema:'musitu.axiom.engineering-command-center.snapshot.browser.v1',mode:ECC_MODE,project_id,builder_id:clean(input.builder_id||'local-builder',180),workspace:input.workspace||{},agent_fleet:input.agent_fleet||{},engineering_space:input.engineering_space||{},deep_context:input.deep_context||{},system_graph:input.system_graph||{},execution:input.execution||{},checkpoints:input.checkpoints||[],product_reality:input.product_reality||{},cloud_handoff:input.cloud_handoff||{},model_routing:input.model_routing||{},deployment:input.deployment||{},enterprise:input.enterprise||{},security:input.security||{},breadth:input.breadth||{routes:BREADTH_SURFACES,home_outcome_first:true,engineering_redefines_product:false},created_at:input.created_at||new Date().toISOString()};body.matrix_evidence=input.matrix_evidence||await deriveEngineeringMatrix(body);return {...body,snapshot_sha256:await sha256(body)};
}
export function localModelRouting(candidates=[]){const result=routeModel(candidates);return {project_id:null,multi_model:candidates.length>1,qualification_aware:true,cost_aware:true,privacy_aware:true,unqualified_execution_allowed:false,selected_qualification:result.selected?.qualification||null,route_result:result};}
export function blockedExternalState(projectId){return {project_id:projectId,cloud_handoff:{project_id:projectId,status:'BLOCKED_EXTERNAL',governed_package:true,isolated_agent_required:true,self_grant_allowed:false,external_execution_receipt_sha256:null},deployment:{project_id:projectId,history:[{stage:'BUILD'}],control_plane_only:true,stage_skip_allowed:false,production_authority:false,release_receipt_sha256:null},enterprise:{project_id:projectId,policy_graph:true,rbac_model:true,agent_policy:true,data_policy:true,network_policy:true,action_policy:true,sso_status:'NOT_PROVEN'},security:{project_id:projectId,independent_security_authority:true,builder_self_certifies:false,independent_verifier:true,fail_closed:true,red_team_status:'NOT_PROVEN'}};}
