import {BREADTH_SURFACES,DEPLOYMENT_STAGES,ECC_MODE,IDE_CAPABILITIES,IDE_QUALIFICATION_FEATURES,MATRIX_ROWS,MATRIX_ROW_IDS,ROW_STATES,SYSTEM_GRAPH_LAYERS,clean,requireBreadth,rowSatisfied,sha256,validateDeploymentHistory,verifyCheckpoint} from './engineering_command_center_security.js';
const uniq=values=>[...new Set(values)];
const array=value=>Array.isArray(value)?value:[];
const digest=value=>/^[0-9a-f]{64}$/.test(clean(value,64).toLowerCase());
const rowBody=row=>Object.fromEntries(Object.entries(row||{}).filter(([key])=>key!=='row_sha256'));
function expectedProject(row,projectId,label,errors){if(row&&row.project_id!==projectId)errors.push(`${label}_project_scope`);}
function externalVerified(row){const x=row?.external_qualification;return x?.status==='VERIFIED'&&Boolean(x.verifier_id)&&Boolean(x.source_id)&&digest(x.evidence_sha256)&&Number.isFinite(Date.parse(x.captured_at));}
async function verifyRows(rows,projectId,errors){
  const map=new Map();
  for(const row of array(rows)){
    if(!MATRIX_ROW_IDS.includes(row?.row_id)){errors.push(`matrix_unknown:${row?.row_id??'missing'}`);continue;}
    if(map.has(row.row_id)){errors.push(`matrix_duplicate:${row.row_id}`);continue;}
    expectedProject(row,projectId,`matrix:${row.row_id}`,errors);
    if(!ROW_STATES.includes(row.state))errors.push(`matrix_state:${row.row_id}`);
    if(await sha256(rowBody(row))!==row.row_sha256)errors.push(`matrix_hash:${row.row_id}`);
    const def=MATRIX_ROWS.find(item=>item.id===row.row_id);if(def?.external&&row.state==='IMPLEMENTED_VERIFIED'&&!externalVerified(row))errors.push(`matrix_external_self_promotion:${row.row_id}`);
    map.set(row.row_id,row);
  }
  for(const id of MATRIX_ROW_IDS)if(!map.has(id))errors.push(`matrix_missing:${id}`);
  return map;
}
function checkWorkspace(snapshot,rowMap,errors){const w=snapshot.workspace||{};expectedProject(w,snapshot.project_id,'workspace',errors);if(w.mode!=='GOVERNED_ENGINEERING_WORKSPACE'||IDE_CAPABILITIES.some(key=>w.capabilities?.[key]!==true))errors.push('IDE_contract');if(rowSatisfied(rowMap.get('IDE'))){const qualified=new Set(array(w.qualified_features));if(w.windsurf_class_claim_authorized!==true||!digest(w.ide_qualification_sha256)||IDE_QUALIFICATION_FEATURES.some(key=>!qualified.has(key)))errors.push('IDE_benchmark_not_authorized');}}
function checkFleet(snapshot,rowMap,errors){const f=snapshot.agent_fleet||{};expectedProject(f,snapshot.project_id,'agent_fleet',errors);if(f.mission_control_integrity!=='PASS'||f.separate_workload_identities!==true||f.least_privilege!==true||f.budgets_enforced!==true||f.kill_controls!==true||f.independent_verifier!==true)errors.push('agent_fleet_local_contract');if(rowSatisfied(rowMap.get('agent_fleet'))&&(!externalVerified(rowMap.get('agent_fleet'))||!digest(f.cloud_execution_receipt_sha256)))errors.push('agent_fleet_cloud_not_proven');}
function checkSpace(snapshot,errors){const s=snapshot.engineering_space||{};expectedProject(s,snapshot.project_id,'engineering_space',errors);if(s.project_graph_integrity!=='PASS'||s.full_project_graph!==true||s.sessions!==true||s.files!==true||s.context!==true)errors.push('spaces_contract');}
function checkContext(snapshot,errors){const c=snapshot.deep_context||{};expectedProject(c,snapshot.project_id,'deep_context',errors);const required=['code','runtime','data','infra','trace','requirement','evidence'];if(c.status!=='PASS'||c.authority_unchanged!==true||required.some(domain=>!array(c.domains).includes(domain)))errors.push('context_contract');}
function checkGraph(snapshot,errors){const g=snapshot.system_graph||{};expectedProject(g,snapshot.project_id,'system_graph',errors);if(g.status!=='PASS'||g.authority_effect!=='NONE'||g.authority_unchanged!==true||SYSTEM_GRAPH_LAYERS.some(layer=>!array(g.layers).includes(layer)))errors.push('maps_contract');if(array(g.relations).some(relation=>/authoriz|grant|delegate|approve/i.test(String(relation))))errors.push('maps_authority_relation');}
function checkExecution(snapshot,errors){const e=snapshot.execution||{};expectedProject(e,snapshot.project_id,'execution',errors);const risks=['S0','S1','S2','S3','S4','S5'];if(e.integrity!=='PASS'||e.independent_gateway!==true||e.network_default_deny!==true||e.host_shell_enabled!==false||e.plaintext_secrets!==false||risks.some(risk=>!array(e.risk_classes).includes(risk)))errors.push('terminal_contract');}
async function checkCheckpoints(snapshot,errors){const rows=array(snapshot.checkpoints);if(!rows.length){errors.push('checkpoints_missing');return;}for(const row of rows){expectedProject(row,snapshot.project_id,`checkpoint:${row?.checkpoint_id}`,errors);const result=await verifyCheckpoint(row);if(result.status!=='PASS')errors.push(...result.errors.map(x=>`${x}:${row?.checkpoint_id||'unknown'}`));}const latest=rows.at(-1);for(const key of ['git_tree','environment','plan','acceptance','tests','security','artifacts','evidence'])if(latest?.components?.[key]?.state!=='PRESENT')errors.push(`checkpoint_latest_incomplete:${key}`);}
function checkReality(snapshot,errors){const p=snapshot.product_reality||{};expectedProject(p,snapshot.project_id,'product_reality',errors);if(p.integration!==true||p.contract!=='NO_FAKE_VISUAL_COMPLETION'||p.fake_visual_completion_allowed!==false)errors.push('preview_contract');}
function checkCloud(snapshot,rowMap,errors){const h=snapshot.cloud_handoff||{};expectedProject(h,snapshot.project_id,'cloud_handoff',errors);if(h.governed_package!==true||h.isolated_agent_required!==true||h.self_grant_allowed!==false)errors.push('cloud_handoff_contract');if(rowSatisfied(rowMap.get('cloud_handoff'))&&(!externalVerified(rowMap.get('cloud_handoff'))||!digest(h.external_execution_receipt_sha256)||h.status!=='VERIFIED'))errors.push('cloud_handoff_not_proven');}
function checkModels(snapshot,errors){const m=snapshot.model_routing||{};expectedProject(m,snapshot.project_id,'model_routing',errors);if(m.multi_model!==true||m.qualification_aware!==true||m.cost_aware!==true||m.privacy_aware!==true||m.unqualified_execution_allowed!==false)errors.push('models_contract');if(m.selected_qualification&&m.selected_qualification!=='QUALIFIED')errors.push('models_unqualified_selected');}
function checkDeployment(snapshot,rowMap,errors){const d=snapshot.deployment||{};expectedProject(d,snapshot.project_id,'deployment',errors);const history=validateDeploymentHistory(d.history);if(history.status!=='PASS')errors.push(...history.errors);if(d.stage_skip_allowed!==false||d.control_plane_only!==true)errors.push('deployment_contract');if(rowSatisfied(rowMap.get('deployment'))){if(!externalVerified(rowMap.get('deployment'))||!history.production_reached||history.highest_stage!=='ROLLBACK'||!digest(d.release_receipt_sha256))errors.push('deployment_external_not_proven');}else if(d.production_authority===true)errors.push('deployment_unqualified_production_authority');}
function checkEnterprise(snapshot,rowMap,errors){const e=snapshot.enterprise||{};expectedProject(e,snapshot.project_id,'enterprise',errors);if(e.policy_graph!==true||e.rbac_model!==true||e.agent_policy!==true||e.data_policy!==true||e.network_policy!==true||e.action_policy!==true)errors.push('enterprise_policy_graph');if(rowSatisfied(rowMap.get('enterprise'))&&(!externalVerified(rowMap.get('enterprise'))||e.sso_status!=='VERIFIED'))errors.push('enterprise_sso_not_proven');}
function checkSecurity(snapshot,rowMap,errors){const s=snapshot.security||{};expectedProject(s,snapshot.project_id,'security',errors);if(s.independent_security_authority!==true||s.builder_self_certifies!==false||s.independent_verifier!==true||s.fail_closed!==true)errors.push('security_contract');if(rowSatisfied(rowMap.get('security'))&&(!externalVerified(rowMap.get('security'))||s.red_team_status!=='VERIFIED'))errors.push('security_red_team_not_proven');}
function checkBreadth(snapshot,errors){const b=snapshot.breadth||{},result=requireBreadth(b.routes);if(result.status!=='PASS')errors.push(...result.missing.map(x=>`breadth_missing:${x}`));if(b.home_outcome_first!==true)errors.push('breadth_home_not_outcome_first');if(b.engineering_redefines_product===true)errors.push('breadth_narrowed_to_engineering');}
export async function verifyEngineeringCommandCenter(snapshot={}){
  const errors=[];if(!snapshot||typeof snapshot!=='object'||Array.isArray(snapshot))return {status:'FAIL',matrix_status:'FAIL',errors:['snapshot_invalid']};const projectId=clean(snapshot.project_id,180);if(!projectId)return {status:'FAIL',matrix_status:'FAIL',errors:['project_id_missing']};if(snapshot.mode!==ECC_MODE)errors.push('ecc_mode');const snapshotBody=Object.fromEntries(Object.entries(snapshot).filter(([key])=>key!=='snapshot_sha256'));if(!digest(snapshot.snapshot_sha256)||await sha256(snapshotBody)!==snapshot.snapshot_sha256)errors.push('snapshot_hash');const rowMap=await verifyRows(snapshot.matrix_evidence,projectId,errors);for(const def of MATRIX_ROWS){const row=rowMap.get(def.id);if(def.external&&rowSatisfied(row)&&row?.external_qualification?.verifier_id===clean(snapshot.builder_id,180))errors.push(`matrix_external_builder_self_verification:${def.id}`);}
  checkWorkspace(snapshot,rowMap,errors);checkFleet(snapshot,rowMap,errors);checkSpace(snapshot,errors);checkContext(snapshot,errors);checkGraph(snapshot,errors);checkExecution(snapshot,errors);await checkCheckpoints(snapshot,errors);checkReality(snapshot,errors);checkCloud(snapshot,rowMap,errors);checkModels(snapshot,errors);checkDeployment(snapshot,rowMap,errors);checkEnterprise(snapshot,rowMap,errors);checkSecurity(snapshot,rowMap,errors);checkBreadth(snapshot,errors);
  const row_results=MATRIX_ROWS.map(def=>({row_id:def.id,state:rowMap.get(def.id)?.state||'NOT_PROVEN',satisfied:rowSatisfied(rowMap.get(def.id)),external:def.external}));const matrix_status=row_results.every(row=>row.satisfied)?'PASS':'BLOCKED';const result={schema:'musitu.axiom.engineering-command-center-verification.browser.v1',project_id:projectId,status:errors.length?'FAIL':'PASS',matrix_status,row_results,unsatisfied_rows:row_results.filter(row=>!row.satisfied).map(row=>row.row_id),errors:uniq(errors).sort(),breadth_required:BREADTH_SURFACES,deployment_stages:DEPLOYMENT_STAGES};result.verification_sha256=await sha256(result);return result;
}
export async function sealEngineeringSnapshot(raw={}){const body={...raw};delete body.snapshot_sha256;const snapshot={...body,snapshot_sha256:await sha256(body)},verification=await verifyEngineeringCommandCenter(snapshot);return {snapshot,verification};}
