import {BREADTH_SURFACES,DEPLOYMENT_STAGES,ECC_MODE,clean,clone,normalizeRowEvidence,rejectSecretLike,routeModel,sealCheckpoint,sha256,validateDeploymentHistory} from './engineering_command_center_security.js';
const DB='musitu-axiom-engineering-command-center-v1',VERSION=1,WRITERS=new Set(['owner','editor']);
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const uid=prefix=>`${prefix}_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
const without=(row,field)=>Object.fromEntries(Object.entries(row).filter(([key])=>key!==field));
export class EngineeringCommandCenterStore{
  constructor(db,{projects}){this.db=db;this.projects=projects;this.serial=Promise.resolve();}
  static async open({projects}={}){if(!projects?.getProject||!projects?.graph)throw new TypeError('earned ProjectStore required');const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;for(const [name,key] of [['spaces','space_id'],['checkpoints','checkpoint_id'],['model_routes','route_id'],['handoffs','handoff_id'],['deployments','deployment_id'],['incidents','incident_id'],['matrix','matrix_key'],['events','event_id']])if(!db.objectStoreNames.contains(name)){const s=db.createObjectStore(name,{keyPath:key});s.createIndex('project_id','project_id',{unique:false});if(name==='events')s.createIndex('project_sequence',['project_id','sequence'],{unique:true});if(name==='matrix')s.createIndex('project_row',['project_id','row_id'],{unique:true});}};return new EngineeringCommandCenterStore(await req(r),{projects});}
  _queue(task){const next=this.serial.then(task,task);this.serial=next.catch(()=>{});return next;}
  async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
  async _all(store,projectId){const tx=this.db.transaction(store,'readonly'),source=projectId?tx.objectStore(store).index('project_id'):tx.objectStore(store),rows=await req(projectId?source.getAll(projectId):source.getAll());await done(tx);return rows.map(clone);}
  async _put(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(clone(row));await done(tx);return clone(row);}
  async _project(projectId,actorId,{write=false}={}){projectId=clean(projectId,180);actorId=clean(actorId,180);const project=await this.projects.getProject(projectId);if(!project)throw new DOMException('project not found','NotFoundError');const role=project.permissions?.find(row=>row.principal_id===actorId)?.role;if(!role||write&&!WRITERS.has(role))throw new DOMException('engineering project permission denied','NotAllowedError');return project;}
  async _event(projectId,actorId,kind,payload={}){const history=(await this._all('events',projectId)).sort((a,b)=>a.sequence-b.sequence),body={schema:'musitu.axiom.engineering-command-center.event.browser.v1',event_id:`ecc-event:${projectId}:${history.length}`,project_id:projectId,actor_id:clean(actorId,180),sequence:history.length,kind:clean(kind,100),payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:history.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};rejectSecretLike(row,'engineering event');return this._put('events',row);}
  async ensureSpace(projectId,actorId='local-user'){return this._queue(async()=>{const project=await this._project(projectId,actorId,{write:true}),existing=(await this._all('spaces',projectId))[0];if(existing)return existing;const body={schema:'musitu.axiom.engineering-space.browser.v1',space_id:`engineering-space:${projectId}`,project_id:projectId,mode:ECC_MODE,name:`${clean(project.name,120)} Engineering Space`,repository:{status:'BROWSER_LOCAL_VIRTUAL_WORKTREE',external_repo_bound:false,base_tree_sha256:null},workspace:{mode:'GOVERNED_ENGINEERING_WORKSPACE',capabilities:{file_tree:true,editor:true,diff:true,diagnostics:true,search:true,tests:true,preview:true},windsurf_class_claim_authorized:false},project_graph_bound:true,sessions:true,files:true,context:true,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},row={...body,space_sha256:await sha256(body)};await this._put('spaces',row);await this._event(projectId,actorId,'engineering.space.created',{space_id:row.space_id,space_sha256:row.space_sha256});return row;});}
  async updateRepositoryBinding(projectId,actorId,{baseTreeSha256=null,externalRepoBound=false}={}){return this._queue(async()=>{await this._project(projectId,actorId,{write:true});const space=await this.ensureSpace(projectId,actorId);space.repository={status:externalRepoBound?'EXTERNAL_REPOSITORY_METADATA_BOUND':'BROWSER_LOCAL_VIRTUAL_WORKTREE',external_repo_bound:Boolean(externalRepoBound),base_tree_sha256:baseTreeSha256?clean(baseTreeSha256,64):null};space.updated_at=new Date().toISOString();space.space_sha256=await sha256(without(space,'space_sha256'));await this._put('spaces',space);await this._event(projectId,actorId,'engineering.repository.bound',{external_repo_bound:space.repository.external_repo_bound,base_tree_sha256:space.repository.base_tree_sha256});return clone(space);});}
  async createCheckpoint(projectId,actorId,{worktreeId='main',components={}}={}){return this._queue(async()=>{await this._project(projectId,actorId,{write:true});const row=await sealCheckpoint({project_id:projectId,checkpoint_id:uid('ecc-checkpoint'),worktree_id:worktreeId,components,created_at:new Date().toISOString()});await this._put('checkpoints',row);await this._event(projectId,actorId,'engineering.checkpoint.created',{checkpoint_id:row.checkpoint_id,checkpoint_sha256:row.checkpoint_sha256,worktree_id:row.worktree_id});return row;});}
  async routeModels(projectId,actorId,candidates,weights={}){return this._queue(async()=>{await this._project(projectId,actorId,{write:false});const result=routeModel(candidates,weights),body={schema:'musitu.axiom.engineering-model-route.browser.v1',route_id:uid('ecc-model-route'),project_id:projectId,multi_model:Array.isArray(candidates)&&candidates.length>1,qualification_aware:true,cost_aware:true,privacy_aware:true,unqualified_execution_allowed:false,selected_qualification:result.selected?.qualification||null,result,created_at:new Date().toISOString()},row={...body,route_sha256:await sha256(body)};await this._put('model_routes',row);await this._event(projectId,actorId,'engineering.model.routed',{route_id:row.route_id,status:result.status,selected:result.selected?.id||null});return row;});}
  async createCloudHandoff(projectId,actorId,{agentId,workloadIdentityId,checkpointSha256=null}={}){return this._queue(async()=>{await this._project(projectId,actorId,{write:true});agentId=clean(agentId,180);workloadIdentityId=clean(workloadIdentityId,180);if(!agentId||!workloadIdentityId)throw new TypeError('agent and workload identity required');const body={schema:'musitu.axiom.engineering-cloud-handoff.browser.v1',handoff_id:uid('ecc-handoff'),project_id:projectId,agent_id:agentId,workload_identity_id:workloadIdentityId,checkpoint_sha256:checkpointSha256?clean(checkpointSha256,64):null,status:'BLOCKED_EXTERNAL',governed_package:true,isolated_agent_required:true,self_grant_allowed:false,external_executor_bound:false,external_execution_receipt_sha256:null,created_at:new Date().toISOString()},row={...body,handoff_sha256:await sha256(body)};await this._put('handoffs',row);await this._event(projectId,actorId,'engineering.cloud-handoff.prepared',{handoff_id:row.handoff_id,status:row.status});return row;});}
  async createDeploymentPlan(projectId,actorId,{artifactSha256=null}={}){return this._queue(async()=>{await this._project(projectId,actorId,{write:true});const history=[{stage:'BUILD',evidence_sha256:artifactSha256?clean(artifactSha256,64):null,at:new Date().toISOString()}],body={schema:'musitu.axiom.engineering-deployment-plan.browser.v1',deployment_id:uid('ecc-deployment'),project_id:projectId,history,control_plane_only:true,stage_skip_allowed:false,production_authority:false,release_receipt_sha256:null,status:'CONTROL_PLANE_ONLY_EXTERNAL_EXECUTOR_REQUIRED',created_at:new Date().toISOString(),updated_at:new Date().toISOString()},row={...body,deployment_sha256:await sha256(body)};await this._put('deployments',row);await this._event(projectId,actorId,'engineering.deployment.plan-created',{deployment_id:row.deployment_id,stage:'BUILD'});return row;});}
  async advanceDeployment(deploymentId,actorId,{stage,evidenceSha256}={}){return this._queue(async()=>{const row=await this._get('deployments',deploymentId);if(!row)throw new DOMException('deployment plan not found','NotFoundError');await this._project(row.project_id,actorId,{write:true});stage=clean(stage,40).toUpperCase();const expected=DEPLOYMENT_STAGES[row.history.length];if(stage!==expected)throw new DOMException(`deployment stage must advance exactly to ${expected||'none'}`,'SecurityError');const evidence=clean(evidenceSha256,64);if(!/^[0-9a-f]{64}$/.test(evidence))throw new TypeError('deployment evidence sha256 required');row.history.push({stage,evidence_sha256:evidence,at:new Date().toISOString()});const check=validateDeploymentHistory(row.history);if(check.status!=='PASS')throw new DOMException('deployment stage sequence invalid','SecurityError');if(['STAGING','CANARY','PRODUCTION','ROLLBACK'].includes(stage)){row.status='BLOCKED_EXTERNAL_QUALIFIED_EXECUTOR_REQUIRED';row.production_authority=false;}row.updated_at=new Date().toISOString();row.deployment_sha256=await sha256(without(row,'deployment_sha256'));await this._put('deployments',row);await this._event(row.project_id,actorId,'engineering.deployment.advanced',{deployment_id:row.deployment_id,stage,evidence_sha256:evidence,status:row.status});return clone(row);});}
  async recordIncident(projectId,actorId,{title,severity='MEDIUM',workId=null,evidenceSha256=null}={}){return this._queue(async()=>{await this._project(projectId,actorId,{write:true});const body={schema:'musitu.axiom.engineering-incident.browser.v1',incident_id:uid('ecc-incident'),project_id:projectId,title:clean(title,180),severity:clean(severity,40).toUpperCase(),work_id:clean(workId,180)||null,evidence_sha256:evidenceSha256?clean(evidenceSha256,64):null,status:'OPEN_REPAIR_WORK_REQUIRED',continuous_repair:true,created_at:new Date().toISOString()},row={...body,incident_sha256:await sha256(body)};rejectSecretLike(row,'incident');await this._put('incidents',row);await this._event(projectId,actorId,'engineering.incident.recorded',{incident_id:row.incident_id,severity:row.severity,status:row.status});return row;});}
  async setMatrixEvidence(projectId,actorId,raw){return this._queue(async()=>{await this._project(projectId,actorId,{write:true});const row=await normalizeRowEvidence({...raw,project_id:projectId},{projectId}),stored={...row,matrix_key:`${projectId}:${row.row_id}`};await this._put('matrix',stored);await this._event(projectId,actorId,'engineering.matrix.updated',{row_id:row.row_id,state:row.state,row_sha256:row.row_sha256});return row;});}
  async snapshot(projectId,actorId='local-user'){await this._project(projectId,actorId);const [spaces,checkpoints,modelRoutes,handoffs,deployments,incidents,matrix,events]=await Promise.all(['spaces','checkpoints','model_routes','handoffs','deployments','incidents','matrix','events'].map(name=>this._all(name,projectId)));return {space:spaces[0]||null,checkpoints:checkpoints.sort((a,b)=>a.created_at.localeCompare(b.created_at)),model_routes:modelRoutes.sort((a,b)=>a.created_at.localeCompare(b.created_at)),handoffs:handoffs.sort((a,b)=>a.created_at.localeCompare(b.created_at)),deployments:deployments.sort((a,b)=>a.created_at.localeCompare(b.created_at)),incidents:incidents.sort((a,b)=>a.created_at.localeCompare(b.created_at)),matrix:matrix.map(({matrix_key,...row})=>row),events:events.sort((a,b)=>a.sequence-b.sequence),breadth:{routes:[],home_outcome_first:false,engineering_redefines_product:false,source:'CALLER_MUST_SUPPLY_ACTUAL_REGISTERED_ROUTES'}};}
  async verifyEventChain(projectId,actorId='local-user'){await this._project(projectId,actorId);const events=(await this._all('events',projectId)).sort((a,b)=>a.sequence-b.sequence),errors=[];let previous=null;for(let i=0;i<events.length;i++){const row=events[i];if(row.sequence!==i||row.previous_event_sha256!==previous||await sha256(without(row,'event_sha256'))!==row.event_sha256)errors.push(`event_chain:${i}`);previous=row.event_sha256;}const result={schema:'musitu.axiom.engineering-event-integrity.browser.v1',project_id:projectId,status:errors.length?'FAIL':'PASS',errors,event_count:events.length,event_chain_tip_sha256:previous};result.integrity_sha256=await sha256(result);return result;}
}
