import {ProjectStore} from '../projects.js';
import {ObservabilityStore} from '../observability.js';
import {AgentAutomationStore} from '../agent_store.js';
import {GovernedExecutionStore} from './execution_store.js';
import {RISK_CLASSES,OPERATION_SPECS} from './execution_security.js';
const $=(s,r=document)=>r.querySelector(s);const clean=(v,n=500)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,n);const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const projectId=()=>{try{return localStorage.getItem('axiom.vnext.active-project')||''}catch{return ''}};const route=()=>((location.hash.match(/^#\/([^/?#]+)/)||[])[1]||'home');
let opening=null,execution=null,agents=null,projects=null,observability=null,sandboxId='';
async function open(){if(execution)return; if(opening)return opening;opening=(async()=>{projects=await ProjectStore.open();observability=await ObservabilityStore.open();agents=await AgentAutomationStore.open({projects:{store:projects},observability:{store:observability}});execution=await GovernedExecutionStore.open();})();try{await opening}finally{opening=null}}
function envelope(agent){return {project_id:agent.project_id,actor_id:agent.agent_id,agent_id:agent.agent_id,workload_identity_id:agent.workload_identity_id,agent_status:agent.status,kill_switch_engaged:Boolean(agent.kill_switch_engaged),revoked:false,requester_type:'AGENT',grant:agent.grant,usage:{compute_units:Number(agent.usage?.compute_units||0)},incident_posture:'NORMAL',jurisdiction:'LOCAL_BROWSER'};}
async function render(){if(route()!=='build')return;const root=$('#workspace-root');if(!root)return;const pid=projectId();if(!pid){root.innerHTML='<div class="card"><h3>Select a project first</h3><p>Governed execution is Project-scoped.</p></div>';return;}await open();const list=await agents.listAgents(pid);root.innerHTML=`<header class="page-head"><div><small class="eyebrow">FA-11 · Governed execution</small><h1>Build</h1><p>Terminal, files, sandbox, build, test, secret-broker, network and worktree requests pass through one S0–S5 authorization gateway.</p></div></header><div class="card"><small class="eyebrow">Authority boundary</small><h3>S0–S5 enforced · browser-local substrate</h3><p>No host shell, direct external network, plaintext secret or production deploy is exposed. S4/S5 stay blocked without the required independent authority and qualified executor.</p></div><section class="section"><div class="metric-grid">${RISK_CLASSES.map(r=>`<div class="metric"><strong>${r}</strong><span>${esc(({S0:'Read/compute',S1:'Local reversible write',S2:'External read',S3:'External/repo write',S4:'Publish/deploy',S5:'Secrets/security/destructive'})[r])}</span></div>`).join('')}</div></section><section class="section"><div class="work-layout"><article class="card"><h3>Execution sandbox</h3><label>Governed agent<select id="exec-agent"><option value="">Choose agent</option>${list.map(a=>`<option value="${esc(a.agent_id)}">${esc(a.name)} · ${esc(a.status)}</option>`).join('')}</select></label><p style="margin-top:10px"><button id="exec-create" class="button primary" type="button">Create isolated sandbox</button></p><div id="exec-sandbox-state" class="muted">No sandbox created.</div></article><aside class="card"><h3>Policy truth</h3><p>Unknown operations fail closed at S5. Retrieved instructions cannot authorize side effects. Network is default-deny. Secret leases are opaque and operation-scoped.</p></aside></div></section><section class="section"><div class="card"><h3>Operation registry</h3><div class="list">${Object.entries(OPERATION_SPECS).map(([name,s])=>`<div class="list-row"><span><strong>${esc(name)}</strong><small>${esc(s.effect)}</small></span><span class="badge">${esc(s.risk)}</span></div>`).join('')}</div></div></section>`;
 $('#exec-create')?.addEventListener('click',async()=>{const agent=list.find(a=>a.agent_id===$('#exec-agent').value),state=$('#exec-sandbox-state');try{if(!agent)throw new Error('Choose an active governed agent.');const row=await execution.createSandbox(envelope(agent),{label:`${agent.name} isolated worktree`});sandboxId=row.sandbox_id;state.textContent=`${row.sandbox_id} · worktree ${row.active_worktree_id} · network denied · host shell denied`; }catch(error){state.textContent=clean(error?.message||'Sandbox creation failed',240);}});
}
window.addEventListener('hashchange',()=>queueMicrotask(()=>void render()));queueMicrotask(()=>void render());window.AxiomVNextExecutionUI=Object.freeze({refresh:render,boundary:'S0_S5_BROWSER_LOCAL_NO_PRODUCTION_EXECUTOR'});
