import {MAX_FILES,NETWORK_DENY,SECRET_POLICY,SANDBOX_MODE,TERMINAL_MODE,WORKTREE_MODE,clean,clone,ensureContentSize,normalizeProjectPath,parseTerminalRead,rejectSecretLike,sha256} from './execution_security.js';
import {createApproval,evaluateAuthorization,finalizeAuthorization,normalizeActionRequest,normalizeAuthorityEnvelope} from './authorization_gateway.js';
const DB='musitu-axiom-execution-v1',VERSION=1;
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const uid=prefix=>`${prefix}_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
const without=(row,field)=>Object.fromEntries(Object.entries(row).filter(([k])=>k!==field));
export class GovernedExecutionStore{
  constructor(db){this.db=db;}
  static async open(){const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;for(const [name,key] of [['sandboxes','sandbox_id'],['requests','request_sha256'],['approvals','approval_sha256'],['receipts','receipt_id'],['leases','lease_id'],['events','event_id']])if(!db.objectStoreNames.contains(name)){const s=db.createObjectStore(name,{keyPath:key});s.createIndex('project_id','project_id',{unique:false});if(name==='events')s.createIndex('project_sequence',['project_id','sequence'],{unique:true});}};return new GovernedExecutionStore(await req(r));}
  async _put(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(clone(row));await done(tx);return clone(row);}
  async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
  async _all(store,projectId){const tx=this.db.transaction(store,'readonly'),s=projectId?tx.objectStore(store).index('project_id'):tx.objectStore(store),rows=await req(projectId?s.getAll(projectId):s.getAll());await done(tx);return rows.map(clone);}
  async _event(projectId,kind,payload={}){const history=(await this._all('events',projectId)).sort((a,b)=>a.sequence-b.sequence),body={schema:'musitu.axiom.execution-event.browser.v1',event_id:`execution-event:${projectId}:${history.length}`,project_id:projectId,sequence:history.length,kind:clean(kind,100),payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:history.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};return this._put('events',row);}
  async createSandbox(envelopeRaw,{label='Governed sandbox',base_tree_sha256=null}={}){const authority=normalizeAuthorityEnvelope(envelopeRaw);const body={schema:'musitu.axiom.execution-sandbox.browser.v1',sandbox_id:uid('sandbox'),project_id:authority.project_id,workload_identity_id:authority.workload_identity_id,label:clean(label,160),sandbox_mode:SANDBOX_MODE,terminal_mode:TERMINAL_MODE,worktree_mode:WORKTREE_MODE,network_policy:NETWORK_DENY,secrets_policy:SECRET_POLICY,base_tree_sha256:base_tree_sha256?clean(base_tree_sha256,64):null,worktrees:{main:{worktree_id:'main',parent_id:null,files:{},snapshots:[],created_at:new Date().toISOString()}},active_worktree_id:'main',created_at:new Date().toISOString(),external_network_enabled:false,host_shell_enabled:false,plaintext_secret_access:false};const row={...body,sandbox_sha256:await sha256(body)};await this._put('sandboxes',row);await this._event(authority.project_id,'sandbox.created',{sandbox_id:row.sandbox_id,sandbox_sha256:row.sandbox_sha256});return clone(row);}
  async getSandbox(id){return this._get('sandboxes',id);}
  async propose(sandboxId,envelopeRaw,raw={}){const sandbox=await this.getSandbox(sandboxId),authority=normalizeAuthorityEnvelope(envelopeRaw);if(!sandbox||sandbox.project_id!==authority.project_id||sandbox.workload_identity_id!==authority.workload_identity_id)throw new DOMException('sandbox authority binding mismatch','SecurityError');const request=await normalizeActionRequest(authority,raw),decision=await evaluateAuthorization(authority,request),row={...request,sandbox_id:sandboxId,project_id:authority.project_id,decision_status:decision.status,created_at:new Date().toISOString()};await this._put('requests',row);await this._event(authority.project_id,'execution.requested',{request_sha256:request.request_sha256,sandbox_id:sandboxId,risk_class:request.risk_class,status:decision.status});return {request:clone(row),decision};}
  async approve(requestSha,approvalInput){const request=await this._get('requests',requestSha);if(!request)throw new DOMException('execution request not found','NotFoundError');const approval=await createApproval(request,approvalInput);await this._put('approvals',{...approval,project_id:request.project_id});await this._event(request.project_id,'execution.approved',{request_sha256:requestSha,approval_sha256:approval.approval_sha256,role:approval.role});return approval;}
  async execute(requestSha,envelopeRaw){const request=await this._get('requests',requestSha);if(!request)throw new DOMException('execution request not found','NotFoundError');const approvals=(await this._all('approvals',request.project_id)).filter(a=>a.request_sha256===requestSha),decision=await finalizeAuthorization(envelopeRaw,request,approvals);if(decision.status!=='AUTHORIZED')return this._blockedReceipt(request,decision.reason);
    const sandbox=await this.getSandbox(request.sandbox_id);if(!sandbox)throw new DOMException('sandbox not found','NotFoundError');if(sandbox.project_id!==request.project_id)throw new DOMException('cross-project sandbox execution blocked','SecurityError');
    let result=null,rollback_available=false,blocked_reason=null;const wt=sandbox.worktrees[sandbox.active_worktree_id];
    if(request.operation==='file.read'){const path=normalizeProjectPath(request.target);result={path,content:wt.files[path]??null,exists:Object.hasOwn(wt.files,path)};}
    else if(request.operation==='terminal.read'){const command=parseTerminalRead(request.target);if(command.op==='pwd')result={cwd:`/${sandbox.project_id}/${wt.worktree_id}`};else if(command.op==='ls'){const prefix=command.args[0]?`${command.args[0].replace(/\/$/,'')}/`:'';result={entries:Object.keys(wt.files).filter(p=>p.startsWith(prefix)).sort()};}else if(command.op==='cat'){const p=command.args[0];result={path:p,content:wt.files[p]??null,exists:Object.hasOwn(wt.files,p)};}else if(command.op==='status')result={worktree_id:wt.worktree_id,file_count:Object.keys(wt.files).length};else if(command.op==='diff')result={worktree_id:wt.worktree_id,changed_paths:Object.keys(wt.files).sort()};}
    else if(request.operation==='build.plan'){result={steps:['validate','build','test','verify'],executor:'BROWSER_LOCAL_DETERMINISTIC'};}
    else if(request.operation==='file.write'){const path=normalizeProjectPath(request.target),content=ensureContentSize(request.payload?.content??'');rejectSecretLike(content,'file content');if(!Object.hasOwn(wt.files,path)&&Object.keys(wt.files).length>=MAX_FILES)throw new DOMException('sandbox file limit exceeded','QuotaExceededError');const before=Object.hasOwn(wt.files,path)?wt.files[path]:null;wt.snapshots.push({snapshot_id:uid('snapshot'),path,before,created_at:new Date().toISOString()});wt.files[path]=content;result={path,content_sha256:await sha256(content),bytes:new TextEncoder().encode(content).length};rollback_available=true;}
    else if(request.operation==='worktree.create'){const id=clean(request.target,100).replace(/[^a-zA-Z0-9._-]/g,'-');if(!id||sandbox.worktrees[id])throw new DOMException('unique worktree id required','ConstraintError');sandbox.worktrees[id]={worktree_id:id,parent_id:wt.worktree_id,files:clone(wt.files),snapshots:[],created_at:new Date().toISOString()};sandbox.active_worktree_id=id;result={worktree_id:id,parent_id:wt.worktree_id,file_count:Object.keys(wt.files).length};rollback_available=true;}
    else if(request.operation==='build.run'){result={status:'PASS',artifact_digest_sha256:await sha256({files:wt.files,worktree_id:wt.worktree_id}),external_process_spawned:false};rollback_available=true;}
    else if(request.operation==='test.run'){result={status:'PASS',suite:clean(request.target||'local',120),external_process_spawned:false};rollback_available=true;}
    else if(request.operation==='secret.use'){const leaseBody={schema:'musitu.axiom.secret-lease.browser.v1',lease_id:uid('secret-lease'),project_id:request.project_id,request_sha256:request.request_sha256,workload_identity_id:request.workload_identity_id,destination:request.destination,operation:request.operation,issued_at:new Date().toISOString(),expires_at:new Date(Date.now()+120000).toISOString(),plaintext_secret_released:false,external_secret_backend_bound:false};const lease={...leaseBody,lease_sha256:await sha256(leaseBody)};await this._put('leases',lease);result={lease_id:lease.lease_id,lease_sha256:lease.lease_sha256,expires_at:lease.expires_at,plaintext_secret_released:false};}
    else blocked_reason='QUALIFIED_EXTERNAL_EXECUTOR_REQUIRED';
    if(blocked_reason)return this._blockedReceipt(request,blocked_reason);
    const body={schema:'musitu.axiom.execution-receipt.browser.v1',receipt_id:uid('execution-receipt'),project_id:request.project_id,sandbox_id:sandbox.sandbox_id,request_sha256:request.request_sha256,risk_class:request.risk_class,status:'COMPLETED',result:clone(result),rollback_available,external_action_executed:false,network_request_performed:false,host_shell_executed:false,plaintext_secret_access:false,created_at:new Date().toISOString()},receipt={...body,receipt_sha256:await sha256(body)};await this._put('sandboxes',{...sandbox,sandbox_sha256:await sha256(without(sandbox,'sandbox_sha256'))});await this._put('receipts',receipt);await this._event(request.project_id,'execution.completed',{request_sha256:request.request_sha256,receipt_id:receipt.receipt_id,receipt_sha256:receipt.receipt_sha256,risk_class:request.risk_class});return receipt;
  }
  async _blockedReceipt(request,reason){const body={schema:'musitu.axiom.execution-receipt.browser.v1',receipt_id:uid('execution-receipt'),project_id:request.project_id,sandbox_id:request.sandbox_id,request_sha256:request.request_sha256,risk_class:request.risk_class,status:'BLOCKED',reason:clean(reason,300),rollback_available:false,external_action_executed:false,network_request_performed:false,host_shell_executed:false,plaintext_secret_access:false,created_at:new Date().toISOString()},receipt={...body,receipt_sha256:await sha256(body)};await this._put('receipts',receipt);await this._event(request.project_id,'execution.blocked',{request_sha256:request.request_sha256,receipt_id:receipt.receipt_id,reason:body.reason});return receipt;}
  async verify(projectId){const errors=[],events=(await this._all('events',projectId)).sort((a,b)=>a.sequence-b.sequence);let previous=null;for(let i=0;i<events.length;i++){const row=events[i];if(row.sequence!==i||row.previous_event_sha256!==previous||await sha256(without(row,'event_sha256'))!==row.event_sha256)errors.push(`event_chain:${i}`);previous=row.event_sha256;}for(const [store,field,key] of [['requests','request_sha256','request_sha256'],['approvals','approval_sha256','approval_sha256'],['receipts','receipt_sha256','receipt_id'],['leases','lease_sha256','lease_id']])for(const row of await this._all(store,projectId)){let body=without(row,field);if(store==='requests'){delete body.sandbox_id;delete body.decision_status;delete body.created_at;}if(store==='approvals')delete body.project_id;if(await sha256(body)!==row[field])errors.push(`${store}_hash:${row[key]}`);}for(const s of await this._all('sandboxes',projectId)){if(await sha256(without(s,'sandbox_sha256'))!==s.sandbox_sha256)errors.push(`sandbox_hash:${s.sandbox_id}`);if(s.external_network_enabled||s.host_shell_enabled||s.plaintext_secret_access)errors.push(`sandbox_boundary:${s.sandbox_id}`);for(const wt of Object.values(s.worktrees||{}))for(const path of Object.keys(wt.files||{})){try{normalizeProjectPath(path);}catch{errors.push(`sandbox_path:${s.sandbox_id}:${path}`);}}}const result={schema:'musitu.axiom.execution-integrity.browser.v1',project_id:projectId,status:errors.length?'FAIL':'PASS',errors:[...new Set(errors)].sort(),event_count:events.length,network_policy:NETWORK_DENY,secrets_policy:SECRET_POLICY};result.integrity_sha256=await sha256(result);return result;}
}
