import {VNextProjectWorkMemoryBridge,FA08_RUNTIME_BOUNDARY} from './project_work_memory_bridge.js';
const $=(s,r=document)=>r.querySelector(s);
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const activeProjectId=()=>{try{return localStorage.getItem('axiom.vnext.active-project')||'';}catch{return '';}};
let bridgePromise=null;
const bridge=()=>bridgePromise||(bridgePromise=VNextProjectWorkMemoryBridge.open());
function currentRoute(){return (location.hash.match(/^#\/([^/?#]+)/)||[])[1]||'home';}
function emit(type,detail={}){try{window.dispatchEvent(new CustomEvent('axiom:fa08-event',{detail:{type,detail}}));}catch{}}
function badge(text,type=''){return `<span class="badge ${type}">${esc(text)}</span>`;}
async function renderMemory(){
  if(currentRoute()!=='memory')return;
  const root=$('#workspace-root');if(!root)return;
  const projectId=activeProjectId();
  if(!projectId){root.innerHTML=`<header class="page-head"><div><small class="eyebrow">FA-08 · PROVENANCE-PRESERVING MEMORY</small><h1>Knowledge / Memory</h1><p>Consent-scoped browser-local memory linked to the Project graph.</p></div></header><div class="card"><h3>Select a project first</h3><p>Memory is project-bound and cannot float outside its provenance graph.</p><p style="margin-top:12px"><a class="button primary" href="#/projects">Open projects</a></p></div>`;return;}
  try{
    const api=await bridge();
    const [graph,visible,all,verification]=await Promise.all([api.graph(projectId),api.recall(projectId,{allowedScopes:['private','project']}),api.listMemory(projectId),api.verifyProvenance(projectId)]);
    if(currentRoute()!=='memory')return;
    const sourceOptions=graph.objects.map(o=>`<option value="${esc(o.object_id)}">${esc(o.type)} · ${esc(o.title)}</option>`).join('');
    const revoked=all.filter(row=>row.revoked||row.scope==='do_not_use').length;
    root.innerHTML=`<header class="page-head"><div><small class="eyebrow">FA-08 · PROJECT / WORK / MEMORY</small><h1>Knowledge / Memory</h1><p>Consent-scoped browser-local memory with source lineage, nondestructive revocation and cross-store verification.</p></div><button class="button" type="button" data-fa08-verify>Verify provenance</button></header>
      <div class="metric-grid"><div class="metric"><strong>${visible.length}</strong><span>Recallable memories</span></div><div class="metric"><strong>${revoked}</strong><span>Do-not-use records</span></div><div class="metric"><strong>${verification.status}</strong><span>Cross-store provenance</span></div><div class="metric"><strong>Local</strong><span>No cloud sync claim</span></div></div>
      <section class="section work-layout"><form class="card" id="fa08-memory-form"><small class="eyebrow">Explicit consent required</small><h3>Remember for this project</h3><label>Subject<input id="fa08-memory-subject" required maxlength="180"></label><label>Summary<textarea id="fa08-memory-summary" rows="4" required maxlength="4000"></textarea></label><label>Scope<select id="fa08-memory-scope"><option value="project">Project</option><option value="private">Private</option></select></label><label>Retention<select id="fa08-memory-retention"><option value="permanent">Permanent</option><option value="temporary">Temporary</option></select></label><label id="fa08-expiry-wrap" hidden>Expires at<input id="fa08-memory-expiry" type="datetime-local"></label><label>Consent source<input id="fa08-memory-consent" value="vnext-explicit-user-memory-form" required maxlength="240"></label><label>Source object<select id="fa08-memory-source"><option value="">No source object</option>${sourceOptions}</select></label><p class="muted">No hidden reasoning or secrets are stored. External memory network policy: deny all.</p><button class="button primary" type="submit">Remember</button></form>
      <article class="card"><div class="section-head"><div><small class="eyebrow">Recall view</small><h3>Active memory</h3></div>${badge(verification.status,verification.status==='PASS'?'ok':'block')}</div><div class="list">${visible.length?visible.map(row=>`<div class="list-row"><span><strong>${esc(row.subject)}</strong><small>${esc(row.summary)} · ${esc(row.scope)} · ${esc(row.retention)} · ${row.source_refs.length} source refs</small></span><button class="button" type="button" data-fa08-revoke="${esc(row.memory_id)}">Do not use</button></div>`).join(''):`<div><p>No recallable memories for this project.</p></div>`}</div></article></section>
      <section class="section"><div class="card"><small class="eyebrow">Provenance gate</small><h3>${verification.status==='PASS'?'Project / Work / Memory lineage verified':'Provenance failure detected'}</h3><p>${verification.status==='PASS'?`Project event chain, ${verification.work_contracts_checked} Work contracts and ${verification.memories_checked} memory records preserve required lineage.`:`${verification.errors.length} inconsistency record(s) are blocking PASS.`}</p><small class="muted">${esc(FA08_RUNTIME_BOUNDARY.persistence)} · ${esc(FA08_RUNTIME_BOUNDARY.gate)} · external consequential execution: false</small></div></section>`;
    bindMemoryEvents();emit('memory.render',{project_id:projectId,provenance:verification.status});
  }catch(error){if(currentRoute()!=='memory')return;root.innerHTML=`<header class="page-head"><div><small class="eyebrow">FA-08 · FAIL CLOSED</small><h1>Knowledge / Memory</h1></div></header><div class="card"><h3>Memory workspace unavailable</h3><p>${esc(error?.message||'Browser-local memory could not be opened.')}</p><p class="muted">No provenance PASS is emitted when the underlying stores cannot be verified.</p></div>`;emit('memory.error',{message:String(error?.message||'unavailable')});}
}
function bindMemoryEvents(){
  const retention=$('#fa08-memory-retention'),expiryWrap=$('#fa08-expiry-wrap');retention?.addEventListener('change',()=>{expiryWrap.hidden=retention.value!=='temporary';});
  $('#fa08-memory-form')?.addEventListener('submit',async event=>{event.preventDefault();const projectId=activeProjectId();if(!projectId)return;const source=$('#fa08-memory-source')?.value||'';const retentionValue=$('#fa08-memory-retention').value;let expiresAt=null;if(retentionValue==='temporary'){const raw=$('#fa08-memory-expiry').value;if(!raw){$('#fa08-memory-expiry').focus();return;}expiresAt=new Date(raw).toISOString();}try{const api=await bridge();await api.remember(projectId,{subject:$('#fa08-memory-subject').value,summary:$('#fa08-memory-summary').value,scope:$('#fa08-memory-scope').value,retention:retentionValue,consent_source:$('#fa08-memory-consent').value,authorized_viewers:['local-user'],source_refs:source?[source]:[],expires_at:expiresAt});emit('memory.remembered',{project_id:projectId});await renderMemory();}catch(error){emit('memory.write-rejected',{message:String(error?.message||'rejected')});alert(`Memory not recorded: ${error?.message||'request rejected'}`);}});
  document.querySelectorAll('[data-fa08-revoke]').forEach(button=>button.addEventListener('click',async()=>{try{const api=await bridge();await api.markDoNotUse(button.dataset.fa08Revoke);emit('memory.do-not-use',{memory_id:button.dataset.fa08Revoke});await renderMemory();}catch(error){emit('memory.revoke-rejected',{message:String(error?.message||'rejected')});}}));
  $('[data-fa08-verify]')?.addEventListener('click',()=>void renderMemory());
}
function schedule(){queueMicrotask(()=>void renderMemory());}
if(typeof window!=='undefined'&&typeof document!=='undefined'){window.addEventListener('hashchange',schedule);window.addEventListener('axiom:fa08-refresh',schedule);schedule();window.AxiomFA08=Object.freeze({renderMemory,boundary:FA08_RUNTIME_BOUNDARY,getBridge:bridge});}
