import {EXECUTION_MODE,clean,grantIsSubset,sha256,uid} from '../agent_security.js';
import {redirectEventBody,redirectReceiptBody,verifyMissionControlSnapshot} from './mission_control_verifier.js';

const DB='musitu-axiom-mission-control-v1',VERSION=1,PREVIEW_TTL_MS=5*60*1000;
const requestResult=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const transactionDone=transaction=>new Promise((resolve,reject)=>{transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error);transaction.onabort=()=>reject(transaction.error||new Error('transaction aborted'));});
const clone=value=>structuredClone(value),scopes=value=>[...new Set((Array.isArray(value)?value:[]).map(item=>clean(item,80)).filter(Boolean))].sort(),active=agent=>agent?.status==='ACTIVE'&&agent?.kill_switch_engaged!==true,hasAll=(values,required)=>required.every(value=>values.includes(value));

export function redirectPreviewBody(row){return {schema:'musitu.axiom.mission-control.redirect-preview.browser.v1',preview_id:row.preview_id,project_id:row.project_id,actor_id:row.actor_id,source_agent_id:row.source_agent_id,target_agent_id:row.target_agent_id,source_grant_sha256:row.source_grant_sha256,target_grant_sha256:row.target_grant_sha256,required_tool_scopes:row.required_tool_scopes,required_data_scopes:row.required_data_scopes,prepared_at:row.prepared_at,expires_at:row.expires_at,execution_mode:EXECUTION_MODE,status:'AWAITING_EXACT_CONFIRMATION'};}

export class MissionControlStore{
  constructor(db,{agentStore,projectStore,clock=()=>Date.now()}){this.db=db;this.agentStore=agentStore;this.projectStore=projectStore;this.clock=clock;this.serial=Promise.resolve();}
  static async open({agentStore,projectStore,clock}={}){
    if(!agentStore?.listAgents||!agentStore?.verify||!projectStore?.getProject||!projectStore?.graph||!projectStore?.addEdge)throw new TypeError('qualified Agent and Project stores required');
    const request=indexedDB.open(DB,VERSION);
    request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('previews')){const store=db.createObjectStore('previews',{keyPath:'confirmation_sha256'});store.createIndex('project_id','project_id',{unique:false});}if(!db.objectStoreNames.contains('redirects')){const store=db.createObjectStore('redirects',{keyPath:'receipt_id'});store.createIndex('project_id','project_id',{unique:false});}if(!db.objectStoreNames.contains('events')){const store=db.createObjectStore('events',{keyPath:'event_id'});store.createIndex('project_id','project_id',{unique:false});}};
    return new MissionControlStore(await requestResult(request),{agentStore,projectStore,clock});
  }
  close(){this.db.close();}
  _queue(task){const next=this.serial.then(task,task);this.serial=next.catch(()=>{});return next;}
  async _all(store,index=null,key=null){const tx=this.db.transaction(store,'readonly'),source=index?tx.objectStore(store).index(index):tx.objectStore(store),rows=await requestResult(key===null?source.getAll():source.getAll(key));await transactionDone(tx);return rows.map(clone);}
  async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await requestResult(tx.objectStore(store).get(key));await transactionDone(tx);return row?clone(row):null;}
  async _put(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(clone(row));await transactionDone(tx);return clone(row);}
  async _owner(projectId,actorId){const project=await this.projectStore.getProject(clean(projectId,180)),actor=clean(actorId,180);if(!project)throw new DOMException('project not found','NotFoundError');const permission=project.permissions?.find(entry=>entry.principal_id===actor);if(actor!==project.owner_id||permission?.role!=='owner')throw new DOMException('project owner authority required','NotAllowedError');return project;}
  async listRedirects(projectId){return (await this._all('redirects','project_id',clean(projectId,180))).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
  async listEvents(projectId){return (await this._all('events','project_id',clean(projectId,180))).sort((a,b)=>a.sequence-b.sequence);}
  async _validateAgents(sourceAgentId,targetAgentId,{projectId=null,requiredToolScopes=[],requiredDataScopes=[]}={}){
    const source=await this.agentStore.getAgent(clean(sourceAgentId,180)),target=await this.agentStore.getAgent(clean(targetAgentId,180));
    if(!source||!target)throw new DOMException('redirect agents must exist','NotFoundError');if(source.agent_id===target.agent_id)throw new DOMException('redirect target must be distinct','SecurityError');if(source.project_id!==target.project_id||projectId&&source.project_id!==projectId)throw new DOMException('redirect must remain inside one Project','SecurityError');if(!active(source)||!active(target))throw new DOMException('redirect requires active non-killed agents','InvalidStateError');if(!grantIsSubset(target.grant,source.grant))throw new DOMException('redirect cannot elevate authority','SecurityError');
    const tools=scopes(requiredToolScopes),data=scopes(requiredDataScopes);if(!hasAll(source.grant.tool_scopes,tools)||!hasAll(target.grant.tool_scopes,tools))throw new DOMException('required tool scopes must exist in both grants','SecurityError');if(!hasAll(source.grant.data_scopes,data)||!hasAll(target.grant.data_scopes,data))throw new DOMException('required data scopes must exist in both grants','SecurityError');return {source,target,tools,data};
  }
  async prepareRedirect(sourceAgentId,targetAgentId,{actorId='local-user',requiredToolScopes=[],requiredDataScopes=[]}={}){return this._queue(async()=>{const validated=await this._validateAgents(sourceAgentId,targetAgentId,{requiredToolScopes,requiredDataScopes});await this._owner(validated.source.project_id,actorId);const now=this.clock(),prepared_at=new Date(now).toISOString(),expires_at=new Date(now+PREVIEW_TTL_MS).toISOString();const row={preview_id:uid('redirect-preview'),project_id:validated.source.project_id,actor_id:clean(actorId,180),source_agent_id:validated.source.agent_id,target_agent_id:validated.target.agent_id,source_grant_sha256:validated.source.grant_sha256,target_grant_sha256:validated.target.grant_sha256,required_tool_scopes:validated.tools,required_data_scopes:validated.data,prepared_at,expires_at,status:'PENDING'};row.confirmation_sha256=await sha256(redirectPreviewBody(row));await this._put('previews',row);return {...redirectPreviewBody(row),confirmation_sha256:row.confirmation_sha256};});}
  async _event(receipt){const rows=await this.listEvents(receipt.project_id),prior=rows.at(-1)||null;const body={schema:'musitu.axiom.mission-control.event.browser.v1',event_id:uid('mission-event'),sequence:rows.length,kind:'agent.redirected',actor_id:receipt.actor_id,project_id:receipt.project_id,receipt_id:receipt.receipt_id,source_agent_id:receipt.source_agent_id,target_agent_id:receipt.target_agent_id,payload:{confirmation_sha256:receipt.confirmation_sha256,project_edge_id:receipt.project_edge_id,external_action_executed:false},created_at:receipt.created_at,previous_event_sha256:prior?.event_sha256||null};const event={...body,event_sha256:await sha256(redirectEventBody(body))};await this._put('events',event);return event;}
  async confirmRedirect(expectedConfirmationSha,actorId='local-user'){return this._queue(async()=>{const confirmation=clean(expectedConfirmationSha,128),preview=await this._get('previews',confirmation);if(!preview||preview.status!=='PENDING')throw new DOMException('exact pending redirect confirmation required','NotAllowedError');if(preview.actor_id!==clean(actorId,180))throw new DOMException('redirect confirmation actor mismatch','NotAllowedError');if(Date.parse(preview.expires_at)<=this.clock())throw new DOMException('redirect confirmation expired','InvalidStateError');if(await sha256(redirectPreviewBody(preview))!==confirmation)throw new DOMException('stale or altered redirect confirmation','SecurityError');const validated=await this._validateAgents(preview.source_agent_id,preview.target_agent_id,{projectId:preview.project_id,requiredToolScopes:preview.required_tool_scopes,requiredDataScopes:preview.required_data_scopes});await this._owner(preview.project_id,actorId);if(validated.source.grant_sha256!==preview.source_grant_sha256||validated.target.grant_sha256!==preview.target_grant_sha256)throw new DOMException('agent authority changed after redirect preview','SecurityError');const receipt_id=uid('redirect'),created_at=new Date(this.clock()).toISOString();const edge=await this.projectStore.addEdge(preview.project_id,actorId,{fromId:validated.source.project_object_id,toId:validated.target.project_object_id,relation:'mission-control-redirect',provenanceSource:`mission-control:${receipt_id}`});const receipt={schema:'musitu.axiom.mission-control.redirect-receipt.browser.v1',receipt_id,project_id:preview.project_id,actor_id:clean(actorId,180),source_agent_id:validated.source.agent_id,target_agent_id:validated.target.agent_id,source_grant_sha256:validated.source.grant_sha256,target_grant_sha256:validated.target.grant_sha256,required_tool_scopes:preview.required_tool_scopes,required_data_scopes:preview.required_data_scopes,confirmation_sha256:confirmation,project_edge_id:edge.edge_id,execution_mode:EXECUTION_MODE,status:'RECORDED',external_action_executed:false,network_request_performed:false,plaintext_secret_access:false,created_at};receipt.receipt_sha256=await sha256(redirectReceiptBody(receipt));const tx=this.db.transaction(['redirects','previews'],'readwrite');tx.objectStore('redirects').add(clone(receipt));tx.objectStore('previews').put({...preview,status:'CONSUMED',consumed_at:created_at,receipt_id});await transactionDone(tx);await this._event(receipt);return clone(receipt);});}
  async verify(projectId){projectId=clean(projectId,180);const [agents,automations,agentReceipts,agentIntegrity,redirects,redirectEvents,graph]=await Promise.all([this.agentStore.listAgents(projectId),this.agentStore.listAutomations(projectId),this.agentStore.listReceipts(),this.agentStore.verify(),this.listRedirects(projectId),this.listEvents(projectId),this.projectStore.graph(projectId)]);return verifyMissionControlSnapshot({agents,automations,agentReceipts:agentReceipts.filter(row=>!row.project_id||row.project_id===projectId),agentIntegrity,redirects,redirectEvents,projectObjects:graph.objects,projectEdges:graph.edges});}
  async destroyForTests(){this.close();await new Promise((resolve,reject)=>{const request=indexedDB.deleteDatabase(DB);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error);request.onblocked=()=>reject(new Error('database deletion blocked'));});}
}
