import {ProductRealityStore} from './product_reality_store.js';
import {collectLocalReality} from './product_reality_adapters.js';
import {REALITY_CHANNELS} from './product_reality_security.js';
const $=(s,r=document)=>r.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));const clean=(v,n=300)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,n);const route=()=>((location.hash.match(/^#\/([^/?#]+)/)||[])[1]||'home');const activeProjectId=()=>{try{return localStorage.getItem('axiom.vnext.active-project')||''}catch{return ''}};
const errors=[];window.addEventListener('error',e=>errors.push({kind:'error',message:clean(e.message||'window error',300),at:new Date().toISOString()}));window.addEventListener('unhandledrejection',e=>errors.push({kind:'unhandledrejection',message:clean(e.reason?.message||e.reason||'unhandled rejection',300),at:new Date().toISOString()}));
let storePromise=null,currentSessionId='';const store=()=>storePromise||(storePromise=ProductRealityStore.open());
async function ensureSession(){const pid=activeProjectId();if(!pid)throw new Error('Select a project before inspecting product reality.');const db=await store();if(currentSessionId){const existing=await db.getSession(currentSessionId);if(existing?.project_id===pid)return existing;}const rows=await db.sessions(pid);const active=rows.find(row=>row.status==='ACTIVE');if(active){currentSessionId=active.session_id;return active;}const created=await db.createSession({projectId:pid,actorId:'local-user'});currentSessionId=created.session_id;return created;}
async function inspect(){const db=await store(),session=await ensureSession();const observations=collectLocalReality(session,{errorBuffer:errors,browserSession:window.AxiomBrowserSession});for(const observation of observations)await db.recordObservation(session.session_id,observation);return db.evaluate(session.session_id,'PASS');}
function panelMarkup(){return `<section id="product-reality-lab" class="section"><div class="card"><div class="card-top"><div><small class="eyebrow">FA-12 · Product Reality Lab</small><h3>No fake visual completion</h3><p>Inspect browser reality, preserve missing evidence, and convert failures into repair work. DOM beauty, emulation, or a screenshot alone can never self-certify completion.</p></div><span class="badge block" id="reality-verdict">NOT PROVEN</span></div><p style="margin-top:12px"><button class="button primary" id="reality-inspect" type="button">Inspect this browser session</button> <button class="button" id="reality-reinspect" type="button">Start re-inspection generation</button></p><div id="reality-summary" class="muted" role="status">No Product Reality inspection recorded in this browser session.</div><div id="reality-channels" class="list" style="margin-top:12px">${REALITY_CHANNELS.map(kind=>`<div class="list-row" data-reality-channel="${kind}"><span><strong>${esc(kind.replace('_',' '))}</strong><small>Evidence not recorded</small></span><span class="badge">MISSING</span></div>`).join('')}</div><p class="muted" style="margin-top:12px">Physical-device truth is separate. Current viewport dimensions and user agent never prove a physical device. Ordinary page JavaScript does not fabricate pixel screenshots, accessibility-tree captures, production headers, or production sessions.</p></div></section>`;}
async function refreshPanel(){if(route()!=='build')return;const panel=$('#product-reality-lab');if(!panel)return;try{const session=await ensureSession(),db=await store(),v=await db.verify(session.session_id,'NOT_PROVEN');$('#reality-verdict').textContent=v.reality_verdict;$('#reality-verdict').className=`badge ${v.reality_verdict==='PASS'?'ok':'block'}`;$('#reality-summary').textContent=`Generation ${v.generation} · verification ${v.status} · unsatisfied ${v.unsatisfied_channels.length} · physical device ${v.physical_device_verified?'VERIFIED':'NOT PROVEN'}`;for(const [kind,state] of Object.entries(v.channel_states)){const row=$(`[data-reality-channel="${kind}"]`);if(!row)continue;row.querySelector('small').textContent=v.unsatisfied_channels.includes(kind)?'Insufficient for Product Reality PASS':'Current-generation evidence satisfies channel policy';const badge=row.querySelector('.badge');badge.textContent=state;badge.className=`badge ${state==='OBSERVED'?'ok':state==='MISSING'||state==='NOT_PROVEN'?'block':'warn'}`;}}catch(error){$('#reality-summary').textContent=clean(error?.message||'Reality verification unavailable',300);}}
function install(){if(route()!=='build')return;const root=$('#workspace-root');if(!root)return;if(!$('#product-reality-lab'))root.insertAdjacentHTML('beforeend',panelMarkup());$('#reality-inspect')?.addEventListener('click',async()=>{const summary=$('#reality-summary');summary.textContent='Inspecting current browser-local reality…';try{const result=await inspect();summary.textContent=`Inspection recorded. Effective verdict ${result.verdict.effective_status}; unsupported channels remain unproven.`;await refreshPanel();}catch(error){summary.textContent=clean(error?.message||'Inspection failed',300);}});$('#reality-reinspect')?.addEventListener('click',async()=>{try{const s=await ensureSession(),db=await store();await db.beginReinspection(s.session_id,'local-user');await refreshPanel();}catch(error){$('#reality-summary').textContent=clean(error?.message||'Reinspection could not start',300);}});void refreshPanel();}
const observer=new MutationObserver(()=>{if(route()==='build'&&!$('#product-reality-lab'))queueMicrotask(install)});observer.observe(document.documentElement,{subtree:true,childList:true});window.addEventListener('hashchange',()=>queueMicrotask(install));queueMicrotask(install);window.AxiomProductRealityLab=Object.freeze({refresh:refreshPanel,boundary:'NO_FAKE_VISUAL_COMPLETION_NO_PHYSICAL_DEVICE_INFERENCE'});
