import {localUnsupportedObservation,normalizeObservation} from './product_reality_security.js';
const uid=prefix=>`${prefix}_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
const now=()=>new Date().toISOString();
function base(session,kind,state,source,payload){return normalizeObservation({observation_id:uid(`reality_${kind}`),session_id:session.session_id,project_id:session.project_id,generation:session.generation,channel:kind,truth_state:state,source_kind:source,captured_at:now(),payload,physical_device_verified:false});}
export function inspectBrowser(session,{doc=document,win=window}={}){return base(session,'browser','OBSERVED','BROWSER_RUNTIME',{href:String(win.location?.href||''),origin:String(win.location?.origin||''),title:String(doc.title||''),visibility:String(doc.visibilityState||'unknown'),online:typeof win.navigator?.onLine==='boolean'?win.navigator.onLine:null,physical_device_claimed:false});}
export function inspectDom(session,{doc=document}={}){const ids=[...doc.querySelectorAll('[id]')].map(el=>el.id),duplicates=[...new Set(ids.filter((id,i)=>ids.indexOf(id)!==i))].sort();return base(session,'dom','OBSERVED','LIVE_DOM_INSPECTION',{element_count:doc.querySelectorAll('*').length,main_count:doc.querySelectorAll('main').length,h1_count:doc.querySelectorAll('h1').length,duplicate_ids:duplicates,dialog_count:doc.querySelectorAll('dialog').length});}
export function inspectAccessibility(session,{doc=document}={}){const unlabeled=[...doc.querySelectorAll('input,select,textarea')].filter(el=>!el.labels?.length&&!el.getAttribute('aria-label')&&!el.getAttribute('aria-labelledby')).length;const buttons=[...doc.querySelectorAll('button')],unnamedButtons=buttons.filter(el=>!(el.textContent||'').trim()&&!el.getAttribute('aria-label')).length;return base(session,'accessibility','STATIC','DOM_ACCESSIBILITY_HEURISTIC_NOT_ACCESSIBILITY_TREE',{unlabeled_form_controls:unlabeled,unnamed_buttons:unnamedButtons,landmark_main_count:doc.querySelectorAll('main').length,coverage:'STATIC_DOM_HEURISTIC_ONLY_NOT_PLATFORM_ACCESSIBILITY_TREE'});}
export function inspectResponsive(session,{win=window}={}){return base(session,'responsive','OBSERVED','CURRENT_BROWSER_VIEWPORT',{inner_width:Number(win.innerWidth||0),inner_height:Number(win.innerHeight||0),device_pixel_ratio:Number(win.devicePixelRatio||1),orientation:win.matchMedia?.('(orientation: portrait)')?.matches?'portrait':'landscape',physical_device_verified:false,note:'viewport observation does not identify a physical device'});}
export function inspectPerformance(session,{perf=performance}={}){const nav=perf?.getEntriesByType?.('navigation')?.[0],paints=perf?.getEntriesByType?.('paint')||[];return base(session,'performance','OBSERVED','PERFORMANCE_API',{navigation_type:nav?.type||null,duration_ms:Number.isFinite(nav?.duration)?nav.duration:null,dom_content_loaded_ms:Number.isFinite(nav?.domContentLoadedEventEnd)?nav.domContentLoadedEventEnd:null,load_event_ms:Number.isFinite(nav?.loadEventEnd)?nav.loadEventEnd:null,paint_entries:paints.map(p=>({name:p.name,start_time:p.startTime})).slice(0,16),coverage:'BROWSER_PERFORMANCE_API_ONLY_NO_LAB_CWV_CLAIM'});}
export function inspectNetwork(session,{perf=performance}={}){const resources=(perf?.getEntriesByType?.('resource')||[]).slice(-100).map(r=>({name:String(r.name||'').slice(0,300),initiator_type:String(r.initiatorType||''),duration_ms:Number.isFinite(r.duration)?r.duration:null,transfer_size:Number.isFinite(r.transferSize)?r.transferSize:null}));return base(session,'network','OBSERVED','RESOURCE_TIMING_API',{resource_count:resources.length,resources,coverage:'RESOURCE_TIMING_ONLY_NO_REQUEST_BODY_RESPONSE_BODY_OR_HEADER_PROOF'});}
export function inspectConsole(session,{errorBuffer=[]}={}){return base(session,'console','OBSERVED','INSTRUMENTED_WINDOW_ERROR_BUFFER',{captured_since_session_start:true,error_count:errorBuffer.length,errors:errorBuffer.slice(-50).map(e=>({kind:String(e.kind||'error'),message:String(e.message||'').slice(0,300),at:String(e.at||'')}))});}
export function inspectAuthSession(session,{browserSession=window.AxiomBrowserSession}={}){if(!browserSession?.getState)return localUnsupportedObservation({observation_id:uid('reality_auth'),session_id:session.session_id,project_id:session.project_id,generation:session.generation,channel:'auth_session',reason:'same-origin session adapter unavailable'});const state=browserSession.getState();return base(session,'auth_session','OBSERVED','SAME_ORIGIN_SESSION_ADAPTER',{authenticated:Boolean(state.authenticated),mode:String(state.mode||''),assurance:String(state.assurance||''),reason:String(state.reason||''),subject_present:Boolean(state.subject),session_id_present:Boolean(state.sessionId),credential_material_exposed:false});}
export function missingScreenshot(session){return localUnsupportedObservation({observation_id:uid('reality_screenshot'),session_id:session.session_id,project_id:session.project_id,generation:session.generation,channel:'screenshot',reason:'ordinary page JavaScript has no qualified pixel screenshot capture authority'});}
export function missingHeaders(session){return localUnsupportedObservation({observation_id:uid('reality_headers'),session_id:session.session_id,project_id:session.project_id,generation:session.generation,channel:'headers',reason:'top-level response/security headers are not proven by ordinary page JavaScript'});}
export function collectLocalReality(session,options={}){return [inspectBrowser(session,options),inspectDom(session,options),missingScreenshot(session),inspectAccessibility(session,options),inspectResponsive(session,options),inspectPerformance(session,options),inspectNetwork(session,options),inspectConsole(session,options),inspectAuthSession(session,options),missingHeaders(session)];}
