import {REALITY_CHANNELS,clean,clone,normalizeObservation,rejectSecretLike,sha256} from './product_reality_security.js';
import {sealRealityVerification,withObservationHash} from './product_reality_verifier.js';
const DB='musitu-axiom-product-reality-v1',VERSION=1;
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const uid=prefix=>`${prefix}_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
const without=(row,field)=>Object.fromEntries(Object.entries(row).filter(([key])=>key!==field));
export class ProductRealityStore{
  constructor(db){this.db=db;}
  static async open(){const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;for(const [name,key] of [['sessions','session_id'],['observations','observation_id'],['findings','finding_id'],['repairs','repair_id'],['verdicts','verdict_id'],['events','event_id']])if(!db.objectStoreNames.contains(name)){const s=db.createObjectStore(name,{keyPath:key});s.createIndex('project_id','project_id',{unique:false});if(name!=='sessions')s.createIndex('session_id','session_id',{unique:false});if(name==='events')s.createIndex('session_sequence',['session_id','sequence'],{unique:true});}};return new ProductRealityStore(await req(r));}
  async _put(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(clone(row));await done(tx);return clone(row);}
  async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
  async _sessionRows(store,sessionId){const tx=this.db.transaction(store,'readonly'),s=tx.objectStore(store).index('session_id'),rows=await req(s.getAll(sessionId));await done(tx);return rows.map(clone);}
  async sessions(projectId){const tx=this.db.transaction('sessions','readonly'),rows=await req(tx.objectStore('sessions').index('project_id').getAll(projectId));await done(tx);return rows.sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).map(clone);}
  async getSession(id){return this._get('sessions',id);}
  async _event(session,kind,payload={}){const events=(await this._sessionRows('events',session.session_id)).sort((a,b)=>a.sequence-b.sequence),body={schema:'musitu.axiom.product-reality.event.browser.v1',event_id:`reality-event:${session.session_id}:${events.length}`,session_id:session.session_id,project_id:session.project_id,sequence:events.length,generation:session.generation,kind:clean(kind,100),payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:events.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};return this._put('events',row);}
  async createSession({projectId,actorId='local-user',environment='BROWSER_LOCAL_VNEXT'}={}){projectId=clean(projectId,180);actorId=clean(actorId,180);if(!projectId||!actorId)throw new TypeError('project and actor required');const body={schema:'musitu.axiom.product-reality.session.browser.v1',session_id:uid('reality-session'),project_id:projectId,actor_id:actorId,environment:clean(environment,120),generation:1,status:'ACTIVE',physical_device_verified:false,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},row={...body,session_sha256:await sha256(body)};await this._put('sessions',row);await this._event(row,'session.created',{generation:1});return clone(row);}
  async beginReinspection(sessionId,actorId='local-user'){const s=await this.getSession(sessionId);if(!s)throw new DOMException('reality session not found','NotFoundError');if(clean(actorId,180)!==s.actor_id)throw new DOMException('actor mismatch','SecurityError');s.generation+=1;s.updated_at=new Date().toISOString();s.status='ACTIVE';s.session_sha256=await sha256(without(s,'session_sha256'));await this._put('sessions',s);await this._event(s,'reinspection.started',{generation:s.generation});return clone(s);}
  async recordObservation(sessionId,raw){const s=await this.getSession(sessionId);if(!s)throw new DOMException('reality session not found','NotFoundError');const normalized=normalizeObservation({...raw,session_id:sessionId,project_id:s.project_id,generation:s.generation}),row=await withObservationHash(normalized);await this._put('observations',row);await this._event(s,'observation.recorded',{observation_id:row.observation_id,channel:row.channel,truth_state:row.truth_state,observation_sha256:row.observation_sha256});return clone(row);}
  async createFinding(sessionId,{channel,severity='BLOCKING',title,detail}={}){const s=await this.getSession(sessionId);if(!s)throw new DOMException('reality session not found','NotFoundError');if(!REALITY_CHANNELS.includes(clean(channel,40).toLowerCase()))throw new TypeError('known reality channel required');const body={schema:'musitu.axiom.product-reality.finding.browser.v1',finding_id:uid('reality-finding'),session_id,project_id:s.project_id,created_generation:s.generation,channel:clean(channel,40).toLowerCase(),severity:clean(severity,40).toUpperCase(),status:'OPEN',title:clean(title,180),detail:clean(detail,1000),created_at:new Date().toISOString(),resolved_by_observation_id:null,resolved_generation:null};rejectSecretLike(body,'reality finding');const row={...body,finding_sha256:await sha256(body)};await this._put('findings',row);await this._event(s,'finding.created',{finding_id:row.finding_id,channel:row.channel,severity:row.severity});return clone(row);}
  async createRepair(sessionId,{findingId,workId=null,summary}={}){const s=await this.getSession(sessionId),finding=await this._get('findings',findingId);if(!s||!finding||finding.session_id!==sessionId)throw new DOMException('same-session finding required','SecurityError');const body={schema:'musitu.axiom.product-reality.repair.browser.v1',repair_id:uid('reality-repair'),session_id,project_id:s.project_id,finding_id:findingId,work_id:clean(workId,180)||null,created_generation:s.generation,status:'OPEN',summary:clean(summary,600),created_at:new Date().toISOString(),implemented_at:null};const row={...body,repair_sha256:await sha256(body)};await this._put('repairs',row);await this._event(s,'repair.created',{repair_id:row.repair_id,finding_id:findingId});return clone(row);}
  async markRepairImplemented(repairId){const r=await this._get('repairs',repairId);if(!r)throw new DOMException('repair not found','NotFoundError');if(r.status!=='OPEN')throw new DOMException('open repair required','InvalidStateError');const s=await this.getSession(r.session_id);r.status='REPAIR_IMPLEMENTED_PENDING_REINSPECTION';r.implemented_at=new Date().toISOString();r.repair_sha256=await sha256(without(r,'repair_sha256'));await this._put('repairs',r);const f=await this._get('findings',r.finding_id);if(f){f.status='REPAIR_IMPLEMENTED_PENDING_REINSPECTION';f.finding_sha256=await sha256(without(f,'finding_sha256'));await this._put('findings',f);}await this._event(s,'repair.implemented',{repair_id:r.repair_id,finding_id:r.finding_id,status:r.status});return clone(r);}
  async resolveFindingFromFreshObservation(findingId,observationId,{verifierId}={}){const f=await this._get('findings',findingId),o=await this._get('observations',observationId);if(!f||!o||f.session_id!==o.session_id||f.project_id!==o.project_id)throw new DOMException('same-session finding and observation required','SecurityError');if(o.generation<=f.created_generation)throw new DOMException('fresh post-finding observation required','SecurityError');if(o.channel!==f.channel)throw new DOMException('resolution observation channel mismatch','SecurityError');const verifier=clean(verifierId,180);if(!verifier)throw new TypeError('independent verifier id required');const s=await this.getSession(f.session_id);if(verifier===s.actor_id)throw new DOMException('inspection actor cannot self-verify finding resolution','SecurityError');f.status='RESOLVED';f.resolved_by_observation_id=o.observation_id;f.resolved_generation=o.generation;f.verifier_id=verifier;f.resolved_at=new Date().toISOString();f.finding_sha256=await sha256(without(f,'finding_sha256'));await this._put('findings',f);await this._event(s,'finding.resolved',{finding_id:f.finding_id,observation_id:o.observation_id,generation:o.generation,verifier_id:verifier});return clone(f);}
  async snapshot(sessionId){const session=await this.getSession(sessionId);if(!session)throw new DOMException('reality session not found','NotFoundError');const [observations,findings,repairs,events]=await Promise.all(['observations','findings','repairs','events'].map(name=>this._sessionRows(name,sessionId)));return {session,observations,findings,repairs,events:events.sort((a,b)=>a.sequence-b.sequence),verdict:{status:'NOT_PROVEN'}};}
  async verify(sessionId,requestedStatus='NOT_PROVEN'){const snap=await this.snapshot(sessionId);snap.verdict={status:clean(requestedStatus,40).toUpperCase()};return sealRealityVerification(snap);}
  async evaluate(sessionId,requestedStatus='NOT_PROVEN'){const snap=await this.snapshot(sessionId);snap.verdict={status:clean(requestedStatus,40).toUpperCase()};const verification=await sealRealityVerification(snap),body={schema:'musitu.axiom.product-reality.verdict.browser.v1',verdict_id:uid('reality-verdict'),session_id:sessionId,project_id:snap.session.project_id,generation:snap.session.generation,requested_status:snap.verdict.status,effective_status:verification.reality_verdict,verification_status:verification.status,verification_sha256:verification.verification_sha256,created_at:new Date().toISOString()},row={...body,verdict_sha256:await sha256(body)};await this._put('verdicts',row);await this._event(snap.session,'verdict.evaluated',{verdict_id:row.verdict_id,effective_status:row.effective_status,verification_status:row.verification_status});return {verdict:clone(row),verification};}
}
