import test from 'node:test';
import assert from 'node:assert/strict';
import {EXECUTION_MODE,NETWORK_POLICY,SECRETS_POLICY,sha256} from '../../agent_security.js';
import {redirectEventBody,redirectReceiptBody,verifyMissionControlSnapshot} from '../mission_control_verifier.js';

const grant=(tools=['project.read','agent.delegate'],data=['project.metadata'],autonomy='LOCAL_PREVIEW',runs=10,compute=20)=>({tool_scopes:tools,data_scopes:data,network_policy:NETWORK_POLICY,secrets_policy:SECRETS_POLICY,autonomy,approval_policy:'HUMAN_EACH_CONFIGURATION',budget:{max_runs:runs,max_compute_units:compute}});
async function validSnapshot(){
  const root={agent_id:'a-root',project_id:'p1',project_object_id:'o-root',parent_agent_id:null,organization_id:'org',workload_identity_id:'workload:a-root:v1',delegation_depth:0,status:'ACTIVE',kill_switch_engaged:false,grant:grant(),grant_sha256:'g-root',usage:{runs:1,compute_units:1}};
  const child={agent_id:'a-child',project_id:'p1',project_object_id:'o-child',parent_agent_id:'a-root',organization_id:'org',workload_identity_id:'workload:a-child:v1',delegation_depth:1,status:'ACTIVE',kill_switch_engaged:false,grant:grant(['project.read'],['project.metadata'],'PROPOSE_ONLY',1,1),grant_sha256:'g-child',usage:{runs:0,compute_units:0}};
  const approval={receipt_id:'approval:auto1',project_id:'p1',decision:'APPROVED',config_sha256:'cfg1'};
  const automation={automation_id:'auto1',project_id:'p1',agent_id:'a-root',action_scope:'project.read',execution_mode:EXECUTION_MODE,status:'ENABLED',approval_receipt_id:approval.receipt_id,config_sha256:'cfg1',external_action_execution_claimed:false,cloud_scheduler_claimed:false};
  const edge={edge_id:'edge1',project_id:'p1',from_id:'o-root',to_id:'o-child',relation:'mission-control-redirect',provenance:{source:'mission-control:r1'}};
  const redirect={schema:'musitu.axiom.mission-control.redirect-receipt.browser.v1',receipt_id:'r1',project_id:'p1',actor_id:'local-user',source_agent_id:'a-root',target_agent_id:'a-child',source_grant_sha256:'g-root',target_grant_sha256:'g-child',required_tool_scopes:['project.read'],required_data_scopes:['project.metadata'],confirmation_sha256:'confirm1',project_edge_id:'edge1',execution_mode:EXECUTION_MODE,status:'RECORDED',external_action_executed:false,network_request_performed:false,plaintext_secret_access:false,created_at:'2026-09-15T07:00:00.000Z'};redirect.receipt_sha256=await sha256(redirectReceiptBody(redirect));
  const event={schema:'musitu.axiom.mission-control.event.browser.v1',event_id:'e1',sequence:0,kind:'agent.redirected',actor_id:'local-user',project_id:'p1',receipt_id:'r1',source_agent_id:'a-root',target_agent_id:'a-child',payload:{confirmation_sha256:'confirm1',project_edge_id:'edge1',external_action_executed:false},created_at:redirect.created_at,previous_event_sha256:null};event.event_sha256=await sha256(redirectEventBody(event));
  return {agents:[root,child],automations:[automation],agentReceipts:[approval],agentIntegrity:{status:'PASS'},redirects:[redirect],redirectEvents:[event],projectObjects:[{object_id:'o-root',type:'agent'},{object_id:'o-child',type:'agent'}],projectEdges:[edge]};
}

test('FA-09 valid Mission Control snapshot passes least-privilege gate',async()=>{const r=await verifyMissionControlSnapshot(await validSnapshot());assert.equal(r.status,'PASS');assert.deepEqual(r.errors,[]);});
test('FA-09 rejects duplicate active workload identity',async()=>{const s=await validSnapshot();s.agents[1].workload_identity_id=s.agents[0].workload_identity_id;const r=await verifyMissionControlSnapshot(s);assert(r.errors.includes('workload_identity_duplicate'));});
test('FA-09 rejects delegation authority elevation',async()=>{const s=await validSnapshot();s.agents[1].grant=grant(['project.read','artifact.write'],['project.metadata'],'PROPOSE_ONLY',1,1);const r=await verifyMissionControlSnapshot(s);assert(r.errors.some(x=>x.startsWith('delegation:')));});
test('FA-09 rejects exhausted budget and broken kill cascade',async()=>{const s=await validSnapshot();s.agents[0].usage.runs=99;s.agents[0].status='KILLED';s.agents[0].kill_switch_engaged=true;const r=await verifyMissionControlSnapshot(s);assert(r.errors.includes('budget:a-root'));assert(r.errors.includes('kill_cascade:a-child'));});
test('FA-09 rejects enabled automation without exact approval authority',async()=>{const s=await validSnapshot();s.agentReceipts=[];const r=await verifyMissionControlSnapshot(s);assert(r.errors.includes('automation_authority:auto1'));});
test('FA-09 rejects redirect escalation and missing shared required scope',async()=>{const s=await validSnapshot();s.agents[1].grant=grant(['artifact.write'],['project.metadata'],'PROPOSE_ONLY',1,1);const r=await verifyMissionControlSnapshot(s);assert(r.errors.includes('redirect_escalation:r1'));assert(r.errors.includes('redirect_target_tool_scope:r1'));});
test('FA-09 rejects tampered redirect receipt, event and provenance',async()=>{const s=await validSnapshot();s.redirects[0].network_request_performed=true;s.redirectEvents[0].payload.external_action_executed=true;s.projectEdges[0].provenance.source='mission-control:wrong';const r=await verifyMissionControlSnapshot(s);assert(r.errors.includes('redirect_boundary:r1'));assert(r.errors.includes('redirect_receipt_hash:r1'));assert(r.errors.includes('redirect_event_hash:0'));assert(r.errors.includes('redirect_provenance:r1'));assert(r.errors.some(x=>x.startsWith('redirect_orphan_edge:')));});
test('FA-09 fails closed when Agent store integrity is not PASS',async()=>{const s=await validSnapshot();s.agentIntegrity={status:'FAIL'};const r=await verifyMissionControlSnapshot(s);assert(r.errors.includes('agent_store_integrity'));});
