import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import test from 'node:test';
import {composeEarnedContext,developerContextRecords} from '../deep_context_adapters.js';

const source='export function add(a,b){ return a+b; }\n';
const sourceSha256=createHash('sha256').update(source).digest('hex');
const baseFile=Object.freeze({file_id:'file_src_add_js',work_id:'work_12345678',path:'src/add.js',language:'javascript',source,source_sha256:sourceSha256,observed_at:'2026-10-05T04:30:00Z'});
const parseResult=input=>({status:'PARSED',project_id:input.project_id,work_id:input.work_id,file_id:input.file_id,query_profile:input.query_profile,tree_sitter_version:'0.27.0',source_sha256:sourceSha256,language:'javascript',root_type:'program',has_error:false,node_count:7,named_node_count:5,captures:[{kind:'function',name:'add',node_type:'identifier',start_byte:16,end_byte:19}],authority_effect:'NONE',release_authority:false,production_authority:false,certification_authority:false});
function makeClient({health=null,mutate=null}={}){const calls=[];return {calls,async health(){return health??{status:'UP',tree_sitter_version:'0.27.0'};},async parse(input){calls.push(structuredClone(input));const result=parseResult(input);return mutate?mutate(result,input):result;}};}
const dev=(client,overrides={})=>developerContextRecords('project_12345678',{source_files:[{...baseFile,...overrides}]},{treeSitterClient:client});

test('Tree-sitter 0.27.0 produces AXIOM-owned project/work-bound code context',async()=>{const client=makeClient(),rows=await dev(client);assert.equal(rows.length,1);assert.equal(client.calls.length,1);assert.deepEqual([client.calls[0].project_id,client.calls[0].work_id,client.calls[0].file_id,client.calls[0].source_sha256,client.calls[0].tree_sitter_version,client.calls[0].query_profile],['project_12345678','work_12345678','file_src_add_js',sourceSha256,'0.27.0','AXIOM_CODE_SYMBOLS_V1']);assert.deepEqual([rows[0].domain,rows[0].sourceType,rows[0].sourceId,rows[0].trust],['code','tree-sitter-code','file_src_add_js','DERIVED_INDEX']);assert.deepEqual(rows[0].content.symbols,[{kind:'function',name:'add',node_type:'identifier',start_byte:16,end_byte:19}]);assert.equal(rows[0].content.source_sha256,sourceSha256);assert.equal(rows[0].metadata.work_id,'work_12345678');assert.equal(rows[0].metadata.tree_sitter_version,'0.27.0');assert.equal(rows[0].metadata.query_profile,'AXIOM_CODE_SYMBOLS_V1');assert.equal(rows[0].metadata.semantic_owner,'AXIOM');assert.equal(rows[0].metadata.provider_authority,'MECHANISM_ONLY');assert.equal(rows[0].metadata.live_runtime_qualification,'NOT_PROVEN');});

test('Tree-sitter observations require exact project/work/file identity',async()=>{const client=makeClient({mutate:r=>({...r,work_id:'work_other'})});await assert.rejects(()=>dev(client),/project\/work\/file identity mismatch/);});

test('Tree-sitter health proves exact frozen version before parser invocation',async()=>{const client=makeClient({health:{status:'UP',tree_sitter_version:'0.26.7'}});await assert.rejects(()=>dev(client),/Tree-sitter 0\.27\.0 health requirement not met/);assert.equal(client.calls.length,0);});

test('Tree-sitter source bytes are digest-bound before parser invocation',async()=>{const client=makeClient();await assert.rejects(()=>dev(client,{source:source+'//changed\n'}),/source digest mismatch/);assert.equal(client.calls.length,0);});

test('Tree-sitter result is bound to source digest, version, query profile and language',async()=>{for(const [variant,pattern] of [[{source_sha256:'e'.repeat(64)},/source digest mismatch/],[{tree_sitter_version:'0.27.1'},/version mismatch/],[{query_profile:'PROVIDER_QUERY'},/query profile mismatch/],[{language:'typescript'},/language mismatch/]]){const client=makeClient({mutate:r=>({...r,...variant})});await assert.rejects(()=>dev(client),pattern);}});

test('Tree-sitter provider output cannot grant release, security, production or certification authority',async()=>{const health=makeClient({health:{status:'UP',tree_sitter_version:'0.27.0',release_authority:true}});await assert.rejects(()=>dev(health),/attempted forbidden authority/);const parse=makeClient({mutate:r=>({...r,security_pass:true})});await assert.rejects(()=>dev(parse),/attempted forbidden authority/);});

test('Tree-sitter failed or malformed structures fail closed',async()=>{const cases=[[{status:'FAILED'},/parse failed closed/],[{node_count:0,named_node_count:0},/node counts invalid/],[{node_count:2,named_node_count:3},/node counts invalid/],[{root_type:''},/root_type required/],[{captures:[{kind:'',name:'add',node_type:'identifier',start_byte:16,end_byte:19}]},/capture identity invalid/],[{captures:[{kind:'function',name:'add',node_type:'identifier',start_byte:-1,end_byte:19}]},/byte range invalid/],[{captures:[{kind:'function',name:'add',node_type:'identifier',start_byte:16,end_byte:9999}]},/byte range invalid/]];for(const [variant,pattern] of cases){const client=makeClient({mutate:r=>({...r,...variant})});await assert.rejects(()=>dev(client),pattern);}});

test('Tree-sitter source identities fail before parse and duplicate file ids cannot collide',async()=>{for(const variant of [{file_id:''},{work_id:''},{path:''},{language:''}]){const client=makeClient();await assert.rejects(()=>dev(client,variant),/(file_id|work_id|path|language).*(required|invalid)/);assert.equal(client.calls.length,0);}const client=makeClient();await assert.rejects(()=>developerContextRecords('project_12345678',{source_files:[baseFile,{...baseFile,path:'src/duplicate.js'}]},{treeSitterClient:client}),/duplicate source file_id/);assert(client.calls.length<=1);});

test('composeEarnedContext routes Tree-sitter into the normal project-bound composition path',async()=>{const client=makeClient(),result=await composeEarnedContext({projectGraph:{project:{project_id:'project_12345678',name:'Axiom',goal:'Ship',memory_scope:'project-only',revision:1,owner_id:'owner',permissions:[],updated_at:'2026-10-05T04:30:00Z'},objects:[]},developerSnapshot:{source_files:[baseFile]}},{treeSitterClient:client});assert.equal(result.records.filter(row=>row.sourceType==='tree-sitter-code').length,1);assert.equal(result.records.find(row=>row.sourceType==='tree-sitter-code').projectId,'project_12345678');});

test('Tree-sitter syntax errors remain observed facts, never certification',async()=>{const cleanRows=await dev(makeClient());assert.equal(cleanRows[0].content.syntax_status,'CLEAN');const errorRows=await dev(makeClient({mutate:r=>({...r,has_error:true})}));assert.equal(errorRows[0].content.syntax_status,'ERROR_NODES_PRESENT');assert.equal(errorRows[0].content.has_error,true);assert.equal(errorRows[0].metadata.certification_authority,false);assert.equal(errorRows[0].metadata.live_runtime_qualification,'NOT_PROVEN');});
