import {CATALOG,CHANNELS,ROLLBACK,BOOTSTRAP} from './generated-data.mjs';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const app=CATALOG.apps[0];
const release=app.releases.find(r=>r.channel===CATALOG.store.defaultChannel)||app.releases[0];

export function detectPlatform(request){
  const u=new URL(request.url); const p=(u.searchParams.get('platform')||'').toLowerCase();
  if(['android','ios','web'].includes(p)) return p;
  const ua=(request.headers.get('user-agent')||'').toLowerCase();
  if(ua.includes('android')) return 'android';
  if(/iphone|ipad|ipod/.test(ua)) return 'ios';
  return 'web';
}

function nav(){return `<header class="header"><div class="wrap"><nav class="nav" aria-label="Primary"><a class="brand" href="/store">MUSITU STORE</a><div class="navlinks"><a href="/store/apps/chemistry">Chemistry</a><a href="/store/releases">What’s New</a><a href="/store/install">Install</a><a href="/store/status">Status</a><a href="/store/developer">Developer Console</a></div></nav></div></header>`}
function shell(title,description,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="stylesheet" href="/store/assets/store.css"></head><body><a class="skip-link" href="#main">Skip to main content</a>${nav()}${body}<footer class="footer"><div class="wrap"><strong>MUSITU Store</strong> · verified software distribution<br><span>Installing does not buy Premium. Paid access remains controlled by a separate MUSITU signed entitlement after verified settlement.</span><div class="footerlinks"><a href="/store/catalog.json">Catalog</a><a href="/store/catalog.sig">Catalog signature</a><a href="/store/developer">Developer Console</a><a href="${esc(app.supportURL)}">Support</a></div></div></footer></body></html>`}
function crumb(label){return `<div class="breadcrumbs"><a href="/store">MUSITU Store</a> / ${esc(label)}</div>`}
function verified(){return `<span class="badge">Verified release</span>`}
function appSummary(){return `<article class="card app-card"><div class="app-meta">${verified()}<span class="badge">${esc(app.category)}</span><span class="badge">Stable ${esc(release.version)}</span></div><h2><a href="/store/apps/chemistry">${esc(app.name)}</a></h2><p>${esc(app.description)}</p><p class="muted">${esc(app.features.join(' · '))}</p><div class="actions"><a class="button" href="/store/install">Install</a><a class="button secondary" href="/store/apps/chemistry">View release</a></div></article>`}
const lifecycle=[['Install','/store/install','Choose the supported carrier for this device.'],['Open','/store/open','Open the browser/PWA product surface.'],['Update','/store/update','Check the current stable release.'],['Repair','/store/repair','Verify hashes and recover a damaged install.'],['Reinstall','/store/reinstall','Reinstall without treating install state as entitlement.'],['Roll Back','/store/rollback','Only a signed catalog can authorize rollback.'],['Transfer Device','/store/transfer-device','Move learner state, then restore/reissue paid entitlement separately.']];
function lifecycleMarkup(){return `<div class="lifecycle">${lifecycle.map(([a,h,d])=>`<a class="life" href="${h}"><strong>${a}</strong><span class="micro">${d}</span></a>`).join('')}</div>`}

export function renderHome(request){const p=detectPlatform(request);const recommendation=p==='android'?'Android install path':p==='ios'?'iOS SideStore + PWA path':'browser/PWA path';return shell('MUSITU Store','Install and verify MUSITU applications from one catalog.',`<main id="main" tabindex="-1"><div class="wrap"><section class="hero"><div><span class="eyebrow">One verified MUSITU catalog</span><h1>Install MUSITU with release truth you can verify.</h1><p class="lead">MUSITU Store routes each device to a supported experience while keeping software distribution separate from payment and Premium entitlement.</p><div class="actions"><a class="button" href="/store/install">Continue with ${esc(recommendation)}</a><a class="button secondary" href="/store/apps/chemistry">Explore ${esc(app.name)}</a></div><p class="micro">Coarse platform routing uses only the current request’s platform hint or user-agent class; no fingerprint profile is created.</p></div><aside class="card trust"><div>${verified()}<strong>${esc(app.name)} ${esc(release.version)}</strong><span class="micro">Stable catalog revision ${CATALOG.revision}</span></div><div><strong>Catalog signature</strong><span class="micro">Pinned P-256 public verification key</span></div><div><strong>Entitlement boundary</strong><span class="micro">Installing does not buy Premium.</span></div></aside></section><section class="section"><h2>Available now</h2><div class="grid">${appSummary()}</div></section><section class="section"><h2>Full product lifecycle</h2><p class="lead">Every recovery action is explicit. Rollback fails closed unless a signed release manifest authorizes a target.</p>${lifecycleMarkup()}</section><section class="section"><h2>Search the catalog</h2><form class="search" action="/store/search" method="get"><label class="micro" for="q">Search by title, subject, feature or audience</label><input id="q" name="q" type="search" autocomplete="off" required><button class="button" type="submit">Search</button></form></section></div></main>`)}

export function renderApp(){const a=release.android,i=release.ios,w=release.web;return shell(`${app.name} · MUSITU Store`,app.description,`<main id="main" tabindex="-1" class="page"><div class="wrap">${crumb(app.name)}<div class="app-meta">${verified()}<span class="badge">${esc(app.developer)}</span><span class="badge">${esc(release.status)}</span></div><h1>${esc(app.name)}</h1><p class="lead">${esc(app.description)}</p><div class="actions"><a class="button" href="/store/install">Install</a><a class="button secondary" href="/store/open">Open</a><a class="button tertiary" href="${esc(app.commerce.catalogURL)}">Access &amp; pricing</a></div><section class="section"><h2>Release ${esc(release.version)}</h2><div class="grid"><article class="panel"><h2>Android</h2><p>Package ${esc(a.packageId)} · min SDK ${a.minSdk} · target SDK ${a.targetSdk}</p><div class="hash">SHA-256 ${esc(a.sha256)}</div><div class="hash">Signing certificate ${esc(a.signingCertificateSha256)}</div></article><article class="panel"><h2>iOS</h2><p>Bundle ${esc(i.bundleIdentifier)} · minimum iOS ${esc(i.minOSVersion)}</p><div class="hash">IPA SHA-256 ${esc(i.sha256)}</div><p class="micro">Native install requires SideStore; the browser/PWA path remains available.</p></article><article class="panel"><h2>Web / PWA</h2><p>Installable PWA · offline capable</p><div class="hash">Carrier SHA-256 ${esc(w.carrierArchiveSha256)}</div></article></div></section><section class="section"><h2>Permissions &amp; privacy</h2><p>No advertising identifier is required by the Store catalog. Platform routing is coarse and request-local. Chemistry learning state can remain device-local; commerce and Premium entitlement remain separate.</p><p><a href="${esc(app.privacyURL)}">Privacy disclosure</a> · <a href="${esc(app.supportURL)}">Support / report a problem</a> · <a href="/store/transfer-device">Restore / transfer device</a></p></section><section class="section"><h2>Lifecycle</h2>${lifecycleMarkup()}</section></div></main>`)}

export function renderInstall(request){const p=detectPlatform(request);let title,content;if(p==='android'){title='Recommended for Android';content=`<p>Install the signed MUSITU Store bootstrap, then use it to verify the detached catalog signature, APK hash, package identity and signing certificate before Android’s installer opens.</p><div class="actions"><a class="button" href="/store/bootstrap/${esc(BOOTSTRAP.artifactFile)}">Install MUSITU Store</a><a class="button secondary" href="${esc(release.web.appURL)}">Open Chemistry in browser</a></div><div class="hash">Bootstrap SHA-256 ${esc(BOOTSTRAP.sha256)}</div><div class="hash">Store signing certificate ${esc(BOOTSTRAP.signingCertificateSha256)}</div>`}else if(p==='ios'){title='Recommended for iOS';content=`<p>Native install requires SideStore and user-account re-signing. MUSITU Store does not claim a direct App Store-style native install. The PWA remains the supported no-sideload fallback.</p><div class="actions"><a class="button" href="/store/ios/source.json">Open SideStore source</a><a class="button secondary" href="${esc(release.web.appURL)}">Open the PWA</a></div><p class="micro">SideStore source: ${esc(release.ios.sideStoreSourceURL)}</p>`}else{title='Recommended for this browser';content=`<p>Open MUSITU Chemistry as an Installable PWA. Native Windows/macOS/Linux packages are not claimed by this Phase-1 catalog.</p><div class="actions"><a class="button" href="${esc(release.web.appURL)}">Open MUSITU Chemistry</a></div><p class="micro">Installable PWA · offline capable after the application caches successfully.</p>`}return shell(`Install · MUSITU Store`,'Choose the supported MUSITU installation path for this device.',`<main id="main" tabindex="-1" class="page"><div class="wrap">${crumb('Install')}<h1>${title}</h1><div class="notice"><strong>Distribution ≠ entitlement.</strong> Installing or reinstalling does not create, copy or prove paid access.</div><section class="section"><div class="panel">${content}</div></section><p><a href="/store/install?platform=android">Android</a> · <a href="/store/install?platform=ios">iOS</a> · <a href="/store/install?platform=web">Web/PWA</a></p></div></main>`)}

export function renderSearch(query){const q=(query||'').trim().toLowerCase();const hay=a=>[a.name,a.developer,a.category,...a.subjects,...a.features,...a.audience,a.description].join(' ').toLowerCase();const found=q?CATALOG.apps.filter(a=>hay(a).includes(q)):[];return shell('Search · MUSITU Store','Search the MUSITU app catalog.',`<main id="main" tabindex="-1" class="page"><div class="wrap">${crumb('Search')}<h1>Search the catalog</h1><form class="search" action="/store/search" method="get"><input aria-label="Search catalog" name="q" value="${esc(query||'')}" required><button class="button" type="submit">Search</button></form>${found.length?`<div class="grid">${found.map(()=>appSummary()).join('')}</div>`:`<p class="notice">No matching apps.</p>`}</div></main>`)}

export function renderDeveloper(){const cert=release.android.signingCertificateSha256;return shell('Developer Console · MUSITU Store','Read-only public release control and provenance for MUSITU Store Phase 1.',`<main id="main" tabindex="-1" class="page"><div class="wrap">${crumb('Developer Console')}<span class="eyebrow">Read-only Phase 1</span><h1>Developer Console</h1><p class="lead">Public release state is rendered from the signed catalog and release manifests. Production promotion, retirement and rollout mutation require a separately signed manifest and release gate.</p><div class="notice"><strong>Signed manifest required.</strong> This console cannot publish an unsigned change.</div><section class="section console-grid"><article class="console-card"><h2>Release control</h2><p><strong>catalog revision</strong> ${CATALOG.revision}</p><p><strong>phase</strong> ${esc(CATALOG.releaseControl.phase)}</p><p><strong>phase2Authorized</strong>: false</p><p><strong>publication state</strong> ${esc(CATALOG.releaseControl.publicationState)}</p><div class="console-actions"><button type="button" disabled>Promote release</button><button type="button" disabled>Retire release</button><button type="button" disabled>Change rollout</button></div></article><article class="console-card"><h2>Signing identities</h2><p>Catalog public key SHA-256</p><div class="hash">${esc(CATALOG.releaseControl.catalogPublicKeySha256)}</div><p>Chemistry Android certificate</p><div class="hash">${esc(cert)}</div><p>Store Android certificate</p><div class="hash">${esc(BOOTSTRAP.signingCertificateSha256)}</div></article><article class="console-card"><h2>Channels</h2><div class="table-wrap"><table class="table"><thead><tr><th>Channel</th><th>State</th><th>Rollout</th></tr></thead><tbody>${Object.entries(CHANNELS.channels).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v.state)}</td><td>${v.rolloutPercent}%${v.paused?' · paused':''}</td></tr>`).join('')}</tbody></table></div></article><article class="console-card"><h2>Provenance &amp; compatibility</h2><p>Source branch: <code>${esc(release.provenance.sourceBranch)}</code></p><p>Sealed Chemistry head: <code>${esc(release.provenance.chemistrySealedHead)}</code></p><p>Android: min SDK ${release.android.minSdk}, target ${release.android.targetSdk}</p><p>iOS: minimum ${esc(release.ios.minOSVersion)}</p><p>Web: installable PWA</p></article></section></div></main>`)}

export function renderReleases(){return shell('What’s New · MUSITU Store','Stable MUSITU release history.',`<main id="main" tabindex="-1" class="page"><div class="wrap">${crumb('What’s New')}<h1>What’s New</h1><article class="release-card">${verified()}<h2>${esc(app.name)} ${esc(release.version)}</h2><p>${esc(release.releaseNotes)}</p><p class="micro">Stable · Android ${release.android.bytes.toLocaleString()} bytes · iOS ${release.ios.bytes.toLocaleString()} bytes</p><a href="/store/apps/chemistry">Verify release</a></article></div></main>`)}

export function renderStatus(){return shell('Status · MUSITU Store','Current signed release-channel status.',`<main id="main" tabindex="-1" class="page"><div class="wrap">${crumb('Status')}<h1>Release status</h1><div class="status">${Object.entries(CATALOG.channels).map(([k,v])=>`<div><strong>${esc(k)}</strong><br><span>${esc(v.state)} · ${v.rolloutPercent}%${v.paused?' · paused':''}</span></div>`).join('')}</div><section class="section"><div class="notice">Phase 2 remains unauthorized. Fresh-device Phase-1 completion is not yet claimed.</div></section></div></main>`)}

export function renderLifecycle(kind){const map={update:['Update',`Current signed stable release: ${app.name} ${release.version}. The Store compares signed catalog state; it does not infer paid status from installation.`],repair:['Repair',`Verify the release hash and signing identity. If bytes are corrupt, reinstall the same signed release; Premium entitlement remains separately verified.`],reinstall:['Reinstall',`Reinstall the supported carrier. Export learner progress first when migrating environments. Reinstallation does not automatically transfer paid entitlement.`],rollback:['Roll Back',ROLLBACK['musitu-chemistry'].authorized?'A signed rollback target is authorized.':'No rollback is currently authorized. The signed rollback policy fails closed.'], 'transfer-device':['Transfer Device',`Export learner progress, install MUSITU Chemistry on the new device, import learner state, then restore or request reissue of Premium for the new Device ID. Do not clone commerce state.`]};const [title,text]=map[kind];return shell(`${title} · MUSITU Store`,text,`<main id="main" tabindex="-1" class="page"><div class="wrap">${crumb(title)}<h1>${title}</h1><div class="panel"><p>${esc(text)}</p><div class="actions"><a class="button" href="/store/install">Install path</a><a class="button secondary" href="${esc(app.supportURL)}">Support / restore purchase</a></div></div></div></main>`)}
