import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {randomBytes,createHash} from 'node:crypto';
import {generateDemonstrationKeys} from '../src/evidence.mjs';
import {MailFabric} from '../src/fabric.mjs';
import {createSimulatedProvider} from '../src/providers.mjs';
import {createKeyTransition,initialTrustHead} from '../src/trust/transitions.mjs';
const entry=new URL('../src/trust/verify-cli.mjs',import.meta.url);
test('standalone verifier requires pinned root AND latest head, refusing rollback and tampering',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'mmf-rotation-cli-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));
 const first=generateDemonstrationKeys(),second=generateDemonstrationKeys(),root=first.publicKey.export({format:'pem',type:'spki'}).toString();
 const tenant='pilot-company';
 const transition=createKeyTransition({tenantId:tenant,previousHead:initialTrustHead(tenant,root),sequence:1,oldPrivateKey:first.privateKey,oldPublicKey:first.publicKey,newPrivateKey:second.privateKey,newPublicKey:second.publicKey,issuedAt:'2026-10-10T00:00:00.000Z'});
 const head=createHash('sha256').update(JSON.stringify(transition)).digest('hex');
 const fab=new MailFabric({tenantId:tenant,verifiedDomains:['example.org'],allowedRegions:['us-east-1'],provider:createSimulatedProvider()},{keys:second,privacyKey:randomBytes(32)});
 const receipt=(await fab.submit({tenantId:tenant,from:'sender@example.org',to:'member@example.net',subject:'Test',text:'Confidential',kind:'ACCOUNT',idempotencyKey:'trusted-012345'})).proof;
 const rp=join(dir,'receipt.json'),tp=join(dir,'rotations.json'),kp=join(dir,'root.pem');
 writeFileSync(rp,JSON.stringify(receipt));writeFileSync(tp,JSON.stringify([transition]));writeFileSync(kp,root);
 const args=['--receipt',rp,'--root-key',kp,'--transitions',tp,'--trusted-head',head,'--tenant',tenant];
 const run=items=>spawnSync(process.execPath,[entry.pathname,...items],{encoding:'utf8'});
 assert.equal(run(args).status,0);
 assert.match(run(args).stdout,/VERIFIED_CURRENT_KEY/);
 const noHead=run(args.slice(0,6).concat(args.slice(8)));assert.notEqual(noHead.status,0);
 const rollback=run(args.map(s=>s===head?'0'.repeat(64):s));assert.notEqual(rollback.status,0);
 const altered=structuredClone(receipt);altered.events[0].detail.kind='SECURITY';writeFileSync(rp,JSON.stringify(altered));assert.notEqual(run(args).status,0);
});
