from pathlib import Path

p = Path(__file__).with_name('index.storefront.mjs')
s = p.read_text()

# Harden the public storefront response without changing checkout/payment handlers.
s = s.replace(
    "return html(`<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>MUSITU Chemistry Mastery</title><meta name=\"description\" content=\"Download MUSITU Chemistry Mastery for Android and unlock premium A-Level Chemistry mastery plans securely.\">",
    "return publicHtml(`<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>MUSITU Chemistry Mastery | Android A-Level Chemistry</title><meta name=\"description\" content=\"Download MUSITU Chemistry Mastery for Android. Diagnose weaknesses, learn A-Level Chemistry, practise under exam conditions and unlock premium plans securely.\"><meta name=\"robots\" content=\"index,follow,max-image-preview:large\"><link rel=\"canonical\" href=\"https://payments.mftintelligence.com/chemistry/\"><meta property=\"og:type\" content=\"website\"><meta property=\"og:title\" content=\"MUSITU Chemistry Mastery\"><meta property=\"og:description\" content=\"Diagnose, learn, practise and review A-Level Chemistry in one focused Android app.\"><meta property=\"og:url\" content=\"https://payments.mftintelligence.com/chemistry/\"><meta name=\"twitter:card\" content=\"summary\">",
    1,
)

old_nav = '<div class="navlinks"><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="/chemistry/claim">Activate a seat</a></div>'
new_nav = '<div class="navlinks"><a href="#features">Features</a><a href="#pricing">Pricing</a><a href="/chemistry/support">Support</a><a href="/chemistry/claim">Activate a seat</a></div>'
if s.count(old_nav) != 1:
    raise SystemExit('storefront nav marker mismatch')
s = s.replace(old_nav, new_nav, 1)

old_footer = '<footer class="footer"><div class="wrap"><strong>MUSITU Chemistry Mastery</strong> · MUSITU Education Nexus<br><span>Payment and licence-signing secrets remain server-side. A licence is issued only after verified settlement.</span></div></footer>'
new_footer = '<footer class="footer"><div class="wrap"><strong>MUSITU Chemistry Mastery</strong> · MUSITU Education Nexus<br><span>Payment and licence-signing secrets remain server-side. A licence is issued only after verified settlement.</span><br><span><a href="/chemistry/privacy">Privacy</a> · <a href="/chemistry/terms">Terms</a> · <a href="/chemistry/support">Support</a> · <a href="/chemistry/sitemap.xml">Sitemap</a></span></div></footer>'
if s.count(old_footer) != 1:
    raise SystemExit('storefront footer marker mismatch')
s = s.replace(old_footer, new_footer, 1)

marker = 'function storefrontPage(){'
if s.count(marker) != 1:
    raise SystemExit('storefront function marker mismatch')

PUBLIC = r'''
const PUBLIC_HEADERS={
  'x-content-type-options':'nosniff',
  'referrer-policy':'strict-origin-when-cross-origin',
  'x-frame-options':'DENY',
  'permissions-policy':'camera=(), microphone=(), geolocation=(), payment=()',
  'content-security-policy':"default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; frame-ancestors 'none'; form-action 'self' https://www.paynow.co.zw"
};
function publicHtml(body,status=200,extra={}){return html(body,status,{...PUBLIC_HEADERS,...extra});}
function publicShell(title,description,body){return publicHtml(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)} | MUSITU Chemistry Mastery</title><meta name="description" content="${escapeHtml(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="https://payments.mftintelligence.com${escapeHtml(new URL('https://payments.mftintelligence.com'+body.path).pathname)}"><style>:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#111827;background:#f7f8fc}*{box-sizing:border-box}body{margin:0;background:#f7f8fc}.wrap{max-width:820px;margin:auto;padding:28px 20px 70px}a{color:#111827}nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:54px}.brand{font-weight:900;letter-spacing:.08em;text-decoration:none}.back{text-decoration:none;font-weight:700}.card{background:#fff;border:1px solid #e3e6ed;border-radius:20px;padding:clamp(22px,5vw,44px)}h1{font-size:clamp(34px,7vw,54px);letter-spacing:-.04em;margin:0 0 16px}h2{margin-top:34px;font-size:22px}p,li{color:#596274;line-height:1.72}li{margin:8px 0}.cta{display:inline-block;background:#111827;color:white;text-decoration:none;font-weight:800;padding:12px 16px;border-radius:11px;margin:8px 8px 8px 0}.secondary{background:white;color:#111827;border:1px solid #111827}.note{background:#f3f4f6;border-radius:12px;padding:14px 16px;font-size:14px}.footer{font-size:13px;color:#6b7280;margin-top:30px}</style></head><body><div class="wrap"><nav><a class="brand" href="/chemistry/">MUSITU</a><a class="back" href="/chemistry/">← Chemistry Mastery</a></nav><div class="card">${body.html}</div><div class="footer"><a href="/chemistry/privacy">Privacy</a> · <a href="/chemistry/terms">Terms</a> · <a href="/chemistry/support">Support</a></div></div></body></html>`,200,{'cache-control':'public, max-age=300'});}
function privacyPage(){return publicShell('Privacy','How MUSITU Chemistry Mastery handles app, purchase and licence data',{path:'/chemistry/privacy',html:`<h1>Privacy</h1><p>Last updated: 6 September 2026.</p><p>MUSITU Chemistry Mastery is designed so that ordinary learning progress can remain on the learner’s device. The commerce service processes only the information needed to create orders, verify settlement, issue device-bound licences, provide multi-seat access and support legitimate restore or transfer requests.</p><h2>Information processed for purchases</h2><ul><li>Plan, price, currency and order identifiers.</li><li>The purchaser or licence-holder name and, when supplied, email address.</li><li>The Chemistry Mastery Device ID needed to bind a paid licence to the intended installation.</li><li>Payment-provider references, status and verification results. MUSITU does not put the Paynow merchant secret inside the Android app.</li><li>Issued licence identifiers, seat numbers, device bindings and entitlement dates.</li></ul><h2>Learning data</h2><p>Chapter progress, confidence, bookmarks, review state and similar study data are primarily stored by the app on the device. Exported backups are controlled by the user unless they are voluntarily supplied for support.</p><h2>Payment provider</h2><p>Checkout is handed to Paynow. Payment information entered on Paynow is handled under Paynow’s own privacy and security practices. MUSITU receives the transaction information needed to verify whether settlement occurred; it does not need to collect card or mobile-wallet credentials inside the APK.</p><h2>Use and retention</h2><p>Commerce records are used to fulfil purchases, prevent duplicate or fraudulent licence issuance, support seat claims and restores, maintain security and meet applicable operational or legal obligations. Data is not sold to advertisers.</p><h2>Security</h2><p>Licence-signing private keys and payment authority stay server-side. The public Android app contains only verification material required to validate a signed entitlement.</p><h2>Questions or access requests</h2><p>Use the <a href="/chemistry/support">support page</a> and include the minimum information needed to identify the order or licence. Never send passwords, payment PINs or one-time codes.</p>`});}
function termsPage(){return publicShell('Terms','Terms for downloading, using and purchasing MUSITU Chemistry Mastery',{path:'/chemistry/terms',html:`<h1>Terms of use</h1><p>Last updated: 6 September 2026.</p><p>These terms apply to MUSITU Chemistry Mastery, including the free Android installer and paid Premium entitlements.</p><h2>Free app</h2><p>The installer may be downloaded without payment. Free access includes the features identified on the storefront. A free installer does not include a paid entitlement.</p><h2>Premium licences</h2><p>Premium access is granted only by a valid MUSITU-signed licence after verified settlement. Licences are bound to the purchased plan, seat and Device ID. Family, Tutor and School plans may claim additional devices only up to the purchased seat limit.</p><h2>Payments</h2><p>Prices displayed at checkout are calculated by the MUSITU server. Checkout may be processed by Paynow or another clearly identified provider. A checkout page, pending transaction or screenshot is not proof of settlement. Premium is issued only after the server verifies settlement evidence.</p><h2>Permitted use</h2><p>You may use the app and valid licence for personal learning, teaching or institutional use consistent with the plan purchased. You may not forge licences, bypass entitlement controls, impersonate another purchaser, manipulate payment callbacks or use another customer’s paid seat without authorization.</p><h2>Education boundary</h2><p>MUSITU Chemistry Mastery is an educational tool. It can support study and exam preparation, but it does not guarantee a particular examination result, grade, admission outcome or qualification.</p><h2>Updates and compatibility</h2><p>Updates may change features, fix defects or strengthen security. Keep the release signing continuity and your progress backup when moving between installations. Device transfers and restores can require purchase verification before a replacement licence is issued.</p><h2>Refunds and disputes</h2><p>Refunds, reversals and disputes are handled according to applicable law, the payment provider’s rules and the circumstances of the transaction. A refunded or reversed purchase may no longer qualify for an active paid entitlement.</p><h2>Support</h2><p>For installation, activation, seat-claim or payment-status guidance, use <a href="/chemistry/support">MUSITU Chemistry support</a>.</p>`});}
function supportPage(){return publicShell('Support','Install, purchase, activate, restore and claim seats in MUSITU Chemistry Mastery',{path:'/chemistry/support',html:`<h1>Support</h1><p>Use the steps below for the fastest path from download to Premium access.</p><h2>1. Install the authentic app</h2><p><a class="cta" href="/chemistry/download/${RELEASE.apk}">Download Android APK</a></p><p class="note">Release ${RELEASE.version} · SHA-256 ${RELEASE.sha256}</p><h2>2. Start free or choose Premium</h2><p>The app can be installed and used in Free mode without payment. When you want Premium, open <a href="/chemistry/#pricing">Pricing</a> and choose a plan.</p><h2>3. Find your Device ID</h2><p>In Chemistry Mastery, open <strong>More → Access & pricing</strong>. Copy the Device ID shown there. Paid licences are bound to that exact installation, so check the value before checkout.</p><h2>4. After payment</h2><p>Return to the MUSITU checkout result page. If settlement has been verified, the page displays the signed activation licence. Copy it into <strong>More → Access & pricing → Activate a licence</strong>.</p><p class="note">If the provider still shows the transaction as pending, do not create repeated payments. The licence is intentionally withheld until settlement is independently verified.</p><h2>5. Family, Tutor or School seats</h2><p>After the order is paid, additional devices can be attached to remaining seats. Use <a href="/chemistry/claim">Activate a seat</a> with the order credentials issued to the purchaser.</p><h2>6. Reinstall, transfer or restore</h2><p>A reinstall can create a new Device ID. Keep your purchase evidence and progress export. A replacement licence may require purchase verification before it is reissued to a new device.</p><h2>Contact support</h2><p><a class="cta" href="https://wa.me/263781572008">WhatsApp MUSITU support</a><a class="cta secondary" href="/chemistry/">Back to storefront</a></p><p>For payment support, provide only the order or provider reference needed to locate the transaction. Never send a password, PIN, OTP, private key or full payment credential.</p>`});}
function sitemapXml(){return new Response(`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://payments.mftintelligence.com/chemistry/</loc></url><url><loc>https://payments.mftintelligence.com/chemistry/privacy</loc></url><url><loc>https://payments.mftintelligence.com/chemistry/terms</loc></url><url><loc>https://payments.mftintelligence.com/chemistry/support</loc></url></urlset>`,{status:200,headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=3600','x-content-type-options':'nosniff'}});}
function securityText(){return new Response(`Contact: https://wa.me/263781572008\nCanonical: https://payments.mftintelligence.com/chemistry/security.txt\nPolicy: https://payments.mftintelligence.com/chemistry/terms\nExpires: 2027-09-06T00:00:00Z\n`,{status:200,headers:{'content-type':'text/plain; charset=utf-8','cache-control':'public, max-age=3600','x-content-type-options':'nosniff'}});}
'''

s = s.replace(marker, PUBLIC + '\n' + marker, 1)

old_dispatch = "export async function handleRequest(req,env){const u=new URL(req.url),p=u.pathname;if(req.method==='GET'&&(p==='/chemistry'||p==='/chemistry/'))return storefrontPage();if(req.method==='GET'&&p==='/chemistry/healthz')return health(env);"
new_dispatch = "export async function handleRequest(req,env){const u=new URL(req.url),p=u.pathname;if(req.method==='GET'&&(p==='/chemistry'||p==='/chemistry/'))return storefrontPage();if(req.method==='GET'&&p==='/chemistry/privacy')return privacyPage();if(req.method==='GET'&&p==='/chemistry/terms')return termsPage();if(req.method==='GET'&&p==='/chemistry/support')return supportPage();if(req.method==='GET'&&p==='/chemistry/sitemap.xml')return sitemapXml();if(req.method==='GET'&&p==='/chemistry/security.txt')return securityText();if(req.method==='GET'&&p==='/chemistry/healthz')return health(env);"
if s.count(old_dispatch) != 1:
    raise SystemExit('public dispatch marker mismatch')
s = s.replace(old_dispatch, new_dispatch, 1)

# Ensure the storefront call was actually upgraded to the public security wrapper.
if 'return publicHtml(`<!doctype html><html lang="en"><head>' not in s:
    raise SystemExit('storefront publicHtml hardening missing')

Path(__file__).with_name('index.public.mjs').write_text(s)
