const VERSION="3.0.0";
const NOAUTH=new Set(["search","fetch","musitu_axiom_capabilities","musitu_axiom_plans","musitu_axiom_recommend_plan"]);
const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const GENERIC_OUTPUT={type:"object",additionalProperties:true};
function response(status,body,extra={}){return new Response(JSON.stringify(body),{status,headers:{...JSON_HEADERS,...extra}})}
function cfg(env){return{db:env.AXIOM_DB,core:env.MCP_CORE,issuer:env.AUTH_ISSUER||"https://auth.mftintelligence.com",resource:env.MCP_PUBLIC_BASE||"https://mcp.mftintelligence.com"}}
async function hash(s){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function bearer(req){const a=req.headers.get("authorization")||"";return a.startsWith("Bearer ")&&a.length>12?a.slice(7):""}
function neededScope(name){if(NOAUTH.has(name))return null;if(name==="musitu_axiom_start_checkout")return"billing.write";if(name==="musitu_axiom_checkout_status")return"billing.read";return"axiom.execute"}
function challenge(c,scope){return `Bearer resource_metadata="${c.resource}/.well-known/oauth-protected-resource", scope="${scope}", error="insufficient_scope", error_description="Connect or reauthorize your MUSITU Axiom account"`}
function authToolResult(id,c,scope,reason="OAuth authorization is required for this MUSITU Axiom capability."){return response(200,{jsonrpc:"2.0",id,result:{content:[{type:"text",text:reason}],structuredContent:{authenticated:false,required_scope:scope},_meta:{"mcp/www_authenticate":[challenge(c,scope)]},isError:true}})}
async function validate(req,c,scope){const token=bearer(req);if(!token)return{ok:false,reason:"missing_token"};const th=await hash(token);const now=new Date().toISOString();const row=await c.db.prepare("SELECT a.customer_id,a.issuer,a.resource,a.scope,a.expires_at,a.revoked_at,k.status AS key_status,k.expires_at AS key_expires,k.revoked_at AS key_revoked FROM oauth_access_tokens a JOIN api_keys k ON k.id=a.api_key_id WHERE a.token_hash=?1 LIMIT 1").bind(th).first();if(!row)return{ok:false,reason:"unknown_token"};if(row.revoked_at||row.key_revoked||row.key_status!=="active")return{ok:false,reason:"revoked_token"};if(row.expires_at<=now||(row.key_expires&&row.key_expires<=now))return{ok:false,reason:"expired_token"};if(row.issuer!==c.issuer||row.resource!==c.resource)return{ok:false,reason:"issuer_or_audience_mismatch"};const scopes=new Set(String(row.scope||"").split(/\s+/).filter(Boolean));if(!scopes.has(scope))return{ok:false,reason:"insufficient_scope"};return{ok:true,customer_id:row.customer_id}}
async function core(c,path,method="GET",headers={},body=null){const req=new Request(c.resource+path,{method,headers,body});return c.core.fetch(req)}
function correctedTool(t){const x={...t};const name=String(x.name||"");let annotations;if(NOAUTH.has(name))annotations={readOnlyHint:true,openWorldHint:false,destructiveHint:false};else if(name==="musitu_axiom_start_checkout")annotations={readOnlyHint:false,openWorldHint:true,destructiveHint:false,idempotentHint:false};else if(name==="musitu_axiom_checkout_status")annotations={readOnlyHint:false,openWorldHint:false,destructiveHint:false};else annotations={readOnlyHint:false,openWorldHint:false,destructiveHint:false};x.annotations=annotations;x.outputSchema=x.outputSchema||GENERIC_OUTPUT;if(NOAUTH.has(name))x.securitySchemes=[{type:"noauth"}];else x.securitySchemes=[{type:"oauth2",scopes:[neededScope(name)]}];x._meta={...(x._meta||{}),"openai/toolInvocation/invoking":"Running MUSITU Axiom…","openai/toolInvocation/invoked":"MUSITU Axiom completed"};return x}
async function rewriteTools(c,id){const r=await core(c,"/mcp","POST",{"content-type":"application/json",accept:"application/json","user-agent":"MUSITU-Axiom-MCP-OAuth-Gate/3.0"},JSON.stringify({jsonrpc:"2.0",id,method:"tools/list",params:{}}));const text=await r.text();let o={};try{o=JSON.parse(text||"{}")}catch{return response(200,{jsonrpc:"2.0",id,error:{code:-32603,message:"MCP core returned invalid tool registry"}})}const tools=o?.result?.tools;if(!Array.isArray(tools))return response(200,o);o.result.tools=tools.map(correctedTool);return response(200,o)}
async function mcp(req,c){if(req.method!=="POST")return response(405,{error:"method_not_allowed"},{allow:"POST"});const raw=await req.text();let m;try{m=JSON.parse(raw)}catch{return response(200,{jsonrpc:"2.0",id:null,error:{code:-32700,message:"Parse error"}})}const id=m?.id??null;if(m?.method==="tools/list")return rewriteTools(c,id);if(m?.method==="tools/call"){const name=String(m?.params?.name||"");const scope=neededScope(name);if(scope){const v=await validate(req,c,scope);if(!v.ok)return authToolResult(id,c,scope,v.reason==="insufficient_scope"?`Your MUSITU OAuth session does not include ${scope}. Reauthorize to use this capability.`:"Connect your MUSITU Axiom account to use this paid capability.")}}
const h=new Headers(req.headers);h.set("content-type","application/json");h.set("accept","application/json");h.set("user-agent","MUSITU-Axiom-MCP-OAuth-Gate/3.0");const r=await core(c,"/mcp","POST",h,raw);return new Response(r.body,{status:r.status,headers:r.headers})}
async function health(c){const r=await core(c,"/health","GET",{accept:"application/json","user-agent":"MUSITU-Axiom-MCP-OAuth-Gate/3.0"});let coreHealth={};try{coreHealth=await r.json()}catch{}let db=false;try{await c.db.prepare("SELECT 1 FROM oauth_access_tokens LIMIT 1").first();db=true}catch{}return{ok:r.status===200&&coreHealth.ok===true&&db,service:"MUSITU Axiom MCP OAuth Gate",server_version:VERSION,oauth_enforced:true,auth_issuer:c.issuer,resource:c.resource,oauth_db_ready:db,core:coreHealth,wolfram_parity:"NOT_CERTIFIED",superiority:"NOT_CERTIFIED"}}
export default{async fetch(req,env){const c=cfg(env),u=new URL(req.url);if(!c.db||!c.core)return response(503,{error:"mcp_oauth_gate_not_configured"});if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"authorization,content-type,mcp-session-id,x-musitu-request-id"}});if(u.pathname==="/health"&&req.method==="GET"){const h=await health(c);return response(h.ok?200:503,h)}if(u.pathname==="/.well-known/oauth-protected-resource"&&req.method==="GET")return response(200,{resource:c.resource,authorization_servers:[c.issuer],scopes_supported:["axiom.execute","billing.read","billing.write"],resource_documentation:c.resource+"/docs"});if(u.pathname==="/docs"&&req.method==="GET")return response(200,{service:"MUSITU Axiom MCP",endpoint:c.resource+"/mcp",authentication:"OAuth 2.1",authorization_server:c.issuer,oauth_enforced:true,scope_model:{"axiom.execute":"Paid Axiom compute and quantitative products","billing.read":"Checkout status and entitlement reconciliation","billing.write":"Explicitly requested subscription checkout creation"},payment_policy:"Checkout creation never authorizes or submits payment; the user completes payment with Paynow."});if(u.pathname==="/mcp")return mcp(req,c);return response(404,{error:"not_found"})}};
