const VERSION="2.0.0";
const DEFAULTS={axiomBase:"https://axiom.mftintelligence.com",billingBase:"https://payments.mftintelligence.com",publicBase:"https://mcp.mftintelligence.com"};
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const BUSINESS={
  investment_npv:"finance.npv",compound_growth:"finance.compound",option_black_scholes:"finance.black_scholes",option_greeks:"finance.greeks",
  implied_volatility:"finance.implied_vol",historical_var:"finance.var_historical",parametric_var:"finance.var_parametric",historical_cvar:"finance.cvar_historical",
  portfolio_metrics:"finance.portfolio_metrics",returns_analysis:"finance.returns",market_beta:"finance.beta",drawdown_analysis:"finance.drawdown",
  monte_carlo_scenario:"finance.monte_carlo_gbm",bond_price:"finance.bond_price",bond_yield:"finance.bond_yield",bond_duration:"finance.duration",
  rolling_volatility:"timeseries.rolling_volatility",moving_average:"timeseries.moving_average",ewma_forecast:"timeseries.ewma",
  regression_analysis:"statistics.regression",correlation_analysis:"statistics.correlation",covariance_analysis:"statistics.covariance",descriptive_statistics:"statistics.describe",
  quantile_analysis:"statistics.quantile",zscore_analysis:"statistics.zscore",linear_optimization:"optimization.linear_program",quadratic_optimization:"optimization.quadratic",
  least_squares:"numeric.least_squares",interpolate_series:"numeric.interpolate",verify_calculation:"verify.crosscheck"
};
function out(s,b,x={}){return new Response(JSON.stringify(b),{status:s,headers:{...H,...x}})}
function ok(id,result){return out(200,{jsonrpc:"2.0",id,result})}
function err(id,code,message,data){return ok(id,{error:{code,message,...(data===undefined?{}:{data})}})}
function tr(text,structuredContent={},meta,isError=false){const r={content:[{type:"text",text}],structuredContent};if(meta)r._meta=meta;if(isError)r.isError=true;return r}
function cfg(env){return{axiomBase:env.AXIOM_BASE||DEFAULTS.axiomBase,billingBase:env.BILLING_BASE||DEFAULTS.billingBase,publicBase:env.MCP_PUBLIC_BASE||DEFAULTS.publicBase,authIssuer:env.AUTH_ISSUER||"",axiomService:env.AXIOM_SERVICE||null,billingService:env.BILLING_SERVICE||null}}
async function jf(service,url,init={}){try{const r=service?.fetch?await service.fetch(url,init):await fetch(url,init);const text=await r.text();let obj={};try{obj=JSON.parse(text||"{}")}catch{}return{status:r.status,obj,text}}catch(e){return{status:0,obj:{},text:String(e)}}}
function bearer(req){const h=req.headers.get("authorization")||"";return h.startsWith("Bearer ")&&h.length>12?h:""}
function schemes(scope){return[{type:"oauth2",scopes:[scope]}]}
function authRequired(c,scope,msg){const meta=c.authIssuer?{"mcp/www_authenticate":[`Bearer resource_metadata="${c.publicBase}/.well-known/oauth-protected-resource", scope="${scope}", error="insufficient_scope"`]}:{"musitu/auth_status":"OAUTH_PROVIDER_NOT_CONFIGURED"};return tr(msg||"Connect your MUSITU account to continue.",{authenticated:false},meta,true)}
async function registry(c){const r=await jf(c.axiomService,`${c.axiomBase}/v1/tools`,{headers:{accept:"application/json","user-agent":"MUSITU-Axiom-MCP/2.0"}});if(r.status!==200)throw new Error(`registry HTTP ${r.status}`);const raw=Array.isArray(r.obj.tools)?r.obj.tools:[];const tools=raw.map(x=>typeof x==="string"?x:String(x?.operation||x?.name||x?.id||"")).filter(Boolean);const n=Number(r.obj.operation_count||tools.length);if(!tools.length||tools.length!==n)throw new Error(`registry cardinality ${tools.length}/${n}`);return{tools,operationCount:n,buildId:r.obj.build_id||null}}
async function health(c){const [ah,rg,bh]=await Promise.all([jf(c.axiomService,`${c.axiomBase}/health`,{headers:{accept:"application/json"}}),registry(c).catch(e=>({error:String(e)})),jf(c.billingService,`${c.billingBase}/billing/healthz`,{headers:{accept:"application/json"}})]);const good=ah.status===200&&!rg.error&&bh.status===200&&bh.obj?.ok===true;return{ok:good,service:"MUSITU Axiom MCP Gateway",server_version:VERSION,axiom_health_http:ah.status,billing_health_http:bh.status,build_id:rg.buildId||ah.obj?.build_id||null,operation_count:rg.operationCount||null,catalog_configured:bh.obj?.catalog_configured===true,checkout_enabled:bh.obj?.checkout_enabled===true,oauth_provider_configured:Boolean(c.authIssuer),service_bound_axiom:Boolean(c.axiomService),service_bound_billing:Boolean(c.billingService),wolfram_parity:"NOT_CERTIFIED",superiority:"NOT_CERTIFIED"}}
function safeName(op,used){let n="axiom_"+op.toLowerCase().replace(/[^a-z0-9_-]+/g,"_").replace(/^_+|_+$/g,"");if(n.length>60)n=n.slice(0,60);let x=n,i=2;while(used.has(x))x=n.slice(0,56)+"_"+(i++);used.add(x);return x}
function ann(op){const n=op.toLowerCase();const destructive=/(delete|remove|terminate|liquidate|closeall|close_all|wipe|purge|revoke)/.test(n);const open=/(trade|order|send|publish|submit|execute|payment|checkout|transfer|withdraw|deposit)/.test(n);return{readOnlyHint:!destructive&&!open,destructiveHint:destructive,openWorldHint:open}}
function argsSchema(){return{type:"object",properties:{args:{type:"object",additionalProperties:true}},required:["args"],additionalProperties:false}}
async function catalog(c){const r=await jf(c.billingService,`${c.billingBase}/billing/catalog`,{headers:{accept:"application/json","user-agent":"MUSITU-Axiom-MCP/2.0"}});if(r.status!==200)throw new Error(`catalog HTTP ${r.status}`);return r.obj}
async function toolSet(c){const rg=await registry(c);const present=new Set(rg.tools),used=new Set(),map=new Map();const stat=[
{name:"search",title:"Search MUSITU Axiom",description:"Search MUSITU Axiom capabilities and commercial offerings. Use for capability discovery before selecting a paid tool.",inputSchema:{type:"object",properties:{query:{type:"string",minLength:1}},required:["query"],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:"noauth"}]},
{name:"fetch",title:"Fetch MUSITU Axiom Resource",description:"Fetch details for a MUSITU Axiom capability or subscription plan returned by search.",inputSchema:{type:"object",properties:{id:{type:"string",minLength:1}},required:["id"],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:"noauth"}]},
{name:"musitu_axiom_capabilities",title:"MUSITU Axiom Capabilities",description:"List MUSITU Axiom runtime and business capabilities.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:"noauth"}]},
{name:"musitu_axiom_plans",title:"MUSITU Axiom Plans",description:"Show current MUSITU Axiom plans, prices and monthly unit limits.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:"noauth"}]},
{name:"musitu_axiom_recommend_plan",title:"Recommend MUSITU Axiom Plan",description:"Recommend the lowest current plan covering an estimated monthly unit requirement.",inputSchema:{type:"object",properties:{estimated_monthly_units:{type:"integer",minimum:1}},required:["estimated_monthly_units"],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:[{type:"noauth"}]},
{name:"musitu_axiom_execute",title:"Execute Any MUSITU Axiom Operation",description:"Execute any operation in the certified Axiom registry. Prefer a focused business or operation tool when available.",inputSchema:{type:"object",properties:{operation:{type:"string",minLength:1},args:{type:"object",additionalProperties:true}},required:["operation","args"],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:schemes("axiom.execute")},
{name:"musitu_axiom_start_checkout",title:"Start MUSITU Axiom Checkout",description:"Create a Paynow checkout only after the user explicitly asks to subscribe or upgrade. This never authorizes or submits payment.",inputSchema:{type:"object",properties:{plan:{type:"string",enum:["developer","pro","enterprise"]},confirm_create_checkout:{type:"boolean",const:true}},required:["plan","confirm_create_checkout"],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:true,idempotentHint:false},securitySchemes:schemes("billing.write")},
{name:"musitu_axiom_checkout_status",title:"Check MUSITU Axiom Checkout Status",description:"Check provider and entitlement reconciliation status for an existing checkout.",inputSchema:{type:"object",properties:{reference:{type:"string",minLength:1,maxLength:256}},required:["reference"],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true},securitySchemes:schemes("billing.read")}
];for(const t of stat)used.add(t.name);
const business=[];for(const [name,op] of Object.entries(BUSINESS)){if(!present.has(op))continue;used.add(name);map.set(name,op);business.push({name,title:name.split("_").map(x=>x[0].toUpperCase()+x.slice(1)).join(" "),description:`Use this paid MUSITU Axiom business capability backed by ${op}. Pass the native operation arguments in args.`,inputSchema:argsSchema(),annotations:ann(op),securitySchemes:schemes("axiom.execute"),_meta:{"musitu/operation":op,"musitu/business_product":true}})}
const dyn=[];for(const op of rg.tools){const name=safeName(op,used);map.set(name,op);dyn.push({name,title:`MUSITU Axiom: ${op}`,description:`Execute certified MUSITU Axiom operation ${op}. This may consume subscription units.`,inputSchema:argsSchema(),annotations:ann(op),securitySchemes:schemes("axiom.execute"),_meta:{"musitu/operation":op}})}return{tools:[...stat,...business,...dyn],map,rg,business}}
async function execOp(req,c,op,args,rg){const a=bearer(req);if(!a)return authRequired(c,"axiom.execute","Connect your MUSITU account to run paid Axiom capabilities.");if(!rg.tools.includes(op))return tr(`Unavailable Axiom operation: ${op}`,{operation:op},undefined,true);const rid=req.headers.get("x-musitu-request-id")||`MUSITU-MCP-${crypto.randomUUID().replaceAll("-","").toUpperCase()}`;const r=await jf(c.axiomService,`${c.axiomBase}/v1/compute`,{method:"POST",headers:{authorization:a,"content-type":"application/json",accept:"application/json","x-musitu-request-id":rid,"user-agent":"MUSITU-Axiom-MCP/2.0"},body:JSON.stringify({operation:op,args:args||{}})});if(r.status===401||r.status===403)return authRequired(c,"axiom.execute","Your MUSITU authorization is missing, expired or insufficient.");if(r.status<200||r.status>=300)return tr(`Axiom operation failed HTTP ${r.status}.`,{operation:op,http_status:r.status,error:r.obj?.error||r.obj?.message||"upstream_error"},undefined,true);return tr(`MUSITU Axiom completed ${op}.`,{operation:op,request_id:rid,result:r.obj})}
async function call(req,c,name,a){const ts=await toolSet(c);if(name==="search"){const q=String(a?.query||"").toLowerCase();const cat=await catalog(c);const caps=[...ts.business.map(x=>({id:`cap:${x.name}`,title:x.title,type:"business_capability"})),...ts.rg.tools.filter(x=>x.toLowerCase().includes(q)).slice(0,25).map(x=>({id:`op:${x}`,title:x,type:"runtime_operation"})),...(cat.plans||[]).filter(x=>JSON.stringify(x).toLowerCase().includes(q)).map(x=>({id:`plan:${x.id}`,title:`MUSITU Axiom ${x.id}`,type:"plan"}))];const filtered=q?caps.filter(x=>JSON.stringify(x).toLowerCase().includes(q)):caps;return tr(`Found ${filtered.length} MUSITU Axiom results.`,{results:filtered.slice(0,50)})}
if(name==="fetch"){const id=String(a?.id||"");if(id.startsWith("plan:")){const cat=await catalog(c);const p=(cat.plans||[]).find(x=>x.id===id.slice(5));return p?tr(`MUSITU Axiom ${p.id} plan.`,{resource:p}):tr("Resource not found.",{id},undefined,true)}if(id.startsWith("op:")){const op=id.slice(3);return ts.rg.tools.includes(op)?tr(`MUSITU Axiom operation ${op}.`,{resource:{operation:op,paid:true}}):tr("Resource not found.",{id},undefined,true)}if(id.startsWith("cap:")){const n=id.slice(4),t=ts.business.find(x=>x.name===n);return t?tr(t.description,{resource:t}):tr("Resource not found.",{id},undefined,true)}return tr("Resource not found.",{id},undefined,true)}
if(name==="musitu_axiom_capabilities")return tr(`MUSITU Axiom exposes ${ts.rg.operationCount} certified runtime operations and ${ts.business.length} business-facing quantitative products.`,{operation_count:ts.rg.operationCount,business_products:ts.business.map(x=>({name:x.name,operation:x._meta["musitu/operation"]})),billing_tools:true});
if(name==="musitu_axiom_plans"){const x=await catalog(c);return tr("Current MUSITU Axiom plans.",{catalog:x})}
if(name==="musitu_axiom_recommend_plan"){const u=Number(a?.estimated_monthly_units||0);if(!Number.isInteger(u)||u<1)return tr("estimated_monthly_units must be positive.",{},undefined,true);const x=await catalog(c),p=(x.plans||[]).slice().sort((m,n)=>m.monthly_unit_limit-n.monthly_unit_limit),r=p.find(z=>z.monthly_unit_limit>=u)||p[p.length-1]||null;return tr(r?`Recommended plan: ${r.id}.`:"No plan available.",{estimated_monthly_units:u,recommended:r,catalog:x})}
if(name==="musitu_axiom_start_checkout"){const auth=bearer(req);if(!auth)return authRequired(c,"billing.write","Connect your MUSITU account before checkout.");if(a?.confirm_create_checkout!==true)return tr("Explicit checkout confirmation is required.",{checkout_created:false},undefined,true);const plan=String(a?.plan||"");if(!["developer","pro","enterprise"].includes(plan))return tr("Invalid plan.",{},undefined,true);const r=await jf(c.billingService,`${c.billingBase}/billing/checkout`,{method:"POST",headers:{authorization:auth,"content-type":"application/json",accept:"application/json"},body:JSON.stringify({plan})});if(r.status===401||r.status===403)return authRequired(c,"billing.write","Your authorization cannot create this checkout.");if(r.status!==201)return tr(`Checkout failed HTTP ${r.status}.`,{checkout_created:false,http_status:r.status,error:r.obj?.error||"checkout_error"},undefined,true);return tr("Checkout created. The user must personally open Paynow and authorize payment.",{checkout_created:true,plan,checkout:r.obj})}
if(name==="musitu_axiom_checkout_status"){const auth=bearer(req);if(!auth)return authRequired(c,"billing.read","Connect your MUSITU account to check checkout status.");const ref=String(a?.reference||"");const r=await jf(c.billingService,`${c.billingBase}/billing/checkout/${encodeURIComponent(ref)}`,{headers:{authorization:auth,accept:"application/json"}});if(r.status===401||r.status===403)return authRequired(c,"billing.read","Your authorization cannot read this checkout.");if(r.status!==200)return tr(`Status lookup failed HTTP ${r.status}.`,{http_status:r.status,error:r.obj?.error||"status_error"},undefined,true);return tr("Checkout status retrieved.",{checkout:r.obj})}
let op=ts.map.get(name);let args=a?.args;if(name==="musitu_axiom_execute"){op=String(a?.operation||"");args=a?.args}if(!op)return tr(`Unknown MCP tool: ${name}`,{},undefined,true);return execOp(req,c,op,args,ts.rg)}
async function mcp(req,c){if(req.method!=="POST")return out(405,{error:"method_not_allowed"},{allow:"POST"});let m;try{m=await req.json()}catch{return ok(null,{error:{code:-32700,message:"Parse error"}})}const id=m?.id??null;if(m?.jsonrpc!=="2.0"||typeof m?.method!=="string")return ok(id,{error:{code:-32600,message:"Invalid Request"}});if(m.method==="initialize")return ok(id,{protocolVersion:String(m.params?.protocolVersion||"2025-06-18"),capabilities:{tools:{listChanged:false}},serverInfo:{name:"musitu-axiom",version:VERSION},instructions:"MUSITU Axiom exposes its complete certified quantitative runtime plus business-facing financial products and paid subscription tools. Prefer focused tools. Never create checkout without explicit user intent. Do not claim company-research capabilities unless the needed company data is supplied or a research connector is available."});if(m.method==="notifications/initialized"||m.method==="notifications/cancelled")return new Response(null,{status:202});if(m.method==="ping")return ok(id,{});if(m.method==="tools/list"){try{return ok(id,{tools:(await toolSet(c)).tools})}catch(e){return ok(id,{error:{code:-32603,message:"Axiom registry unavailable",data:{detail:String(e)}}})}}if(m.method==="tools/call"){const name=String(m.params?.name||""),a=m.params?.arguments&&typeof m.params.arguments==="object"?m.params.arguments:{};if(!name)return ok(id,{error:{code:-32602,message:"Tool name required"}});try{return ok(id,await call(req,c,name,a))}catch(e){return ok(id,tr("MUSITU Axiom tool failed safely.",{error:String(e)},undefined,true))}}return ok(id,{error:{code:-32601,message:"Method not found"}})}
export default{async fetch(req,env){const c=cfg(env),u=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"authorization,content-type,mcp-session-id,x-musitu-request-id"}});if(u.pathname==="/health"&&req.method==="GET"){const x=await health(c);return out(x.ok?200:503,x)}if(u.pathname==="/.well-known/oauth-protected-resource"&&req.method==="GET")return out(c.authIssuer?200:503,{resource:c.publicBase,authorization_servers:c.authIssuer?[c.authIssuer]:[],scopes_supported:["openid","email","profile","axiom.execute","billing.read","billing.write"],resource_documentation:`${c.publicBase}/docs`});if(u.pathname==="/docs"&&req.method==="GET")return out(200,{service:"MUSITU Axiom MCP Gateway",endpoint:`${c.publicBase}/mcp`,authentication:c.authIssuer?"OAuth 2.1":"OAuth provider pending; controlled bearer E2E only",operation_policy:"All certified Axiom runtime operations are wired dynamically; business product names map only to real certified primitives.",payment_policy:"Checkout creation never charges automatically; the user authorizes payment at Paynow."});if(u.pathname==="/mcp")return mcp(req,c);return out(404,{error:"not_found"})}};
