import { ComputerStore } from './computer_store.js';
import { FIXTURES, clean, uid } from './computer_security.js';

import { markup } from './computer_ui_markup.js';
export async function initComputerWorkspace({projects,observability}={}){
  if(!projects?.store||!observability?.store)throw new TypeError('qualified Project and Observability substrates required');
  const main=document.querySelector('#main-workspace');if(!main)return null;
  const style=document.createElement('link');style.rel='stylesheet';style.href='./styles/computer.css';document.head.append(style);main.insertAdjacentHTML('beforeend',markup());
  const store=await ComputerStore.open(),space=document.querySelector('#computer-space'),hero=document.querySelector('.hero-card'),runStage=document.querySelector('.run-stage'),actor='local-user';let current='',currentAction='';
  const frame=()=>document.querySelector('#computer-frame');
  async function refreshProjects(){const rows=await projects.store.listProjects(),sel=document.querySelector('#computer-project'),preferred=sel.value||projects.getCurrentProjectId?.()||'';sel.replaceChildren(new Option('Choose project',''));for(const p of rows)sel.add(new Option(`${p.name} · ${p.project_id}`,p.project_id));if(preferred&&rows.some(p=>p.project_id===preferred))sel.value=preferred;}
  function applyFrame(row){const fixture=FIXTURES[row?.fixture]||FIXTURES.safe,f=frame();if(f.dataset.fixture!==row?.fixture){f.srcdoc=fixture.html;f.dataset.fixture=row?.fixture||'safe';}f.onload=()=>syncFrameState(row).catch(()=>{});syncFrameState(row).catch(()=>{});}
  async function syncFrameState(row){const doc=frame().contentDocument;if(!doc||!row)return;for(const [sel,v] of Object.entries(row.sandbox_state.fields||{})){const el=doc.querySelector(sel);if(el&&'value'in el)el.value=String(v);}for(const [sel,count] of Object.entries(row.sandbox_state.clicks||{})){const el=doc.querySelector(sel);if(el)el.dataset.axiomClicks=String(count);}frame().contentWindow?.scrollTo?.(0,Number(row.sandbox_state.scroll_y||0));}
  async function observe(kind,linkage={},operational={}){if(!current)return;const trace=await observability.store.getRun(current);if(!trace)return;await observability.store.recordEvent(current,{kind,actorId:actor,linkage,operational});}
  async function ensureTrace(row){if(await observability.store.getRun(row.session_id))return;await observability.store.startRun({runId:row.session_id,traceId:uid('trace'),actorId:actor,userIntentId:`computer:${row.session_id}`,projectId:row.project_id,production:false,startedAt:row.started_at});await observe('policy.decided',{policy_decision_id:`policy:${row.session_id}`},{status:'SANDBOX_BOUND',policy_intervention:false});}
  function renderPreview(action){const preview=document.querySelector('#computer-preview');preview.replaceChildren();if(!action){preview.textContent='No action preview.';return;}const strong=document.createElement('strong'),target=document.createElement('span'),code=document.createElement('code'),status=document.createElement('span');strong.textContent=action.action_type.toUpperCase();target.textContent=`target ${clean(action.target||'(local state)',180)}`;code.textContent=`sha256:${action.action_sha256}`;status.textContent=`${action.status} · approval required`;preview.append(strong,target,code,status);}
  async function render(){const row=current?await store.get(current):null;document.querySelector('#computer-state').textContent=row?`${row.status}${row.takeover?' · USER TAKEOVER':''}`:'No session';document.querySelector('#computer-site').textContent=row?.current_url||'None';document.querySelector('#computer-step').textContent=row?.current_step||'READY';const policy=document.querySelector('#computer-policy'),ack=document.querySelector('#computer-ack');if(row?.prompt_injection_quarantined){policy.dataset.state='blocked';policy.textContent=`Blocked by prompt-injection quarantine: ${row.prompt_injection_flags.join(', ')}. Retrieved instructions remain DATA_ONLY.`;ack.hidden=false;}else{policy.dataset.state='clear';policy.textContent=row?.prompt_injection_flags?.length?`Quarantine acknowledged. Flags remain recorded: ${row.prompt_injection_flags.join(', ')}. Authority remains DATA_ONLY.`:'Retrieved page instructions are DATA_ONLY; no embedded content can authorize execution.';ack.hidden=true;}const active=Boolean(row&&row.status==='ACTIVE'&&!row.takeover);document.querySelector('#computer-pause').disabled=!active;document.querySelector('#computer-resume').disabled=!(row?.status==='PAUSED'&&!row.takeover);document.querySelector('#computer-takeover').disabled=!row||row.status==='STOPPED'||row.takeover;document.querySelector('#computer-release').disabled=!row?.takeover;document.querySelector('#computer-stop').disabled=!row||row.status==='STOPPED';document.querySelector('#computer-action-form').querySelector('button').disabled=!active||row?.prompt_injection_quarantined;const action=row?.actions.find(x=>x.action_id===currentAction)||row?.actions.at(-1)||null;if(action&&!currentAction)currentAction=action.action_id;renderPreview(action);document.querySelector('#computer-approve').disabled=!(action?.status==='PROPOSED');document.querySelector('#computer-execute').disabled=!(action?.status==='APPROVED'&&active);document.querySelector('#computer-rollback').disabled=!(action?.status==='COMPLETED');const receipts=document.querySelector('#computer-receipts');receipts.replaceChildren();for(const r of row?.receipts||[]){const li=document.createElement('li');li.textContent=`${r.receipt_id} · sha256:${r.receipt_sha256.slice(0,16)}…`;receipts.append(li);}document.querySelector('#computer-trace').textContent=row?JSON.stringify({session_id:row.session_id,status:row.status,takeover:row.takeover,current_url:row.current_url,current_step:row.current_step,prompt_injection_flags:row.prompt_injection_flags,events:row.events},null,2):'No trace';if(row)applyFrame(row);}
  function report(error,id='AXIOM-COMPUTER'){window.AxiomUI?.reportError?.({errorId:id,component:'Computer',impact:'Computer action not completed',failed:error.message,recovery:'Inspect the visible policy, approval and sandbox state, then retry'});}
  async function route(){const on=/^#\/computer(?:\/|$)/.test(location.hash);space.hidden=!on;if(hero)hero.hidden=on;if(runStage)runStage.hidden=on;if(on){document.querySelector('#workspace-title').textContent='Computer';document.querySelector('#workspace-description').textContent='Visible sandboxed browser execution with explicit approvals, takeover, receipts and rollback where supported.';await refreshProjects();await render();}}
  document.querySelector('#computer-start').addEventListener('click',async()=>{try{const projectId=document.querySelector('#computer-project').value;if(!projectId)throw new TypeError('choose a project');const row=await store.start(projects,{projectId,actorId:actor,fixture:document.querySelector('#computer-fixture').value});current=row.session_id;currentAction='';await ensureTrace(row);window.AxiomUI?.emit?.('computer.session.started',{state:'active'});await render();}catch(e){report(e,'AXIOM-COMPUTER-START');}});
  document.querySelector('#computer-action-form').addEventListener('submit',async e=>{e.preventDefault();try{const action=await store.propose(current,{actionType:document.querySelector('#computer-action-type').value,target:document.querySelector('#computer-action-target').value,value:document.querySelector('#computer-action-value').value,credentialHandle:document.querySelector('#computer-credential').value||null});currentAction=action.action_id;await observe('policy.decided',{policy_decision_id:`policy:${action.action_id}`},{status:'ACTION_PREVIEWED',policy_intervention:false});await render();}catch(err){report(err,'AXIOM-COMPUTER-PREVIEW');}});
  document.querySelector('#computer-approve').addEventListener('click',async()=>{try{const row=await store.get(current),a=row.actions.find(x=>x.action_id===currentAction);const receipt=await store.approve(current,currentAction,a.action_sha256,actor);await observe('approval.updated',{policy_decision_id:`policy:${currentAction}`},{approval_state:'approved',status:'ACTION_APPROVED'});window.AxiomUI?.emit?.('computer.approval',{state:receipt.receipt_id});await render();}catch(e){report(e,'AXIOM-COMPUTER-APPROVAL');}});
  document.querySelector('#computer-execute').addEventListener('click',async()=>{try{const before=performance.now(),receipt=await store.execute(current,currentAction),row=await store.get(current);await observe('tool.called',{tool_call_id:currentAction,policy_decision_id:`policy:${currentAction}`},{status:'ACTION_COMPLETED',tool_duration_ms:Math.max(0,performance.now()-before),approval_state:'approved'});await render();await syncFrameState(row);window.AxiomUI?.emit?.('computer.action.completed',{state:receipt.receipt_id});}catch(e){report(e,'AXIOM-COMPUTER-EXECUTE');}});
  document.querySelector('#computer-rollback').addEventListener('click',async()=>{try{await store.rollback(current,currentAction,actor);await observe('run.progress',{}, {status:'ACTION_ROLLED_BACK'});await render();}catch(e){report(e,'AXIOM-COMPUTER-ROLLBACK');}});
  document.querySelector('#computer-ack').addEventListener('click',async()=>{try{await store.acknowledgeQuarantine(current,actor);await observe('policy.decided',{policy_decision_id:`quarantine:${current}`},{status:'QUARANTINE_ACKNOWLEDGED',policy_intervention:true});await render();}catch(e){report(e,'AXIOM-COMPUTER-QUARANTINE');}});
  for(const [id,fn,status] of [['computer-pause','pause','PAUSED'],['computer-resume','resume','ACTIVE'],['computer-takeover','takeover','USER_TAKEOVER'],['computer-release','releaseTakeover','ACTIVE']])document.querySelector(`#${id}`).addEventListener('click',async()=>{try{await store[fn](current,actor);await observe('run.progress',{}, {status});await render();}catch(e){report(e);}});
  document.querySelector('#computer-stop').addEventListener('click',async()=>{try{await store.stop(current,actor);const trace=await observability.store.getRun(current);if(trace&&!trace.final_status)await observability.store.finishRun(current,{status:'CANCELLED',actorId:actor,operational:{status:'CANCELLED',recovery_state:'user-stopped'}});await render();}catch(e){report(e,'AXIOM-COMPUTER-STOP');}});
  window.addEventListener('hashchange',()=>route().catch(()=>{}));await refreshProjects();await route();const api={store,fixtures:FIXTURES,getCurrentSessionId:()=>current,refresh:render,selectSession:async id=>{current=id;currentAction='';await render();}};window.AxiomComputer=Object.freeze(api);return api;
}
