import { initComputerWorkspace } from './computer.js';

const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitForQualifiedDependencies(){for(let i=0;i<240;i++){if(window.AxiomProjects?.store&&window.AxiomObservability?.store)return {projects:window.AxiomProjects,observability:window.AxiomObservability};await sleep(25);}throw new Error('qualified Project/Observability APIs were not ready');}
function installNavigation(){const nav=document.querySelector('.global-rail nav');if(!nav||nav.querySelector('[data-route="computer"]'))return;const link=document.createElement('a');link.className='nav-item';link.href='#/computer';link.dataset.route='computer';link.innerHTML='<span aria-hidden="true">▰</span><span>Computer</span>';const agents=nav.querySelector('[data-route="agents"]');nav.insertBefore(link,agents||null);link.addEventListener('click',()=>window.AxiomUI?.emit?.('nav.activate',{control:'computer'}));}
async function reconcileVisibleState(api,deps){for(let i=0;i<240;i++){const sid=api.getCurrentSessionId?.();if(sid){const [row,trace]=await Promise.all([api.store.get(sid),deps.observability.store.getRun(sid)]);if(row&&trace){const events=await deps.observability.store.events(sid);const policyReady=events.some(e=>e.kind==='policy.decided'&&e.linkage?.policy_decision_id===`policy:${sid}`);if(policyReady){await api.refresh();return true;}}}await sleep(25);}return false;}
function installStateReconciliation(api,deps){const start=document.querySelector('#computer-start');start?.addEventListener('click',()=>{reconcileVisibleState(api,deps).catch(()=>{});});window.addEventListener('pageshow',()=>{if(/^#\/computer(?:\/|$)/.test(location.hash))reconcileVisibleState(api,deps).catch(()=>{});});}
async function boot(){installNavigation();const deps=await waitForQualifiedDependencies();const api=await initComputerWorkspace(deps);installStateReconciliation(api,deps);window.AxiomUI?.emit?.('workspace.phase8.ready',{state:'computer-visible-local-sandbox'});return api;}
window.AxiomComputerBootstrap=boot().catch(error=>{window.AxiomUI?.reportError?.({errorId:'AXIOM-COMPUTER-INIT',component:'Computer',impact:'Computer sandbox unavailable',failed:error.message,recovery:'Reload the workspace and retry'});throw error;});
