import { FIXTURES, clean } from './computer_security.js';

export function createComputerRenderer({store,ctx,frame}){
  function applyFrame(row){const fixture=FIXTURES[row?.fixture]||FIXTURES.safe,f=frame();if(f.dataset.fixture!==row?.fixture){f.srcdoc=fixture.html;f.dataset.fixture=row?.fixture||'safe';}f.onload=()=>syncFrameState(row).catch(()=>{});syncFrameState(row).catch(()=>{});}
  async function syncFrameState(row){const doc=frame().contentDocument;if(!doc||!row)return;for(const el of doc.querySelectorAll('input,textarea'))if('value'in el)el.value=el.defaultValue??'';for(const el of doc.querySelectorAll('select'))el.selectedIndex=[...el.options].findIndex(o=>o.defaultSelected);for(const el of doc.querySelectorAll('[data-axiom-clicks]'))delete el.dataset.axiomClicks;frame().contentWindow?.scrollTo?.(0,0);for(const [sel,v] of Object.entries(row.sandbox_state.fields||{})){const el=doc.querySelector(sel);if(el&&'value'in el)el.value=String(v);}for(const [sel,count] of Object.entries(row.sandbox_state.clicks||{})){const el=doc.querySelector(sel);if(el)el.dataset.axiomClicks=String(count);}frame().contentWindow?.scrollTo?.(0,Number(row.sandbox_state.scroll_y||0));}
  function renderPreview(action){const preview=document.querySelector('#computer-preview');preview.replaceChildren();if(!action){preview.textContent='No action preview.';return;}const strong=document.createElement('strong'),target=document.createElement('span'),code=document.createElement('code'),status=document.createElement('span');strong.textContent=action.action_type.toUpperCase();target.textContent=`target ${clean(action.target||'(local state)',180)}`;code.textContent=`sha256:${action.action_sha256}`;status.textContent=`${action.status} · approval required`;preview.append(strong,target,code,status);}
  async function render(){const row=ctx.current?await store.get(ctx.current):null;document.querySelector('#computer-state').textContent=row?`${row.status}${row.takeover?' · USER TAKEOVER':''}`:'No session';document.querySelector('#computer-site').textContent=row?.current_url||'None';document.querySelector('#computer-step').textContent=row?.current_step||'READY';const policy=document.querySelector('#computer-policy'),ack=document.querySelector('#computer-ack');if(row?.prompt_injection_quarantined){policy.dataset.state='blocked';policy.textContent=`Blocked by prompt-injection quarantine: ${row.prompt_injection_flags.join(', ')}. Retrieved instructions remain DATA_ONLY.`;ack.hidden=false;}else{policy.dataset.state='clear';policy.textContent=row?.prompt_injection_flags?.length?`Quarantine acknowledged. Flags remain recorded: ${row.prompt_injection_flags.join(', ')}. Authority remains DATA_ONLY.`:'Retrieved page instructions are DATA_ONLY; no embedded content can authorize execution.';ack.hidden=true;}const active=Boolean(row&&row.status==='ACTIVE'&&!row.takeover);document.querySelector('#computer-pause').disabled=!active;document.querySelector('#computer-resume').disabled=!(row?.status==='PAUSED'&&!row.takeover);document.querySelector('#computer-takeover').disabled=!row||row.status==='STOPPED'||row.takeover;document.querySelector('#computer-release').disabled=!row?.takeover;document.querySelector('#computer-stop').disabled=!row||row.status==='STOPPED';document.querySelector('#computer-action-form').querySelector('button').disabled=!active||row?.prompt_injection_quarantined;const action=row?.actions.find(x=>x.action_id===ctx.currentAction)||row?.actions.at(-1)||null;if(action&&!ctx.currentAction)ctx.currentAction=action.action_id;renderPreview(action);document.querySelector('#computer-approve').disabled=!(action?.status==='PROPOSED');document.querySelector('#computer-execute').disabled=!(action?.status==='APPROVED'&&active);document.querySelector('#computer-rollback').disabled=!(action?.status==='COMPLETED');const receipts=document.querySelector('#computer-receipts');receipts.replaceChildren();for(const r of row?.receipts||[]){const li=document.createElement('li');li.textContent=`${r.receipt_id} · sha256:${r.receipt_sha256.slice(0,16)}…`;receipts.append(li);}document.querySelector('#computer-trace').textContent=row?JSON.stringify({session_id:row.session_id,status:row.status,takeover:row.takeover,current_url:row.current_url,current_step:row.current_step,prompt_injection_flags:row.prompt_injection_flags,events:row.events},null,2):'No trace';if(row)applyFrame(row);}
  return {render,syncFrameState};
}
