import { initComputerWorkspace } from './computer.js';

const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitForQualifiedDependencies(){for(let i=0;i<240;i++){if(window.AxiomProjects?.store&&window.AxiomObservability?.store)return {projects:window.AxiomProjects,observability:window.AxiomObservability};await sleep(25);}throw new Error('qualified Project/Observability APIs were not ready');}
function installNavigation(){const nav=document.querySelector('.global-rail nav');if(!nav||nav.querySelector('[data-route="computer"]'))return;const link=document.createElement('a');link.className='nav-item';link.href='#/computer';link.dataset.route='computer';link.innerHTML='<span aria-hidden="true">▰</span><span>Computer</span>';const agents=nav.querySelector('[data-route="agents"]');nav.insertBefore(link,agents||null);link.addEventListener('click',()=>window.AxiomUI?.emit?.('nav.activate',{control:'computer'}));}
async function policyTraceReady(sid,deps){const trace=await deps.observability.store.getRun(sid);if(!trace)return false;const events=await deps.observability.store.events(sid);return events.some(e=>e.kind==='policy.decided'&&e.linkage?.policy_decision_id===`policy:${sid}`);}
async function ensurePolicyTrace(row,deps){const sid=row.session_id;let trace=await deps.observability.store.getRun(sid);if(!trace){try{await deps.observability.store.startRun({runId:sid,traceId:`trace_${crypto.randomUUID?.()||Date.now()}`,actorId:row.actor_id,userIntentId:`computer:${sid}`,projectId:row.project_id,production:false,startedAt:row.started_at});}catch(error){trace=await deps.observability.store.getRun(sid);if(!trace)throw error;}}if(await policyTraceReady(sid,deps))return true;try{await deps.observability.store.recordEvent(sid,{kind:'policy.decided',actorId:row.actor_id,linkage:{policy_decision_id:`policy:${sid}`},operational:{status:'SANDBOX_BOUND',policy_intervention:false}});}catch(error){if(!await policyTraceReady(sid,deps))throw error;}return policyTraceReady(sid,deps);}
async function reconcileVisibleState(api,deps){for(let i=0;i<40;i++){const sid=api.getCurrentSessionId?.();if(sid&&await policyTraceReady(sid,deps)){await api.refresh();return true;}await sleep(25);}const sid=api.getCurrentSessionId?.();if(!sid)return false;const row=await api.store.get(sid);if(!row||row.status==='STOPPED')return false;if(await ensurePolicyTrace(row,deps)){await api.refresh();return true;}return false;}
function installStateReconciliation(api,deps){const start=document.querySelector('#computer-start');start?.addEventListener('click',()=>{reconcileVisibleState(api,deps).catch(()=>{});});window.addEventListener('pageshow',()=>{if(/^#\/computer(?:\/|$)/.test(location.hash))reconcileVisibleState(api,deps).catch(()=>{});});}
async function boot(){installNavigation();const deps=await waitForQualifiedDependencies();const api=await initComputerWorkspace(deps);installStateReconciliation(api,deps);window.AxiomUI?.emit?.('workspace.phase8.ready',{state:'computer-visible-local-sandbox'});return api;}
window.AxiomComputerBootstrap=boot().catch(error=>{window.AxiomUI?.reportError?.({errorId:'AXIOM-COMPUTER-INIT',component:'Computer',impact:'Computer sandbox unavailable',failed:error.message,recovery:'Reload the workspace and retry'});throw error;});
