import {DB,VERSION,ALLOWED_DOMAINS,ACCOUNTS_DOMAIN,NETWORK_POLICY,SANDBOX_MODE,CLIPBOARD_POLICY,CREDENTIAL_POLICY,FIXTURES,clone,req,done,uid,sha,requireAllowedUrl,scan} from './computer_security.js';
import { installComputerStoreActions } from './computer_store_actions.js';

export class ComputerStore{
  constructor(db){this.db=db;}
  static async open(){const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('sessions')){const s=db.createObjectStore('sessions',{keyPath:'session_id'});s.createIndex('project_id','project_id',{unique:false});}};return new ComputerStore(await req(r));}
  async get(id){const tx=this.db.transaction('sessions','readonly'),row=await req(tx.objectStore('sessions').get(id));await done(tx);return row?clone(row):null;}
  async list(projectId=null){const tx=this.db.transaction('sessions','readonly'),s=tx.objectStore('sessions'),rows=projectId?await req(s.index('project_id').getAll(projectId)):await req(s.getAll());await done(tx);return rows.sort((a,b)=>b.started_at.localeCompare(a.started_at)).map(clone);}
  async put(row){const tx=this.db.transaction('sessions','readwrite');tx.objectStore('sessions').put(clone(row));await done(tx);return clone(row);}
  async _event(row,kind,payload={}){const previous=row.events.at(-1)?.event_sha256||null,at=new Date().toISOString(),body={schema:'musitu.axiom.computer-event.browser.v1',event_id:`${row.session_id}:evt:${row.events.length}`,sequence:row.events.length,session_id:row.session_id,project_id:row.project_id,actor_id:row.actor_id,kind,at,payload:clone(payload),previous_event_sha256:previous},event={...body,event_sha256:await sha(body)};row.events.push(event);row.updated_at=at;return event;}
  async start(projects,{projectId,actorId='local-user',fixture='safe'}={}){const project=await projects.store.getProject(projectId);if(!project)throw new DOMException('project not found','NotFoundError');const role=project.permissions?.find(x=>x.principal_id===actorId)?.role;if(!['owner','editor'].includes(role))throw new DOMException('project write permission required','NotAllowedError');if(!FIXTURES[fixture])throw new TypeError('unknown local fixture');const at=new Date().toISOString(),session_id=uid('computer'),object=await projects.store.addObject(projectId,actorId,{type:'task',title:`Computer session · ${fixture}`,provenanceSource:'axiom-computer:browser-local',evidenceLinks:[`computer-session:${session_id}`]});const row={schema:'musitu.axiom.computer-session.browser.v1',session_id,project_id:projectId,project_object_id:object.object_id,actor_id:actorId,status:'ACTIVE',takeover:false,started_at:at,ended_at:null,updated_at:at,fixture,current_url:null,current_title:null,current_step:'READY',allowed_domains:[...ALLOWED_DOMAINS],network_policy:NETWORK_POLICY,sandbox_mode:SANDBOX_MODE,hidden_privileged_browser_session:false,clipboard_policy:CLIPBOARD_POLICY,credential_policy:CREDENTIAL_POLICY,credential_scopes:{'demo-login':[ACCOUNTS_DOMAIN]},prompt_injection_quarantined:false,prompt_injection_flags:[],page_text_sha256:null,restricted_clipboard:null,actions:[],receipts:[],events:[],snapshots:{},sandbox_state:{fields:{},clicks:{},scroll_y:0}};await this._event(row,'session.started',{sandbox_mode:SANDBOX_MODE,network_policy:NETWORK_POLICY});await this.loadFixtureRow(row,fixture);return this.put(row);}
  async loadFixtureRow(row,fixture){if(!FIXTURES[fixture])throw new TypeError('unknown local fixture');const f=FIXTURES[fixture],host=requireAllowedUrl(f.url),flags=scan(f.text);row.fixture=fixture;row.current_url=f.url;row.current_title=f.title;row.current_step='PAGE_OBSERVED';row.page_text_sha256=await sha(f.text);row.prompt_injection_flags=flags;row.prompt_injection_quarantined=Boolean(flags);await this._event(row,'page.observed',{host,page_text_sha256:row.page_text_sha256,prompt_injection_flags:flags,retrieved_instruction_authority:'DATA_ONLY',network_request_performed:false});if(flags.length)await this._event(row,'policy.blocked',{reason:'PROMPT_INJECTION_QUARANTINE',flags});return row;}
  async loadFixture(id,fixture){const row=await this.get(id);this._live(row);await this.loadFixtureRow(row,fixture);return this.put(row);}
  _live(row){if(!row||row.status==='STOPPED')throw new DOMException('live computer session required','InvalidStateError');}
  _agent(row){this._live(row);if(row.status!=='ACTIVE'||row.takeover)throw new DOMException('agent execution unavailable','InvalidStateError');}
  async acknowledgeQuarantine(id,actor='local-user'){const row=await this.get(id);this._live(row);if(actor!==row.actor_id)throw new DOMException('actor mismatch','SecurityError');if(row.prompt_injection_quarantined){row.prompt_injection_quarantined=false;await this._event(row,'quarantine.acknowledged',{flags:row.prompt_injection_flags,authority_remains:'DATA_ONLY'});await this.put(row);}return clone(row);}
}

installComputerStoreActions(ComputerStore);
