export function installComputerUIEvents(ctx){
  const {store,projects,observability,actor,observe,ensureTrace,render,syncFrameState,report}=ctx;
  document.querySelector('#computer-start').addEventListener('click',async()=>{try{const projectId=document.querySelector('#computer-project').value;if(!projectId)throw new TypeError('choose a project');const row=await store.start(projects,{projectId,actorId:actor,fixture:document.querySelector('#computer-fixture').value});ctx.current=row.session_id;ctx.currentAction='';await ensureTrace(row);window.AxiomUI?.emit?.('computer.session.started',{state:'active'});await render();}catch(e){report(e,'AXIOM-COMPUTER-START');}});
  document.querySelector('#computer-action-form').addEventListener('submit',async e=>{e.preventDefault();try{const action=await store.propose(ctx.current,{actionType:document.querySelector('#computer-action-type').value,target:document.querySelector('#computer-action-target').value,value:document.querySelector('#computer-action-value').value,credentialHandle:document.querySelector('#computer-credential').value||null});ctx.currentAction=action.action_id;await observe('policy.decided',{policy_decision_id:`policy:${action.action_id}`},{status:'ACTION_PREVIEWED',policy_intervention:false});await render();}catch(err){report(err,'AXIOM-COMPUTER-PREVIEW');}});
  document.querySelector('#computer-approve').addEventListener('click',async()=>{try{const row=await store.get(ctx.current),a=row.actions.find(x=>x.action_id===ctx.currentAction);const receipt=await store.approve(ctx.current,ctx.currentAction,a.action_sha256,actor);await observe('approval.updated',{policy_decision_id:`policy:${ctx.currentAction}`},{approval_state:'approved',status:'ACTION_APPROVED'});window.AxiomUI?.emit?.('computer.approval',{state:receipt.receipt_id});await render();}catch(e){report(e,'AXIOM-COMPUTER-APPROVAL');}});
  document.querySelector('#computer-execute').addEventListener('click',async()=>{try{const before=performance.now(),receipt=await store.execute(ctx.current,ctx.currentAction),row=await store.get(ctx.current);await observe('tool.called',{tool_call_id:ctx.currentAction,policy_decision_id:`policy:${ctx.currentAction}`},{status:'ACTION_COMPLETED',tool_duration_ms:Math.max(0,performance.now()-before),approval_state:'approved'});await render();await syncFrameState(row);window.AxiomUI?.emit?.('computer.action.completed',{state:receipt.receipt_id});}catch(e){report(e,'AXIOM-COMPUTER-EXECUTE');}});
  document.querySelector('#computer-rollback').addEventListener('click',async()=>{try{await store.rollback(ctx.current,ctx.currentAction,actor);await observe('run.progress',{}, {status:'ACTION_ROLLED_BACK'});await render();}catch(e){report(e,'AXIOM-COMPUTER-ROLLBACK');}});
  document.querySelector('#computer-ack').addEventListener('click',async()=>{try{await store.acknowledgeQuarantine(ctx.current,actor);await observe('policy.decided',{policy_decision_id:`quarantine:${ctx.current}`},{status:'QUARANTINE_ACKNOWLEDGED',policy_intervention:true});await render();}catch(e){report(e,'AXIOM-COMPUTER-QUARANTINE');}});
  for(const [id,fn,status] of [['computer-pause','pause','PAUSED'],['computer-resume','resume','ACTIVE'],['computer-takeover','takeover','USER_TAKEOVER'],['computer-release','releaseTakeover','ACTIVE']])document.querySelector(`#${id}`).addEventListener('click',async()=>{try{await store[fn](ctx.current,actor);await observe('run.progress',{}, {status});await render();}catch(e){report(e);}});
  document.querySelector('#computer-stop').addEventListener('click',async()=>{try{await store.stop(ctx.current,actor);const trace=await observability.store.getRun(ctx.current);if(trace&&!trace.final_status)await observability.store.finishRun(ctx.current,{status:'CANCELLED',actorId:actor,operational:{status:'CANCELLED',recovery_state:'user-stopped'}});await render();}catch(e){report(e,'AXIOM-COMPUTER-STOP');}});
}
