import {NETWORK_POLICY,SANDBOX_MODE,SECRET_RX,clean,sha,requireAllowedUrl} from './computer_security.js';

export function installComputerControlActions(ComputerStore){
  ComputerStore.prototype.pause=async function pause(id,actor='local-user'){const row=await this.get(id);this._agent(row);if(actor!==row.actor_id)throw new DOMException('actor mismatch','SecurityError');row.status='PAUSED';row.current_step='PAUSED';await this._event(row,'session.paused');return this.put(row);};
  ComputerStore.prototype.resume=async function resume(id,actor='local-user'){const row=await this.get(id);this._live(row);if(row.status!=='PAUSED'||row.takeover)throw new DOMException('paused non-takeover session required','InvalidStateError');if(actor!==row.actor_id)throw new DOMException('actor mismatch','SecurityError');row.status='ACTIVE';row.current_step='RESUMED';await this._event(row,'session.resumed');return this.put(row);};
  ComputerStore.prototype.takeover=async function takeover(id,actor='local-user'){const row=await this.get(id);this._live(row);if(actor!==row.actor_id)throw new DOMException('actor mismatch','SecurityError');row.takeover=true;row.status='PAUSED';row.current_step='USER_TAKEOVER';await this._event(row,'takeover.started',{agent_execution_enabled:false});return this.put(row);};
  ComputerStore.prototype.releaseTakeover=async function releaseTakeover(id,actor='local-user'){const row=await this.get(id);this._live(row);if(!row.takeover||actor!==row.actor_id)throw new DOMException('takeover/actor mismatch','InvalidStateError');row.takeover=false;row.status='ACTIVE';row.current_step='TAKEOVER_RELEASED';await this._event(row,'takeover.ended',{agent_execution_enabled:true});return this.put(row);};
  ComputerStore.prototype.stop=async function stop(id,actor='local-user'){const row=await this.get(id);this._live(row);if(actor!==row.actor_id)throw new DOMException('actor mismatch','SecurityError');row.status='STOPPED';row.takeover=false;row.current_step='STOPPED';row.ended_at=new Date().toISOString();row.restricted_clipboard=null;await this._event(row,'session.stopped',{clipboard_cleared:true});return this.put(row);};
  ComputerStore.prototype.copyRestricted=async function copyRestricted(id,text){const row=await this.get(id);this._live(row);text=clean(text,4096);if(!text)throw new TypeError('clipboard text required');if(SECRET_RX.test(text))throw new DOMException('secret-like material forbidden','SecurityError');row.restricted_clipboard=text;await this._event(row,'clipboard.copied',{content_sha256:await sha(text),length:text.length});await this.put(row);return true;};
  ComputerStore.prototype.pasteRestricted=async function pasteRestricted(id){const row=await this.get(id);this._agent(row);if(row.restricted_clipboard==null)throw new DOMException('restricted clipboard empty','InvalidStateError');return row.restricted_clipboard;};
  ComputerStore.prototype.authorizeCredentialRow=function authorizeCredentialRow(row,handle,url){handle=clean(handle,180);const scopes=row.credential_scopes?.[handle];if(!scopes)throw new DOMException('credential handle not granted','SecurityError');const host=requireAllowedUrl(url);if(!scopes.includes(host))throw new DOMException('credential handle outside domain scope','SecurityError');return {handle,host,plaintext_secret_exposed:false};};
  ComputerStore.prototype.authorizeCredential=async function authorizeCredential(id,handle,url){const row=await this.get(id);this._live(row);return this.authorizeCredentialRow(row,handle,url);};
  ComputerStore.prototype.verify=async function verify(id){const row=await this.get(id);if(!row)return {status:'FAIL',errors:['session_missing']};const errors=[];let prev=null;for(let i=0;i<row.events.length;i++){const e=row.events[i],body=Object.fromEntries(Object.entries(e).filter(([k])=>k!=='event_sha256'));if(e.sequence!==i||e.previous_event_sha256!==prev)errors.push(`event_chain:${i}`);if(await sha(body)!==e.event_sha256)errors.push(`event_hash:${i}`);prev=e.event_sha256;}for(const a of row.actions){const body={schema:a.schema,action_id:a.action_id,session_id:a.session_id,action_type:a.action_type,target:a.target,host:a.host,preview_value:a.preview_value,credential_handle:a.credential_handle,approval_required:a.approval_required,status:'PROPOSED',reversible:a.reversible,created_at:a.created_at};if(await sha(body)!==a.action_sha256)errors.push(`action_hash:${a.action_id}`);}for(const r of row.receipts){const body=Object.fromEntries(Object.entries(r).filter(([k])=>k!=='receipt_sha256'));if(await sha(body)!==r.receipt_sha256)errors.push(`receipt_hash:${r.receipt_id}`);}if(row.hidden_privileged_browser_session!==false)errors.push('hidden_privileged_session');if(row.network_policy!==NETWORK_POLICY||row.sandbox_mode!==SANDBOX_MODE)errors.push('sandbox_boundary');const result={schema:'musitu.axiom.computer-integrity.browser.v1',status:errors.length?'FAIL':'PASS',session_id:id,errors:[...new Set(errors)].sort()};result.integrity_sha256=await sha(result);return result;};
}
