export const NETWORK_POLICY='DENY_ALL_EXTERNAL_NETWORK';
export const PLATFORM_MODE='BROWSER_LOCAL_CONFORMANCE_AND_INSTALL_PREVIEW_ONLY';
export const CREDENTIAL_POLICY='SYMBOLIC_HANDLE_ONLY_NO_PLAINTEXT_API_KEYS';
export const WEBHOOK_POLICY='DECLARATION_AND_LOCAL_SIGNED_FIXTURE_ONLY_NO_DELIVERY';
export const MCP_POLICY='MCP_2026_LOCAL_CONFORMANCE_ONLY_NO_REMOTE_BINDING';
export const A2A_POLICY='A2A_LOCAL_CAPABILITY_CARD_CONFORMANCE_ONLY';
export const PACKAGE_EXECUTION_POLICY='STATIC_MANIFEST_VALIDATION_NO_UNTRUSTED_CODE_EXECUTION';
export const MARKETPLACE_POLICY='EXACT_PACKAGE_DIGEST_AND_LEAST_PRIVILEGE_INSTALL_APPROVAL';
export const INTERFACES=Object.freeze(['sdk.python','sdk.javascript','mcp.2026','a2a.v1','webhook.v1']);
export const PACKAGE_KINDS=Object.freeze(['AGENT_PACKAGE','TEMPLATE']);
export const PACKAGE_PERMISSIONS=Object.freeze(['analysis.read','analysis.execute','audit.read']);
export const API_SCOPES=Object.freeze(['sdk.invoke','mcp.invoke','a2a.card.read','webhook.fixture']);
export const WEBHOOK_EVENTS=Object.freeze(['package.installed','agent.preview.completed','artifact.version.created']);
const SECRET_RX=/(?:api[_ -]?key|access[_ -]?token|refresh[_ -]?token|password|private[_ -]?key|authorization)\s*[:=]|\b(?:sk|ghp|github_pat)_[A-Za-z0-9_-]{12,}|\bbearer\s+[A-Za-z0-9._~-]{12,}/i;
export const clean=(value,limit=300)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,limit);
export function required(value,label,limit=180){const out=clean(value,limit);if(!out)throw new TypeError(`${label} required`);return out;}
export function rejectSecretLike(value,label='value'){const raw=JSON.stringify(value);if(SECRET_RX.test(raw))throw new DOMException(`${label} contains secret-like material`,'SecurityError');}
export function exactList(values,allowed,label,{requiredValue=true}={}){if(!Array.isArray(values)||(requiredValue&&!values.length))throw new TypeError(`${label} must be a${requiredValue?' non-empty':''} list`);const out=[...new Set(values.map(value=>required(value,label,80)))].sort();if(!out.every(value=>allowed.includes(value)))throw new DOMException(`${label} exceeds the allow-list`,'SecurityError');return out;}
export function normalizePackage(raw={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('package manifest required');const allowedKeys=['schema','packageId','name','version','publisherId','kind','description','interfaces','permissions'];if(Object.keys(raw).some(key=>!allowedKeys.includes(key)))throw new DOMException('package manifest contains executable or unsupported fields','SecurityError');rejectSecretLike(raw,'package manifest');const version=required(raw.version,'version',40);if(!/^\d+\.\d+\.\d+(?:-[a-z0-9.-]+)?$/i.test(version))throw new TypeError('semantic package version required');const kind=required(raw.kind,'package kind',32).toUpperCase();if(!PACKAGE_KINDS.includes(kind))throw new TypeError('unsupported package kind');return {schema:'musitu.axiom.developer-package.browser.v1',package_id:required(raw.packageId,'package id',120).toLowerCase().replace(/[^a-z0-9._-]/g,'-'),name:required(raw.name,'package name',160),version,publisher_id:required(raw.publisherId,'publisher id',120),kind,description:clean(raw.description,500),interfaces:exactList(raw.interfaces,INTERFACES,'interfaces'),requested_permissions:exactList(raw.permissions,PACKAGE_PERMISSIONS,'permissions'),network_permissions:[],external_code_included:false,remote_binding_claimed:false};}
export function normalizeWebhook(raw={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('webhook declaration required');if(Object.keys(raw).some(key=>!['label','endpoint','events'].includes(key)))throw new DOMException('webhook declaration contains unsupported fields','SecurityError');rejectSecretLike(raw,'webhook declaration');let url;try{url=new URL(required(raw.endpoint,'webhook endpoint',500));}catch{throw new TypeError('valid webhook endpoint required');}if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw new DOMException('webhook endpoint must be credential-free HTTPS without query or fragment','SecurityError');return {label:required(raw.label,'webhook label',160),endpoint:url.toString(),events:exactList(raw.events,WEBHOOK_EVENTS,'webhook events'),delivery_enabled:false};}
export const canonical=value=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`:JSON.stringify(value);
export async function sha256(value){const bytes=new TextEncoder().encode(canonical(value)),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}
export const uid=prefix=>`${prefix}:${crypto.randomUUID()}`;
