import {A2A_POLICY,API_SCOPES,CREDENTIAL_POLICY,INTERFACES,MARKETPLACE_POLICY,MCP_POLICY,NETWORK_POLICY,PACKAGE_EXECUTION_POLICY,PACKAGE_PERMISSIONS,PLATFORM_MODE,WEBHOOK_POLICY,clean,exactList,normalizePackage,normalizeWebhook,rejectSecretLike,required,sha256,uid} from './developer_security.js';
const DB='musitu-axiom-developer-v1',VERSION=1;
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const clone=value=>structuredClone(value);
const installKey=(orgId,packageId)=>`${orgId}:${packageId}`;
const hashBody=(row,field)=>Object.fromEntries(Object.entries(row).filter(([key])=>key!==field));
export class DeveloperPlatformStore{
 constructor(db,{operator}){this.db=db;this.operator=operator;this.serial=Promise.resolve();}
 static async open({operator}={}){if(!operator?.store)throw new TypeError('earned Operator control plane required');const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;for(const [name,key] of [['credentials','credential_handle'],['packages','package_id'],['installs','install_key'],['webhooks','webhook_id'],['events','event_id'],['receipts','receipt_id']])if(!db.objectStoreNames.contains(name)){const store=db.createObjectStore(name,{keyPath:key});if(['credentials','packages','installs','webhooks','events','receipts'].includes(name))store.createIndex('org_id','org_id',{unique:false});}};return new DeveloperPlatformStore(await req(request),{operator});}
 close(){this.db.close();}
 _queue(task){const next=this.serial.then(task,task);this.serial=next.catch(()=>{});return next;}
 async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
 async _all(store,orgId){const tx=this.db.transaction(store,'readonly'),source=orgId?tx.objectStore(store).index('org_id'):tx.objectStore(store),rows=await req(orgId?source.getAll(clean(orgId,180)):source.getAll());await done(tx);return rows.map(clone);}
 async _put(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(clone(row));await done(tx);return clone(row);}
 async listCredentialHandles(orgId){return (await this._all('credentials',orgId)).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
 async listPackages(orgId){return (await this._all('packages',orgId)).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
 async listInstalls(orgId){return (await this._all('installs',orgId)).sort((a,b)=>a.installed_at.localeCompare(b.installed_at));}
 async listWebhooks(orgId){return (await this._all('webhooks',orgId)).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
 async listReceipts(orgId){return (await this._all('receipts',orgId)).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
 async _authorize(orgId,actorId,permission='policy.manage'){orgId=required(orgId,'organization id',180);actorId=required(actorId,'actor id',180);await this.operator.store.authorize(orgId,actorId,permission);return {orgId,actorId};}
 async _event(orgId,kind,actorId,payload={}){const history=(await this._all('events',orgId)).sort((a,b)=>a.sequence-b.sequence),body={schema:'musitu.axiom.developer-event.browser.v1',event_id:`developer-event:${orgId}:${history.length}`,org_id:orgId,sequence:history.length,kind:required(kind,'event kind',80),actor_id:actorId,payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:history.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};await this._put('events',row);return row;}
 async _receipt(orgId,operation,actorId,payload={}){const body={schema:'musitu.axiom.developer-receipt.browser.v1',receipt_id:uid('developer-receipt'),org_id:orgId,operation,actor_id:actorId,payload:clone(payload),created_at:new Date().toISOString(),platform_mode:PLATFORM_MODE},row={...body,receipt_sha256:await sha256(body)};await this._put('receipts',row);return row;}
 async registerCredentialHandle(orgId,actorId,raw={}){return this._queue(async()=>{({orgId,actorId}=await this._authorize(orgId,actorId));if(Object.keys(raw).some(key=>!['label','scopes'].includes(key)))throw new DOMException('credential input accepts metadata only','SecurityError');rejectSecretLike(raw,'credential metadata');const scopes=exactList(raw.scopes,API_SCOPES,'API scopes'),created=new Date().toISOString(),body={schema:'musitu.axiom.symbolic-api-credential.browser.v1',credential_handle:uid('credential-handle'),org_id:orgId,label:required(raw.label,'credential label',160),scopes,status:'ACTIVE_LOCAL_HANDLE',created_at:created,credential_policy:CREDENTIAL_POLICY,plaintext_secret_present:false,production_credential_issued:false},row={...body,credential_fingerprint_sha256:await sha256(body)};await this._put('credentials',row);await this._event(orgId,'credential.handle_registered',actorId,{credential_handle:row.credential_handle,scopes,row_sha256:row.credential_fingerprint_sha256});await this._receipt(orgId,'SYMBOLIC_CREDENTIAL_HANDLE_REGISTERED',actorId,{credential_handle:row.credential_handle});return clone(row);});}
 async registerPackage(orgId,actorId,raw={}){return this._queue(async()=>{({orgId,actorId}=await this._authorize(orgId,actorId));const manifest=normalizePackage(raw);if(await this._get('packages',manifest.package_id))throw new DOMException('package id already registered','ConstraintError');const created=new Date().toISOString(),body={...manifest,org_id:orgId,created_at:created,platform_mode:PLATFORM_MODE,mcp_policy:MCP_POLICY,a2a_policy:A2A_POLICY,package_execution_policy:PACKAGE_EXECUTION_POLICY},row={...body,package_sha256:await sha256(body)};await this._put('packages',row);await this._event(orgId,'package.registered',actorId,{package_id:row.package_id,package_sha256:row.package_sha256});await this._receipt(orgId,'PACKAGE_REGISTERED_LOCAL_PREVIEW',actorId,{package_id:row.package_id,package_sha256:row.package_sha256});return clone(row);});}
 async prepareInstall(orgId,actorId,packageId,permissions=[]){({orgId,actorId}=await this._authorize(orgId,actorId));packageId=required(packageId,'package id',120);const pkg=await this._get('packages',packageId);if(!pkg||pkg.org_id!==orgId)throw new DOMException('package not found','NotFoundError');const granted=exactList(permissions,PACKAGE_PERMISSIONS,'install permissions');if(!granted.every(permission=>pkg.requested_permissions.includes(permission)))throw new DOMException('install grants exceed package request','SecurityError');const body={schema:'musitu.axiom.marketplace-install-preview.browser.v1',org_id:orgId,actor_id:actorId,package_id:packageId,package_sha256:pkg.package_sha256,granted_permissions:granted,status:'AWAITING_EXACT_CONFIRMATION',marketplace_policy:MARKETPLACE_POLICY};return {...body,preview_sha256:await sha256(body)};}
 async applyInstall(orgId,actorId,packageId,permissions,expectedPreviewSha){return this._queue(async()=>{const preview=await this.prepareInstall(orgId,actorId,packageId,permissions);if(expectedPreviewSha!==preview.preview_sha256)throw new DOMException('stale or altered package install preview','SecurityError');const body={schema:'musitu.axiom.marketplace-install.browser.v1',install_key:installKey(preview.org_id,preview.package_id),org_id:preview.org_id,package_id:preview.package_id,package_sha256:preview.package_sha256,granted_permissions:preview.granted_permissions,preview_sha256:preview.preview_sha256,status:'ACTIVE_LOCAL_PREVIEW',installed_by:preview.actor_id,installed_at:new Date().toISOString(),execution_enabled:false,external_code_executed:false},row={...body,install_sha256:await sha256(body)};await this._put('installs',row);await this._event(preview.org_id,'package.installed_local_preview',preview.actor_id,{package_id:row.package_id,package_sha256:row.package_sha256,install_sha256:row.install_sha256,granted_permissions:row.granted_permissions});await this._receipt(preview.org_id,'PACKAGE_INSTALL_LOCAL_PREVIEW',preview.actor_id,{package_id:row.package_id,preview_sha256:row.preview_sha256,install_sha256:row.install_sha256});return clone(row);});}
 async declareWebhook(orgId,actorId,raw={}){return this._queue(async()=>{({orgId,actorId}=await this._authorize(orgId,actorId));const declaration=normalizeWebhook(raw),body={schema:'musitu.axiom.webhook-declaration.browser.v1',webhook_id:uid('webhook'),org_id:orgId,...declaration,created_at:new Date().toISOString(),webhook_policy:WEBHOOK_POLICY,network_policy:NETWORK_POLICY,delivery_attempt_count:0},row={...body,webhook_sha256:await sha256(body)};await this._put('webhooks',row);await this._event(orgId,'webhook.declared_no_delivery',actorId,{webhook_id:row.webhook_id,webhook_sha256:row.webhook_sha256});return clone(row);});}
 async previewWebhookEvent(orgId,actorId,webhookId,eventName,payload={}){return this._queue(async()=>{({orgId,actorId}=await this._authorize(orgId,actorId));const hook=await this._get('webhooks',required(webhookId,'webhook id',180));if(!hook||hook.org_id!==orgId)throw new DOMException('webhook declaration not found','NotFoundError');eventName=required(eventName,'webhook event',100);if(!hook.events.includes(eventName))throw new DOMException('webhook event not granted','SecurityError');rejectSecretLike(payload,'webhook fixture');const payloadSha=await sha256(payload),signature=await sha256({webhook_sha256:hook.webhook_sha256,event_name:eventName,payload_sha256:payloadSha,delivery_enabled:false});return this._receipt(orgId,'WEBHOOK_SIGNED_FIXTURE_NO_DELIVERY',actorId,{webhook_id:hook.webhook_id,event_name:eventName,payload_sha256:payloadSha,fixture_signature_sha256:signature,delivery_enabled:false});});}
 async sdkBundle(orgId,actorId,packageId,credentialHandle){({orgId,actorId}=await this._authorize(orgId,actorId,'analysis.read'));const install=await this._get('installs',installKey(orgId,required(packageId,'package id',120))),credential=await this._get('credentials',required(credentialHandle,'credential handle',180));if(!install||install.status!=='ACTIVE_LOCAL_PREVIEW'||!credential||credential.org_id!==orgId)throw new DOMException('installed package and symbolic credential handle required','NotAllowedError');const binding={package_id:packageId,credential_handle:credentialHandle,transport:'LOCAL_PREVIEW_ONLY',network_policy:NETWORK_POLICY};return {schema:'musitu.axiom.sdk-bundle.browser.v1',binding,binding_sha256:await sha256(binding),python:`client = AxiomLocalPreview(package_id=${JSON.stringify(packageId)}, credential_handle=${JSON.stringify(credentialHandle)})`,javascript:`const client = new AxiomLocalPreview({packageId:${JSON.stringify(packageId)}, credentialHandle:${JSON.stringify(credentialHandle)}});`,mcp:{protocol:'2026-07-28',transport:'IN_PROCESS_STATELESS_LOCAL_PREVIEW',remote_binding:false},a2a:{schema:'musitu.axiom.a2a-card.local.v1',package_id:packageId,interfaces:INTERFACES.filter(value=>value.startsWith('a2a.')),external_endpoint:null}};}
 async conformance(orgId,actorId,packageId){({orgId,actorId}=await this._authorize(orgId,actorId,'audit.read'));const pkg=await this._get('packages',required(packageId,'package id',120)),install=await this._get('installs',installKey(orgId,packageId)),errors=[];if(!pkg||pkg.org_id!==orgId)return {status:'FAIL',errors:['package_missing']};if(await sha256(hashBody(pkg,'package_sha256'))!==pkg.package_sha256)errors.push('package_hash');if(pkg.network_permissions.length||pkg.external_code_included||pkg.remote_binding_claimed)errors.push('package_isolation');if(!install)errors.push('install_missing');else{if(await sha256(hashBody(install,'install_sha256'))!==install.install_sha256)errors.push('install_hash');if(!install.granted_permissions.every(permission=>pkg.requested_permissions.includes(permission)))errors.push('permission_escalation');if(install.execution_enabled||install.external_code_executed)errors.push('unexpected_execution');}return {schema:'musitu.axiom.developer-conformance.browser.v1',status:errors.length?'FAIL':'PASS',errors,package_id:packageId,interfaces:pkg.interfaces,network_policy:NETWORK_POLICY,platform_mode:PLATFORM_MODE,mcp_conformance:pkg.interfaces.includes('mcp.2026')?'MCP_2026_LOCAL_DESCRIPTOR_VALID':'NOT_REQUESTED',a2a_conformance:pkg.interfaces.includes('a2a.v1')?'A2A_LOCAL_CARD_VALID':'NOT_REQUESTED',webhook_conformance:pkg.interfaces.includes('webhook.v1')?'DECLARATION_ONLY_NO_DELIVERY':'NOT_REQUESTED',least_privilege_verified:errors.every(error=>error!=='permission_escalation'),isolation_verified:errors.every(error=>error!=='package_isolation'&&error!=='unexpected_execution'),production_api_key_issued:false,remote_mcp_binding_claimed:false,outbound_webhook_delivery_claimed:false,untrusted_package_code_executed:false};}
 async verify(orgId){orgId=required(orgId,'organization id',180);const errors=[],events=(await this._all('events',orgId)).sort((a,b)=>a.sequence-b.sequence);let previous=null;for(let i=0;i<events.length;i++){const row=events[i];if(row.sequence!==i||row.previous_event_sha256!==previous||await sha256(hashBody(row,'event_sha256'))!==row.event_sha256)errors.push(`event_chain:${i}`);previous=row.event_sha256;}for(const [store,field,key] of [['credentials','credential_fingerprint_sha256','credential_handle'],['packages','package_sha256','package_id'],['installs','install_sha256','package_id'],['webhooks','webhook_sha256','webhook_id'],['receipts','receipt_sha256','receipt_id']])for(const row of await this._all(store,orgId))if(await sha256(hashBody(row,field))!==row[field])errors.push(`${store}_hash:${row[key]}`);return {schema:'musitu.axiom.developer-integrity.browser.v1',status:errors.length?'FAIL':'PASS',errors:[...new Set(errors)].sort(),event_count:events.length,network_policy:NETWORK_POLICY,credential_policy:CREDENTIAL_POLICY,package_execution_policy:PACKAGE_EXECUTION_POLICY};}
}
