import {CLAIM_CLASSES,CLAIM_POLICY,EXTERNAL_CLAIM_CLASSES,FAILURE_POLICY,HISTORY_POLICY,PUBLICATION_MODE,REVIEW_POLICY,normalizeDefinition,normalizeEvaluation,required,sha256} from './evidence_security.js';
const DB='musitu-axiom-evidence-observatory-v1',VERSION=1;
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const clone=value=>structuredClone(value);
const without=(row,field)=>Object.fromEntries(Object.entries(row).filter(([key])=>key!==field));
export class EvidenceObservatoryStore{
 constructor(db){this.db=db;this.serial=Promise.resolve();}
 static async open(){const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;for(const [name,key] of [['definitions','definition_id'],['evaluations','evaluation_id'],['events','event_id']])if(!db.objectStoreNames.contains(name)){const store=db.createObjectStore(name,{keyPath:key});if(name==='evaluations')store.createIndex('status','status',{unique:false});}};return new EvidenceObservatoryStore(await req(request));}
 close(){this.db.close();}
 _queue(task){const next=this.serial.then(task,task);this.serial=next.catch(()=>{});return next;}
 async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
 async _all(store){const tx=this.db.transaction(store,'readonly'),rows=await req(tx.objectStore(store).getAll());await done(tx);return rows.map(clone);}
 async _add(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).add(clone(row));await done(tx);return clone(row);}
 async listDefinitions(){return (await this._all('definitions')).sort((a,b)=>a.definition_id.localeCompare(b.definition_id));}
 async listEvaluations(){return (await this._all('evaluations')).sort((a,b)=>b.evaluation_date.localeCompare(a.evaluation_date)||a.evaluation_id.localeCompare(b.evaluation_id));}
 async listEvents(){return (await this._all('events')).sort((a,b)=>a.sequence-b.sequence);}
 async _event(kind,payload={}){const history=await this.listEvents(),body={schema:'musitu.axiom.evidence-observatory-event.browser.v1',event_id:`observatory-event:${history.length}`,sequence:history.length,kind:required(kind,'event kind',100),payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:history.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};return this._add('events',row);}
 async registerDefinition(raw={}){return this._queue(async()=>{const normalized=normalizeDefinition(raw);if(await this._get('definitions',normalized.definition_id))throw new DOMException('evaluation definition identity already exists','ConstraintError');const body={...normalized,registered_at:new Date().toISOString()},row={...body,definition_sha256:await sha256(body)};await this._add('definitions',row);await this._event('DEFINITION_PUBLISHED',{definition_id:row.definition_id,definition_sha256:row.definition_sha256});return clone(row);});}
 async publishEvaluation(raw={}){return this._queue(async()=>{const id=required(raw.evaluationId,'evaluation id',180);if(await this._get('evaluations',id))throw new DOMException('evaluation identity already exists','ConstraintError');const definition=await this._get('definitions',required(raw.definitionId,'definition id',180));const normalized=normalizeEvaluation(raw,definition),body={...normalized,published_at:new Date().toISOString()},row={...body,entry_sha256:await sha256(body)};await this._add('evaluations',row);await this._event('EVALUATION_PUBLISHED',{evaluation_id:id,entry_sha256:row.entry_sha256,status:row.status});return clone(row);});}
 async appendLifecycleStatus(evaluationId,status,reason){return this._queue(async()=>{const evaluation=await this._get('evaluations',required(evaluationId,'evaluation id',180));if(!evaluation)throw new DOMException('evaluation not found','NotFoundError');status=required(status,'lifecycle status',40).toUpperCase();if(!['RETIRED','CONTAMINATED'].includes(status))throw new DOMException('only retired or contaminated lifecycle events are appendable','SecurityError');return this._event('EVALUATION_STATUS_APPENDED',{evaluation_id:evaluationId,status,reason:required(reason,'lifecycle reason',1000),original_entry_sha256:evaluation.entry_sha256});});}
 async claimAuthorization(evaluationId,claimClass){const evaluation=await this._get('evaluations',required(evaluationId,'evaluation id',180));if(!evaluation)throw new DOMException('evaluation not found','NotFoundError');claimClass=required(claimClass,'claim class',100).toUpperCase();if(!CLAIM_CLASSES.includes(claimClass))throw new TypeError('claim class is invalid');const lifecycle=(await this.listEvents()).filter(row=>row.kind==='EVALUATION_STATUS_APPENDED'&&row.payload.evaluation_id===evaluationId),disqualified=lifecycle.some(row=>['RETIRED','CONTAMINATED'].includes(row.payload.status)),localReady=evaluation.status==='PASS'&&evaluation.evidence_artifact_digests.length>0&&!disqualified,external=EXTERNAL_CLAIM_CLASSES.includes(claimClass),authorized=localReady&&!external,blockers=[];if(!localReady)blockers.push('exact passing non-retired evaluation evidence required');if(external)blockers.push('authenticated external origin required','independent review required','candidate-local ledger cannot self-authorize this claim class');return {schema:'musitu.axiom.claim-authorization-display.browser.v1',evaluation_id:evaluationId,entry_sha256:evaluation.entry_sha256,claim_class:claimClass,authorized,status:authorized?'AUTHORIZED_LOCAL_SCOPE':'BLOCKED',blockers,claim_policy:CLAIM_POLICY,independent_review_complete:false,global_superiority_claim_allowed:false};}
 async verify(){const errors=[];for(const row of await this.listDefinitions())if(await sha256(without(row,'definition_sha256'))!==row.definition_sha256)errors.push(`definition_hash:${row.definition_id}`);for(const row of await this.listEvaluations())if(await sha256(without(row,'entry_sha256'))!==row.entry_sha256)errors.push(`evaluation_hash:${row.evaluation_id}`);let previous=null;const events=await this.listEvents();for(let index=0;index<events.length;index++){const row=events[index];if(row.sequence!==index||row.previous_event_sha256!==previous||await sha256(without(row,'event_sha256'))!==row.event_sha256)errors.push(`event_chain:${index}`);previous=row.event_sha256;}return {schema:'musitu.axiom.evidence-observatory-integrity.browser.v1',status:errors.length?'FAIL':'PASS',errors:[...new Set(errors)].sort(),definition_count:(await this.listDefinitions()).length,evaluation_count:(await this.listEvaluations()).length,event_count:events.length,history_policy:HISTORY_POLICY};}
 async publicSnapshot(){const body={schema:'musitu.axiom.evidence-observatory-public-snapshot.browser.v1',publication_mode:PUBLICATION_MODE,definitions:await this.listDefinitions(),evaluations:await this.listEvaluations(),events:await this.listEvents(),integrity:await this.verify(),failed_evaluations_visible:true,retired_and_contaminated_history_visible:true,external_attestations_authenticated:false,global_superiority_claim_allowed:false};return {...body,snapshot_sha256:await sha256(body)};}
 async independentReviewPacket(trustDocuments){if(!Array.isArray(trustDocuments)||!trustDocuments.length)throw new TypeError('trust documents required');const snapshot=await this.publicSnapshot(),events=await this.listEvents(),body={schema:'musitu.axiom.phase13-independent-review-packet.browser.v1',snapshot_sha256:snapshot.snapshot_sha256,ledger_event_root_sha256:events.at(-1)?.event_sha256||null,trust_documents:trustDocuments.map(row=>({id:required(row.id,'trust document id',120),path:required(row.path,'trust document path',300),sha256:required(row.sha256,'trust document digest',64),status:required(row.status,'trust document status',120)})),claim_policy:CLAIM_POLICY,review_policy:REVIEW_POLICY,review_status:'AWAITING_AUTHENTICATED_INDEPENDENT_REVIEW',independent_review_complete:false,phase13_earned:false,global_superiority_claim_allowed:false};return {...body,review_packet_sha256:await sha256(body)};}
 async seed(definitions,evaluations){for(const definition of definitions)if(!await this._get('definitions',definition.definitionId))await this.registerDefinition(definition);for(const evaluation of evaluations)if(!await this._get('evaluations',evaluation.evaluationId))await this.publishEvaluation(evaluation);return this.verify();}
}
export const policies=Object.freeze({publication:PUBLICATION_MODE,history:HISTORY_POLICY,failure:FAILURE_POLICY,claim:CLAIM_POLICY,review:REVIEW_POLICY});
