const DB='musitu-axiom-live-semantic-v1';
const VERSION=1;
const HEX64=/^[0-9a-f]{64}$/;
const clone=v=>structuredClone(v);
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
async function sha(v){const bytes=new TextEncoder().encode(canonical(v)),digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function clean(v,n=8000){return String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,n);}
function assertHex(v,label){if(typeof v!=='string'||!HEX64.test(v))throw new TypeError(`${label} must be lowercase SHA-256`);return v;}
function bytesBase64(buffer){const bytes=new Uint8Array(buffer);let out='';for(let i=0;i<bytes.length;i+=0x8000)out+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(out);}

class SemanticBridgeStore{
  constructor(db){this.db=db;}
  static async open(){const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('receipts')){const s=db.createObjectStore('receipts',{keyPath:'bridge_id'});s.createIndex('session_id','session_id',{unique:false});}if(!db.objectStoreNames.contains('interruptions')){const s=db.createObjectStore('interruptions',{keyPath:'interruption_id'});s.createIndex('session_id','session_id',{unique:false});}};return new SemanticBridgeStore(await req(r));}
  async list(sessionId){const tx=this.db.transaction('receipts','readonly'),rows=await req(tx.objectStore('receipts').index('session_id').getAll(sessionId));await done(tx);return rows.sort((a,b)=>a.sequence-b.sequence).map(clone);}
  async interruptions(sessionId){const tx=this.db.transaction('interruptions','readonly'),rows=await req(tx.objectStore('interruptions').index('session_id').getAll(sessionId));await done(tx);return rows.sort((a,b)=>a.created_at.localeCompare(b.created_at)).map(clone);}
  async append(sessionId,receipt){const prior=await this.list(sessionId),previous=prior.at(-1)?.bridge_sha256||null,body={schema:'musitu.axiom.live-semantic-bridge-receipt.browser.v1',bridge_id:`${sessionId}:semantic:${prior.length}`,sequence:prior.length,session_id:sessionId,receipt:clone(receipt),previous_bridge_sha256:previous,created_at:new Date().toISOString()};const row={...body,bridge_sha256:await sha(body)},tx=this.db.transaction('receipts','readwrite');tx.objectStore('receipts').put(row);await done(tx);return clone(row);}
  async appendInterruption(sessionId,value){const body={schema:'musitu.axiom.live-semantic-bridge-interruption.browser.v1',interruption_id:`${sessionId}:semantic-interrupt:${crypto.randomUUID?.()||Date.now()}`,session_id:sessionId,value:clone(value),created_at:new Date().toISOString()},row={...body,bridge_sha256:await sha(body)},tx=this.db.transaction('interruptions','readwrite');tx.objectStore('interruptions').put(row);await done(tx);return clone(row);}
  async verify(sessionId){const rows=await this.list(sessionId),errors=[];let previous=null;for(let i=0;i<rows.length;i++){const row=rows[i],body=Object.fromEntries(Object.entries(row).filter(([k])=>k!=='bridge_sha256'));if(row.sequence!==i||row.previous_bridge_sha256!==previous)errors.push(`receipt_chain:${i}`);if(await sha(body)!==row.bridge_sha256)errors.push(`receipt_hash:${i}`);previous=row.bridge_sha256;}for(const row of await this.interruptions(sessionId)){const body=Object.fromEntries(Object.entries(row).filter(([k])=>k!=='bridge_sha256'));if(await sha(body)!==row.bridge_sha256)errors.push(`interruption_hash:${row.interruption_id}`);}const result={schema:'musitu.axiom.live-semantic-bridge-integrity.browser.v1',status:errors.length?'FAIL':'PASS',session_id:sessionId,receipt_count:rows.length,errors:[...new Set(errors)].sort(),head_sha256:previous};result.integrity_sha256=await sha(result);return result;}
}

function validateReceipt(receipt,{row,capture}){
  if(!receipt||typeof receipt!=='object')throw new TypeError('semantic receipt object required');
  for(const [key,expected] of [['session_id',row.session_id],['project_id',row.project_id],['actor_id',row.actor_id],['modality',capture.modality],['input_sha256',capture.content_sha256]])if(receipt[key]!==expected)throw new DOMException(`semantic receipt ${key} mismatch`,'DataError');
  assertHex(receipt.receipt_sha256,'receipt_sha256');assertHex(receipt.output_sha256,'output_sha256');assertHex(receipt.engine_asset_sha256,'engine_asset_sha256');
  if(receipt.hidden_reasoning_recorded!==false||receipt.cloud_provider_used!==false)throw new DOMException('semantic receipt violates privacy boundary','SecurityError');
  if(typeof receipt.semantic_scope!=='string'||!receipt.semantic_scope)throw new TypeError('semantic_scope required');
  if(capture.modality==='voice'){
    if(receipt.semantic_scope!=='OFFLINE_ASR_VERIFIED_MCP_SPECIALIST_TTS_DIALOGUE')throw new DOMException('voice semantic scope mismatch','DataError');
    assertHex(receipt.tool_receipt_sha256,'tool_receipt_sha256');
    if(!clean(receipt.output?.transcript)||!clean(receipt.output?.spoken_response))throw new DOMException('voice transcript/response missing','DataError');
  }else if(!receipt.semantic_scope.startsWith('OCR_TEXT_'))throw new DOMException('visual semantic scope mismatch','DataError');
  return clone(receipt);
}

function semanticMarkup(available){const section=document.createElement('section');section.id='live-semantic-bridge';section.className='project-card';section.innerHTML=`<h3>Local semantic runtime</h3><p id="live-semantic-status" role="status" aria-live="polite">${available?'Connected · offline scoped semantics':'Unavailable · capture/control remains available'}</p><p class="boundary-note">Scoped offline ASR, OCR/QR and MCP specialist receipts only. No general VLM, cloud media upload, hidden reasoning or real-device certification is implied.</p><div class="outcome-actions"><button id="live-semantic-run" class="button secondary" type="button" ${available?'':'disabled'}>Analyze selected capture</button><button id="live-semantic-interrupt" class="button secondary" type="button" ${available?'':'disabled'}>Interrupt semantic work</button></div><ol id="live-semantic-receipts" aria-label="Semantic receipts"></ol>`;return section;}

export async function attachLiveSemanticBridge({api,emit=()=>{},host=globalThis.AxiomLiveSemanticHost}={}){
  if(!api?.store||typeof api.store.media!=='function'||typeof api.store.transcriptTurn!=='function')throw new TypeError('Axiom Live API required');
  const store=await SemanticBridgeStore.open(),available=Boolean(host&&typeof host.execute==='function'&&typeof host.interrupt==='function');
  const liveSpace=document.querySelector('#live-space');if(!liveSpace)throw new DOMException('Live surface unavailable','NotFoundError');
  let section=document.querySelector('#live-semantic-bridge');if(!section){section=semanticMarkup(available);const grid=liveSpace.querySelector('.live-grid');(grid||liveSpace).append(section);}
  const status=section.querySelector('#live-semantic-status'),list=section.querySelector('#live-semantic-receipts');
  async function render(sessionId=api.getCurrentSessionId?.()){
    const rows=sessionId?await store.list(sessionId):[];list.replaceChildren();for(const row of rows){const li=document.createElement('li');li.textContent=`${row.receipt.modality} · ${row.receipt.semantic_scope} · ${row.receipt.receipt_sha256.slice(0,12)}…`;list.append(li);}status.textContent=available?`Connected · ${rows.length} verified semantic receipt${rows.length===1?'':'s'}`:'Unavailable · capture/control remains available';
  }
  async function executeCapture(captureId){
    if(!available)throw new DOMException('local semantic host unavailable','NotSupportedError');const sessionId=api.getCurrentSessionId?.(),row=await api.store.get(sessionId);if(!row||row.status!=='ACTIVE')throw new DOMException('active Live session required','InvalidStateError');const capture=row.captures.find(c=>c.capture_id===captureId);if(!capture)throw new DOMException('capture not found','NotFoundError');if(row.permissions[capture.modality]!=='granted')throw new DOMException('semantic execution requires granted modality permission','NotAllowedError');const media=await api.store.media(captureId);if(!media?.blob)throw new DOMException('capture media unavailable','NotFoundError');const request={schema:'musitu.axiom.live-semantic-host-request.v1',action:capture.modality==='voice'?'voice_turn':'interpret_capture',session_id:row.session_id,project_id:row.project_id,actor_id:row.actor_id,capture_id:capture.capture_id,modality:capture.modality,input_sha256:capture.content_sha256,mime_type:capture.mime_type,screen_region:capture.screen_region||null,bytes_base64:bytesBase64(await media.blob.arrayBuffer())};const receipt=validateReceipt(await host.execute(request),{row,capture}),saved=await store.append(sessionId,receipt);
    if(capture.modality==='voice'){await api.store.transcriptTurn(sessionId,{role:'user',text:receipt.output.transcript,source:'offline-vosk-asr'});await api.store.transcriptTurn(sessionId,{role:'assistant',text:receipt.output.spoken_response,source:'offline-mcp-2026-specialist'});await api.refresh();}
    emit('live.semantic.receipt',{state:`${capture.modality}:verified`});await render(sessionId);return saved;
  }
  async function interrupt(){if(!available)throw new DOMException('local semantic host unavailable','NotSupportedError');const sessionId=api.getCurrentSessionId?.();if(!sessionId)throw new DOMException('Live session required','InvalidStateError');const value=await host.interrupt({schema:'musitu.axiom.live-semantic-host-interrupt.v1',session_id:sessionId});if(!value||value.scope!=='SEMANTIC_EXECUTION_END_TO_END_STOP'||value.worker_stopped!==true||value.within_target!==true||Number(value.stop_latency_ms)>250)throw new DOMException('semantic interruption target not satisfied','TimeoutError');const saved=await store.appendInterruption(sessionId,value);emit('live.semantic.interrupt',{state:'within-target'});status.textContent=`Semantic execution stopped in ${Number(value.stop_latency_ms).toFixed(2)} ms`;return saved;}
  async function evidence(sessionId=api.getCurrentSessionId?.()){if(!sessionId)throw new DOMException('Live session required','InvalidStateError');const receipts=await store.list(sessionId),interruptions=await store.interruptions(sessionId),integrity=await store.verify(sessionId);return {schema:'musitu.axiom.live-semantic-bridge-evidence.browser.v1',status:integrity.status,session_id:sessionId,host_connected:available,receipt_count:receipts.length,modalities:[...new Set(receipts.map(r=>r.receipt.modality))].sort(),voice_turn_count:receipts.filter(r=>r.receipt.modality==='voice').length,mcp_tool_receipts_verified:receipts.filter(r=>r.receipt.modality==='voice').every(r=>HEX64.test(r.receipt.tool_receipt_sha256||'')),semantic_interruption_verified:interruptions.some(r=>r.value?.scope==='SEMANTIC_EXECUTION_END_TO_END_STOP'&&r.value?.within_target===true),privacy_boundary:'LOCAL_HOST_ONLY_NO_CLOUD_NO_HIDDEN_REASONING_NO_GENERAL_VLM_CLAIM',integrity};}
  section.querySelector('#live-semantic-run').addEventListener('click',()=>{const captureId=document.querySelector('#live-capture-select')?.value;executeCapture(captureId).catch(error=>window.AxiomUI?.reportError?.({errorId:'AXIOM-LIVE-SEMANTIC',component:'Axiom Live',impact:'Semantic receipt not recorded',failed:error.message,recovery:'Choose a durable capture and verify the local semantic host'}));});
  section.querySelector('#live-semantic-interrupt').addEventListener('click',()=>interrupt().catch(error=>window.AxiomUI?.reportError?.({errorId:'AXIOM-LIVE-SEMANTIC-INTERRUPT',component:'Axiom Live',impact:'Semantic work may still be active',failed:error.message,recovery:'Retry interruption or stop the local runtime'})));
  const bridge=Object.freeze({store,host_connected:available,executeCapture,interrupt,evidence,refresh:render});globalThis.AxiomLiveSemantic=bridge;await render();return bridge;
}

export const LiveSemanticBridgeContract=Object.freeze({host_transport:'IN_PROCESS_HOST_ADAPTER',fail_closed_without_host:true,max_semantic_stop_ms:250,general_vlm_claimed:false,cloud_media_upload_claimed:false,hidden_reasoning_recorded:false,real_device_certification_claimed:false});
