import {canonical,sha256,validateMemoryInput,memoryVisible} from './memory_security.js';
const DB='musitu-axiom-memory-v1',VERSION=1,now=()=>new Date().toISOString(),uid=prefix=>`${prefix}_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
export class MemoryGraphStore{
 constructor(db,{projects,observability,emit=()=>{}}={}){this.db=db;this.projects=projects;this.observability=observability;this.emit=emit;}
 static open(deps={}){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('memories')){const s=db.createObjectStore('memories',{keyPath:'memory_id'});s.createIndex('project_id','project_id',{unique:false});s.createIndex('subject','subject',{unique:false});}if(!db.objectStoreNames.contains('events')){const s=db.createObjectStore('events',{keyPath:'event_id'});s.createIndex('project_id','project_id',{unique:false});}if(!db.objectStoreNames.contains('receipts'))db.createObjectStore('receipts',{keyPath:'receipt_id'});};request.onsuccess=()=>resolve(new MemoryGraphStore(request.result,deps));request.onerror=()=>reject(request.error);});}
 close(){this.db.close();}
 async _all(store,index=null,key=null){const tx=this.db.transaction(store,'readonly'),source=index?tx.objectStore(store).index(index):tx.objectStore(store),rows=await req(key===null?source.getAll():source.getAll(key));await done(tx);return rows;}
 async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row||null;}
 async _event(projectId,actorId,type,payload){const prior=(await this._all('events','project_id',projectId)).sort((a,b)=>b.sequence-a.sequence)[0]||null,body={schema:'musitu.axiom.memory.event.browser.v1',project_id:projectId,actor_id:actorId,sequence:prior?prior.sequence+1:0,event_type:type,payload:structuredClone(payload),previous_event_sha256:prior?.event_sha256||null,created_at:now()};return {...body,event_id:uid('mevt'),event_sha256:await sha256(body)};}
 async remember(projectId,actorId,input={}){const project=await this.projects.store.getProject(projectId);if(!project)throw new DOMException('project not found','NotFoundError');const grant=project.permissions.find(row=>row.principal_id===actorId);if(!grant||!['owner','editor'].includes(grant.role))throw new DOMException('project write permission denied','NotAllowedError');const normalized=validateMemoryInput(input),graph=await this.projects.store.graph(projectId),objectIds=new Set(graph.objects.map(row=>row.object_id));if(normalized.source_refs.some(ref=>!objectIds.has(ref)))throw new TypeError('source refs must be existing project objects');const projectObject=await this.projects.store.addObject(projectId,actorId,{type:'memory',title:normalized.subject,provenanceSource:normalized.consent_source,evidenceLinks:normalized.source_refs});for(const ref of normalized.source_refs)await this.projects.store.addEdge(projectId,actorId,{fromId:projectObject.object_id,toId:ref,relation:'derived-from',provenanceSource:normalized.consent_source});const created_at=now(),body={schema:'musitu.axiom.memory.browser.v1',memory_id:uid('mem'),project_id:projectId,project_object_id:projectObject.object_id,...normalized,created_at,updated_at:created_at,revoked:false,revoked_at:null,revocation_consent_source:null};const record={...body,record_sha256:await sha256(body)},event=await this._event(projectId,actorId,'memory.remembered',{memory_id:body.memory_id,record_sha256:record.record_sha256,scope:record.scope,retention:record.retention});const receiptBody={schema:'musitu.axiom.memory-receipt.browser.v1',receipt_id:uid('mrcpt'),operation:'REMEMBER',memory_id:record.memory_id,project_id:projectId,actor_id:actorId,consent_source:record.consent_source,record_sha256:record.record_sha256,created_at};const receipt={...receiptBody,receipt_sha256:await sha256(receiptBody)};const tx=this.db.transaction(['memories','events','receipts'],'readwrite');tx.objectStore('memories').add(record);tx.objectStore('events').add(event);tx.objectStore('receipts').add(receipt);await done(tx);this.emit('memory.remembered',{state:record.scope});return structuredClone(record);}
 async markDoNotUse(memoryId,actorId,consentSource){const current=await this._get('memories',memoryId);if(!current)throw new DOMException('memory not found','NotFoundError');const project=await this.projects.store.getProject(current.project_id),grant=project?.permissions.find(row=>row.principal_id===actorId);if(!grant||!['owner','editor'].includes(grant.role))throw new DOMException('project write permission denied','NotAllowedError');consentSource=String(consentSource??'').trim().slice(0,240);if(!consentSource)throw new TypeError('revocation consent source required');const base={...current,scope:'do_not_use',revoked:true,revoked_at:now(),revocation_consent_source:consentSource,updated_at:now()};delete base.record_sha256;const next={...base,record_sha256:await sha256(base)},event=await this._event(current.project_id,actorId,'memory.do_not_use',{memory_id:memoryId,prior_record_sha256:current.record_sha256,record_sha256:next.record_sha256});const receiptBody={schema:'musitu.axiom.memory-receipt.browser.v1',receipt_id:uid('mrcpt'),operation:'DO_NOT_USE',memory_id:memoryId,project_id:current.project_id,actor_id:actorId,consent_source:consentSource,record_sha256:next.record_sha256,created_at:now()};const receipt={...receiptBody,receipt_sha256:await sha256(receiptBody)};const tx=this.db.transaction(['memories','events','receipts'],'readwrite');tx.objectStore('memories').put(next);tx.objectStore('events').add(event);tx.objectStore('receipts').add(receipt);await done(tx);this.emit('memory.revoked',{state:'do-not-use'});return structuredClone(next);}
 async recall(projectId,{subject='',viewer,allowed_scopes=[]}={}){const needle=String(subject||'').trim().toLowerCase(),rows=await this._all('memories','project_id',projectId),visible=rows.filter(row=>(!needle||row.subject.toLowerCase().includes(needle)||row.summary.toLowerCase().includes(needle))&&memoryVisible(row,{viewer,allowed_scopes}));this.emit('memory.recall',{state:`visible:${visible.length}`});return visible.sort((a,b)=>b.updated_at.localeCompare(a.updated_at)).map(row=>structuredClone(row));}
 async list(projectId){return (await this._all('memories','project_id',projectId)).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));}
 async receipts(){return this._all('receipts');}
 async verify(projectId){const errors=[],events=(await this._all('events','project_id',projectId)).sort((a,b)=>a.sequence-b.sequence);let previous=null;for(let i=0;i<events.length;i++){const e=events[i],body={schema:e.schema,project_id:e.project_id,actor_id:e.actor_id,sequence:e.sequence,event_type:e.event_type,payload:e.payload,previous_event_sha256:e.previous_event_sha256,created_at:e.created_at};if(e.sequence!==i||e.previous_event_sha256!==previous||await sha256(body)!==e.event_sha256)errors.push(`event:${e.event_id}`);previous=e.event_sha256;}for(const row of await this.list(projectId)){const body={...row};delete body.record_sha256;if(await sha256(body)!==row.record_sha256)errors.push(`memory:${row.memory_id}`);}for(const row of await this._all('receipts')){const body={...row};delete body.receipt_sha256;if(await sha256(body)!==row.receipt_sha256)errors.push(`receipt:${row.receipt_id}`);}return {status:errors.length?'FAIL':'PASS',errors,integrity_sha256:await sha256({project_id:projectId,events:events.map(e=>e.event_sha256),errors})};}
}
