import {MemoryGraphStore} from './memory_store.js';import {memoryMarkup} from './memory_ui_markup.js';
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
export async function initMemoryGraphWorkspace({emit=()=>{},projects,observability}={}){if(!projects?.store)throw new TypeError('project workspace required');const workspace=document.querySelector('#main-workspace');workspace.insertAdjacentHTML('beforeend',memoryMarkup());const store=await MemoryGraphStore.open({projects,observability,emit}),space=document.querySelector('#memory-space');let projectId='';
 async function projectsRefresh(){const rows=await projects.store.listProjects(),select=document.querySelector('#memory-project');select.replaceChildren(new Option('Select project',''));for(const p of rows)select.add(new Option(p.name,p.project_id));if(projectId&&rows.some(p=>p.project_id===projectId))select.value=projectId;else projectId=select.value;await sourceRefresh();await render();}
 async function sourceRefresh(){const select=document.querySelector('#memory-sources');select.replaceChildren();if(!projectId)return;const graph=await projects.store.graph(projectId);for(const row of graph.objects.filter(row=>row.type!=='memory'))select.add(new Option(`${row.type}: ${row.title}`,row.object_id));}
 async function render(rows=null){const list=document.querySelector('#memory-list');if(!projectId){list.textContent='Select a project to inspect its memory graph.';document.querySelector('#memory-integrity').textContent='No project selected';return;}const memories=rows||await store.list(projectId);list.replaceChildren();if(!memories.length){list.textContent='No memory records yet.';}for(const row of memories){const article=document.createElement('article');article.className='memory-record';article.dataset.memoryId=row.memory_id;article.innerHTML=`<header><strong>${esc(row.subject)}</strong><span class="status-pill neutral">${esc(row.revoked?'do-not-use':row.scope)}</span></header><p>${esc(row.summary)}</p><dl><div><dt>Retention</dt><dd>${esc(row.retention)}</dd></div><div><dt>Consent</dt><dd>${esc(row.consent_source)}</dd></div><div><dt>Viewers</dt><dd>${esc(row.authorized_viewers.join(', '))}</dd></div><div><dt>Sources</dt><dd>${esc(row.source_refs.join(', ')||'none')}</dd></div><div><dt>Record SHA-256</dt><dd><code>${esc(row.record_sha256)}</code></dd></div></dl>`;if(!row.revoked){const button=document.createElement('button');button.type='button';button.className='button secondary';button.textContent='Mark do not use';button.addEventListener('click',()=>void revoke(row.memory_id,button));article.append(button);}list.append(article);}const integrity=await store.verify(projectId);document.querySelector('#memory-integrity').textContent=`Integrity ${integrity.status} · ${integrity.integrity_sha256.slice(0,16)}…`;}
 async function revoke(id,button){button.disabled=true;try{await store.markDoNotUse(id,'local-user','user-explicit-revocation');await render();}catch(error){window.AxiomUI?.reportError?.({errorId:'AXIOM-MEMORY-REVOKE',component:'Memory Graph',impact:'Memory remains unchanged',failed:error.message,recovery:'Verify project permission and retry'});}finally{button.disabled=false;}}
 document.querySelector('#memory-project').addEventListener('change',async event=>{projectId=event.target.value;await sourceRefresh();await render();});
 document.querySelector('#memory-retention').addEventListener('change',event=>{document.querySelector('#memory-expiry').disabled=event.target.value==='permanent';if(event.target.value==='permanent')document.querySelector('#memory-expiry').value='';});document.querySelector('#memory-expiry').disabled=true;
 document.querySelector('#memory-create-form').addEventListener('submit',event=>{event.preventDefault();void(async()=>{if(!projectId)throw new TypeError('select a project');const viewers=document.querySelector('#memory-viewers').value.split(',').map(x=>x.trim()).filter(Boolean),source_refs=[...document.querySelector('#memory-sources').selectedOptions].map(option=>option.value),expiry=document.querySelector('#memory-expiry').value;await store.remember(projectId,'local-user',{subject:document.querySelector('#memory-subject').value,summary:document.querySelector('#memory-summary').value,scope:document.querySelector('#memory-scope').value,retention:document.querySelector('#memory-retention').value,expires_at:expiry?new Date(expiry).toISOString():null,authorized_viewers:viewers,consent_source:document.querySelector('#memory-consent').value,source_refs});event.target.reset();document.querySelector('#memory-viewers').value='local-user';document.querySelector('#memory-consent').value='user-explicit';document.querySelector('#memory-expiry').disabled=true;await sourceRefresh();await render();})().catch(error=>window.AxiomUI?.reportError?.({errorId:'AXIOM-MEMORY-REMEMBER',component:'Memory Graph',impact:'Memory was not stored',failed:error.message,recovery:'Provide valid consent, scope, retention, viewer and source controls then retry'}));});
 document.querySelector('#memory-recall-form').addEventListener('submit',event=>{event.preventDefault();void(async()=>{if(!projectId)throw new TypeError('select a project');const allowed_scopes=[...document.querySelectorAll('[name="memory-allowed-scope"]:checked')].map(node=>node.value),rows=await store.recall(projectId,{subject:document.querySelector('#memory-query').value,viewer:document.querySelector('#memory-recall-viewer').value,allowed_scopes}),target=document.querySelector('#memory-recall-results');target.textContent=`${rows.length} authorized memor${rows.length===1?'y':'ies'} recalled.`;await render(rows);})().catch(error=>window.AxiomUI?.reportError?.({errorId:'AXIOM-MEMORY-RECALL',component:'Memory Graph',impact:'No memory returned',failed:error.message,recovery:'Verify viewer and allowed scopes then retry'}));});
 document.querySelector('#memory-refresh').addEventListener('click',()=>void projectsRefresh());
 function sync(){const active=location.hash==='#/project/memory';space.hidden=!active;if(active){document.querySelector('.hero-card').hidden=true;document.querySelector('.run-stage').hidden=true;document.querySelector('#workspace-title').textContent='Memory';document.querySelector('#workspace-description').textContent='Inspect consent, scope, retention, provenance, authorization, expiry and revocation as a durable memory graph.';void projectsRefresh();}else if(!location.hash.startsWith('#/project/')){document.querySelector('.hero-card').hidden=false;document.querySelector('.run-stage').hidden=false;}}
 window.addEventListener('hashchange',sync);sync();const api=Object.freeze({store,refresh:projectsRefresh,selectProject:async id=>{projectId=id;document.querySelector('#memory-project').value=id;await sourceRefresh();await render();}});window.AxiomMemory=api;return api;}
