export const MEMORY_SCOPES=Object.freeze(['private','project','organization','shared','do_not_use']);
export const MEMORY_RETENTION=Object.freeze(['temporary','permanent']);
export const MEMORY_NETWORK_POLICY='DENY_ALL_EXTERNAL_NETWORK';
export const MEMORY_SECRET_POLICY='NO_SECRET_OR_HIDDEN_REASONING_STORAGE';
const clean=(value,max=1000)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max);
export function canonical(value){if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;return JSON.stringify(value);}
export async function sha256(value){const bytes=new TextEncoder().encode(typeof value==='string'?value:canonical(value));const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function normalizeList(values,max=120){return [...new Set((Array.isArray(values)?values:[]).map(value=>clean(value,max)).filter(Boolean))].sort();}
export function validateMemoryInput(input={}){const subject=clean(input.subject,180),summary=clean(input.summary,4000),scope=clean(input.scope,32),retention=clean(input.retention,32),consent_source=clean(input.consent_source,240),authorized_viewers=normalizeList(input.authorized_viewers),source_refs=normalizeList(input.source_refs,180);if(!subject||!summary||!consent_source)throw new TypeError('subject, summary and consent source are required');if(!MEMORY_SCOPES.includes(scope)||scope==='do_not_use')throw new TypeError('invalid active memory scope');if(!MEMORY_RETENTION.includes(retention))throw new TypeError('invalid memory retention');if(!authorized_viewers.length)throw new TypeError('at least one authorized viewer is required');let expires_at=input.expires_at?new Date(input.expires_at).toISOString():null;if(retention==='temporary'){if(!expires_at||Date.parse(expires_at)<=Date.now())throw new TypeError('temporary memory requires a future expiry');}else if(expires_at)throw new TypeError('permanent memory cannot have expiry');return {subject,summary,scope,retention,consent_source,authorized_viewers,source_refs,expires_at};}
export function memoryVisible(record,{viewer,allowed_scopes,now=Date.now()}={}){if(!record||record.revoked||record.scope==='do_not_use')return false;const scopes=new Set(Array.isArray(allowed_scopes)?allowed_scopes:[]);if(!scopes.has(record.scope))return false;if(record.expires_at&&Date.parse(record.expires_at)<=now)return false;if(!record.authorized_viewers.includes('*')&&!record.authorized_viewers.includes(String(viewer||'')))return false;return true;}
