const DB='musitu-axiom-observability-v1';
const VERSION=1;
const TRACE_LINK_FIELDS=['user_intent_id','project_id','run_id','agent_id','model_execution_id','tool_call_id','policy_decision_id','source_id','artifact_id','verification_id','deployment_id'];
const OP_FIELDS=new Set(['latency_ms','model_route','tool_duration_ms','retries','failure_code','cost_usd','compute_units','cache_hit','approval_state','policy_intervention','evidence_coverage','confidence_before','confidence_after','status','error_code','error_category','recovery_state']);
const ERROR_TAXONOMY=new Set(['VALIDATION','PERMISSION','POLICY','MODEL','TOOL','NETWORK','TIMEOUT','DEPENDENCY','INTEGRITY','USER_CANCELLED','INTERNAL']);
const FINAL=new Set(['COMPLETED','FAILED','BLOCKED','CANCELLED']);
const KINDS=new Set(['run.started','model.executed','tool.called','policy.decided','source.used','artifact.updated','verification.completed','deployment.updated','approval.updated','run.progress','run.finished','error.recorded']);
const FORBIDDEN=['secret','password','token','credential','api_key','authorization','prompt','chain_of_thought','private_reasoning','hidden_reasoning','reasoning_text'];
const clone=v=>structuredClone(v);
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const clean=(v,n=240)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,n);
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
async function sha(v){const b=new TextEncoder().encode(canonical(v)),d=await crypto.subtle.digest('SHA-256',b);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function safeId(v,name){const x=clean(v,180);if(!x)throw new TypeError(`${name} required`);return x;}
function safeOperational(data={}){if(!data||typeof data!=='object'||Array.isArray(data))throw new TypeError('operational data must be object');const out={};for(const [raw,v] of Object.entries(data)){const k=clean(raw,80),lower=k.toLowerCase();if(FORBIDDEN.some(x=>lower.includes(x)))throw new DOMException(`forbidden trace field: ${k}`,'SecurityError');if(!OP_FIELDS.has(k))throw new TypeError(`unapproved trace field: ${k}`);if(['latency_ms','tool_duration_ms','cost_usd','compute_units'].includes(k)){const n=Number(v);if(!Number.isFinite(n)||n<0)throw new TypeError(`${k} invalid`);out[k]=n;}else if(k==='retries'){const n=Number(v);if(!Number.isInteger(n)||n<0)throw new TypeError('retries invalid');out[k]=n;}else if(['evidence_coverage','confidence_before','confidence_after'].includes(k)){const n=Number(v);if(!Number.isFinite(n)||n<0||n>1)throw new TypeError(`${k} invalid`);out[k]=n;}else if(['cache_hit','policy_intervention'].includes(k)){if(typeof v!=='boolean')throw new TypeError(`${k} invalid`);out[k]=v;}else if(k==='error_category'){const x=clean(v,48).toUpperCase();if(!ERROR_TAXONOMY.has(x))throw new TypeError('invalid error category');out[k]=x;}else out[k]=clean(v,240);}return out;}

export class ObservabilityStore{
  constructor(db){this.db=db;}
  static async open(){const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('runs')){const s=db.createObjectStore('runs',{keyPath:'run_id'});s.createIndex('project_id','project_id',{unique:false});s.createIndex('trace_id','trace_id',{unique:true});}if(!db.objectStoreNames.contains('events')){const s=db.createObjectStore('events',{keyPath:'event_id'});s.createIndex('run_id','run_id',{unique:false});}};return new ObservabilityStore(await req(r));}
  async getRun(runId){const tx=this.db.transaction('runs','readonly'),row=await req(tx.objectStore('runs').get(runId));await done(tx);return row?clone(row):null;}
  async listRuns(){const tx=this.db.transaction('runs','readonly'),rows=await req(tx.objectStore('runs').getAll());await done(tx);return rows.sort((a,b)=>b.started_at.localeCompare(a.started_at)).map(clone);}
  async events(runId){const tx=this.db.transaction('events','readonly'),rows=await req(tx.objectStore('events').index('run_id').getAll(runId));await done(tx);return rows.sort((a,b)=>a.sequence-b.sequence).map(clone);}
  async _putRun(row){const tx=this.db.transaction('runs','readwrite');tx.objectStore('runs').put(clone(row));await done(tx);return clone(row);}
  async startRun({runId,traceId,actorId,userIntentId,projectId,production=false,startedAt=new Date().toISOString()}={}){runId=safeId(runId,'runId');traceId=safeId(traceId,'traceId');actorId=safeId(actorId,'actorId');userIntentId=safeId(userIntentId,'userIntentId');projectId=safeId(projectId,'projectId');if(await this.getRun(runId))throw new DOMException('duplicate run id','ConstraintError');const row={schema:'musitu.axiom.observability.run.browser.v1',run_id:runId,trace_id:traceId,actor_id:actorId,user_intent_id:userIntentId,project_id:projectId,production:Boolean(production),started_at:startedAt,ended_at:null,final_status:null,error_category:null,operational_replay_only:true,hidden_reasoning_recorded:false,secrets_recorded:false};await this._putRun(row);await this.recordEvent(runId,{kind:'run.started',actorId,at:startedAt});return clone(row);}
  async recordEvent(runId,{kind,actorId,at=new Date().toISOString(),linkage={},operational={}}={}){const run=await this.getRun(runId);if(!run)throw new DOMException('run not found','NotFoundError');if(run.final_status)throw new DOMException('run is terminal','InvalidStateError');kind=clean(kind,80);if(!KINDS.has(kind))throw new TypeError('unsupported event kind');actorId=safeId(actorId,'actorId');const unknown=Object.keys(linkage||{}).filter(k=>!TRACE_LINK_FIELDS.includes(k));if(unknown.length)throw new TypeError(`unapproved linkage fields: ${unknown.join(',')}`);const links=Object.fromEntries(TRACE_LINK_FIELDS.map(k=>[k,null]));Object.assign(links,{user_intent_id:run.user_intent_id,project_id:run.project_id,run_id:runId});for(const [k,v] of Object.entries(linkage||{}))links[k]=safeId(v,k);if(links.user_intent_id!==run.user_intent_id||links.project_id!==run.project_id||links.run_id!==runId)throw new DOMException('root trace linkage mismatch','InvalidStateError');const history=await this.events(runId),sequence=history.length;const body={schema:'musitu.axiom.observability.event.browser.v1',event_id:`${runId}:evt:${sequence}`,run_id:runId,sequence,trace_id:run.trace_id,actor_id:actorId,kind,at,linkage:links,operational:safeOperational(operational),previous_event_sha256:history.at(-1)?.event_sha256||null};const event={...body,event_sha256:await sha(body)};const tx=this.db.transaction('events','readwrite');tx.objectStore('events').add(event);await done(tx);return clone(event);}
  async finishRun(runId,{status,actorId,errorCategory=null,operational={},endedAt=new Date().toISOString()}={}){const run=await this.getRun(runId);if(!run)throw new DOMException('run not found','NotFoundError');status=clean(status,48).toUpperCase();if(!FINAL.has(status))throw new TypeError('invalid final status');let category=null;if(errorCategory){category=clean(errorCategory,48).toUpperCase();if(!ERROR_TAXONOMY.has(category))throw new TypeError('invalid error category');}const op={...operational,status};if(category)op.error_category=category;await this.recordEvent(runId,{kind:'run.finished',actorId,at:endedAt,operational:op});run.ended_at=endedAt;run.final_status=status;run.error_category=category;return this._putRun(run);}
  async verify(runId=null){const rows=runId?[await this.getRun(runId)]:(await this.listRuns()).slice().reverse(),errors=[];for(const run of rows){if(!run){errors.push(`run_missing:${runId}`);continue;}for(const k of ['trace_id','actor_id','user_intent_id','project_id','run_id'])if(!run[k])errors.push(`run_link_missing:${run.run_id}:${k}`);if(run.production&&(!run.trace_id||!run.actor_id))errors.push(`production_identity_missing:${run.run_id}`);let prev=null;const history=await this.events(run.run_id);for(let i=0;i<history.length;i++){const e=history[i],body=Object.fromEntries(Object.entries(e).filter(([k])=>k!=='event_sha256'));if(e.sequence!==i||e.previous_event_sha256!==prev)errors.push(`event_chain:${run.run_id}:${i}`);if(e.trace_id!==run.trace_id||e.linkage?.run_id!==run.run_id)errors.push(`event_link:${run.run_id}:${i}`);if(!e.actor_id)errors.push(`event_actor:${run.run_id}:${i}`);if(await sha(body)!==e.event_sha256)errors.push(`event_hash:${run.run_id}:${i}`);prev=e.event_sha256;}if(!history.length||history[0].kind!=='run.started')errors.push(`run_start_event:${run.run_id}`);if(run.final_status&&history.at(-1)?.kind!=='run.finished')errors.push(`run_finish_event:${run.run_id}`);if(run.hidden_reasoning_recorded||run.secrets_recorded)errors.push(`privacy_boundary:${run.run_id}`);}const result={schema:'musitu.axiom.observability.integrity.browser.v1',status:errors.length?'FAIL':'PASS',run_ids:rows.filter(Boolean).map(r=>r.run_id),errors:[...new Set(errors)].sort()};result.integrity_sha256=await sha(result);return result;}
  async replay(runId){const run=await this.getRun(runId);if(!run)throw new DOMException('run not found','NotFoundError');return {schema:'musitu.axiom.observability.replay.browser.v1',scope:'OPERATIONAL_METADATA_ONLY_NO_SECRETS_NO_HIDDEN_REASONING',run,events:await this.events(runId),integrity:await this.verify(runId)};}
  async operatorHealth(){const rows=await this.listRuns(),finished=rows.filter(r=>r.final_status),failed=finished.filter(r=>r.final_status==='FAILED'),latencies=[],statusCounts=Object.fromEntries([...FINAL].sort().map(x=>[x,0]));let retries=0;for(const r of finished)statusCounts[r.final_status]=(statusCounts[r.final_status]||0)+1;for(const r of rows)for(const e of await this.events(r.run_id)){if(Number.isFinite(e.operational?.latency_ms))latencies.push(e.operational.latency_ms);retries+=Number(e.operational?.retries||0);}latencies.sort((a,b)=>a-b);const med=latencies.length?(latencies[Math.floor((latencies.length-1)/2)]+latencies[Math.ceil((latencies.length-1)/2)])/2:null;return {schema:'musitu.axiom.observability.operator-health.browser.v1',run_count:rows.length,finished_count:finished.length,failed_count:failed.length,failure_rate:finished.length?failed.length/finished.length:0,median_latency_ms:med,retry_count:retries,status_counts:statusCounts,error_taxonomy:[...ERROR_TAXONOMY].sort()};}
}

function markup(){return `<section id="observability-space" class="observability-space" aria-labelledby="observability-title" hidden><div class="section-heading"><div><span class="eyebrow">Evidence-safe operational visibility</span><h2 id="observability-title">Observability</h2></div><span class="status-pill neutral">No private reasoning</span></div><p class="boundary-note">Operational replay exposes IDs, timing, policy/tool/model metadata, evidence coverage, status and recovery signals. Prompts, credentials, secrets and hidden chain-of-thought are outside this trace schema.</p><div class="obs-tabs" role="tablist" aria-label="Observability interfaces"><button class="button secondary active" role="tab" aria-selected="true" data-obs-tab="user">User Run Inspector</button><button class="button secondary" role="tab" aria-selected="false" data-obs-tab="developer">Developer Trace Explorer</button><button class="button secondary" role="tab" aria-selected="false" data-obs-tab="operator">Operator Control Plane</button></div><div class="obs-grid"><section class="project-card"><label>Run<select id="obs-run-select"><option value="">No runs recorded</option></select></label><button id="obs-refresh" class="button secondary" type="button">Refresh traces</button><div id="obs-summary" class="project-summary" aria-live="polite"></div></section><section class="project-card"><div id="obs-user-panel"></div><pre id="obs-developer-panel" hidden></pre><div id="obs-operator-panel" hidden></div></section></div><section class="project-card"><h3>Error taxonomy</h3><div id="obs-error-taxonomy" class="chip-list"></div></section></section>`;}

export async function initObservabilityWorkspace({emit=()=>{},projects}={}){if(!projects?.store)throw new TypeError('qualified Project substrate required');const main=document.querySelector('#main-workspace');if(!main)return null;const style=document.createElement('link');style.rel='stylesheet';style.href='./styles/observability.css';document.head.append(style);main.insertAdjacentHTML('beforeend',markup());const store=await ObservabilityStore.open(),space=document.querySelector('#observability-space'),hero=document.querySelector('.hero-card'),runStage=document.querySelector('.run-stage');let current='';let tab='user';
  function setTab(next){tab=next;document.querySelectorAll('[data-obs-tab]').forEach(b=>{const active=b.dataset.obsTab===next;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));});document.querySelector('#obs-user-panel').hidden=next!=='user';document.querySelector('#obs-developer-panel').hidden=next!=='developer';document.querySelector('#obs-operator-panel').hidden=next!=='operator';render().catch(()=>{});emit('observability.tab',{state:next});}
  async function refresh(){const rows=await store.listRuns(),sel=document.querySelector('#obs-run-select'),preferred=current||sel.value;sel.replaceChildren(new Option(rows.length?'Choose run':'No runs recorded',''));for(const r of rows)sel.add(new Option(`${r.final_status||'ACTIVE'} · ${r.run_id}`,r.run_id));if(preferred&&rows.some(r=>r.run_id===preferred)){sel.value=preferred;current=preferred;}else current=sel.value;await render();}
  async function render(){const summary=document.querySelector('#obs-summary'),user=document.querySelector('#obs-user-panel'),dev=document.querySelector('#obs-developer-panel'),op=document.querySelector('#obs-operator-panel');summary.replaceChildren();user.replaceChildren();dev.textContent='';op.replaceChildren();if(current){const replay=await store.replay(current),r=replay.run;const dl=document.createElement('dl');dl.className='project-meta';for(const [k,v] of [['Trace ID',r.trace_id],['Actor',r.actor_id],['Project',r.project_id],['Run',r.run_id],['Status',r.final_status||'ACTIVE'],['Integrity',replay.integrity.status]]){const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=String(v);d.append(dt,dd);dl.append(d);}summary.append(dl);const ol=document.createElement('ol');ol.className='obs-timeline';for(const e of replay.events){const li=document.createElement('li');li.textContent=`${e.sequence} · ${e.kind} · actor ${e.actor_id} · ${new Date(e.at).toLocaleString()}`;ol.append(li);}user.append(ol);dev.textContent=JSON.stringify(replay,null,2);}else{user.textContent='No run selected.';dev.textContent='No trace selected.';}const health=await store.operatorHealth();const dl2=document.createElement('dl');dl2.className='project-meta';for(const [k,v] of [['Runs',health.run_count],['Finished',health.finished_count],['Failed',health.failed_count],['Failure rate',health.failure_rate],['Median latency ms',health.median_latency_ms??'n/a'],['Retries',health.retry_count]]){const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=String(v);d.append(dt,dd);dl2.append(d);}op.append(dl2);const chips=document.querySelector('#obs-error-taxonomy');chips.replaceChildren(...health.error_taxonomy.map(x=>{const s=document.createElement('span');s.className='chip';s.textContent=x;return s;}));}
  function route(){const match=location.hash.match(/^#\/(observability|developer)(?:\/|$)/);const on=Boolean(match);space.hidden=!on;if(hero)hero.hidden=on;if(runStage)runStage.hidden=on;if(on){document.querySelector('#workspace-title').textContent=match[1]==='developer'?'Developer Trace Explorer':'Observability';document.querySelector('#workspace-description').textContent='Inspect operational evidence, linked actors, traces, errors and health without exposing secrets or hidden reasoning.';if(match[1]==='developer')setTab('developer');refresh();}}
  document.querySelectorAll('[data-obs-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.obsTab)));document.querySelector('#obs-run-select').addEventListener('change',e=>{current=e.target.value;render();});document.querySelector('#obs-refresh').addEventListener('click',refresh);window.addEventListener('hashchange',route);await refresh();route();const api={store,refresh,getCurrentRunId:()=>current,setCurrentRun:async id=>{current=id;await refresh();}};window.AxiomObservability=Object.freeze(api);return api;}

export const ObservabilityContract=Object.freeze({TRACE_LINK_FIELDS:[...TRACE_LINK_FIELDS],ERROR_TAXONOMY:[...ERROR_TAXONOMY],scope:'OPERATIONAL_METADATA_ONLY_NO_SECRETS_NO_HIDDEN_REASONING'});
