import {BILLING_POLICY,CONTROL_PLANE_MODE,HIDDEN_REASONING_POLICY,IDENTITY_POLICY,NETWORK_POLICY,can,clean,normalizePolicy,rejectSecretLike,required,role,sha256,uid} from './operator_security.js';
const DB='musitu-axiom-operator-v1',VERSION=1;
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const clone=value=>structuredClone(value);
const memberKey=(orgId,principalId)=>`${orgId}:${principalId}`;
const memberBody=row=>({schema:row.schema,member_key:row.member_key,org_id:row.org_id,principal_id:row.principal_id,role:row.role,status:row.status,created_at:row.created_at,updated_at:row.updated_at});
export class OperatorControlStore{
 constructor(db,{agents,observability}){this.db=db;this.agents=agents;this.observability=observability;this.serial=Promise.resolve();}
 static async open({agents,observability}={}){if(!agents?.store||!observability?.store)throw new TypeError('earned Agent and Observability substrates required');const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains('orgs'))db.createObjectStore('orgs',{keyPath:'org_id'});if(!db.objectStoreNames.contains('members')){const store=db.createObjectStore('members',{keyPath:'member_key'});store.createIndex('org_id','org_id',{unique:false});}if(!db.objectStoreNames.contains('policies'))db.createObjectStore('policies',{keyPath:'org_id'});if(!db.objectStoreNames.contains('events')){const store=db.createObjectStore('events',{keyPath:'event_id'});store.createIndex('org_id','org_id',{unique:false});}if(!db.objectStoreNames.contains('receipts')){const store=db.createObjectStore('receipts',{keyPath:'receipt_id'});store.createIndex('org_id','org_id',{unique:false});}};return new OperatorControlStore(await req(request),{agents,observability});}
 close(){this.db.close();}
 _queue(task){const next=this.serial.then(task,task);this.serial=next.catch(()=>{});return next;}
 async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
 async _all(store,index=null,key=null){const tx=this.db.transaction(store,'readonly'),source=index?tx.objectStore(store).index(index):tx.objectStore(store),rows=await req(key===null?source.getAll():source.getAll(key));await done(tx);return rows.map(clone);}
 async _put(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(clone(row));await done(tx);return clone(row);}
 async listOrganizations(){return (await this._all('orgs')).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
 async getOrganization(orgId){return this._get('orgs',clean(orgId,180));}
 async listMembers(orgId){return (await this._all('members','org_id',clean(orgId,180))).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
 async getMember(orgId,principalId){return this._get('members',memberKey(clean(orgId,180),clean(principalId,180)));}
 async listReceipts(orgId){return (await this._all('receipts','org_id',clean(orgId,180))).sort((a,b)=>a.created_at.localeCompare(b.created_at));}
 async _event(orgId,kind,actorId,payload={}){const history=(await this._all('events','org_id',orgId)).sort((a,b)=>a.sequence-b.sequence),body={schema:'musitu.axiom.operator-event.browser.v1',event_id:`operator-event:${orgId}:${history.length}`,org_id:orgId,sequence:history.length,kind:required(kind,'event kind',80),actor_id:required(actorId,'actor',180),payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:history.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};await this._put('events',row);return row;}
 async _receipt(orgId,operation,actorId,payload={}){const body={schema:'musitu.axiom.operator-receipt.browser.v1',receipt_id:uid('operator-receipt'),org_id:orgId,operation,actor_id:actorId,payload:clone(payload),created_at:new Date().toISOString(),control_plane_mode:CONTROL_PLANE_MODE},row={...body,receipt_sha256:await sha256(body)};await this._put('receipts',row);return row;}
 async authorize(orgId,actorId,permission){const org=await this.getOrganization(orgId);if(!org||org.status!=='ACTIVE')throw new DOMException('active organization preview required','NotAllowedError');const member=await this.getMember(orgId,actorId);if(!member||member.status!=='ACTIVE'||!can(member.role,permission))throw new DOMException(`${permission} authorization required`,'SecurityError');return true;}
 async bootstrapOrganization({orgId,name,ownerId='local-user'}={}){return this._queue(async()=>{orgId=required(orgId,'org id',180);name=required(name,'organization name',200);ownerId=required(ownerId,'owner id',180);rejectSecretLike({orgId,name,ownerId},'organization declaration');if(await this.getOrganization(orgId))throw new DOMException('organization already exists','ConstraintError');const created=new Date().toISOString(),body={schema:'musitu.axiom.enterprise-preview.browser.v1',org_id:orgId,name,status:'ACTIVE',owner_principal_id:ownerId,created_at:created,updated_at:created,deployment_environment:'BROWSER_LOCAL_DEVICE',identity_policy:IDENTITY_POLICY,billing_policy:BILLING_POLICY,network_policy:NETWORK_POLICY},org={...body,org_sha256:await sha256(body)};await this._put('orgs',org);const member={schema:'musitu.axiom.enterprise-member-preview.browser.v1',member_key:memberKey(orgId,ownerId),org_id:orgId,principal_id:ownerId,role:'owner',status:'ACTIVE',created_at:created,updated_at:created};member.member_sha256=await sha256(memberBody(member));await this._put('members',member);await this._event(orgId,'organization.bootstrapped',ownerId,{org_sha256:org.org_sha256,owner_principal_id:ownerId});await this._receipt(orgId,'ORGANIZATION_BOOTSTRAP_LOCAL_PREVIEW',ownerId,{org_sha256:org.org_sha256});return clone(org);});}
 async addMember(orgId,actorId,{principalId,memberRole='viewer'}={}){return this._queue(async()=>{orgId=required(orgId,'org id',180);actorId=required(actorId,'actor',180);principalId=required(principalId,'principal id',180);memberRole=role(memberRole);await this.authorize(orgId,actorId,'member.manage');const actor=await this.getMember(orgId,actorId);if(memberRole==='owner'&&actor.role!=='owner')throw new DOMException('owner role required to add owner','SecurityError');if(await this.getMember(orgId,principalId))throw new DOMException('member already exists','ConstraintError');rejectSecretLike({principalId},'principal');const now=new Date().toISOString(),row={schema:'musitu.axiom.enterprise-member-preview.browser.v1',member_key:memberKey(orgId,principalId),org_id:orgId,principal_id:principalId,role:memberRole,status:'ACTIVE',created_at:now,updated_at:now};row.member_sha256=await sha256(memberBody(row));await this._put('members',row);await this._event(orgId,'member.added',actorId,{principal_id:principalId,role:memberRole,member_sha256:row.member_sha256});await this._receipt(orgId,'MEMBER_ADD_LOCAL_PREVIEW',actorId,{principal_id:principalId,role:memberRole});return clone(row);});}
 async prepareRoleChange(orgId,actorId,principalId,nextRole){orgId=required(orgId,'org id',180);actorId=required(actorId,'actor',180);principalId=required(principalId,'principal id',180);nextRole=role(nextRole);await this.authorize(orgId,actorId,'member.manage');const target=await this.getMember(orgId,principalId);if(!target)throw new DOMException('member not found','NotFoundError');if(target.role==='owner'&&nextRole!=='owner'){const owners=(await this.listMembers(orgId)).filter(row=>row.status==='ACTIVE'&&row.role==='owner');if(owners.length<=1)throw new DOMException('final active owner cannot be demoted','SecurityError');}const body={schema:'musitu.axiom.role-change-preview.browser.v1',org_id:orgId,actor_id:actorId,principal_id:principalId,current_role:target.role,next_role:nextRole,current_member_sha256:target.member_sha256,status:'AWAITING_EXACT_CONFIRMATION'};return {...body,preview_sha256:await sha256(body)};}
 async applyRoleChange(orgId,actorId,principalId,nextRole,expectedPreviewSha){return this._queue(async()=>{const preview=await this.prepareRoleChange(orgId,actorId,principalId,nextRole);if(expectedPreviewSha!==preview.preview_sha256)throw new DOMException('stale or altered role-change preview','SecurityError');const target=await this.getMember(orgId,principalId);target.role=preview.next_role;target.updated_at=new Date().toISOString();target.member_sha256=await sha256(memberBody(target));await this._put('members',target);await this._event(orgId,'member.role_changed',actorId,{principal_id:principalId,next_role:target.role,preview_sha256:preview.preview_sha256,member_sha256:target.member_sha256});return this._receipt(orgId,'ROLE_CHANGE_LOCAL_PREVIEW',actorId,{principal_id:principalId,next_role:target.role,preview_sha256:preview.preview_sha256});});}
 async preparePolicy(orgId,actorId,rawPolicy={}){orgId=required(orgId,'org id',180);actorId=required(actorId,'actor',180);await this.authorize(orgId,actorId,'policy.manage');const policy=normalizePolicy(rawPolicy),current=await this._get('policies',orgId),body={schema:'musitu.axiom.operator-policy-preview.browser.v1',org_id:orgId,actor_id:actorId,version:(current?.version||0)+1,policy,status:'AWAITING_EXACT_CONFIRMATION'};return {...body,preview_sha256:await sha256(body)};}
 async applyPolicy(orgId,actorId,rawPolicy,expectedPreviewSha){return this._queue(async()=>{const preview=await this.preparePolicy(orgId,actorId,rawPolicy);if(expectedPreviewSha!==preview.preview_sha256)throw new DOMException('stale or altered policy preview','SecurityError');const now=new Date().toISOString(),row={schema:'musitu.axiom.operator-policy.browser.v1',org_id:orgId,version:preview.version,policy:preview.policy,preview_sha256:preview.preview_sha256,applied_by:actorId,applied_at:now,control_plane_mode:CONTROL_PLANE_MODE,production_enforcement_claimed:false};row.policy_sha256=await sha256({org_id:row.org_id,version:row.version,policy:row.policy,preview_sha256:row.preview_sha256,applied_by:row.applied_by,applied_at:row.applied_at,control_plane_mode:row.control_plane_mode,production_enforcement_claimed:false});await this._put('policies',row);await this._event(orgId,'policy.applied_local_preview',actorId,{policy_sha256:row.policy_sha256,preview_sha256:row.preview_sha256,version:row.version});await this._receipt(orgId,'POLICY_APPLY_LOCAL_PREVIEW',actorId,{policy_sha256:row.policy_sha256,preview_sha256:row.preview_sha256});return clone(row);});}
 async currentPolicy(orgId){return this._get('policies',clean(orgId,180));}
 async posture(orgId,actorId,{projectId}={}){orgId=required(orgId,'org id',180);actorId=required(actorId,'actor',180);projectId=required(projectId,'project id',180);await this.authorize(orgId,actorId,'analysis.read');const agents=await this.agents.store.listAgents(projectId),automations=await this.agents.store.listAutomations(projectId),health=await this.observability.store.operatorHealth(),agentIntegrity=await this.agents.store.verify(),observabilityIntegrity=await this.observability.store.verify(),policy=(await this.currentPolicy(orgId))?.policy||{failure_rate_slo:1,max_active_agents:1000,max_local_compute_units:1000000,incident_escalation_required:true},activeAgents=agents.filter(row=>row.status==='ACTIVE'&&!row.kill_switch_engaged),computeUnits=agents.reduce((sum,row)=>sum+Number(row.usage?.compute_units||0),0),breaches=[];if(health.failure_rate>policy.failure_rate_slo)breaches.push('FAILURE_RATE_SLO');if(activeAgents.length>policy.max_active_agents)breaches.push('ACTIVE_AGENT_LIMIT');if(computeUnits>policy.max_local_compute_units)breaches.push('LOCAL_COMPUTE_LIMIT');if(agentIntegrity.status!=='PASS')breaches.push('AGENT_INTEGRITY');if(observabilityIntegrity.status!=='PASS')breaches.push('OBSERVABILITY_INTEGRITY');return {schema:'musitu.axiom.operator-posture.browser.v1',status:breaches.length?'ATTENTION':'PASS',org_id:orgId,project_id:projectId,active_agent_count:activeAgents.length,total_agent_count:agents.length,automation_count:automations.length,local_compute_units:computeUnits,observability_health:health,agent_integrity:agentIntegrity.status,observability_integrity:observabilityIntegrity.status,policy,breaches,network_policy:NETWORK_POLICY,control_plane_mode:CONTROL_PLANE_MODE,production_identity_mutation_claimed:false,production_billing_claimed:false,cloud_control_plane_claimed:false,external_action_execution_claimed:false,hidden_reasoning_recorded:false};}
 async verify(orgId){orgId=required(orgId,'org id',180);const org=await this.getOrganization(orgId);if(!org)return {status:'FAIL',errors:['organization_missing']};const errors=[],events=(await this._all('events','org_id',orgId)).sort((a,b)=>a.sequence-b.sequence);let previous=null;for(let i=0;i<events.length;i++){const row=events[i],body=Object.fromEntries(Object.entries(row).filter(([key])=>key!=='event_sha256'));if(row.sequence!==i||row.previous_event_sha256!==previous)errors.push(`event_chain:${i}`);if(await sha256(body)!==row.event_sha256)errors.push(`event_hash:${i}`);previous=row.event_sha256;}for(const member of await this.listMembers(orgId))if(await sha256(memberBody(member))!==member.member_sha256)errors.push(`member_hash:${member.principal_id}`);for(const receipt of await this.listReceipts(orgId)){const body=Object.fromEntries(Object.entries(receipt).filter(([key])=>key!=='receipt_sha256'));if(await sha256(body)!==receipt.receipt_sha256)errors.push(`receipt_hash:${receipt.receipt_id}`);}return {schema:'musitu.axiom.operator-integrity.browser.v1',status:errors.length?'FAIL':'PASS',errors:[...new Set(errors)].sort(),event_count:events.length,network_policy:NETWORK_POLICY,hidden_reasoning_policy:HIDDEN_REASONING_POLICY};}
}
