const DB='musitu-axiom-outcome-runs-v1';
const VERSION=1;
const BOUNDARY='LOCAL_BROWSER_DURABLE_SIMULATION_NO_EXTERNAL_CONSEQUENTIAL_ACTIONS';
const clone=v=>structuredClone(v);
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const uid=p=>`${p}_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;

class OutcomeRunStore{
  constructor(db){this.db=db;}
  static async open(){const r=indexedDB.open(DB,VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('runs')){const s=db.createObjectStore('runs',{keyPath:'run_id'});s.createIndex('contract_id','contract_id',{unique:true});}};return new OutcomeRunStore(await req(r));}
  async byContract(contractId){const tx=this.db.transaction('runs','readonly');const row=await req(tx.objectStore('runs').index('contract_id').get(contractId));await done(tx);return row?clone(row):null;}
  async get(runId){const tx=this.db.transaction('runs','readonly');const row=await req(tx.objectStore('runs').get(runId));await done(tx);if(!row)throw new DOMException('outcome run not found','NotFoundError');return clone(row);}
  async put(row){const tx=this.db.transaction('runs','readwrite');tx.objectStore('runs').put(clone(row));await done(tx);return clone(row);}
  async start(contract,approval){if(!approval)throw new DOMException('approval receipt required before execution','NotAllowedError');const existing=await this.byContract(contract.contract_id);if(existing)return existing;const now=new Date().toISOString();return this.put({schema:'musitu.axiom.outcome-run.browser.v1',run_id:uid('run'),contract_id:contract.contract_id,contract_sha256:contract.contract_sha256,status:'BACKGROUND_READY',plan:[{id:'prepare',status:'PENDING'},{id:'execute',status:'PENDING'},{id:'accept',status:'PENDING'}],checkpoints:[],approval_receipt_id:approval.receipt_id,acceptance_attempts:[],execution_boundary:BOUNDARY,created_at:now,updated_at:now});}
  async advance(runId){const row=await this.get(runId);if(!row.approval_receipt_id)throw new DOMException('approval receipt required','NotAllowedError');const now=new Date().toISOString();if(!row.checkpoints.some(x=>x.step==='PREPARED')){row.plan.find(x=>x.id==='prepare').status='COMPLETED';row.checkpoints.push({sequence:row.checkpoints.length,step:'PREPARED',created_at:now});row.status='RUNNING';}else if(!row.checkpoints.some(x=>x.step==='EXECUTION_COMPLETE')){row.plan.find(x=>x.id==='execute').status='COMPLETED';row.checkpoints.push({sequence:row.checkpoints.length,step:'EXECUTION_COMPLETE',created_at:now});row.status='AWAITING_ACCEPTANCE';}row.updated_at=now;return this.put(row);}
  async acceptance(runId,results,evidence='browser-local acceptance evidence'){const row=await this.get(runId);if(!['AWAITING_ACCEPTANCE','ACCEPTANCE_FAILED'].includes(row.status))throw new DOMException('run is not awaiting acceptance','InvalidStateError');const accepted=results.length>0&&results.every(Boolean);const attempt={attempt_id:uid('accept'),accepted,results:[...results],evidence:String(evidence).slice(0,500),created_at:new Date().toISOString()};row.acceptance_attempts.push(attempt);if(accepted){row.plan.find(x=>x.id==='accept').status='COMPLETED';row.status='SUCCEEDED';}else row.status='ACCEPTANCE_FAILED';row.updated_at=attempt.created_at;await this.put(row);return clone(attempt);}
}

function markup(){return `<section id="outcome-run-space" class="outcome-card outcome-run-space" aria-labelledby="outcome-run-title"><div class="section-heading"><div><span class="eyebrow">Durable execution</span><h3 id="outcome-run-title">Plan, checkpoints &amp; acceptance</h3></div><span id="outcome-run-state" class="status-pill neutral">No run</span></div><p class="boundary-note">Browser-local execution evidence can resume after reload. It does not claim cloud scheduling, multi-device continuity, or external consequential actions.</p><label>Approved contract<select id="outcome-run-contract"><option value="">Choose approved contract</option></select></label><div class="outcome-actions"><button class="button primary" id="outcome-start-run" type="button">Start / resume run</button><button class="button secondary" id="outcome-advance-run" type="button" disabled>Advance checkpoint</button></div><ol id="outcome-plan" class="outcome-plan" aria-label="Execution plan"></ol><div id="outcome-checkpoints" class="outcome-checkpoints" aria-live="polite"></div><form id="outcome-acceptance-form" class="outcome-acceptance" hidden><h4>Acceptance test</h4><div id="outcome-acceptance-criteria"></div><label>Evidence summary<input id="outcome-acceptance-evidence" value="browser-local verification"></label><button class="button primary" type="submit">Record acceptance</button></form></section>`;}

export async function initOutcomeExecutionWorkspace({emit=()=>{},projects,outcomes}={}){if(!projects?.store||!outcomes?.store)throw new TypeError('qualified Project and Outcome Contract substrates are required');const parent=document.querySelector('#outcome-contract-space .outcome-layout');if(!parent)return null;const style=document.createElement('link');style.rel='stylesheet';style.href='./styles/outcome_execution.css';document.head.append(style);parent.insertAdjacentHTML('afterend',markup());const store=await OutcomeRunStore.open();let current='';
  async function refreshContracts(){const sel=document.querySelector('#outcome-run-contract');const projectId=document.querySelector('#outcome-project')?.value||projects.getCurrentProjectId?.()||'';const rows=projectId?await outcomes.store.list(projectId):[];const preferred=sel.value;sel.replaceChildren(new Option('Choose approved contract',''));for(const c of rows){if(await outcomes.store.approval(projects,c.contract_id))sel.add(new Option(`${c.title} · ${c.contract_id}`,c.contract_id));}if(preferred&&[...sel.options].some(o=>o.value===preferred))sel.value=preferred;await render();}
  async function render(){const sel=document.querySelector('#outcome-run-contract');const contractId=sel.value;const state=document.querySelector('#outcome-run-state'),plan=document.querySelector('#outcome-plan'),cps=document.querySelector('#outcome-checkpoints'),advance=document.querySelector('#outcome-advance-run'),form=document.querySelector('#outcome-acceptance-form');plan.replaceChildren();cps.replaceChildren();form.hidden=true;advance.disabled=true;if(!contractId){state.textContent='No run';return;}const run=await store.byContract(contractId);if(!run){state.textContent='Approved · not started';return;}current=run.run_id;state.textContent=run.status.replaceAll('_',' ');for(const n of run.plan){const li=document.createElement('li');li.textContent=`${n.id} · ${n.status}`;plan.append(li);}for(const cp of run.checkpoints){const p=document.createElement('p');p.textContent=`Checkpoint ${cp.sequence+1} · ${cp.step} · ${new Date(cp.created_at).toLocaleString()}`;cps.append(p);}advance.disabled=!['BACKGROUND_READY','RUNNING'].includes(run.status);if(['AWAITING_ACCEPTANCE','ACCEPTANCE_FAILED'].includes(run.status)){form.hidden=false;const criteria=document.querySelector('#outcome-acceptance-criteria');criteria.replaceChildren();const contract=await outcomes.store.get(contractId);contract.success_criteria.forEach((text,i)=>{const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';input.dataset.criterion=String(i);label.append(input,document.createTextNode(` ${text}`));criteria.append(label);});}emit('outcome.run.render',{state:run.status});}
  document.querySelector('#outcome-start-run').addEventListener('click',async()=>{try{const contractId=document.querySelector('#outcome-run-contract').value;if(!contractId)throw new TypeError('choose an approved contract');const contract=await outcomes.store.get(contractId);const approval=await outcomes.store.approval(projects,contractId);const run=await store.start(contract,approval);current=run.run_id;emit('outcome.run.started',{state:'background-ready'});await render();}catch(error){window.AxiomUI?.reportError?.({errorId:'AXIOM-OUTCOME-RUN',component:'Outcome execution',impact:'Run not started',failed:error.message,recovery:'Choose an approved contract and retry'});}});
  document.querySelector('#outcome-advance-run').addEventListener('click',async()=>{try{if(!current)throw new TypeError('start or resume a run first');const run=await store.advance(current);emit('outcome.checkpoint',{state:run.status});await render();}catch(error){window.AxiomUI?.reportError?.({errorId:'AXIOM-OUTCOME-CHECKPOINT',component:'Outcome execution',impact:'Checkpoint not advanced',failed:error.message,recovery:'Inspect approval and durable run state, then retry'});}});
  document.querySelector('#outcome-acceptance-form').addEventListener('submit',async e=>{e.preventDefault();try{if(!current)throw new TypeError('no active run');const results=[...document.querySelectorAll('#outcome-acceptance-criteria input')].map(x=>x.checked);const attempt=await store.acceptance(current,results,document.querySelector('#outcome-acceptance-evidence').value);emit('outcome.acceptance',{state:attempt.accepted?'accepted':'failed'});await render();}catch(error){window.AxiomUI?.reportError?.({errorId:'AXIOM-OUTCOME-ACCEPT',component:'Outcome execution',impact:'Acceptance not recorded',failed:error.message,recovery:'Verify every acceptance criterion and retry'});}});
  document.querySelector('#outcome-run-contract').addEventListener('change',async()=>{current='';await render();});document.querySelector('#outcome-refresh').addEventListener('click',refreshContracts);document.querySelector('#outcome-project').addEventListener('change',refreshContracts);await refreshContracts();const api={store,refresh:refreshContracts,getCurrentRunId:()=>current};window.AxiomOutcomeRuns=Object.freeze(api);return api;}
