const DB_NAME = 'musitu-axiom-projects-v1';
const DB_VERSION = 1;
const STORES = ['projects', 'objects', 'edges', 'events'];
const OBJECT_TYPES = new Set(['conversation','source','artifact','task','memory','agent','decision','evaluation','deployment','failure']);
const MEMORY_SCOPES = new Set(['private','project-only','organization-wide','temporary','permanent','do-not-use']);
const ROLES = new Set(['owner','editor','viewer']);

const now = () => new Date().toISOString();
const uid = (prefix) => `${prefix}_${crypto.randomUUID?.() || `${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
const clean = (value, max=500) => String(value ?? '').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,max);
const clone = (value) => structuredClone(value);

function canonical(value) {
  if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
  if (value && typeof value === 'object') return `{${Object.keys(value).sort().map(k => `${JSON.stringify(k)}:${canonical(value[k])}`).join(',')}}`;
  return JSON.stringify(value);
}
async function sha256(value) {
  const bytes = new TextEncoder().encode(typeof value === 'string' ? value : canonical(value));
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('');
}
function requestResult(request) { return new Promise((resolve,reject)=>{ request.onsuccess=()=>resolve(request.result); request.onerror=()=>reject(request.error); }); }
function txDone(tx) { return new Promise((resolve,reject)=>{ tx.oncomplete=()=>resolve(); tx.onerror=()=>reject(tx.error); tx.onabort=()=>reject(tx.error || new Error('transaction aborted')); }); }

export class ProjectStore {
  constructor(db) { this.db = db; }
  static open() {
    return new Promise((resolve,reject)=>{
      const request=indexedDB.open(DB_NAME,DB_VERSION);
      request.onupgradeneeded=()=>{
        const db=request.result;
        if(!db.objectStoreNames.contains('projects')) db.createObjectStore('projects',{keyPath:'project_id'});
        if(!db.objectStoreNames.contains('objects')) { const s=db.createObjectStore('objects',{keyPath:'object_id'}); s.createIndex('project_id','project_id',{unique:false}); s.createIndex('project_type',['project_id','type'],{unique:false}); }
        if(!db.objectStoreNames.contains('edges')) { const s=db.createObjectStore('edges',{keyPath:'edge_id'}); s.createIndex('project_id','project_id',{unique:false}); }
        if(!db.objectStoreNames.contains('events')) { const s=db.createObjectStore('events',{keyPath:'event_id'}); s.createIndex('project_id','project_id',{unique:false}); }
      };
      request.onsuccess=()=>resolve(new ProjectStore(request.result)); request.onerror=()=>reject(request.error);
    });
  }
  close(){ this.db.close(); }
  async _all(store,index=null,key=null){ const tx=this.db.transaction(store,'readonly'); const source=index?tx.objectStore(store).index(index):tx.objectStore(store); const result=await requestResult(key===null?source.getAll():source.getAll(key)); await txDone(tx); return result; }
  async listProjects(){ return (await this._all('projects')).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)); }
  async getProject(projectId){ const tx=this.db.transaction('projects','readonly'); const row=await requestResult(tx.objectStore('projects').get(projectId)); await txDone(tx); return row || null; }
  async graph(projectId){ const project=await this.getProject(projectId); if(!project) throw new Error('project not found'); const [objects,edges,events]=await Promise.all([this._all('objects','project_id',projectId),this._all('edges','project_id',projectId),this._all('events','project_id',projectId)]); return {project,objects:objects.sort((a,b)=>a.created_at.localeCompare(b.created_at)),edges:edges.sort((a,b)=>a.created_at.localeCompare(b.created_at)),events:events.sort((a,b)=>a.sequence-b.sequence)}; }
  async _eventBody(projectId,actorId,type,payload,prior){ const created_at=now(); const body={project_id:projectId,actor_id:actorId,sequence:prior?prior.sequence+1:0,event_type:type,payload:clone(payload),previous_sha256:prior?.event_sha256 || null,created_at,schema_version:'musitu.axiom.project.event.v1'}; return {...body,event_id:uid('pevt'),event_sha256:await sha256(body)}; }
  async createProject({name,goal='',ownerId='local-user',memoryScope='project-only',permissions=null,source='user'}={}){
    name=clean(name,120); goal=clean(goal,2000); ownerId=clean(ownerId,120); source=clean(source,180); if(!name||!ownerId||!source) throw new TypeError('name, ownerId and source are required'); if(!MEMORY_SCOPES.has(memoryScope)) throw new TypeError('invalid memory scope'); const created_at=now(); const project_id=uid('prj'); const permissionList=permissions || [{principal_id:ownerId,role:'owner'}]; this._validatePermissions(permissionList,ownerId); const project={schema:'musitu.axiom.project.v1',project_id,name,goal,owner_id:ownerId,created_at,updated_at:created_at,revision:0,memory_scope:memoryScope,permissions:clone(permissionList),provenance:{source,actor_id:ownerId,created_at},version_history:[{revision:0,actor_id:ownerId,at:created_at,change:'project.created'}],evidence_links:[],persistence_scope:'browser-local-device'}; const event=await this._eventBody(project_id,ownerId,'project.created',{revision:0,source,memory_scope:memoryScope},null); const tx=this.db.transaction(['projects','events'],'readwrite'); tx.objectStore('projects').add(project); tx.objectStore('events').add(event); await txDone(tx); return clone(project);
  }
  _validatePermissions(list,ownerId){ if(!Array.isArray(list)||!list.length) throw new TypeError('permissions required'); const seen=new Set(); let owns=false; for(const p of list){ const principal=clean(p.principal_id,120); if(!principal||seen.has(principal)||!ROLES.has(p.role)) throw new TypeError('invalid permissions'); seen.add(principal); if(principal===ownerId&&p.role==='owner') owns=true; } if(!owns) throw new TypeError('owner permission is required'); }
  _authorize(project,actorId,write=false){ const grant=project.permissions.find(p=>p.principal_id===actorId); if(!grant || (write && !['owner','editor'].includes(grant.role))) throw new DOMException('project permission denied','NotAllowedError'); return grant; }
  async updateProject(projectId,actorId,patch,expectedRevision){ const current=await this.getProject(projectId); if(!current) throw new Error('project not found'); this._authorize(current,actorId,true); if(current.revision!==expectedRevision) throw new DOMException('project revision conflict','InvalidStateError'); const allowed={}; if('name' in patch){allowed.name=clean(patch.name,120);if(!allowed.name)throw new TypeError('name required');} if('goal' in patch)allowed.goal=clean(patch.goal,2000); if('memory_scope' in patch){if(!MEMORY_SCOPES.has(patch.memory_scope))throw new TypeError('invalid memory scope');allowed.memory_scope=patch.memory_scope;} if('permissions' in patch){this._validatePermissions(patch.permissions,current.owner_id);allowed.permissions=clone(patch.permissions);} const updated_at=now(); const next={...current,...allowed,updated_at,revision:current.revision+1,version_history:[...current.version_history,{revision:current.revision+1,actor_id:actorId,at:updated_at,change:'project.updated',fields:Object.keys(allowed)}]}; const events=await this._all('events','project_id',projectId); const event=await this._eventBody(projectId,actorId,'project.updated',{revision:next.revision,fields:Object.keys(allowed)},events.sort((a,b)=>b.sequence-a.sequence)[0]); const tx=this.db.transaction(['projects','events'],'readwrite'); tx.objectStore('projects').put(next); tx.objectStore('events').add(event); await txDone(tx); return clone(next); }
  async addObject(projectId,actorId,{type,title,provenanceSource='user',evidenceLinks=[]}={}){ const project=await this.getProject(projectId); if(!project)throw new Error('project not found'); this._authorize(project,actorId,true); if(!OBJECT_TYPES.has(type))throw new TypeError('invalid object type'); title=clean(title,180); provenanceSource=clean(provenanceSource,180); if(!title||!provenanceSource)throw new TypeError('title and provenanceSource required'); const created_at=now(); const object={schema:'musitu.axiom.project.object.v1',object_id:uid('obj'),project_id:projectId,type,title,owner_id:actorId,created_at,updated_at:created_at,permissions:clone(project.permissions),provenance:{source:provenanceSource,actor_id:actorId,created_at},version_history:[{revision:0,actor_id:actorId,at:created_at,change:'object.created'}],evidence_links:[...new Set(evidenceLinks.map(x=>clean(x,200)).filter(Boolean))]}; const events=await this._all('events','project_id',projectId); const event=await this._eventBody(projectId,actorId,'object.created',{object_id:object.object_id,type,provenance_source:provenanceSource},events.sort((a,b)=>b.sequence-a.sequence)[0]); const next={...project,updated_at:created_at,revision:project.revision+1,version_history:[...project.version_history,{revision:project.revision+1,actor_id:actorId,at:created_at,change:'object.created',object_id:object.object_id}]}; const tx=this.db.transaction(['projects','objects','events'],'readwrite'); tx.objectStore('projects').put(next); tx.objectStore('objects').add(object); tx.objectStore('events').add(event); await txDone(tx); return clone(object); }
  async addEdge(projectId,actorId,{fromId,toId,relation='references',provenanceSource='user'}={}){ const graph=await this.graph(projectId); this._authorize(graph.project,actorId,true); fromId=clean(fromId,150);toId=clean(toId,150);relation=clean(relation,80);provenanceSource=clean(provenanceSource,180); const ids=new Set(graph.objects.map(x=>x.object_id)); if(!ids.has(fromId)||!ids.has(toId)||fromId===toId)throw new TypeError('edge endpoints must be distinct project objects'); if(!relation||!provenanceSource)throw new TypeError('relation and provenance source required'); const created_at=now(); const edge={schema:'musitu.axiom.project.edge.v1',edge_id:uid('edge'),project_id:projectId,from_id:fromId,to_id:toId,relation,created_at,actor_id:actorId,provenance:{source:provenanceSource,actor_id:actorId,created_at}}; const prior=graph.events.at(-1)||null; const event=await this._eventBody(projectId,actorId,'edge.created',{edge_id:edge.edge_id,from_id:fromId,to_id:toId,relation},prior); const next={...graph.project,updated_at:created_at,revision:graph.project.revision+1,version_history:[...graph.project.version_history,{revision:graph.project.revision+1,actor_id:actorId,at:created_at,change:'edge.created',edge_id:edge.edge_id}]}; const tx=this.db.transaction(['projects','edges','events'],'readwrite');tx.objectStore('projects').put(next);tx.objectStore('edges').add(edge);tx.objectStore('events').add(event);await txDone(tx);return clone(edge); }
  async verifyEventChain(projectId){ const events=(await this._all('events','project_id',projectId)).sort((a,b)=>a.sequence-b.sequence); let previous=null; for(let i=0;i<events.length;i++){const e=events[i];if(e.sequence!==i||e.previous_sha256!==previous)return false;const body={project_id:e.project_id,actor_id:e.actor_id,sequence:e.sequence,event_type:e.event_type,payload:e.payload,previous_sha256:e.previous_sha256,created_at:e.created_at,schema_version:e.schema_version};if(await sha256(body)!==e.event_sha256)return false;previous=e.event_sha256;}return true; }
  async destroyForTests(){ this.close(); await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);r.onblocked=()=>reject(new Error('database deletion blocked'));}); }
}

function projectMarkup(){ return `<section id="project-space" class="project-space" aria-labelledby="project-space-title" hidden>
  <div class="section-heading"><div><span class="eyebrow">Persistent intelligence graph</span><h2 id="project-space-title">Projects</h2></div><span class="status-pill neutral" id="project-persistence">Local device</span></div>
  <p class="boundary-note">Phase 2 stores this graph in this browser using IndexedDB. It proves cross-session persistence on this device; it does not claim cloud or multi-device sync.</p>
  <div class="project-grid">
    <section class="project-card" aria-labelledby="project-create-title"><h3 id="project-create-title">Create project</h3><form id="project-create-form"><label>Name<input id="project-name" required maxlength="120"></label><label>Goal<textarea id="project-goal" rows="3" maxlength="2000"></textarea></label><label>Memory scope<select id="project-memory"><option value="project-only">Project only</option><option value="private">Private</option><option value="temporary">Temporary</option><option value="permanent">Permanent</option><option value="do-not-use">Do not use</option></select></label><button class="button primary" type="submit">Create project</button></form></section>
    <section class="project-card" aria-labelledby="project-list-title"><h3 id="project-list-title">Project home</h3><label>Select project<select id="project-select"><option value="">No project yet</option></select></label><div id="project-summary" class="project-summary" role="status" aria-live="polite"></div></section>
  </div>
  <div id="project-controls" hidden>
    <div class="project-grid">
      <section class="project-card" aria-labelledby="object-title"><h3 id="object-title">Add linked object</h3><form id="object-form"><label>Type<select id="object-type"><option>conversation</option><option>source</option><option>artifact</option><option>task</option><option>memory</option><option>agent</option><option>decision</option></select></label><label>Title<input id="object-name" required maxlength="180"></label><label>Provenance source<input id="object-source" value="user" required maxlength="180"></label><button class="button secondary" type="submit">Add object</button></form></section>
      <section class="project-card" aria-labelledby="link-title"><h3 id="link-title">Link objects</h3><form id="edge-form"><label>From<select id="edge-from"></select></label><label>Relation<input id="edge-relation" value="references" required maxlength="80"></label><label>To<select id="edge-to"></select></label><button class="button secondary" type="submit">Create link</button></form></section>
    </div>
    <section class="project-card graph-card" aria-labelledby="graph-title"><div class="section-heading"><div><h3 id="graph-title">Project graph</h3><span id="project-chain-state" class="eyebrow">Provenance chain pending</span></div><button id="project-refresh" class="button secondary" type="button">Refresh</button></div><div id="project-graph" class="project-object-list"></div></section>
  </div>
</section>`; }

export async function initProjectWorkspace({emit=()=>{}}={}){
  const workspace=document.querySelector('#main-workspace'); if(!workspace) return null; workspace.insertAdjacentHTML('beforeend',projectMarkup());
  const space=document.querySelector('#project-space'); const hero=document.querySelector('.hero-card'); const run=document.querySelector('.run-stage'); const store=await ProjectStore.open(); const actor='local-user'; let current='';
  async function refreshList(preferred=current){ const rows=await store.listProjects(); const select=document.querySelector('#project-select'); select.replaceChildren(new Option('No project yet','')); for(const p of rows)select.add(new Option(`${p.name} · r${p.revision}`,p.project_id)); if(preferred&&rows.some(p=>p.project_id===preferred)){select.value=preferred;current=preferred;}else{current=select.value;} await render(); }
  async function render(){ const controls=document.querySelector('#project-controls'); const summary=document.querySelector('#project-summary'); if(!current){controls.hidden=true;summary.textContent='Create a project to start a persistent graph.';return;} const graph=await store.graph(current); controls.hidden=false; summary.replaceChildren(); const dl=document.createElement('dl');dl.className='project-meta';for(const [k,v] of [['Project ID',graph.project.project_id],['Owner',graph.project.owner_id],['Revision',String(graph.project.revision)],['Memory scope',graph.project.memory_scope],['Persistence','Browser-local device'],['Objects',String(graph.objects.length)],['Links',String(graph.edges.length)]]){const d=document.createElement('div');const dt=document.createElement('dt');dt.textContent=k;const dd=document.createElement('dd');dd.textContent=v;d.append(dt,dd);dl.append(d);}summary.append(dl); const list=document.querySelector('#project-graph');list.replaceChildren(); for(const obj of graph.objects){const article=document.createElement('article');article.className='project-object';const h=document.createElement('h4');h.textContent=obj.title;const meta=document.createElement('p');meta.textContent=`${obj.type} · ${obj.object_id} · provenance: ${obj.provenance.source}`;const links=graph.edges.filter(e=>e.from_id===obj.object_id||e.to_id===obj.object_id);const rel=document.createElement('span');rel.textContent=links.length?`${links.length} linked relation${links.length===1?'':'s'}`:'No links yet';article.append(h,meta,rel);list.append(article);} if(!graph.objects.length){const p=document.createElement('p');p.className='proof-empty';p.textContent='No project objects yet.';list.append(p);} for(const id of ['edge-from','edge-to']){const s=document.querySelector(`#${id}`);s.replaceChildren();for(const obj of graph.objects)s.add(new Option(`${obj.type}: ${obj.title}`,obj.object_id));} const ok=await store.verifyEventChain(current);document.querySelector('#project-chain-state').textContent=ok?`Provenance chain verified · ${graph.events.length} events`:'Provenance chain FAILED';document.querySelector('.rail-header strong').textContent=graph.project.name; emit('project.render',{state:ok?'verified':'invalid'}); }
  function route(){ const on=/^#\/(projects|project(?:\/|$))/.test(location.hash);space.hidden=!on;if(hero)hero.hidden=on;if(run)run.hidden=on;if(on){document.querySelector('#workspace-title').textContent='Projects';document.querySelector('#workspace-description').textContent='Persistent browser-local intelligence graphs with stable identity, permissions, provenance and version history.';refreshList().catch(error=>window.AxiomUI?.reportError?.({errorId:'AXIOM-PROJECT-READ',component:'Projects',impact:'Project graph unavailable',failed:error.message,recovery:'Reload and retry'}));}}
  document.querySelector('#project-create-form').addEventListener('submit',async e=>{e.preventDefault();try{const p=await store.createProject({name:document.querySelector('#project-name').value,goal:document.querySelector('#project-goal').value,ownerId:actor,memoryScope:document.querySelector('#project-memory').value,source:'user'});current=p.project_id;e.target.reset();emit('project.created',{state:'browser-local'});await refreshList(current);}catch(error){window.AxiomUI?.reportError?.({errorId:'AXIOM-PROJECT-CREATE',component:'Projects',impact:'Project not created',failed:error.message,recovery:'Correct project fields and retry'});}});
  document.querySelector('#project-select').addEventListener('change',async e=>{current=e.target.value;await render();});
  document.querySelector('#object-form').addEventListener('submit',async e=>{e.preventDefault();try{await store.addObject(current,actor,{type:document.querySelector('#object-type').value,title:document.querySelector('#object-name').value,provenanceSource:document.querySelector('#object-source').value});document.querySelector('#object-name').value='';emit('project.object.created',{state:'persisted'});await refreshList(current);}catch(error){window.AxiomUI?.reportError?.({errorId:'AXIOM-PROJECT-OBJECT',component:'Project graph',impact:'Object not added',failed:error.message,recovery:'Correct object fields and retry'});}});
  document.querySelector('#edge-form').addEventListener('submit',async e=>{e.preventDefault();try{await store.addEdge(current,actor,{fromId:document.querySelector('#edge-from').value,toId:document.querySelector('#edge-to').value,relation:document.querySelector('#edge-relation').value,provenanceSource:'user'});emit('project.edge.created',{state:'persisted'});await refreshList(current);}catch(error){window.AxiomUI?.reportError?.({errorId:'AXIOM-PROJECT-EDGE',component:'Project graph',impact:'Objects not linked',failed:error.message,recovery:'Choose two distinct project objects and retry'});}});
  document.querySelector('#project-refresh').addEventListener('click',()=>refreshList(current)); window.addEventListener('hashchange',route); await refreshList(); route();
  const api={store,getCurrentProjectId:()=>current,selectProject:async id=>{current=id;await refreshList(id);},refresh:()=>refreshList(current)}; window.AxiomProjects=Object.freeze(api); return api;
}
