export const INSTALLABILITY_SCOPE='STANDALONE_PWA_SHELL_INSTALLABILITY_NO_APP_STORE_OR_NATIVE_BINARY_CLAIM';
export const OFFLINE_POLICY='CACHED_SHELL_AND_BROWSER_LOCAL_PROJECT_ACCESS';
export const QUEUE_POLICY='ALLOWLISTED_LOCAL_ACTIONS_ONLY_NO_EXTERNAL_SIDE_EFFECTS';
export const REPLAY_POLICY='EXACT_ACTION_SHA256_IDEMPOTENT_RECONNECT_REPLAY';
export const MATRIX_SCOPE='BROWSER_EMULATED_MID_TIER_AND_CONSTRAINED_NETWORK_CANDIDATE_ONLY';
export const QUALIFICATION_BOUNDARY='AUTHENTICATED_REAL_MID_TIER_DEVICE_MATRIX_REQUIRED_FOR_PHASE14_SEAL';
export const SAFE_ACTION_KINDS=Object.freeze(['LOCAL_PROJECT_REFRESH','LOCAL_DRAFT_CHECKPOINT','LOCAL_EVIDENCE_SNAPSHOT']);
const HEX64=/^[0-9a-f]{64}$/;
const SECRET_RX=/(?:api[_ -]?key|access[_ -]?token|refresh[_ -]?token|password|private[_ -]?key|authorization)\s*[:=]|\b(?:sk|ghp|github_pat)_[A-Za-z0-9_-]{12,}|\bbearer\s+[A-Za-z0-9._~-]{12,}/i;
export const clean=(value,limit=500)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,'').trim().slice(0,limit);
export function required(value,label,limit=500){const out=clean(value,limit);if(!out)throw new TypeError(`${label} required`);return out;}
export function rejectSecretLike(value,label='value'){if(SECRET_RX.test(JSON.stringify(value)))throw new DOMException(`${label} contains secret-like material`,'SecurityError');}
export const canonical=value=>Array.isArray(value)?`[${value.map(canonical).join(',')}]`:value&&typeof value==='object'?`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`:JSON.stringify(value);
export async function sha256(value){const bytes=new TextEncoder().encode(canonical(value)),hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(byte=>byte.toString(16).padStart(2,'0')).join('');}
export function normalizeQueuedAction(raw={}){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new TypeError('offline queue action must be an object');const kind=required(raw.kind,'action kind',80).toUpperCase();if(!SAFE_ACTION_KINDS.includes(kind))throw new DOMException('offline queue action is not allow-listed','SecurityError');const payload=raw.payload;if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new TypeError('offline queue payload must be an object');const allowed={LOCAL_PROJECT_REFRESH:['projectId','reason'],LOCAL_DRAFT_CHECKPOINT:['projectId','draftSha256','reason'],LOCAL_EVIDENCE_SNAPSHOT:['reason']}[kind];if(Object.keys(payload).some(key=>!allowed.includes(key)))throw new DOMException('offline queue payload contains unsupported fields','SecurityError');rejectSecretLike(payload,'offline queue payload');const normalized={reason:required(payload.reason,'action reason',300)};if(kind!=='LOCAL_EVIDENCE_SNAPSHOT')normalized.project_id=required(payload.projectId,'project id',180);if(kind==='LOCAL_DRAFT_CHECKPOINT'){const digest=required(payload.draftSha256,'draft digest',64).toLowerCase();if(!HEX64.test(digest))throw new TypeError('draft digest must be lowercase SHA-256');normalized.draft_sha256=digest;}return {kind,payload:normalized};}
export function assessNetwork({online=true,effectiveType='',saveData=false,downlink=null}={}){if(!online)return 'offline';const type=clean(effectiveType,20).toLowerCase(),speed=typeof downlink==='number'&&Number.isFinite(downlink)?downlink:null;if(Boolean(saveData)||['slow-2g','2g','3g'].includes(type)||(speed!==null&&speed<=1))return 'constrained';return 'standard';}
export function deviceDescriptor({width,height,deviceMemory=null,hardwareConcurrency=null}={}){const w=Number(width),h=Number(height);if(!Number.isFinite(w)||!Number.isFinite(h)||w<280||h<400)throw new TypeError('valid viewport required');return {schema:'musitu.axiom.pwa-device-descriptor.browser.v1',viewport_width:w,viewport_height:h,form_factor:w<=520?'mobile':w<=900?'tablet':'desktop',device_memory_gb:typeof deviceMemory==='number'?deviceMemory:null,hardware_concurrency:Number.isInteger(hardwareConcurrency)?hardwareConcurrency:null,measurement_scope:MATRIX_SCOPE,real_device_certification_claimed:false};}
