import {QUEUE_POLICY,REPLAY_POLICY,normalizeQueuedAction,required,sha256} from './pwa_security.js';
const DB='musitu-axiom-pwa-queue-v1',VERSION=1;
const req=request=>new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
const clone=value=>structuredClone(value),without=(row,field)=>Object.fromEntries(Object.entries(row).filter(([key])=>key!==field));
export class PwaLocalQueue{
 constructor(db){this.db=db;this.serial=Promise.resolve();}
 static async open(){const request=indexedDB.open(DB,VERSION);request.onupgradeneeded=()=>{const db=request.result;for(const [name,key] of [['actions','action_id'],['events','event_id'],['receipts','receipt_id']])if(!db.objectStoreNames.contains(name)){const store=db.createObjectStore(name,{keyPath:key});if(name==='actions')store.createIndex('status','status',{unique:false});}};return new PwaLocalQueue(await req(request));}
 close(){this.db.close();}
 _queue(task){const next=this.serial.then(task,task);this.serial=next.catch(()=>{});return next;}
 async _get(store,key){const tx=this.db.transaction(store,'readonly'),row=await req(tx.objectStore(store).get(key));await done(tx);return row?clone(row):null;}
 async _all(store){const tx=this.db.transaction(store,'readonly'),rows=await req(tx.objectStore(store).getAll());await done(tx);return rows.map(clone);}
 async _add(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).add(clone(row));await done(tx);return clone(row);}
 async _put(store,row){const tx=this.db.transaction(store,'readwrite');tx.objectStore(store).put(clone(row));await done(tx);return clone(row);}
 async listActions(){return (await this._all('actions')).sort((a,b)=>a.queued_at.localeCompare(b.queued_at));}
 async listEvents(){return (await this._all('events')).sort((a,b)=>a.sequence-b.sequence);}
 async listReceipts(){return (await this._all('receipts')).sort((a,b)=>a.completed_at.localeCompare(b.completed_at));}
 async _event(kind,payload){const events=await this.listEvents(),body={schema:'musitu.axiom.pwa-queue-event.browser.v1',event_id:`pwa-event:${events.length}`,sequence:events.length,kind:required(kind,'event kind',100),payload:clone(payload),created_at:new Date().toISOString(),previous_event_sha256:events.at(-1)?.event_sha256||null},row={...body,event_sha256:await sha256(body)};return this._add('events',row);}
 async prepare(raw={}){const normalized=normalizeQueuedAction(raw),body={schema:'musitu.axiom.offline-action-preview.browser.v1',...normalized,queue_policy:QUEUE_POLICY,external_side_effect:false};return {...body,preview_sha256:await sha256(body)};}
 async enqueue(raw={},expectedPreviewSha256){return this._queue(async()=>{const preview=await this.prepare(raw);if(preview.preview_sha256!==expectedPreviewSha256)throw new DOMException('stale or altered offline action preview','SecurityError');const body={schema:'musitu.axiom.offline-action.browser.v1',action_id:`offline-action:${crypto.randomUUID()}`,kind:preview.kind,payload:preview.payload,preview_sha256:preview.preview_sha256,status:'QUEUED',attempt_count:0,queued_at:new Date().toISOString(),queue_policy:QUEUE_POLICY,replay_policy:REPLAY_POLICY,external_side_effect:false},row={...body,action_sha256:await sha256(body)};await this._add('actions',row);await this._event('ACTION_QUEUED',{action_id:row.action_id,action_sha256:row.action_sha256,kind:row.kind});return clone(row);});}
 async drain({online,handlers}){return this._queue(async()=>{if(!online)return {status:'DEFERRED_OFFLINE',completed:0,external_side_effect:false};const completed=[];for(const action of (await this.listActions()).filter(row=>row.status==='QUEUED'||row.status==='RETRY_LOCAL')){if(await sha256(without(action,'action_sha256'))!==action.action_sha256)throw new DOMException('queued action integrity failure','SecurityError');const handler=handlers?.[action.kind];if(typeof handler!=='function')throw new DOMException('allow-listed local replay handler required','SecurityError');try{const result=await handler(clone(action.payload)),previousSha=action.action_sha256;action.status='COMPLETED_LOCAL';action.attempt_count+=1;action.completed_at=new Date().toISOString();action.action_sha256=await sha256(without(action,'action_sha256'));await this._put('actions',action);const receiptBody={schema:'musitu.axiom.offline-action-local-replay-receipt.browser.v1',receipt_id:`pwa-receipt:${crypto.randomUUID()}`,action_id:action.action_id,queued_action_sha256:previousSha,completed_action_sha256:action.action_sha256,kind:action.kind,result_sha256:await sha256(result??{}),status:'COMPLETED_LOCAL_NO_EXTERNAL_SIDE_EFFECT',completed_at:action.completed_at,external_side_effect:false},receipt={...receiptBody,receipt_sha256:await sha256(receiptBody)};await this._add('receipts',receipt);await this._event('ACTION_REPLAYED_LOCAL',{action_id:action.action_id,receipt_sha256:receipt.receipt_sha256});completed.push(receipt);}catch(error){action.status='RETRY_LOCAL';action.attempt_count+=1;action.last_error_type=required(error?.name||'Error','error type',80);action.action_sha256=await sha256(without(action,'action_sha256'));await this._put('actions',action);await this._event('ACTION_RETRY_LOCAL',{action_id:action.action_id,error_type:action.last_error_type});}}return {status:'LOCAL_REPLAY_COMPLETE',completed:completed.length,receipt_sha256s:completed.map(row=>row.receipt_sha256),external_side_effect:false};});}
 async verify(){const errors=[];for(const row of await this.listActions()){if(await sha256(without(row,'action_sha256'))!==row.action_sha256)errors.push(`action_hash:${row.action_id}`);if(row.external_side_effect!==false)errors.push(`action_policy:${row.action_id}`);}for(const row of await this.listReceipts())if(await sha256(without(row,'receipt_sha256'))!==row.receipt_sha256||row.external_side_effect!==false)errors.push(`receipt_hash:${row.receipt_id}`);let previous=null;const events=await this.listEvents();for(let index=0;index<events.length;index++){const row=events[index];if(row.sequence!==index||row.previous_event_sha256!==previous||await sha256(without(row,'event_sha256'))!==row.event_sha256)errors.push(`event_chain:${index}`);previous=row.event_sha256;}return {schema:'musitu.axiom.pwa-queue-integrity.browser.v1',status:errors.length?'FAIL':'PASS',errors:[...new Set(errors)].sort(),action_count:(await this.listActions()).length,event_count:events.length,receipt_count:(await this.listReceipts()).length,queue_policy:QUEUE_POLICY};}
}
