const DB_NAME='musitu-axiom-research-v1';
const DB_VERSION=1;
const SOURCE_SCHEMA='musitu.axiom.research-source.v1';
const CLAIM_SCHEMA='musitu.axiom.research-claim.v1';
const CITATION_SCHEMA='musitu.axiom.research-citation.v1';
const WRITERS=new Set(['owner','editor']);
const STANCES=new Set(['supports','contradicts']);
const SOURCE_TYPES=new Set(['web','paper','document','dataset','filing','transcript']);
const TTL={web:3600,paper:2592000,document:604800,dataset:86400,filing:604800,transcript:604800};

const clone=v=>structuredClone(v);
const clean=(v,max=1000)=>String(v??'').replace(/[\u0000-\u001f\u007f]/g,' ').trim().slice(0,max);
const uid=p=>`${p}_${crypto.randomUUID?.()||`${Date.now()}_${Math.random().toString(16).slice(2)}`}`;
const canonical=v=>Array.isArray(v)?`[${v.map(canonical).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`:JSON.stringify(v);
async function sha(v){const bytes=new TextEncoder().encode(typeof v==='string'?v:canonical(v));const d=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('');}
const request=req=>new Promise((resolve,reject)=>{req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});
const done=tx=>new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('transaction aborted'));});
function authorize(project,actor){const role=project?.permissions?.find(x=>x.principal_id===actor)?.role;if(!WRITERS.has(role))throw new DOMException('project write permission required','NotAllowedError');return role;}
function timestamp(v,name){const text=clean(v,96);const t=Date.parse(text);if(!text||Number.isNaN(t)||!/([zZ]|[+-]\d\d:\d\d)$/.test(text))throw new TypeError(`${name} requires timezone-aware ISO timestamp`);return text;}
function domains(v){return clean(v,2000).split(',').map(x=>x.trim().toLowerCase().replace(/^\./,'')).filter(Boolean);}
function host(url){const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new TypeError('source URL must be http(s)');return u.hostname.toLowerCase().replace(/\.$/,'');}
const matches=(h,r)=>h===r||h.endsWith(`.${r}`);
function parseControls(form){return {allow_domains:domains(form.allowDomains),deny_domains:domains(form.denyDomains),source_types:[...form.sourceTypes],start_as_of:form.startAsOf||null,end_as_of:form.endAsOf||null};}
function enforceControls(controls,{url,source_type,as_of}){const h=host(url);if(controls.deny_domains.some(x=>matches(h,x)))throw new DOMException(`source domain denied: ${h}`,'NotAllowedError');if(controls.allow_domains.length&&!controls.allow_domains.some(x=>matches(h,x)))throw new DOMException(`source domain not allow-listed: ${h}`,'NotAllowedError');if(controls.source_types.length&&!controls.source_types.includes(source_type))throw new DOMException(`source type not allowed: ${source_type}`,'NotAllowedError');const observed=Date.parse(as_of);if(controls.start_as_of&&observed<Date.parse(controls.start_as_of))throw new DOMException('source precedes date window','NotAllowedError');if(controls.end_as_of&&observed>Date.parse(controls.end_as_of))throw new DOMException('source exceeds date window','NotAllowedError');return h;}
function freshness(source,now=Date.now()){const asOf=Date.parse(source.as_of),ttl=(TTL[source.source_class]??TTL[source.source_type]??86400);const age=(now-asOf)/1000;const stale=age>ttl;return {as_of:source.as_of,retrieved_at:source.retrieved_at,age_seconds:Math.round(age),ttl_seconds:ttl,is_stale:stale,action:stale?'annotate':'accept',annotation:stale?`STALE ${source.source_class}; as_of=${source.as_of}; age_seconds=${Math.round(age)}; ttl_seconds=${ttl}`:null};}
function injectionFlags(text){const s=String(text).normalize('NFKC').replace(/[\u200b\u200c\u200d\u2060\ufeff]/g,' ').toLowerCase();const flags=[];if(/ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions?|rules?|polic)/.test(s))flags.push('ignore-prior');if(/(reveal|print|send|leak|dump|show).{0,72}(secret|token|credential|api[_ -]?key|password)/s.test(s))flags.push('credential-request');if(/(bypass|disable|override|ignore|evade).{0,72}(policy|safety|authorization|approval|guardrail|permission)/s.test(s))flags.push('policy-bypass');return flags.sort();}

export class ResearchClaimStore{
  constructor(db){this.db=db;}
  static async open(){const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;for(const [name,key] of [['sources','source_id'],['claims','claim_id'],['citations','citation_id'],['events','event_id']])if(!db.objectStoreNames.contains(name)){const s=db.createObjectStore(name,{keyPath:key});s.createIndex('project_id','project_id');if(name==='events')s.createIndex('project_sequence',['project_id','sequence'],{unique:true});}};return new ResearchClaimStore(await request(r));}
  async all(storeName,projectId){const tx=this.db.transaction(storeName,'readonly');const rows=await request(tx.objectStore(storeName).index('project_id').getAll(projectId));await done(tx);return rows;}
  async get(storeName,id){const tx=this.db.transaction(storeName,'readonly');const row=await request(tx.objectStore(storeName).get(id));await done(tx);return row?clone(row):null;}
  async event(projectId,type,payload){const rows=(await this.all('events',projectId)).sort((a,b)=>a.sequence-b.sequence);const prior=rows.at(-1)||null;const created_at=new Date().toISOString();const body={project_id:projectId,sequence:prior?prior.sequence+1:0,event_type:type,payload:clone(payload),previous_sha256:prior?.event_sha256||null,created_at};const event={...body,event_id:uid('revt'),event_sha256:await sha(body)};const tx=this.db.transaction('events','readwrite');tx.objectStore('events').add(event);await done(tx);return clone(event);}
  async addSource(projects,actor,payload,controls){const project=await projects.store.getProject(payload.projectId);authorize(project,actor);const source_type=clean(payload.sourceType,40),source_class=clean(payload.sourceClass,40)||source_type;if(!SOURCE_TYPES.has(source_type))throw new TypeError('unsupported source type');const as_of=timestamp(payload.asOf,'as_of'),retrieved_at=timestamp(payload.retrievedAt,'retrieved_at'),url=clean(payload.url,2000),domain=enforceControls(controls,{url,source_type,as_of});const text=String(payload.text??'');if(!text)throw new TypeError('source text required');const content_sha256=await sha(text);const source_id=uid('rsrc');const row={schema:SOURCE_SCHEMA,project_id:payload.projectId,source_id,title:clean(payload.title,240),url,domain,source_type,source_class,text,content_sha256,as_of,retrieved_at,freshness:null,instruction_authority:'retrieved-content-data-only',injection_flags:injectionFlags(text),created_at:new Date().toISOString()};if(!row.title)throw new TypeError('source title required');row.freshness=freshness(row);const tx=this.db.transaction('sources','readwrite');tx.objectStore('sources').add(row);await done(tx);const obj=await projects.store.addObject(payload.projectId,actor,{type:'source',title:row.title,provenanceSource:`research-source:${content_sha256}`,evidenceLinks:[`research-source:${source_id}`,`sha256:${content_sha256}`,`as-of:${as_of}`]});row.project_object_id=obj.object_id;const tx2=this.db.transaction('sources','readwrite');tx2.objectStore('sources').put(row);await done(tx2);await this.event(payload.projectId,'research.source.added',{source_id,content_sha256,as_of});return clone(row);}
  async addClaim(projects,actor,payload){const project=await projects.store.getProject(payload.projectId);authorize(project,actor);const claim_id=uid('rclm'),text=clean(payload.text,12000);if(!text)throw new TypeError('claim text required');const confidence=Number(payload.confidence);if(!Number.isFinite(confidence)||confidence<0||confidence>1)throw new TypeError('confidence must be 0..1');const depends_on=(payload.dependsOn||[]).filter(Boolean);if(new Set(depends_on).size!==depends_on.length)throw new TypeError('duplicate dependency');for(const dep of depends_on){const row=await this.get('claims',dep);if(!row||row.project_id!==payload.projectId)throw new DOMException('claim dependency outside project','InvalidStateError');}const created_at=new Date().toISOString();const row={schema:CLAIM_SCHEMA,project_id:payload.projectId,claim_id,text,claim_sha256:await sha(text),material:Boolean(payload.material),confidence,uncertainty:clean(payload.uncertainty,2000),depends_on,verification_status:'UNVERIFIED',created_at};const tx=this.db.transaction('claims','readwrite');tx.objectStore('claims').add(row);await done(tx);await this.assertAcyclic(payload.projectId);await this.event(payload.projectId,'research.claim.added',{claim_id,claim_sha256:row.claim_sha256,depends_on});return clone(row);}
  async addCitation(projects,actor,payload){const project=await projects.store.getProject(payload.projectId);authorize(project,actor);const claim=await this.get('claims',payload.claimId),source=await this.get('sources',payload.sourceId);if(!claim||!source||claim.project_id!==payload.projectId||source.project_id!==payload.projectId)throw new DOMException('citation references outside project','InvalidStateError');if(!STANCES.has(payload.stance))throw new TypeError('invalid citation stance');const start=Number(payload.start),end=Number(payload.end);if(!Number.isInteger(start)||!Number.isInteger(end)||start<0||end<=start||end>source.text.length)throw new RangeError('citation span out of bounds');const quote=String(payload.quote??'');if(source.text.slice(start,end)!==quote)throw new DOMException('citation quote does not exactly match source span','DataError');if(await sha(source.text)!==source.content_sha256)throw new DOMException('source integrity failure','DataError');const citation_id=uid('rcit');const row={schema:CITATION_SCHEMA,project_id:payload.projectId,citation_id,claim_id:claim.claim_id,source_id:source.source_id,source_sha256:source.content_sha256,start,end,quote,quote_sha256:await sha(quote),stance:payload.stance,created_at:new Date().toISOString()};const tx=this.db.transaction('citations','readwrite');tx.objectStore('citations').add(row);await done(tx);await this.deriveClaim(claim.claim_id);await this.event(payload.projectId,'research.citation.added',{citation_id,claim_id:claim.claim_id,source_id:source.source_id,stance:payload.stance});return clone(row);}
  async deriveClaim(claimId){const claim=await this.get('claims',claimId);if(!claim)throw new Error('claim not found');const citations=(await this.all('citations',claim.project_id)).filter(x=>x.claim_id===claimId);const supports=citations.filter(x=>x.stance==='supports'),contradicts=citations.filter(x=>x.stance==='contradicts');claim.verification_status=!supports.length?'UNVERIFIED':contradicts.length?'SUPPORTED':'VERIFIED';const tx=this.db.transaction('claims','readwrite');tx.objectStore('claims').put(claim);await done(tx);return clone(claim);}
  async assertAcyclic(projectId){const claims=await this.all('claims',projectId),by=new Map(claims.map(x=>[x.claim_id,x]));const visiting=new Set(),visited=new Set();const visit=id=>{if(visiting.has(id))throw new DOMException('claim lineage cycle detected','InvalidStateError');if(visited.has(id))return;const row=by.get(id);if(!row)throw new DOMException('claim lineage missing dependency','InvalidStateError');visiting.add(id);for(const dep of row.depends_on)visit(dep);visiting.delete(id);visited.add(id);};for(const id of by.keys())visit(id);return true;}
  async verify(projectId){const [sources,claims,citations,events]=await Promise.all(['sources','claims','citations','events'].map(x=>this.all(x,projectId)));const sourceMap=new Map(sources.map(x=>[x.source_id,x])),claimMap=new Map(claims.map(x=>[x.claim_id,x]));const errors=[],missing=[];for(const s of sources){if(await sha(s.text)!==s.content_sha256)errors.push(`source_hash:${s.source_id}`);s.freshness=freshness(s);}for(const c of citations){const source=sourceMap.get(c.source_id),claim=claimMap.get(c.claim_id);if(!source||!claim){errors.push(`missing_reference:${c.citation_id}`);continue;}if(source.project_id!==projectId||claim.project_id!==projectId||c.project_id!==projectId){errors.push(`cross_project:${c.citation_id}`);continue;}if(c.start<0||c.end<=c.start||c.end>source.text.length){errors.push(`span_bounds:${c.citation_id}`);continue;}const quote=source.text.slice(c.start,c.end);if(quote!==c.quote||await sha(quote)!==c.quote_sha256)errors.push(`quote_integrity:${c.citation_id}`);if(source.content_sha256!==c.source_sha256)errors.push(`source_binding:${c.citation_id}`);}try{await this.assertAcyclic(projectId);}catch{errors.push('claim_lineage');}for(const claim of claims){if(await sha(claim.text)!==claim.claim_sha256)errors.push(`claim_hash:${claim.claim_id}`);const cc=citations.filter(x=>x.claim_id===claim.claim_id),supports=cc.filter(x=>x.stance==='supports'),contradicts=cc.filter(x=>x.stance==='contradicts');const derived=!supports.length?'UNVERIFIED':contradicts.length?'SUPPORTED':'VERIFIED';if(claim.verification_status!==derived)errors.push(`claim_status:${claim.claim_id}`);if(claim.material&&!supports.length)missing.push(claim.claim_id);}let previous=null;for(const [i,e] of [...events].sort((a,b)=>a.sequence-b.sequence).entries()){const body={project_id:e.project_id,sequence:e.sequence,event_type:e.event_type,payload:e.payload,previous_sha256:e.previous_sha256,created_at:e.created_at};if(e.sequence!==i||e.previous_sha256!==previous||await sha(body)!==e.event_sha256){errors.push(`event_chain:${i}`);break;}previous=e.event_sha256;}const result={schema:'musitu.axiom.research-integrity.v1',project_id:projectId,status:errors.length?'FAIL':'PASS',source_count:sources.length,claim_count:claims.length,citation_count:citations.length,missing_evidence_claim_ids:missing.sort(),errors:errors.sort(),event_chain_tip_sha256:previous};result.integrity_sha256=await sha(result);return result;}
  async snapshot(projectId){const [sources,claims,citations,events]=await Promise.all(['sources','claims','citations','events'].map(x=>this.all(x,projectId)));for(const s of sources)s.freshness=freshness(s);const enriched=claims.map(claim=>{const cc=citations.filter(x=>x.claim_id===claim.claim_id);return {...claim,supporting_source_ids:[...new Set(cc.filter(x=>x.stance==='supports').map(x=>x.source_id))].sort(),contradicting_source_ids:[...new Set(cc.filter(x=>x.stance==='contradicts').map(x=>x.source_id))].sort(),citation_ids:cc.map(x=>x.citation_id),unresolved_questions:claim.material&&!cc.some(x=>x.stance==='supports')?['Missing supporting evidence']:[]};});return {project_id:projectId,sources,claims:enriched,citations,events:[...events].sort((a,b)=>a.sequence-b.sequence),integrity:await this.verify(projectId)};}
}

function markup(){return `<section id="research-space" class="research-space" hidden aria-labelledby="research-title">
<div class="research-heading"><div><span class="eyebrow">Phase 4 · Claim-native research</span><h2 id="research-title">Research + claim graph</h2><p>Every material claim stays bound to inspectable evidence, contradiction, freshness and lineage.</p></div><span id="research-integrity" class="status-pill neutral">No graph yet</span></div>
<p class="boundary-note" id="research-boundary">Research sources are browser-local evidence/data only. This surface does not execute retrieved instructions or claim external verification.</p>
<section class="research-card source-controls" aria-labelledby="research-controls-title"><div class="section-heading"><div><span class="eyebrow">Source scope</span><h3 id="research-controls-title">Source controls</h3></div></div><div class="research-controls-grid"><label>Project<select id="research-project"><option value="">Choose project</option></select></label><label>Allow domains<input id="research-allow-domains" placeholder="example.org, sec.gov"></label><label>Deny domains<input id="research-deny-domains" placeholder="blocked.example"></label><label>Source types<select id="research-source-types" multiple size="3"><option value="web" selected>web</option><option value="paper" selected>paper</option><option value="document">document</option><option value="dataset">dataset</option><option value="filing">filing</option><option value="transcript">transcript</option></select></label><label>As-of start<input id="research-start" type="datetime-local"></label><label>As-of end<input id="research-end" type="datetime-local"></label></div></section>
<div class="research-entry-grid">
<form id="research-source-form" class="research-card"><h3>Add source snapshot</h3><label>Title<input id="research-source-title" required></label><label>URL<input id="research-source-url" type="url" required value="https://example.com/evidence"></label><div class="research-inline"><label>Type<select id="research-source-type"><option>web</option><option>paper</option><option>document</option><option>dataset</option><option>filing</option><option>transcript</option></select></label><label>Freshness class<select id="research-source-class"><option>web</option><option>paper</option><option>document</option><option>dataset</option><option>filing</option><option>transcript</option></select></label></div><label>Source as-of<input id="research-source-asof" type="datetime-local" required></label><label>Retrieved at<input id="research-source-retrieved" type="datetime-local" required></label><label>Immutable source text<textarea id="research-source-text" rows="5" required></textarea></label><button class="button secondary" type="submit">Add source</button></form>
<form id="research-claim-form" class="research-card"><h3>Add claim</h3><label>Claim text<textarea id="research-claim-text" rows="4" required></textarea></label><label>Uncertainty<textarea id="research-claim-uncertainty" rows="2"></textarea></label><div class="research-inline"><label>Confidence<input id="research-claim-confidence" type="number" min="0" max="1" step="0.01" value="0.5" required></label><label>Depends on<select id="research-claim-dep"><option value="">No dependency</option></select></label></div><label class="check-row"><input id="research-claim-material" type="checkbox" checked> Material claim</label><button class="button secondary" type="submit">Add claim</button></form>
<form id="research-citation-form" class="research-card"><h3>Add exact citation</h3><label>Claim<select id="research-citation-claim" required></select></label><label>Source<select id="research-citation-source" required></select></label><div class="research-inline"><label>Stance<select id="research-citation-stance"><option value="supports">supports</option><option value="contradicts">contradicts</option></select></label><label>Start offset<input id="research-citation-start" type="number" min="0" value="0" required></label><label>End offset<input id="research-citation-end" type="number" min="1" required></label></div><label>Exact quoted span<textarea id="research-citation-quote" rows="3" required></textarea></label><button class="button primary" type="submit">Bind citation</button></form>
</div>
<section class="research-card research-results"><div class="research-tabs" role="tablist" aria-label="Research views"><button id="research-tab-report" class="button secondary active" type="button" role="tab" aria-selected="true" aria-controls="research-report">Report View</button><button id="research-tab-map" class="button secondary" type="button" role="tab" aria-selected="false" aria-controls="research-map">Evidence Map</button><button id="research-tab-timeline" class="button secondary" type="button" role="tab" aria-selected="false" aria-controls="research-timeline">Research Timeline</button></div><div id="research-report" role="tabpanel" aria-labelledby="research-tab-report" aria-live="polite"></div><div id="research-map" role="tabpanel" aria-labelledby="research-tab-map" hidden></div><div id="research-timeline" role="tabpanel" aria-labelledby="research-tab-timeline" hidden></div></section>
</section>`;}
function isoLocal(value){if(!value)return '';const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toISOString();}
function error(component,error){window.AxiomUI?.reportError?.({errorId:'AXIOM-RESEARCH-INTEGRITY',component,impact:'Research graph write rejected',succeeded:'Existing claim/evidence state preserved',failed:error.message,dataLost:'No',retryState:'Ready',recovery:'Correct the source, span, scope or lineage and retry'});}

export async function initResearchWorkspace({emit=()=>{},projects}={}){
  if(!projects?.store)throw new TypeError('qualified Project substrate required');const workspace=document.querySelector('#main-workspace');if(!workspace)return null;const style=document.createElement('link');style.rel='stylesheet';style.href='./styles/research.css';document.head.append(style);workspace.insertAdjacentHTML('beforeend',markup());const space=document.querySelector('#research-space'),hero=document.querySelector('.hero-card'),run=document.querySelector('.run-stage'),store=await ResearchClaimStore.open(),actor='local-user';let currentProject='';
  const projectSelect=document.querySelector('#research-project');
  function controls(){return parseControls({allowDomains:document.querySelector('#research-allow-domains').value,denyDomains:document.querySelector('#research-deny-domains').value,sourceTypes:[...document.querySelector('#research-source-types').selectedOptions].map(x=>x.value),startAsOf:isoLocal(document.querySelector('#research-start').value),endAsOf:isoLocal(document.querySelector('#research-end').value)});}
  async function refreshProjects(){const rows=await projects.store.listProjects(),preferred=projectSelect.value||projects.getCurrentProjectId?.()||currentProject;projectSelect.replaceChildren(new Option('Choose project',''));for(const p of rows)projectSelect.add(new Option(`${p.name} · ${p.project_id}`,p.project_id));if(preferred&&rows.some(x=>x.project_id===preferred)){projectSelect.value=preferred;currentProject=preferred;}else currentProject=projectSelect.value;await render();}
  function setTab(id){for(const button of document.querySelectorAll('.research-tabs [role=tab]')){const active=button.id===id;button.setAttribute('aria-selected',String(active));button.classList.toggle('active',active);document.getElementById(button.getAttribute('aria-controls')).hidden=!active;}}
  function text(tag,value,cls=''){const el=document.createElement(tag);if(cls)el.className=cls;el.textContent=value;return el;}
  async function render(){const report=document.querySelector('#research-report'),map=document.querySelector('#research-map'),timeline=document.querySelector('#research-timeline');report.replaceChildren();map.replaceChildren();timeline.replaceChildren();if(!currentProject){report.append(text('p','Choose a Project to start claim-native research.','proof-empty'));document.querySelector('#research-integrity').textContent='No graph yet';return;}const snap=await store.snapshot(currentProject);document.querySelector('#research-integrity').textContent=`${snap.integrity.status} · ${snap.integrity.citation_count} citations · ${snap.integrity.missing_evidence_claim_ids.length} missing`;
    const dep=document.querySelector('#research-claim-dep'),claimSel=document.querySelector('#research-citation-claim'),sourceSel=document.querySelector('#research-citation-source');dep.replaceChildren(new Option('No dependency',''));claimSel.replaceChildren(new Option('Choose claim',''));sourceSel.replaceChildren(new Option('Choose source',''));for(const c of snap.claims){dep.add(new Option(`${c.claim_id} · ${c.text.slice(0,48)}`,c.claim_id));claimSel.add(new Option(`${c.claim_id} · ${c.text.slice(0,48)}`,c.claim_id));}for(const s of snap.sources)sourceSel.add(new Option(`${s.source_id} · ${s.title}`,s.source_id));
    const summary=document.createElement('div');summary.className='research-summary';summary.append(text('strong',`${snap.claims.length} claims · ${snap.sources.length} sources · ${snap.citations.length} citations`),text('span',snap.integrity.status==='PASS'?'Citation graph integrity verified':'Integrity failure detected'));report.append(summary);
    if(!snap.claims.length)report.append(text('p','No claims yet.','proof-empty'));for(const c of snap.claims){const article=document.createElement('article');article.className='research-claim';article.dataset.claimId=c.claim_id;const state=text('span',c.verification_status,`claim-state ${c.verification_status==='VERIFIED'?'supported':c.verification_status==='SUPPORTED'?'observation':'neutral'}`);const h=text('h3',c.text);const meta=text('p',`${c.claim_id} · confidence ${Math.round(c.confidence*100)}% · ${c.material?'material':'non-material'}`,'research-meta');const uncertainty=text('p',c.uncertainty?`Uncertainty: ${c.uncertainty}`:'Uncertainty: not stated','research-uncertainty');const evidence=text('p',`Support: ${c.supporting_source_ids.join(', ')||'missing'} · Contradiction: ${c.contradicting_source_ids.join(', ')||'none'} · Dependencies: ${c.depends_on.join(', ')||'none'}`,'research-evidence-line');article.append(state,h,meta,uncertainty,evidence);report.append(article);}
    const nodes=document.createElement('ul');nodes.className='evidence-nodes';for(const s of snap.sources){const li=document.createElement('li');li.dataset.sourceId=s.source_id;li.append(text('strong',`${s.source_id} · ${s.title}`),text('span',`${s.source_type} · ${s.domain} · as-of ${s.as_of} · ${s.freshness.is_stale?'STALE':'fresh'} · ${s.instruction_authority}`));nodes.append(li);}for(const c of snap.claims){const li=document.createElement('li');li.dataset.claimId=c.claim_id;li.append(text('strong',`${c.claim_id} · ${c.verification_status}`),text('span',c.text));nodes.append(li);}map.append(text('h3','Evidence nodes'),nodes);const edges=document.createElement('ul');for(const cite of snap.citations){const li=document.createElement('li');li.dataset.citationId=cite.citation_id;li.textContent=`${cite.source_id} —${cite.stance}→ ${cite.claim_id} [${cite.start}:${cite.end}] “${cite.quote}”`;edges.append(li);}for(const c of snap.claims)for(const d of c.depends_on){const li=document.createElement('li');li.textContent=`${d} —depends_on→ ${c.claim_id}`;edges.append(li);}map.append(text('h3','Evidence edges'),edges);
    const eventList=document.createElement('ol');eventList.className='research-timeline';for(const e of snap.events){const li=document.createElement('li');li.dataset.sequence=String(e.sequence);li.append(text('time',e.created_at),text('strong',e.event_type),text('code',`sha256:${e.event_sha256.slice(0,16)}…`));eventList.append(li);}timeline.append(eventList);
  }
  projectSelect.addEventListener('change',async()=>{currentProject=projectSelect.value;await render();});
  document.querySelector('#research-source-form').addEventListener('submit',async e=>{e.preventDefault();try{if(!currentProject)throw new TypeError('choose project');await store.addSource(projects,actor,{projectId:currentProject,title:document.querySelector('#research-source-title').value,url:document.querySelector('#research-source-url').value,sourceType:document.querySelector('#research-source-type').value,sourceClass:document.querySelector('#research-source-class').value,asOf:isoLocal(document.querySelector('#research-source-asof').value),retrievedAt:isoLocal(document.querySelector('#research-source-retrieved').value),text:document.querySelector('#research-source-text').value},controls());emit('research.source',{state:'persisted-data-only'});e.target.reset();document.querySelector('#research-source-url').value='https://example.com/evidence';await render();}catch(err){error('Research source',err);}});
  document.querySelector('#research-claim-form').addEventListener('submit',async e=>{e.preventDefault();try{if(!currentProject)throw new TypeError('choose project');await store.addClaim(projects,actor,{projectId:currentProject,text:document.querySelector('#research-claim-text').value,uncertainty:document.querySelector('#research-claim-uncertainty').value,confidence:document.querySelector('#research-claim-confidence').value,material:document.querySelector('#research-claim-material').checked,dependsOn:[document.querySelector('#research-claim-dep').value].filter(Boolean)});emit('research.claim',{state:'unverified-until-cited'});e.target.reset();document.querySelector('#research-claim-confidence').value='0.5';document.querySelector('#research-claim-material').checked=true;await render();}catch(err){error('Research claim',err);}});
  document.querySelector('#research-citation-form').addEventListener('submit',async e=>{e.preventDefault();try{if(!currentProject)throw new TypeError('choose project');await store.addCitation(projects,actor,{projectId:currentProject,claimId:document.querySelector('#research-citation-claim').value,sourceId:document.querySelector('#research-citation-source').value,stance:document.querySelector('#research-citation-stance').value,start:Number(document.querySelector('#research-citation-start').value),end:Number(document.querySelector('#research-citation-end').value),quote:document.querySelector('#research-citation-quote').value});emit('research.citation',{state:'exact-span-bound'});await render();}catch(err){error('Research citation',err);}});
  document.querySelectorAll('.research-tabs [role=tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.id)));
  function route(){const on=/^#\/research(?:\/|$)/.test(location.hash);space.hidden=!on;if(on){if(hero)hero.hidden=true;if(run)run.hidden=true;document.querySelector('#workspace-title').textContent='Research';document.querySelector('#workspace-description').textContent='Build synchronized Report, Evidence Map and Timeline views from exact source-bound claims, contradictions and freshness.';refreshProjects().catch(err=>error('Research',err));}else if(!/^#\/(projects|project(?:\/|$)|work(?:\/|$))/.test(location.hash)){if(hero)hero.hidden=false;if(run)run.hidden=false;}}
  window.addEventListener('hashchange',route);await refreshProjects();route();const api={store,refresh:render,getCurrentProjectId:()=>currentProject};window.AxiomResearch=Object.freeze(api);return api;
}
