from __future__ import annotations
from http.server import SimpleHTTPRequestHandler,ThreadingHTTPServer
import json,os,shutil,threading
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];OUT=Path(os.environ.get('AXIOM_PHASE11_ARTIFACT_DIR','/tmp/axiom-interface-phase11'));OUT.mkdir(parents=True,exist_ok=True)
class Quiet(SimpleHTTPRequestHandler):
 def log_message(self,*_):pass
def main():
 handler=lambda *a,**k:Quiet(*a,directory=str(ROOT),**k);server=ThreadingHTTPServer(('127.0.0.1',0),handler);threading.Thread(target=server.serve_forever,daemon=True).start();origin=f'http://127.0.0.1:{server.server_port}'
 try:
  with sync_playwright() as p:
   browser=p.chromium.launch(headless=True,executable_path=os.environ.get('AXIOM_CHROMIUM_EXECUTABLE') or shutil.which('chromium') or None);context=browser.new_context(viewport={'width':1440,'height':1150},reduced_motion='reduce');page=context.new_page();requests=[];page.on('request',lambda request:requests.append(request.url));page.goto(origin+'/index.html#/projects',wait_until='networkidle');page.wait_for_function('()=>Boolean(window.AxiomOperatorBootstrap)');page.evaluate('()=>window.AxiomOperatorBootstrap');page.locator('#project-name').fill('Phase 11 Operator Control Proof');page.locator('#project-goal').fill('Prove local enterprise RBAC, exact admin previews, fleet posture and tamper-evident control receipts');page.get_by_role('button',name='Create project').click();page.wait_for_timeout(120);project_id=page.locator('#project-select').input_value();
   for name in ['Operator Agent A','Operator Agent B']:
    page.evaluate("args=>window.AxiomAgents.store.createAgent({projectId:args.projectId,name:args.name,purpose:'Phase 11 governed fleet posture proof',toolScopes:['project.read'],dataScopes:['project.metadata'],autonomy:'PROPOSE_ONLY',maxRuns:5,maxComputeUnits:10})",{'projectId':project_id,'name':name})
   page.goto(origin+'/index.html#/operator',wait_until='networkidle');page.locator('#operator-space').wait_for(state='visible');page.locator('#operator-org-id').fill('phase11-org');page.locator('#operator-org-name').fill('Phase 11 Local Enterprise');page.get_by_role('button',name='Bootstrap local organization').click();page.wait_for_timeout(120);page.locator('#operator-project').select_option(project_id);page.locator('#operator-member-id').fill('reviewer-1');page.locator('#operator-member-role').select_option('viewer');page.get_by_role('button',name='Add local member preview').click();page.wait_for_timeout(100);
   unauthorized=page.evaluate("()=>window.AxiomOperator.store.preparePolicy('phase11-org','reviewer-1',{failureRateSlo:.2,maxActiveAgents:1,maxLocalComputeUnits:5,incidentEscalationRequired:true}).then(()=> 'ALLOWED').catch(e=>e.name)");assert unauthorized=='SecurityError',unauthorized
   owner_demote=page.evaluate("()=>window.AxiomOperator.store.prepareRoleChange('phase11-org','local-user','local-user','admin').then(()=> 'ALLOWED').catch(e=>e.name)");assert owner_demote=='SecurityError',owner_demote
   preview=page.evaluate("()=>window.AxiomOperator.store.preparePolicy('phase11-org','local-user',{failureRateSlo:.2,maxActiveAgents:1,maxLocalComputeUnits:5,incidentEscalationRequired:true})");wrong=page.evaluate("args=>window.AxiomOperator.store.applyPolicy('phase11-org','local-user',{failureRateSlo:.2,maxActiveAgents:1,maxLocalComputeUnits:5,incidentEscalationRequired:true},'0'.repeat(64)).then(()=> 'ALLOWED').catch(e=>e.name)",{});assert wrong=='SecurityError',wrong;applied=page.evaluate("args=>window.AxiomOperator.store.applyPolicy('phase11-org','local-user',{failureRateSlo:.2,maxActiveAgents:1,maxLocalComputeUnits:5,incidentEscalationRequired:true},args.sha)",{'sha':preview['preview_sha256']});assert applied['production_enforcement_claimed'] is False
   posture=page.evaluate("id=>window.AxiomOperator.store.posture('phase11-org','local-user',{projectId:id})",project_id);assert posture['status']=='ATTENTION' and 'ACTIVE_AGENT_LIMIT' in posture['breaches'];assert posture['production_identity_mutation_claimed'] is False and posture['production_billing_claimed'] is False and posture['cloud_control_plane_claimed'] is False and posture['external_action_execution_claimed'] is False and posture['hidden_reasoning_recorded'] is False
   integrity=page.evaluate("()=>window.AxiomOperator.store.verify('phase11-org')");assert integrity['status']=='PASS',integrity;page.reload(wait_until='networkidle');page.wait_for_function('()=>Boolean(window.AxiomOperatorBootstrap)');page.evaluate('()=>window.AxiomOperatorBootstrap');persisted=page.evaluate("()=>window.AxiomOperator.store.getOrganization('phase11-org')");assert persisted and persisted['name']=='Phase 11 Local Enterprise';page.goto(origin+'/index.html#/operator',wait_until='networkidle');page.locator('#operator-space').wait_for(state='visible');page.keyboard.press('Control+K');assert page.locator('#composer-input').evaluate('el=>el===document.activeElement');page.screenshot(path=str(OUT/'phase11-operator-control-plane.png'),full_page=True);foreign=[url for url in requests if not url.startswith(origin+'/')];assert foreign==[],foreign;evidence={'schema':'musitu.axiom.interface.phase11-operator-browser-evidence.v1','status':'PASS','project_id':project_id,'org_id':'phase11-org','rbac_unauthorized_denied':True,'final_owner_safeguard_verified':True,'exact_policy_digest_verified':True,'stale_policy_digest_rejected':True,'fleet_limit_breach_verified':True,'cross_reload_persistence_verified':True,'ctrl_k_inherited_focus_verified':True,'integrity_verified':True,'foreign_requests':foreign,'network_policy':'DENY_ALL_EXTERNAL_NETWORK','control_plane_mode':'BROWSER_LOCAL_ADMIN_PREVIEW_ONLY_NO_PRODUCTION_MUTATION','production_identity_mutation_claimed':False,'production_billing_claimed':False,'cloud_control_plane_claimed':False,'external_action_execution_claimed':False,'hidden_reasoning_recorded':False};(OUT/'phase11-operator-browser-evidence.json').write_text(json.dumps(evidence,indent=2,sort_keys=True)+'\n',encoding='utf-8');browser.close()
 finally:server.shutdown();server.server_close()
 print('MUSITU_AXIOM_INTERFACE_PHASE11_OPERATOR_BROWSER_PASS')
if __name__=='__main__':main()
