from __future__ import annotations
import argparse, cmath, importlib, json, math, pathlib, re, sys
import numpy as np

def close(a,b,tol=1e-8):
    return abs(float(a)-float(b)) <= tol*max(1.0,abs(float(b)))

def bs(S,K,T,r,sigma,kind='call',q=0.0):
    cdf=lambda z:0.5*(1+math.erf(z/math.sqrt(2)))
    d1=(math.log(S/K)+(r-q+.5*sigma*sigma)*T)/(sigma*math.sqrt(T)); d2=d1-sigma*math.sqrt(T)
    if kind=='call': return S*math.exp(-q*T)*cdf(d1)-K*math.exp(-r*T)*cdf(d2)
    return K*math.exp(-r*T)*cdf(-d2)-S*math.exp(-q*T)*cdf(-d1)

def main():
    ap=argparse.ArgumentParser();ap.add_argument("--runtime",required=True);ap.add_argument("--fixtures",required=True);ns=ap.parse_args()
    sys.path.insert(0,str(pathlib.Path(ns.runtime).resolve()))
    m=importlib.import_module("kernel.app.main")
    fixtures=json.load(open(ns.fixtures))["fixtures"]
    covered=set(); failures=[]

    def run(op,args):
        covered.add(op); return m.encode(m.dispatch(op,args,50))
    def chk(op,args,pred,label):
        try:
            r=run(op,args)
            if not pred(r): failures.append((op,label,r))
        except Exception as e: failures.append((op,label,type(e).__name__+":"+str(e)))

    chk("arithmetic.evaluate",{"expression":"2+3*4"},lambda r:close(r,14),"precedence")
    chk("algebra.simplify",{"expression":"(x^2-1)/(x-1)"},lambda r:str(r)=="x + 1","simplify")
    chk("algebra.expand",{"expression":"(x+2)^3"},lambda r:str(r)=="x**3 + 6*x**2 + 12*x + 8","expand")
    chk("algebra.factor",{"expression":"x^2-5*x+6"},lambda r:str(r) in {"(x - 3)*(x - 2)","(x - 2)*(x - 3)"},"factor")
    chk("algebra.solve",{"equations":["x+y-5","x-y-1"],"symbols":["x","y"]},lambda r:any(str(z.get("x"))=="3" and str(z.get("y"))=="2" for z in r),"solve")
    chk("calculus.diff",{"expression":"x^4","symbol":"x"},lambda r:str(r)=="4*x**3","diff")
    chk("calculus.integrate",{"expression":"x^2","symbol":"x","bounds":[0,3]},lambda r:close(r,9),"integral")
    chk("calculus.limit",{"expression":"sin(x)/x","symbol":"x","to":0},lambda r:str(r) in {"1","1.0000000000000000000000000000000000000000000000000"},"limit")
    chk("calculus.series",{"expression":"exp(x)","symbol":"x","at":0,"order":4},lambda r:"x**3/6" in str(r) and "O(x**4)" in str(r),"series")
    chk("numeric.root",{"expression":"x^2-9","symbol":"x","guess":2},lambda r:abs(float(r)-3)<1e-12,"root")
    chk("numeric.integrate",{"expression":"cos(x)","a":0,"b":math.pi/2},lambda r:abs(r["value"]-1)<1e-10,"num-integral")
    chk("numeric.ode",{"rhs":"y","t0":0,"t1":1,"y0":2},lambda r:r["success"] and abs(r["y"][-1]-2*math.e)<2e-7,"ode")
    chk("numeric.optimize_scalar",{"expression":"(x+1.5)^2","a":-5,"b":5},lambda r:r["success"] and abs(r["x"]+1.5)<1e-5,"scalar-opt")
    A=np.array([[4.,7.],[2.,6.]])
    chk("linear.det",{"A":A.tolist()},lambda r:abs(r-10)<1e-12,"det")
    chk("linear.inv",{"A":A.tolist()},lambda r:np.linalg.norm(A@np.asarray(r)-np.eye(2))<1e-10,"inv")
    chk("linear.solve",{"A":[[3,1],[1,2]],"b":[9,8]},lambda r:np.linalg.norm(np.array([[3,1],[1,2]])@np.asarray(r)-np.array([9,8]))<1e-10,"linear-solve")
    chk("linear.eigen",{"A":[[2,0],[0,5]]},lambda r:sorted(round(float(x),8) for x in r["values"])==[2.0,5.0],"eigen")
    chk("statistics.describe",{"data":[1,2,3,4]},lambda r:r["n"]==4 and close(r["mean"],2.5) and close(r["std_sample"],math.sqrt(5/3)),"describe")
    chk("statistics.correlation",{"x":[1,2,3],"y":[4,7,10]},lambda r:abs(r-1)<1e-12,"corr")
    chk("statistics.regression",{"x":[0,1,2,3],"y":[1,3,5,7]},lambda r:close(r["slope"],2) and close(r["intercept"],1) and close(r["rvalue"],1),"regression")
    chk("statistics.quantile",{"data":[0,10],"q":.25},lambda r:close(r,2.5),"quantile")
    chk("probability.normal_cdf",{"x":0,"mu":0,"sigma":1},lambda r:close(r,.5,1e-12),"normal-cdf")
    chk("probability.normal_ppf",{"p":.5,"mu":0,"sigma":1},lambda r:abs(r)<1e-12,"normal-ppf")
    chk("finance.compound",{"principal":100,"rate":.1,"years":2,"n":1},lambda r:close(r,121),"compound")
    chk("finance.npv",{"cashflows":[-100,110],"rate":.1},lambda r:abs(r)<1e-10,"npv")
    chk("finance.black_scholes",{"S":100,"K":100,"T":1,"r":.05,"sigma":.2,"kind":"call"},lambda r:abs(r-10.450583572185565)<1e-9,"bs")
    chk("finance.greeks",{"S":100,"K":100,"T":1,"r":.05,"sigma":.2,"kind":"call"},lambda r:abs(r["delta"]-.6368306512)<1e-8 and abs(r["gamma"]-.01876201735)<1e-8 and abs(r["vega"]-37.52403469)<1e-6,"greeks")
    chk("finance.var_historical",{"returns":[-.1,-.05,0,.05,.1],"alpha":.8},lambda r:close(r["var"],.06),"hist-var")
    chk("units.convert",{"value":1,"from":"km","to":"m"},lambda r:close(r,1000),"units")
    chk("verify.evaluate",{"lhs":"(x+1)^2","rhs":"x^2+2*x+1"},lambda r:r["symbolically_equal"] is True and r["difference"]=="0","verify-evaluate")
    chk("knowledge.constant",{"name":"c"},lambda r:r["value"]==299792458.0 and r["unit"]=="m/s","constant")
    chk("combinatorics.factorial",{"n":5},lambda r:r==120,"factorial")
    chk("combinatorics.binomial",{"n":5,"k":2},lambda r:r==10,"binomial")
    chk("numbertheory.isprime",{"n":97},lambda r:r is True,"isprime")
    chk("numbertheory.factorint",{"n":360},lambda r:r=={"2":3,"3":2,"5":1},"factorint")
    chk("numbertheory.gcd",{"a":84,"b":30},lambda r:r==6,"gcd")
    chk("numbertheory.lcm",{"a":12,"b":18},lambda r:r==36,"lcm")
    chk("transforms.fft",{"data":[1,0,0,0]},lambda r:len(r)==3 and all(close(z["re"],1) and close(z["im"],0) for z in r),"fft")
    chk("statistics.covariance",{"x":[1,2,3],"y":[2,4,6]},lambda r:close(r,2),"cov")
    chk("statistics.zscore",{"data":[1,2,3]},lambda r:abs(r[0]+math.sqrt(1.5))<1e-10 and abs(r[1])<1e-12 and abs(r[2]-math.sqrt(1.5))<1e-10,"zscore")
    chk("probability.binomial_pmf",{"k":2,"n":4,"p":.5},lambda r:close(r,.375),"binomial-pmf")
    chk("probability.poisson_pmf",{"k":2,"mu":3},lambda r:abs(r-math.exp(-3)*9/2)<1e-12,"poisson-pmf")
    chk("finance.returns",{"prices":[100,110,99],"kind":"simple"},lambda r:np.max(np.abs(np.asarray(r)-np.array([.1,-.1])))<1e-12,"returns")
    R=np.array([[.01,.02],[-.01,.005],[.015,.01],[0,-.005]]);w=np.array([.6,.4]);pr=R@w;ann=252.;mean=pr.mean()*ann;vol=pr.std(ddof=1)*math.sqrt(ann)
    chk("finance.portfolio_metrics",{"returns":R.tolist(),"weights":w.tolist(),"annualization":ann,"risk_free":0},lambda r:abs(r["annualized_return"]-mean)<1e-12 and abs(r["annualized_volatility"]-vol)<1e-12 and abs(r["sharpe"]-mean/vol)<1e-12,"portfolio")
    rr=np.array([-.02,0,.02]);sd=rr.std(ddof=1);expected=1.959963984540054*sd
    chk("finance.var_parametric",{"returns":rr.tolist(),"alpha":.975},lambda r:abs(r["var"]-expected)<1e-10,"param-var")
    chk("finance.cvar_historical",{"returns":[-.1,-.05,0,.05,.1],"alpha":.8},lambda r:close(r["var"],.06) and close(r["cvar"],.1),"cvar")
    chk("timeseries.moving_average",{"data":[1,2,3,4],"window":2},lambda r:r==[1.5,2.5,3.5],"ma")
    chk("timeseries.ewma",{"data":[0,2,2],"alpha":.5},lambda r:r==[0.0,1.0,1.5],"ewma")
    chk("geometry.distance",{"p":[0,0,0],"q":[1,2,2]},lambda r:close(r,3),"distance")
    chk("knowledge.element",{"symbol":"O"},lambda r:r["atomic_number"]==8 and r["name"]=="Oxygen","element")
    chk("algebra.polynomial_roots",{"expression":"x^2-5*x+6","symbol":"x"},lambda r:sorted(round(float(x),8) for x in r)==[2.0,3.0],"poly-roots")
    chk("calculus.sum",{"expression":"k^2","symbol":"k","start":1,"end":3},lambda r:int(r)==14,"sum")
    chk("calculus.product",{"expression":"k+1","symbol":"k","start":1,"end":3},lambda r:int(r)==24,"product")
    chk("numeric.least_squares",{"A":[[1],[2],[3]],"b":[2,4,6]},lambda r:abs(r["x"][0]-2)<1e-12 and r["rank"]==1,"lstsq")
    chk("numeric.interpolate",{"x":[0,1,2],"y":[0,2,4],"at":[.5,1.5]},lambda r:np.max(np.abs(np.asarray(r)-np.array([1,3])))<1e-12,"interp")
    chk("verified.interval_eval",{"expression":"x^2","symbol":"x","interval":[1,2]},lambda r:r["engine"]=="mpmath.iv" and "1.0" in r["interval"] and "4.0" in r["interval"],"interval")
    chk("optimization.linear_program",{"c":[1,1],"A_ub":[[-1,-1]],"b_ub":[-1],"bounds":[[0,None],[0,None]]},lambda r:r["success"] and abs(r["fun"]-1)<1e-9 and abs(sum(r["x"])-1)<1e-8,"lp")
    chk("optimization.quadratic",{"Q":[[2.0]],"c":[-4.0],"bounds":[[0,1]]},lambda r:r["success"] and abs(r["x"][0]-1)<1e-8 and abs(r["fun"]+3)<1e-8 and r["verification"]["verified"],"qp")
    chk("statistics.ttest_ind",{"x":[1,2,3],"y":[1,2,3],"equal_var":False},lambda r:abs(r["statistic"])<1e-12 and abs(r["pvalue"]-1)<1e-12,"ttest")
    chk("statistics.normal_fit",{"data":[1,2,3]},lambda r:abs(r["mu"]-2)<1e-12 and abs(r["sigma"]-math.sqrt(2/3))<1e-12,"normal-fit")
    chk("probability.exponential_cdf",{"x":2,"rate":.5},lambda r:abs(r-(1-math.exp(-1)))<1e-12,"exp-cdf")
    chk("probability.chi2_cdf",{"x":2,"df":2},lambda r:abs(r-(1-math.exp(-1)))<1e-12,"chi2-cdf")
    target=.3;price=bs(100,100,1,.05,target,'call',0)
    chk("finance.implied_vol",{"price":price,"S":100,"K":100,"T":1,"r":.05,"kind":"call"},lambda r:abs(r-target)<1e-8,"implied-vol")
    face=1000;cr=.05;mat=5;yld=.04;freq=2;n=10;c=face*cr/freq;flows=[c]*n;flows[-1]+=face;bp=sum(cf/(1+yld/freq)**i for i,cf in enumerate(flows,1))
    chk("finance.bond_price",{"face":face,"coupon_rate":cr,"maturity":mat,"yield":yld,"frequency":freq},lambda r:abs(r-bp)<1e-10,"bond-price")
    chk("finance.bond_yield",{"face":face,"coupon_rate":cr,"maturity":mat,"price":bp,"frequency":freq},lambda r:abs(r-yld)<1e-9,"bond-yield")
    pv=np.array([cf/(1+yld/freq)**i for i,cf in enumerate(flows,1)]);times=np.arange(1,n+1)/freq;mac=float(times@pv/pv.sum())
    chk("finance.duration",{"face":face,"coupon_rate":cr,"maturity":mat,"yield":yld,"frequency":freq},lambda r:abs(r["macaulay"]-mac)<1e-12 and abs(r["modified"]-mac/(1+yld/freq))<1e-12,"duration")
    chk("finance.beta",{"asset_returns":[.02,-.04,.06,.0],"market_returns":[.01,-.02,.03,0]},lambda r:abs(r-2)<1e-12,"beta")
    chk("finance.drawdown",{"values":[100,120,90,108]},lambda r:abs(r["max_drawdown"]+.25)<1e-12 and np.max(np.abs(np.asarray(r["drawdowns"])-np.array([0,0,-.25,-.1])))<1e-12,"drawdown")
    terminal=100*math.exp(.05)
    chk("finance.monte_carlo_gbm",{"S0":100,"mu":.05,"sigma":0,"T":1,"steps":10,"paths":100,"seed":42},lambda r:abs(r["mean_terminal"]-terminal)<1e-10 and abs(r["p05"]-terminal)<1e-10 and abs(r["p95"]-terminal)<1e-10,"gbm")
    chk("timeseries.rolling_volatility",{"returns":[0,1,0,1],"window":2,"annualization":1},lambda r:np.max(np.abs(np.asarray(r)-math.sqrt(.5)))<1e-12,"rolling-vol")
    chk("geometry.area_circle",{"radius":2},lambda r:abs(r-4*math.pi)<1e-12,"area")
    chk("geometry.volume_sphere",{"radius":3},lambda r:abs(r-36*math.pi)<1e-12,"volume")
    chk("transforms.ifft",{"data":[{"re":10,"im":0},{"re":-2,"im":2},{"re":-2,"im":0}],"n":4},lambda r:np.max(np.abs(np.asarray(r)-np.array([1,2,3,4])))<1e-12,"ifft")
    chk("verify.crosscheck",{"operation":"linear.solve","args":{"A":[[2,0],[0,4]],"b":[6,8]}},lambda r:np.max(np.abs(np.asarray(r["result"])-np.array([3,2])))<1e-12 and r["verification"]["verified"] is True,"crosscheck")

    expected=set(fixtures)
    if covered!=expected:
        failures.append(("coverage","missing-or-extra",{"missing":sorted(expected-covered),"extra":sorted(covered-expected)}))
    if failures:
        print("ORACLE_FAILURES="+json.dumps(failures,default=str))
        raise SystemExit(f"{len(failures)} oracle failures")
    print("MUSITU_AXIOM_74_OPERATION_ORACLE_PASS")
    print("ORACLE_COVERAGE="+str(len(covered)))
    return 0
if __name__=="__main__":raise SystemExit(main())
